### ISSUE TITLE
OVA should redirect http requests to https requests

### ISSUE THREAD

**Issue by mdubya66** [vmware/vic-product#1005]
@mhagen-vmware commented on [Tue Apr 11 2017](https://github.com/vmware/vic/issues/4685)

If I don't explicitly specify https protocol I get an ERR_EMPTY_RESPONSE page

We should add an auto redirect to https or at least a better error than that.

---

@andrewtchin commented on [Tue Apr 25 2017](https://github.com/vmware/vic/issues/4685#issuecomment-297166180)

What URL/port is this for? This won't be possible for the webserver on 9443 because that socket is already using TLS
We would only be able to redirect if the initial dest port is using HTTP then we can redirect to a TLS port

---

@andrewtchin commented on [Wed May 24 2017](https://github.com/vmware/vic/issues/4685#issuecomment-303792444)

Something like this might be possible with nginx

---

@andrewtchin commented on [Tue Jun 27 2017](https://github.com/vmware/vic/issues/4685#issuecomment-311477054)

Run nginx on port 80 and redirect to 9443

---

@andrewtchin commented on [Mon Aug 14 2017](https://github.com/vmware/vic/issues/4685#issuecomment-322214677)

Jason implemented the redirect from 80 to 9443, leaving this open to see if we can catch http requests to the services listening for https and redirect them to https

**Comment by mdubya66** [comment]
Moved for vmware/vic

**Comment by andrewtchin** [comment]
Closing as we have a redirect from 80 to https on 9443 and docs tell users to use 80
