### ISSUE TITLE
Update doc link in output of `systemctl status harbor/admiral/fileserver`

### ISSUE THREAD

**Issue by mdubya66** [vmware/vic-product#1007]
@stuclem commented on [Wed Apr 05 2017](https://github.com/vmware/vic/issues/4581)

**VIC version:**

OVA installer: `vic-v1.1.0-rc2-81820686.ova`

**Deployment details:**

N/A

**Steps to reproduce:**

SSH into the appliance VM and run  `systemctl status harbor/admiral/fileserver`

**Actual behavior:**
Output inludes links to the docs.

Registry: `Docs: http://github.com/vmware/harbor`
Portal: `Docs: https://github.com/vmware/admiral`
Engine: `Docs: https://github.com/vmware/vic`

**Expected behavior:**

Now that I am unifying the docs, it would be better if the link were to https://vmware.github.io/vic-product/index.html#getting-started in all cases.

**Comment by mdubya66** [comment]
Moved from vmware/vic

**Comment by mlh78750** [comment]
This is not really a bug, the links point to valid stuff that useful. It could be more useful. I've removed the bug label and added enhancement and quality.
