### ISSUE TITLE
Identify VIC Appliance VM

### ISSUE THREAD

**Issue by andrewtchin** [vmware/vic-product#1018]
**User Statement:**

As a UI I need to be able to identify which VMs are VIC Appliances.

**Details:**
Related to #920 
http://pubs.vmware.com/vsphere-6-5/index.jsp#com.vmware.vspsdk.apiref.doc/vim.ExtensibleManagedObject.html?resultof=%2522%2573%2565%2574%2543%2575%2573%2574%256f%256d%2556%2561%256c%2575%2565%2522%2520%2522%2573%2565%2574%2563%2575%2573%2574%256f%256d%2576%2561%256c%2575%2522%2520

Get the VirtualMachine object and set a custom value on it
Tag should be on key `identifier` with value `vic-appliance-<BUILD_NUMBER>` 
Figure out build number format with @jooskim and @mdharamadas1 

**Acceptance Criteria:**
- [ ] Use API to tag the VM during the appliance initialization process
- [ ] Same process needs to apply during all cases of initialization - getting started page, upgrade, registration API

**Comment by andrewtchin** [comment]
https://github.com/vmware/vic-product/blob/master/installer/fileserver/server.go#L250
https://github.com/vmware/vic-product/blob/master/installer/fileserver/register.go

Also needs to be verified for this path:
https://github.com/vmware/vic-product/blob/master/installer/fileserver/server.go#L171
https://github.com/vmware/vic-product/blob/master/installer/build/scripts/upgrade/upgrade.sh#L39

**Comment by zjs** [comment]
Can we re-use the tagging used by VCHs to discover the OVA?

**Comment by jooskim** [comment]
@andrewtchin @morris-jason Another request here: is it possible to set another `CustomFieldDef` for IP address of the VM? After perusing the documentation on `CustomFieldsManager` I feel like it would be more efficient to expose the IP address directly as a `CustomFieldStringValue` object than to acquire the base64 encoded form and decode it out of an array of hundreds of entities from `vm.config.extraConfig`.

**Comment by zjs** [comment]
If we expose the IP address in a new place, we'll need to ensure it gets updated each time the IP address changes. How feasible is that (especially in the case of DHCP)?

**Comment by andrewtchin** [comment]
Also how does the UI handle IP vs hostname? I don't think it's possible for us to update the tag value since we do not store the vSphere credentials used to tag the VM

**Comment by jooskim** [comment]
Hmm, it makes sense that if we add another custom field for IP there will be another burden to update the value every time the IP changes. I'll then hold onto the current approach to retrieving the IP address of a VM.

**Comment by jooskim** [comment]
@andrewtchin We will be using the information to construct, in the Angular service, a URL to the vic-machine-server endpoint. It doesn't really matter whether that's hostname or IP for our use case.

**Comment by andrewtchin** [comment]
What about for TLS? Do you ignore cert errors if the user is using a self signed or one signed by a non public CA?

**Comment by jooskim** [comment]
I think that issue was handled by Cristian. @cristianfalcone Could you let us know how we handled that?
