### ISSUE TITLE
Create tests for static IP

### ISSUE THREAD

**Issue by mdharamadas1** [vmware/vic-product#1027]
**User Statement:**
As a developer, I want scenarios related to static IP ~and certificates~ verified as part of OVA build

**Details:**
Need to define manual test scenarios first.

**Acceptance Criteria:**
Static IP tests running as part of CI build

**Comment by andrewtchin** [comment]
certs covered in #1379

**Comment by andrewtchin** [comment]
From https://github.com/vmware/vic-product/blob/master/installer/build/bootable/config/builder.ovf
options for ovftool
```
network.ip0
network.netmask0
network.gateway
network.dns
network.searchpath
network.fqdn
```

This test should deploy an appliance with these options, SSH to the appliance and check `/etc/systemd/network/09-vic.network`, optionally `ip addr`, `ip route show`, `resolv.conf`, etc.
