### ISSUE TITLE
Run drone steps in parallel

### ISSUE THREAD

**Issue by mdharamadas1** [vmware/vic-product#1028]
**User Statement:**
As a developer, I want drone run some possible steps in parallel to reduce overall build time.

**Details:**
- DCH and build steps can be run concurrently
- This may not be possible in 0.5 but we can do this after we upgrade drone..
http://docs.drone.io/pipelines/#parallel-execution

**Acceptance Criteria:**
Reduced build time after concurrent step executions.

**Comment by wy65701436** [comment]
Do we have a schedule on this？Team definitely needs this feature to reduce the overall build time of PR.

**Comment by mdharamadas1** [comment]
@wy65701436 I'm not sure if its possible in current version of drone we have but it is planned after drone upgrade, which is not happening anytime soon.
