### ISSUE TITLE
Ability to update VCH container network

### ISSUE THREAD

**Issue by kumuduh** [vmware/vic-product#1029]
# For bug reports, please include the information below:

**VIC Product version:**

OVA version (e.g. `vic-v1.2.3-aaaaaaa.ova`)
VIC-1.2.1 GA
**Deployment details:**

Environment where the OVA is deployed
 Production and Dev test
**Steps to reproduce:**
Created a VCH with container network without --cnr. Then update container network with network range using vic-machine-linux configure.

**Actual behavior:**
vic-machine-linux configure throws 
ERROR Found changes to existing container network Container-NW

**Expected behavior:**
vic (vic-machine-os configure) should allow user to update the container network settings if no containers are running on that network. If any containers are running display them, so user can make a decision 

**Logs:**

**Additional details as necessary:**

# For stories, please include the information below:

**User Statement:**

A brief statement describe who, what and why of the story for example - As a job seeker, I want to search for a job, so I can advance my career.

**Details:**
Any details of what you want that might clarify for the developer how to approach the implementation.

**Acceptance Criteria:**
Specific deliverable and actionable items that the story needs to deliver in order to be considered complete, the more detail here the more accurate the implementation will be.

**Comment by chengwang86** [comment]
Moved to https://github.com/vmware/vic/issues/6674
