### ISSUE TITLE
Document docker container pause

### ISSUE THREAD

**Issue by stuclem** [vmware/vic-product#103]
_From @stuclem on August 5, 2016 9:50_

Per https://github.com/vmware/vic/issues/381. This is in the table of supported Docker commands but is marked as "Future Release". Looks like it is now in GA, but it might get iceboxed.

_Copied from original issue: vmware/vic#1828_

**Comment by stuclem** [comment]
https://github.com/vmware/vic/issues/381 is still in the Icebox with no milestone, so leaving this doc issue in icebox too.

**Comment by stuclem** [comment]
Not in 1.1

**Comment by stuclem** [comment]
https://github.com/vmware/vic/issues/381 is not flagged as in 1.2, but is flagged as a blocker for `docker commit`, which is in 1.2.

**Comment by stuclem** [comment]
Confirmed with @sflxn that this is not in 1.2.

**Comment by stuclem** [comment]
Doesn't look like this is in 1.3.

**Comment by zjs** [comment]
Closing as vmware/vic#381 was closed.
