### ISSUE TITLE
[DOC] The URL of vulnerability data source should not point to github code.

### ISSUE THREAD

**Issue by reasonerjt** [vmware/vic-product#1035]
In this document, 
https://github.com/vmware/vic-product/blob/master/docs/user_doc/vic_cloud_admin/vulnerability_scanning.md

the links under column `Database URL` are pointing to Clair's code, they should be point to the actual URL on the internet, so user don't need to read the code to figure out.

**Comment by stuclem** [comment]
@reasonerjt these are the links that we were given by @dbarkelew. Can you please provide the correct links? Thanks!

**Comment by stuclem** [comment]
@reasonerjt should we be pointing to the links in the `ovalURI` entry for each one?
