### ISSUE TITLE
Document docker save

### ISSUE THREAD

**Issue by stuclem** [vmware/vic-product#104]
_From @stuclem on July 27, 2016 15:7_

Doc the docker command to get a tarball of images, per https://github.com/vmware/vic/issues/501.

_Copied from original issue: vmware/vic#1699_

**Comment by stuclem** [comment]
_From @npakrasi on August 3, 2016 2:18_

Added to Supported Docker Commands table under Future Release and will move it to Supported in GA when it is.

**Comment by stuclem** [comment]
https://github.com/vmware/vic/issues/501 is still in the Icebox with no milestone, so leaving this doc issue in icebox too.

**Comment by stuclem** [comment]
Not in 1.2.

**Comment by stuclem** [comment]
Doesn't look like this is in 1.3.

**Comment by stuclem** [comment]
Not in 1.4.x.

**Comment by zjs** [comment]
Closing as vmware/vic#501 has been closed.
