### ISSUE TITLE
Document Registry hardware/software requirements

### ISSUE THREAD

**Issue by stuclem** [vmware/vic-product#1048]
Per https://github.com/vmware/harbor/issues/3572.

**Comment by stuclem** [comment]
This is a bit of a gap in the docs. High priority.

**Comment by alextopuzov** [comment]
Comments from Patrick over email:
Only a few minor things caught my eye:
- At the beginning of the page we say explicitely that running VCH on stand-alone ESXi is NOT supported. Yet standalone ESXi is listed in supported configurations and referenced throughout the requirements. You should check with Siddharth Popli of GSS to confirm that it is supported. 
- In the storage section, we need to be more explicit about shared storage needing to be visible from all members of he vSphere cluster.

**Comment by stuclem** [comment]
I think that the first point is a misunderstanding by @pdaigle. We say that deployment to an ESXi host is not supported for the OVA deployment, not for VCHs. For VCHs we do say that deployment to an ESXi host is supported. This has been clarified by adding a sub-heading to make it clear that we're talking about the appliance, not VCHs, when we say that deployment to ESXi is not supported. I have addressed both of these concerns in a recent update that I have not yet merged:

https://github.com/stuclem/vic-product/blob/vchui/docs/user_doc/vic_vsphere_admin/vic_installation_prereqs.md

As for storage, I think that the statement is also clarified in the above update.

**Comment by stuclem** [comment]
Merged in https://github.com/vmware/vic-product/pull/1259/
