### ISSUE TITLE
Document that vic-machine creates default volume store automatically

### ISSUE THREAD

**Issue by stuclem** [vmware/vic-product#105]
_From @stuclem on October 26, 2016 8:49_

Per https://github.com/vmware/vic/issues/2899. An option will exist to disable this behaviour. https://github.com/vmware/vic/issues/2899 is in the icebox, so this is for a future release.

_Copied from original issue: vmware/vic#2904_

**Comment by stuclem** [comment]
Not in 1.2

**Comment by stuclem** [comment]
Doesn't look like this is in 1.3.

**Comment by stuclem** [comment]
Not in 1.4.x.

**Comment by zjs** [comment]
Closing as vmware/vic#2899 was closed.
