### ISSUE TITLE
Document change in behaviour of default datastore for volume-store when only one datastore available

### ISSUE THREAD

**Issue by stuclem** [vmware/vic-product#106]
_From @stuclem on August 12, 2016 14:7_

Per https://github.com/vmware/vic/issues/1928.

_Copied from original issue: vmware/vic#1943_

**Comment by stuclem** [comment]
https://github.com/vmware/vic/issues/1928 is now in the icebox.

**Comment by stuclem** [comment]
https://github.com/vmware/vic/issues/1928 is still in the Icebox with no milestone, so leaving this doc issue in icebox too.

**Comment by stuclem** [comment]
Not in 1.2.

**Comment by stuclem** [comment]
Doesn't look like this is in 1.3.

**Comment by stuclem** [comment]
Not in 1.4.x.

**Comment by zjs** [comment]
Closing as vmware/vic#1928 has been closed.
