### ISSUE TITLE
Update path to Harbor logs

### ISSUE THREAD

**Issue by stuclem** [vmware/vic-product#1065]
According to @reasonerjt, the log path will change in 1.3.

**Comment by ywk253100** [comment]
The directory structure of Harbor log files are changed from 
```
|── harbor_log_directory
        |── 2017-11-20
            |──adminserver.log
            |──ui.log
            |──other_component.log
        |──2017-11-21
            |──adminserver.log
            |──ui.log
            |──other_component.log
```
to
```
|── harbor_log_directory
        |──adminserver.log
        |──ui.log
        |──ui.log.1.gz
        |──ui.log.2.gz
        |──other_component.log
```

The log files are not put into the folder named by date anymore, they are all in the parent folder directly and rotated by rules defined.

**Comment by stuclem** [comment]
Thanks @ywk253100. New behaviour, so marking as a high priority.

**Comment by alextopuzov** [comment]
Looking at what we have, i'd say that no update is necessary as the current doc does not talk about date folders anyway: https://vmware.github.io/vic-product/assets/files/html/1.2/vic_vsphere_admin/appliance_logs.html

**Comment by stuclem** [comment]
@alextopuzov if you have confirmed that the parent directory is in the same place as before, then we can close this one.
