### ISSUE TITLE
VIC appliance config migration workflow

### ISSUE THREAD

**Issue by reasonerjt** [vmware/vic-product#1071]
**VIC Product version:**
OVA version 1.3.0

**Description**
Currently when migration of configuration has to be done by editing the 1.2.0 version of config files.

IMO, it would be better if it could be changed to **editing** the 1.3.0 version to carry the needed value from old configuration.  Otherwise, whenever there's a new configuration attribute introduced the script will need to be changed.

**Comment by andrewtchin** [comment]
@reasonerjt I agree that this approach should be an option for upgrade based on what the component developers prefer. A PR could be submitted to update to use this workflow as the Harbor team is responsible for the contents of the component upgrade script where the config migration takes place
https://github.com/vmware/vic-product/blob/master/installer/build/scripts/upgrade/upgrade-harbor.sh
https://github.com/vmware/vic-product/blob/master/installer/DESIGN.md#appliance-upgrade
