### ISSUE TITLE
VIC Shortcut on VCSA H5UI shows incorrect number of VCH and containers

### ISSUE THREAD

**Issue by lgayatri** [vmware/vic-product#1076]
VIC 1.3: vic-dev-2419-v1.3.0-dev1-178-gfbdb6d5.ova
VCSA : 6.5U1 GA

![image](https://user-images.githubusercontent.com/25006749/32794130-fdce0944-c98d-11e7-9b11-86a73f69583a.png)

Inventory shown is incorrect, I have 50 VCHs and 2500 containers on this VCSA.

**Comment by mhagen-vmware** [comment]
Issue moved to [vmware/vic-ui #49](https://github.com/vmware/vic-ui/issues/49) via [**ZenHub**](https://www.zenhub.com/)
