### ISSUE TITLE
Update doc links in Getting Started page to point to the 1.3 docs and mention VCH Creation Wizard

### ISSUE THREAD

**Issue by stuclem** [vmware/vic-product#1081]
The links in the Getting Started page currently point to the 1.2 docs. We need to update all URLs to include  1.3. For example:

https://vmware.github.io/vic-product/assets/files/html/1.3/

I will create (but not publicize) a 1.3 version of the doc at that location in the coming days.

**Comment by stuclem** [comment]
@andrewtchin, placeholder docs are now live at https://vmware.github.io/vic-product/assets/files/html/1.3/. It should hopefully be a case of substituting `/1.2` with `/1.3` in all Getting Started links, but now we can check that they all work.

**Comment by stuclem** [comment]
@mdubya66 this really needs to be in 1.3, as the getting started links all currently point to 1.2 docs.

@andrewtchin here are the updated links for Getting Started page in 1.3:

**Open the Management Portal**

**READ MORE** : https://vmware.github.io/vic-product/assets/files/html/1.3/vic_cloud_admin/

**Post-Install & Deployment Tasks** 

1. Install vSphere Client plug-ins on vCenter Server: https://vmware.github.io/vic-product/assets/files/html/1.3/vic_vsphere_admin/install_vic_plugin.html 
2. Deploy VCHs: https://vmware.github.io/vic-product/assets/files/html/1.3/vic_vsphere_admin/deploy_vch.html
3. Manage VCHs: https://vmware.github.io/vic-product/assets/files/html/1.3/vic_vsphere_admin/vch_admin.html

**Configuration Tasks** 

1. Configure the management portal: https://vmware.github.io/vic-product/assets/files/html/1.3/vic_cloud_admin/configure_system.html
2. Create projects: https://vmware.github.io/vic-product/assets/files/html/1.3/vic_cloud_admin/create_projects.html
3. Add users: https://vmware.github.io/vic-product/assets/files/html/1.3/vic_cloud_admin/add_users.html
4. Add hosts to the management portal: https://vmware.github.io/vic-product/assets/files/html/1.3/vic_cloud_admin/vchs_and_mgmt_portal.html
3. Add registries to the management portal: https://vmware.github.io/vic-product/assets/files/html/1.3/vic_cloud_admin/add_repos_in_portal.html
6. Run projects and provision containers: https://vmware.github.io/vic-product/assets/files/html/1.3/vic_app_dev/run_dev_project.html

**Deploy a Demo VCH** 

I _strongly_ recommend that we remove this whole section, even if we don't remove the demo VCH wizard itself. See https://github.com/vmware/vic-product/issues/1144

**Deploy a VCH**

**READ MORE**:  https://vmware.github.io/vic-product/assets/files/html/1.3/vic_vsphere_admin/deploy_vch.html

**Comment by andrewtchin** [comment]
@jooskim @jak-atx @lweitzman What should we do for the removing the Deploy a Demo VCH section? 
![screen shot 2017-11-28 at 10 49 05 am](https://user-images.githubusercontent.com/1649165/33332407-d2554b8c-d429-11e7-8b4e-b6b160c3a832.jpg)

**Comment by lweitzman** [comment]
Summary page in the plugin area now includes some introductory text and a link to the full documentation. 
![screen shot 2017-11-28 at 4 23 22 pm](https://user-images.githubusercontent.com/626032/33344960-ab7eedf4-d458-11e7-888c-0d3b6c92f56c.png)
https://vmware.invisionapp.com/share/PYEK7TOCJ#/265003510_Plugin_-_Summary

**Comment by lweitzman** [comment]
updated the mockups to remove the deploy a demo VCH. 
https://vmware.invisionapp.com/share/8HD5AAYUQ#/249802786_Landing_Page_-_Install_Complete
![screen shot 2017-11-28 at 4 41 04 pm](https://user-images.githubusercontent.com/626032/33345636-fff479ec-d45a-11e7-9fbb-a071a0c42998.png)

**Comment by andrewtchin** [comment]
@lweitzman maybe we should also address https://github.com/vmware/vic-product/issues/1168 at the same time as this issue?

**Comment by stuclem** [comment]
@andrewtchin and @lweitzman I think that this issue automatically fixes https://github.com/vmware/vic-product/issues/1168, because the Deploy VCH link that I gave you above will be about using the UI-based deployment in the client. I haven't updated those topics yet, but this URL will include subtopics about both UI and CLI deployment of VCHs.

**Comment by andrewtchin** [comment]
changes for this will be in https://github.com/vmware/vic-product/tree/master/installer/fileserver/html

**Comment by stuclem** [comment]
@lweitzman the link for the green banner you cite in https://github.com/vmware/vic-product/issues/1081#issuecomment-347672926 should be https://vmware.github.io/vic-product/assets/files/html/1.3/vic_vsphere_admin/restart_services.html.

Thanks for spotting this!

**Comment by zjs** [comment]
We should fix this for 1.3.0.
