### ISSUE TITLE
Document revised upgrade procedure for 1.3

### ISSUE THREAD

**Issue by stuclem** [vmware/vic-product#1082]
Details TBC.

**Comment by andrewtchin** [comment]
The biggest changes are:
- Do NOT delete any disks from the new appliance - there should be 4 hard disks attached by default
- Add the disk from the old appliance to the new appliance as the 5th disk - Virtual Device Node should be `SCSI(0:4)`
- Updated upgrade script name is `upgrade.sh`
@morris-jason anything else?

**Comment by morris-jason** [comment]
I think the actual process is consistent with 1.1 upgrade, just with revised disk deletion:
- Delete *only* the data disk from the new appliance, this is the 2nd vmdk on the data store, likely titled `vic-<version>_1.vmdk`.
- Add the disk from the old appliance to the new appliance as the 2nd disk - Virtual Device Node should be `SCSI(0:1)`
- Updated upgrade script name is `upgrade.sh`

**Comment by morris-jason** [comment]
I think the actual process is consistent with 1.1 upgrade, just with revised disk deletion:
- Remove *only* the data disk from the _new_ appliance using the Edit Settings menu for virtual hardwae., this is the 2nd hard disk.
- Delete *only* the data disk vmdk on the data store for the _new_ appliance, likely titled `vic-<version>_1.vmdk`.
- Move the data disk from the _old_ appliance folder on the data store to the _new_ appliance folder. 
- Add the data disk from the _old_ appliance to the _new_ appliance using the Edit Settings menu as the 2nd disk - Virtual Device Node should be `SCSI(0:1)`
- Updated upgrade script name is `upgrade.sh`

**Comment by stonezdj** [comment]
I followed @morris-jason 's guide to upgrade vic 1.2.1 to build:vic-dev-2485-v1.3.0-dev1-185-gbf98353.ova.  
The vic 1.2.1 contains a project testlibrary includes two repository: openldap and golang 
1.Screenshot of the upgrade.sh
<img width="1148" alt="screen shot 2017-11-17 at 10 11 42 am" src="https://user-images.githubusercontent.com/2696760/32926747-901af222-cb0e-11e7-9139-9a109be28f84.png">
2. The testlibrary is empty after migrate
![screen shot 2017-11-17 at 10 34 05 am](https://user-images.githubusercontent.com/2696760/32926775-b32c54cc-cb0e-11e7-82ab-a491bac391bd.png)

**Comment by stuclem** [comment]
Great, thanks @andrewtchin and @morris-jason. I'll test the procedure and write up accordingly.

**Comment by stuclem** [comment]
@morris-jason and @andrewtchin, @lgayatri and I have been discussing upgrade and have a question:

- In 1.2, disk 2 was 50GB
- In 1.3, disk 2 is only 20GB. I assume that this is because of the separation of persistent and non-persistent data into separate disks in 1.3.
- Presumably the upgrade script migrates the appropriate data from the 50GB disk into its new locations on disks 3 and 4.
- But, this presumably leaves us with a 50GB disk 2 in an upgraded 1.3 as opposed to a 20GB disk 2 in a freshly installed 1.3.

My main thought is that resource requirements are now different, depending on whether you did a fresh install or an upgrade. Also, I'm thinking about what will happen when I have to document upgrading from 1.3 to 1.4 and we have to do the same operation: in some cases disk 2 will be a 50GB disk and in others it'll be a 20GB disk, which makes selecting the correct disk more error-prone. 

Does this even matter? Thanks!

**Comment by stuclem** [comment]
@morris-jason and @andrewtchin, another observation: 

- Luckily, in the [1.2 upgrade doc](https://vmware.github.io/vic-product/assets/files/html/1.2/vic_vsphere_admin/upgrade_appliance.html), we do instruct users to move the VMDK file from 1.1 into the datastore folder for the new 1.2 appliance. Had we not done that, users who upgraded from 1.1 to 1.2 who are now attempting to upgrade from 1.2 to 1.3 would have to go looking for an old datastore folder from 1.1 to find that disk. Let's hope that they read the 1.2 upgrade doc carefully and obeyed this step. :)
- However, even though we do tell people to move the 1.1 VMDK file into the 1.2 datastore folder, we do not tell them to rename it. So, if you are upgrading a 1.2 appliance that was already upgraded from 1.1, the VMDK file that you move into the 1.3 datastore folder will actually most likely have a name that relates to 1.1. 

Again, I'm not sure whether this is much of an issue or whether there's anything that we can do about it, but it's going to require a bit of careful documentation, which is why I am recording this observation here.

**Comment by morris-jason** [comment]
@stuclem:
>So, if you are upgrading a 1.2 appliance that was already upgraded from 1.1, the VMDK file that you move into the 1.3 datastore folder will actually most likely have a name that relates to 1.1.

I'm not sure we can do anything (or should) about the naming of vmdks from 1.1/1.2 -> 1.3. It would require us renaming disks on the data store, or instructing vAdmin's to do so, which may be confusing and more documentation complexity. 

>But, this presumably leaves us with a 50GB disk 2 in an upgraded 1.3 as opposed to a 20GB disk 2 in a freshly installed 1.3.

This is true, and that's definitely confusing when considering your point on upgrades in the future, eg 1.3.1+, 1.5.
We considered an upgrade approach where the old data disk is added as a 5th vmdk, contents are copied off to the 2/3/4th disks, and then the 5th is detached and can be discarded. That seems to be in line with your concerns but is not in scope at the moment. Perhaps worth investigation.

**Comment by stuclem** [comment]
Thanks for the info @morris-jason. I'm not sure that I was expecting you to make any changes in 1.3. I suppose I was just thinking with my fingers while it was quiet over the Thanksgiving break :)

**Comment by stuclem** [comment]
@alextopuzov is doing the upgrade updates for 1.3.

**Comment by alextopuzov** [comment]
Hey guys, just finished upgrading from 1.2.1 to 1.3:
Here's the PR with the revised procedure: https://github.com/vmware/vic-product/pull/1175 
Here's the procedure itself in more readable format: https://github.com/alextopuzov/vic-product/blob/upgrade13/docs/user_doc/vic_vsphere_admin/upgrade_appliance.md

Happy to have feedback.
Thanks.

**Comment by alextopuzov** [comment]
Wanted to note that with the latest changes, during the upgrade the 1.2 disk is mapped as Hard disk 4 and not Hard Disk 2 as it's been the case so far. The next upgrade doc should tell users to detach Disk 4 if it is 50 GB or Disk 2 if Disk 4 is 20GB... It is getting more and more complicated for both doc and users.

**Comment by stuclem** [comment]
@morris-jason @andrewtchin ^^^^

**Comment by andrewtchin** [comment]
I agree we want to script this process
