### ISSUE TITLE
upgrade vic 1.2.1 to 1.3 ova version error

### ISSUE THREAD

**Issue by sigsbee** [vmware/vic-product#1084]
Add a 1.2.1(vic-v1.2.1-4104e5f9.ova) data disk to 1.3 ova(vic-dev-2446-v1.3.0-dev1-179-g59ab3a2.ova)
run /etc/vmware/upgrade/upgrade.sh
will see
```
Detected old OVA's version as 1.1.x. We no longer support this upgrade path.
If the version of the old OVA is not 1.1.x, please contract VMware support:
```

**Comment by stonezdj** [comment]
1.2.0 failed with same error
<img width="1095" alt="screen shot 2017-11-16 at 11 00 06 am" src="https://user-images.githubusercontent.com/2696760/32874558-b26eab40-ca58-11e7-9674-7b711227a1e1.png">

**Comment by wy65701436** [comment]
**What we did**
1, Keep all disks(4 disks) on the new appliance(1.3), do not delete any of them.
2, Add the 50GB to the new appliance as the 5th disk -- SCSI(0:4).
3, Run the upgrade script.
Then, got the above error message. 

**Investigate**
From the source code(https://github.com/vmware/vic-product/blob/master/installer/build/scripts/upgrade/upgrade.sh#L99), it confirms the existence of psc-config.properties, but the /storage/data is SCSI(0:1), fail always.

**Furthermore** 
We did remove the SCSI(0:1) and add the 50GB as the second disk. And the upgrade can be executed. But I saw there is an version file in the old /data disk points to 1.2 artifact, if we add this disk as SCSI(0:1) in the new appliance, the upgrade script should handle the version upgrading. 

@andreiw, can you help to confirm the correctly steps?

**Comment by andrewtchin** [comment]
@morris-jason will update upgrade instructions in #1082

**Comment by andrewtchin** [comment]
@sigsbee @stonezdj sorry my instructions provided yesterday were wrong, updated instructions are in #1082

**Comment by andrewtchin** [comment]
Closing this as Yan verified the correct instructions work
