### ISSUE TITLE
Document how to configure NSX-T for VIC

### ISSUE THREAD

**Issue by stuclem** [vmware/vic-product#1088]
We provide no guidance on configuring NSX logical switches. This is a major gap that needs to be addressed.

**Comment by stuclem** [comment]
Per @pdaigle we need something similar to this doc from VIO: https://pubs.vmware.com/integrated-openstack-1/index.jsp?topic=%2Fcom.vmware.openstack.getstart.doc%2FGUID-3E07562F-0B02-406E-A22B-3513636ED9D7.html

**Comment by stuclem** [comment]
Needed, but not a new feature. Medium.

**Comment by stuclem** [comment]
We don't have sufficient info about this. @hickeng @renmaosheng where can we find information about how to configure NSX for use with VIC? Thanks!

**Comment by stuclem** [comment]
NSX-T support is new in 1.5, but we currently do not provide any docs about NSX at all.

**Comment by stuclem** [comment]
Per https://github.com/vmware/vic-planning/issues/92.

**Comment by stuclem** [comment]
@lgayatri can you please confirm the supported versions of NSX-T? Thanks!

**Comment by lgayatri** [comment]
@stuclem , Version would be NSX T 2.3 (with latest patches)

**Comment by stuclem** [comment]
Thank you @lgayatri !

**Comment by stuclem** [comment]
Some info from @yuyangbj via email:

1. You need to create at least two logical switches for bridge and container network in NSXT
2. Make sure you can see these two opaque networks in vCenter
3. Make sure all hosts in the compute cluster are managed by these two opaque networks
4. Set these two opaque networks as bridge and container network via `vic-machine` cmd or UI
5. If you use logical switches for the other networks, you need to make sure that the logical switch can talk to the outside if you use it for the public network
6. [In response to Q about how many T0 and T1 routers are needed]: For the bridge network, we do not care about layer 3, so we do not need T1 and T0. For container network, that depends how you use it. If you want to access to container VMs from outside, you may need T1 for bridging overlay and underlay network. But if you only want to validate the container connection via container network, then you do not care about T1 and T0.

**Comment by lgayatri** [comment]
@stuclem , the NSX T version we are using for this release is 2.3.1.
