### ISSUE TITLE
Upgrade from 1.2.x to 1.3 need to remove some file and directory 

### ISSUE THREAD

**Issue by stonezdj** [vmware/vic-product#1095]
**VIC Product version:**

OVA version:   vic-dev-2485-v1.3.0-dev1-185-gbf98353.ova

**Deployment details:**

Migrate from 1.1.x to 1.2.1, then migrate 1.2.1 to vic 1.3.0

**Steps to reproduce:**
1. Deploy vic 1.1.x ova
2. Migrate vic 1.1.x to vic 1.2.1
3. Migrate vic 1.2.1 to vic 1.3.0

**Actual behavior:**
Failed three times with different message:
**First time:**
Directory /storage/data/harbor_backup already exists. If upgrade is not already running or previously completed, remove the directory and retry upgrade.
**Second time:**
If upgrade is not already running or completed, execute the following command and rerun the upgrade script:
    rm /etc/vmware/admiral/upgrade_status
**Third time:**
Directory /storage/data/harbor_migration already exists. If upgrade is not already running or previously completed, remove the directory and retry upgrade.
**Expected behavior:**
List all these file/directories need to remove

- rm -rf /etc/vmware/admiral/upgrade_status
- rm -rf /storage/data/harbor_migration
- rm -rf /storage/data/harbor_backup

**Comment by andrewtchin** [comment]
@stonezdj @wy65701436 @reasonerjt Can we remove `harbor_migration` and `harbor_backup` after a successful upgrade?

**Comment by wy65701436** [comment]
what are these files for? If you are using these files as a upgrade flag, what will happen if user run it again?

**Comment by stonezdj** [comment]
These file/directories were generated when migrate from vic 1.1.x to 1.2.1, need to manualy remove them before upgrade 1.2.1 to 1.3.0

**Comment by wy65701436** [comment]
If presence of these files is used to determine the upgrade result, it should be there. Otherwise, how could the upgrade script to stop user to run it again?

But for the issue, it could add the version as the suffix rather than hard code the name.

**Comment by andrewtchin** [comment]
`harbor_migration` is from `docker run -ti --rm -e DB_USR=${DB_USER} -e DB_PWD=${DB_PASSWORD} -e EXPORTPATH=/harbor_migration -v ${harbor_migration}:/harbor_migration -v ${harbor_database}:/var/lib/mysql ${migrator_image} export`

`harbor_backup` is from `docker run -it --rm -e DB_USR=${DB_USER} -e DB_PWD=${DB_PASSWORD} -v ${harbor_database}:/var/lib/mysql -v ${harbor_backup}:/harbor-migration/backup ${migrator_image} backup`

Does the user need to keep these two things ever? If not, we can document a manual step before upgrade to 1.3 or add a prompt to remove these in the upgrade script and version any backup files going forward and remove the `upgrade_status` file after a successful upgrade.

**Comment by wy65701436** [comment]
harbor_migration could be removed as they are the temporary results for import script. And it's 1.2 only.
harbor_backup could be also removed after a successful upgrade, but reserve after a failure. Or give user an option to determine whether to reserve them. But, whatever it should not block the upgrade process. I think you ca

**Comment by andrewtchin** [comment]
Sounds good thanks
