### ISSUE TITLE
Document that demo VCH wizard is deprecated in 1.3

### ISSUE THREAD

**Issue by stuclem** [vmware/vic-product#1106]
Per Slack chat with @andrewtchin we are not adding any new features to the demo VCH wizard, but it will still be present in 1.3. The docs should mention that it's deprecated and direct users to the vSphere Client VCH deployment wizard.

**Comment by stuclem** [comment]
Actually, following conversation with @mdubya66 we might remove the demo VCH wizard completely in 1.3. Leaving this one in Verify until a decision is made.

**Comment by stuclem** [comment]
In the end I removed the topic on the Demo installer completely. Because the demo installer requires you to have downloaded the vic-machine bundle and run vic-machine update firewall, keeping the demo installer procedure in the doc really screws up the order that I have to present the topics in. Without it, I can present the topics in a more logical sequence.

**Comment by stuclem** [comment]
Leaving this one in verify pending decision to remove in https://github.com/vmware/vic-product/issues/1144. The only remaining mentions in the doc are in the OVA installer topic and ports reference.

**Comment by stuclem** [comment]
@andrewtchin @mdubya66 did we decide to leave the demo VCH wizard in the product, and just remove it from the Getting Started page?

**Comment by andrewtchin** [comment]
I think we're only removing it from the Getting Started page

**Comment by stuclem** [comment]
Confirmed by @mdubya66. The demo VCH wizard is marked as deprecated in the only places where it is still necessary to mention it (OVA deployment and ports ref).
