### ISSUE TITLE
Document supported Docker versions for 1.3

### ISSUE THREAD

**Issue by stuclem** [vmware/vic-product#1112]
The doc currently states: "vSphere Integrated Containers Engine 1.3 supports Docker client 1.13.0. The supported version of the Docker API is 1.25." This was carried over from 1.2.

@mdubya66 @mhagen-vmware is this still correct?

**Comment by stuclem** [comment]
Also "vSphere Integrated Containers Engine 1.3 supports [Docker Compose file version 2 and 2.1](https://docs.docker.com/compose/compose-file/compose-file-v2/)."

**Comment by mdubya66** [comment]
Yes. No changes to this have been made.

**Comment by stuclem** [comment]
OK, thanks @mdubya66
