### ISSUE TITLE
Add security information for Registry and Portal

### ISSUE THREAD

**Issue by stuclem** [vmware/vic-product#112]
We need to provide a security reference doc for all VMware products. We have such a doc for VIC Engine, but we need the same information for Registry/Portal:

https://github.com/vmware/vic-product/blob/master/docs/user_doc/vic_vsphere_admin/security_reference.md

@martin-borisov and @bradmeiseles can you please provide the corresponding information for Harbor/Admiral, or put me in contact with someone who knows?

Thanks!

**Comment by stuclem** [comment]
Some general updates are required to remove instances of "engine", etc.

**Comment by stuclem** [comment]
@alextopuzov can you please investigate the Admiral aspects of this? Thanks!

**Comment by stuclem** [comment]
@martin-borisov and @hainingzhang can you please provide the relevant Admiral and Harbor security information to this issue, so that we can update the [Security Reference](https://github.com/vmware/vic-product/blob/master/docs/user_doc/vic_vsphere_admin/security_reference.md) to cover all three VIC components? Thanks!

**Comment by stuclem** [comment]
@sergiosagu and @reasonerjt can you please provide the following security-related information for Admiral/Harbor?

- External interfaces and ports used
- Any vSphere services used
- Service accounts and privileges  created during deployment (as opposed to user accounts)
- I imagine that we need the exact privileges of the example users created during OVA deployment too
- Where to find security related log messages
- Any sensitive data that Admiral/Harbor might store.

For examples of the kinds of information we need, please see https://github.com/vmware/vic-product/blob/master/docs/user_doc/vic_vsphere_admin/security_reference.md.

**Comment by sergiosagu** [comment]
@stuclem - sorry for the delay, let me know if you need anything else about Admiral.

> External interfaces and ports used

Admiral exposes its UI and API via port 8282.

> Any vSphere services used

Should the PSC integration be mentioned here? Apart from that Admiral does not make use of any vSphere service.

> Service accounts and privileges created during deployment (as opposed to user accounts)

Admiral does not have any service account created for its usage.

> I imagine that we need the exact privileges of the example users created during OVA deployment too

There are 3 example users created during the OVA deployment:
- default cloud administrator - who has the Cloud Admin role assigned
- default project administrator (for the default project) - who has the DevOps Admin role assigned in the context of the Default project
- default developer (for the default project) - who has the Developer role assigned in the context of the Default project

> Where to find security related log messages

There's no specific file for security related log messages in Admiral. All Admiral logs are available, for example, via the standard `docker logs`.

> Any sensitive data that Admiral/Harbor might store.

Admiral stores credentials to access 3rd party (Docker) hosts and registries in a safe manner. Private parts of those credentials (passwords or private keys) are kept encrypted in Admiral's data store.

**Comment by stuclem** [comment]
Now it's my turn to apologize for the delay, @sergiosagu. Thank you!

@reasonerjt can you please provide similar information for Harbor? Thanks!
