### ISSUE TITLE
Error while powering on containers - "Server error from portlayer: could not find IP range"

### ISSUE THREAD

**Issue by lgayatri** [vmware/vic-product#1123]
@andrewtchin @cgtexmex @mhagen-vmware 

![image](https://user-images.githubusercontent.com/25006749/33111526-9e35474e-cf74-11e7-9b8b-950373bfd907.png)

![image](https://user-images.githubusercontent.com/25006749/33111538-ad43dc28-cf74-11e7-8ac2-9b850f0c4886.png)

Service https://10.197.37.143:2376/v1.24/containers/c8b910a14b383e2d473ac18befbc220d0e072829e9b44424cf8554714f21ac49/start returned error 500 for POST. id 284135304 message Server error from portlayer: could not find IP range; Reason: {"message":"Server error from portlayer: could not find IP range"}
docker-personality.log says:
```
Nov 22 2017 05:09:54.751Z INFO  volumes found:
Nov 22 2017 05:09:55.326Z WARN  error getting config from source: config not modified
Nov 22 2017 05:14:47.145Z ERROR Operation failed with errors.apiError{error:(*errors.errorString)(0xc420a15240), statusCode:500}
Nov 22 2017 05:14:47.145Z ERROR Handler for POST /v1.24/containers/c8b910a14b383e2d473ac18befbc220d0e072829e9b44424cf8554714f21ac49/start returned error: Server error from portlayer: could not find IP range
Nov 22 2017 05:14:48.231Z ERROR Operation failed with errors.apiError{error:(*errors.errorString)(0xc4202c9ad0), statusCode:500}
Nov 22 2017 05:14:48.231Z ERROR Handler for POST /v1.24/containers/c8b910a14b383e2d473ac18befbc220d0e072829e9b44424cf8554714f21ac49/start returned error: Server error from portlayer: could not find IP range
Nov 22 2017 05:14:48.379Z ERROR Operation failed with errors.apiError{error:(*errors.errorString)(0xc420573f30), statusCode:500}
Nov 22 2017 05:14:48.379Z ERROR Handler for POST /v1.24/containers/c8b910a14b383e2d473ac18befbc220d0e072829e9b44424cf8554714f21ac49/start returned error: Server error from portlayer: could not find IP range
Nov 22 2017 05:14:48.661Z ERROR Operation failed with errors.apiError{error:(*errors.errorString)(0xc42048b360), statusCode:500}
Nov 22 2017 05:14:48.661Z ERROR Handler for POST /v1.24/containers/c8b910a14b383e2d473ac18befbc220d0e072829e9b44424cf8554714f21ac49/start returned error: Server error from portlayer: could not find IP range

```

Logs attached.

**Comment by lgayatri** [comment]
[container-logs (2).zip](https://github.com/vmware/vic-product/files/1494714/container-logs.2.zip)

**Comment by lgayatri** [comment]
Hitting this issue on other VCHs too.

![image](https://user-images.githubusercontent.com/25006749/33113026-34d1bb54-cf7c-11e7-8e17-44ca9a7a8fcf.png)

**Comment by mdubya66** [comment]
@sergiosagu could this be related to the ip range work we did?

**Comment by sergiosagu** [comment]
@mdubya66 - hmm... I don't think so, but we should investigate it.

@lgayatri - could you attach the application template that you used for the deployment? or perhaps to create one if you ran the container directly.

**Comment by lgayatri** [comment]
@sergiosagu , I have live setup. Please take a look

https://10.197.37.132:8282/#/home/containers - administrator@vsphere.local/Admin!23 and root/Admin!23

**Comment by sergiosagu** [comment]
@mdubya66 - It's looks like it could be something with the VCH host itself.

I've found these:
- https://github.com/vmware/vic/issues/4237
- https://github.com/vmware/vic/issues/6751

Probably someone from the engine team should take a look.

**Comment by andrewtchin** [comment]
@lgayatri Were these VCHs restarted? What are the steps to reproduce this?

**Comment by andrewtchin** [comment]
Issue moved to [vmware/vic #6851](https://github.com/vmware/vic/issues/6851) via [**ZenHub**](https://www.zenhub.com/)

**Comment by lgayatri** [comment]
@andrewtchin , VCHs were not restarted
