### ISSUE TITLE
Overhaul the topics on constraints of using VIC in App Dev doc

### ISSUE THREAD

**Issue by stuclem** [vmware/vic-product#113]
Many of the constraints and limitations of using VIC as an application developer have been relaxed since 0.8/0.9. As a consequence, the following topics require updating:

- [Constraints of Using vSphere Integrated Containers Engine to Build Applications](https://github.com/vmware/vic-product/blob/master/docs/user_doc/vic_app_dev/constraints_using_vic.md)
- [Use and Limitations of vSphere Integrated Containers Engine](https://github.com/vmware/vic-product/blob/master/docs/user_doc/vic_app_dev/container_limitations.md) 
- [Creating a Containerized Application with vSphere Integrated Containers Engine](https://github.com/vmware/vic-product/blob/master/docs/user_doc/vic_app_dev/creating_containerized_app_with_vic.md)
- [Example of Building an Application with vSphere Integrated Containers Engine](https://github.com/vmware/vic-product/blob/master/docs/user_doc/vic_app_dev/build_app_with_vic.md)

**Comment by stuclem** [comment]
In [Example of Building an Application with vSphere Integrated Containers Engine](https://github.com/vmware/vic-product/blob/master/docs/user_doc/vic_app_dev/build_app_with_vic.md), the example is adapted because VIC did not support `build`, `tag`, or `push`. VIC 1.1 supports `tag`. @chengwang86 does this affect the voting example? Thanks!

**Comment by chengwang86** [comment]
@stuclem I remember that we still do not support push. So even if we tag the image by VIC, we cannot push it to the registry. I think we don't need to change your current write-up for the voting example.

**Comment by stuclem** [comment]
Great, thanks @chengwang86!

**Comment by stuclem** [comment]
I have just reread all of the developer doc and the examples appear to be OK. With @chengwang86 's comment above, I am happy to close this one.
