### ISSUE TITLE
Add conceptual diagrams for VIC

### ISSUE THREAD

**Issue by stuclem** [vmware/vic-product#1130]
At present we only have one conceptual diagram for VIC Engine, which is horribly out of date:
https://vmware.github.io/vic-product/assets/files/html/1.3/vic_overview/introduction.html#concepts

@pdaigle @pescerosso do you have any decent architectural/conceptual diagrams for all of VIC that we can reuse? Thanks!

**Comment by stuclem** [comment]
Also @emeirelles, do you have anything? Thanks!

**Comment by alextopuzov** [comment]
We can use this image from TMM as reference. 
![image](https://user-images.githubusercontent.com/22492280/33133042-2bbf8fbe-cfa4-11e7-82ae-364cedecd775.png)

**Comment by stuclem** [comment]
@alextopuzov I like this one a lot. We should definitely get this tidied up and included in the overview. Thanks!

**Comment by alextopuzov** [comment]
I've made a more IX styled diagram that needs to be reviewed before i send it to the graphics designer.
![conceptual-overview](https://user-images.githubusercontent.com/22492280/33174853-4fafaad0-d062-11e7-9f5a-6f5e0ffa6338.png)

**Comment by stuclem** [comment]
@alextopuzov I like it a lot. As discussed, I think that this deserves to be in a separate topic, for maximum visibility. So we should pull the User Roles content out of the Overview and slap it into a separate topic, with this pic front and centre.

**Comment by stuclem** [comment]
@pdaigle @pescerosso @emeirell can you please review the image above before we send it to our graphic artist for beautification? Thanks!

**Comment by pdaigle** [comment]
A few comments:

1. Cloud Admin -> “Manages Hosts” should read “Manages Container Hosts”
2. "docker push" should go through DCH, not directly to the registry. One option would be to add a DCH endpoint (either as it's own entity or as a C-VM under the VCH). I believe the TMM document where you got the original diagram has a diagram the includes the DCH as well.

**Comment by stuclem** [comment]
@pdaigle would this do the trick? 

![dchphoton](https://user-images.githubusercontent.com/16718369/33612500-031eb4bc-d9d2-11e7-9c13-cb5444de8d99.jpg)

Obviously, this is a very rough sketch and the final version would be a lot less amateurish. 

Do we need to remove the `docker push` line from the Docker client to Registry?
