### ISSUE TITLE
Upgrade from OVA vic-v1.2.1-4104e5f9.ova to VIC 1.3 failed

### ISSUE THREAD

**Issue by lgayatri** [vmware/vic-product#1134]
@stuclem @andrewtchin @mhagen-vmware @mdubya66 

Upgrade Path - VIC 1.2.1 (vic-v1.2.1-4104e5f9.ova) to VIC 1.3 (vic-dev-2419-v1.3.0-dev1-178-gfbdb6d5.ova) 
Steps followed:
1. VIC 1.2.1 had inventory and was shutdown gracefully
2. Deployed new VIC 1.3 with above build and in Edit Settings  added Hard Disk 2 of VIC 1.2.1 as SCSI(0:4)
3. Powered on VIC 1.3
4. cd /etc/vmware/upgrade
```
./upgrade.sh
Enter vCenter Server FQDN or IP: wdc-stvc3944-152-dhcp212.eng.vmware.com
Enter vCenter Administrator Username: administrator@vsphere.sgp.dbs.com
Enter vCenter Administrator Password:
If using an external PSC, enter the FQDN of the PSC instance (leave blank otherw                                                                                                                     ise): wdc-stvc3944-152-dhcp211.eng.vmware.com
If using an external PSC, enter the PSC Admin Domain (leave blank otherwise): vs                                                                                                                     phere.sgp.dbs.com

-------------------------
Starting upgrade 2017-11-23 07:09:51 +0000 UTC
Detected old OVA's version as 1.1.x. We no longer support this upgrade path.
If the version of the old OVA is not 1.1.x, please contact VMware support: root@
```
5. Code at which the script fails checking for a file existence.
```
# Check for presence of Admiral's PSC config file. If the file exists, the old
# OVA is version 1.2.x.
function proceedWithUpgrade {
  if [ ! -f "/storage/data/admiral/configs/psc-config.properties" ]; then
    echo "Detected old OVA's version as 1.1.x. We no longer support this upgrade path." | tee /dev/fd/3
    echo -n "If the version of the old OVA is not 1.1.x, please contact VMware support: " | tee /dev/fd/3
    exit 1
  else
```
6. The admiral folder is empty.

/storage/data/admiral ]# ls
root@vic-st-h2-186 [ /storage/data/admiral ]#

**Comment by lgayatri** [comment]
journalctl attached: 
[LG-upgrade1.2.1-1.3-186.zip](https://github.com/vmware/vic-product/files/1498305/LG-upgrade1.2.1-1.3-186.zip)

Interesting notes:
```
Nov 23 07:09:00 vic-st-h2-186.eng.vmware.com systemd[1]: Reloading.
Nov 23 07:09:00 vic-st-h2-186.eng.vmware.com systemd[1]: Configuration file /etc/systemd/system/systemd-networkd-wait-online.service.d/50-override-start.conf is marked world-inaccessible. T
his has no effect as configuration data is accessible via APIs without restrictions. Proceeding anyway.
Nov 23 07:09:00 vic-st-h2-186.eng.vmware.com systemd[1]: Started Loads Cached Docker Images.
Nov 23 07:09:00 vic-st-h2-186.eng.vmware.com systemd[1]: Reached target System customization for VIC(Integrated containers engine on vSphere) based on user provided parameters.
Nov 23 07:09:00 vic-st-h2-186.eng.vmware.com systemd[1]: Started VIC Appliance Environment.
Nov 23 07:09:00 vic-st-h2-186.eng.vmware.com systemd[1]: vic_machine_server.service: Failed to load environment files: No such file or directory
Nov 23 07:09:00 vic-st-h2-186.eng.vmware.com systemd[1]: vic_machine_server.service: Failed to run 'start-pre' task: No such file or directory
Nov 23 07:09:00 vic-st-h2-186.eng.vmware.com systemd[1]: Failed to start VIC Machine API.
Nov 23 07:09:00 vic-st-h2-186.eng.vmware.com systemd[1]: vic_machine_server.service: Unit entered failed state.
```

**Comment by lgayatri** [comment]
I also tried with the steps outlined by @morris-jason https://github.com/vmware/vic-product/issues/1082 , but still seeing the same issue.

/storage/data/admiral/configs/psc-config.properties is not available

The Hard disk from old appliance is added as SCSI(0:1) and is Hard disk 4.
![image](https://user-images.githubusercontent.com/25006749/33167591-00c8f05a-d064-11e7-8813-21e9d1d3c4d4.png)

**Comment by gmuleshkov** [comment]
The admiral upgrade process is not touching the file /storage/data/admiral/configs/psc-config.properties. @andrewtchin Can you please take a look at this. I suppose that it is something related to the OVA upgrade process. For the upgrade from 1.2.1 to 1.3 for admiral we just need the old storage and config folders on the same places as on the old instance.

**Comment by morris-jason** [comment]
@lgayatri 
>Deployed new VIC 1.3 with above build and in Edit Settings added Hard Disk 2 of VIC 1.2.1 as SCSI(0:4)
This is not going to work. Hard Disk 2 from VIC 1.2.x, the _data disk_, needs to be migrated Hard disk 2 on VIC 1.3.x, that is why I mentioned `SCSI(0:1)`. 
The screenshot you posted is puzzling because it says Hard disk 4 and SCSI(0:1).

**Comment by lgayatri** [comment]
@morris-jason , can you please update the correct sequence of upgrade steps from 1.2.x to 1.3? I will try again asap.

**Comment by andrewtchin** [comment]
@lgayatri the updated docs are in progress here https://github.com/vmware/vic-product/issues/1082

**Comment by andrewtchin** [comment]
This looks like an issue with the disk ordering as I verified this process works with these versions today.

**Comment by lgayatri** [comment]
@morris-jason , As Hard Disk 2 which SCSI 0:1 was deleted from the newly deployed OVA the SCSI adapter was free, I reused the same while adding the Hard Disk2 from 1.2 OVA. Hence the screenshot.
