### ISSUE TITLE
Create VCH fails with "VIC appliance VM was not found or unreachable. Please make sure you have deployed it correctly."

### ISSUE THREAD

**Issue by lgayatri** [vmware/vic-product#1135]
@jooskim 
VIC 1.3 - vic-dev-2419-v1.3.0-dev1-178-gfbdb6d5.ova
VCSA: 6.5U1

![image](https://user-images.githubusercontent.com/25006749/33164525-37977d78-d059-11e7-8c11-ca762265e78c.png)

My inventory looks like : 
![image](https://user-images.githubusercontent.com/25006749/33165200-e9bce338-d05b-11e7-8e64-1611df93d7df.png)

Please feel free to SSH to VCSA 10.133.146.15 - root/Admin!23

**Comment by stuclem** [comment]
I just successfully created a VCH by using the wizard on the VC that @jooskim set up for me, that includes the fix for https://github.com/vmware/vic-ui/issues/105, which is in PR https://github.com/vmware/vic-ui/pull/114 (not merged yet).

**Comment by lgayatri** [comment]
Once the latest build is available, I will retry this to confirm.

**Comment by lgayatri** [comment]
@jooskim mentioned that the related code got merged last evening. Hope to get my hands on new build soon.

**Comment by stuclem** [comment]
I just deployed OVA build 2603, VIC bundle 15115, and I'm still seeing the same issue with the compute resources selector spinning endlessly

**Comment by stuclem** [comment]
When I cancel the VCH deployment, I see the following:

![certerror](https://user-images.githubusercontent.com/16718369/33272195-bd3887aa-d389-11e7-8fe7-27f4a8e9b31c.jpg)

If I click the `FIX` button, I fail to connect:

![fixbutton](https://user-images.githubusercontent.com/16718369/33273394-7164f184-d38d-11e7-8391-9d7d588774fe.jpg)

**Comment by andrewtchin** [comment]
Issue moved to [vmware/vic-ui #122](https://github.com/vmware/vic-ui/issues/122) via [**ZenHub**](https://www.zenhub.com/)
