### ISSUE TITLE
Remove demo VCH deployment from OVA?

### ISSUE THREAD

**Issue by stuclem** [vmware/vic-product#1144]
With the arrival of the VCH deployment wizard in the vSphere Client, the demo VCH deployment wizard is redundant. @andrewtchin and @morris-jason tell me that no dev work is being done on it in 1.3. I marked it as deprecated in the docs in https://github.com/vmware/vic-product/issues/1106, but @mdubya66 questions whether we should remove it completely. 

@pdaigle, what do you think?  Even if we don't remove it completely, we should probably remove it from the Getting Started page, as users will possibly see the link to the demo installer in that page before they see the full installer in the vSphere Client plugin. It won't be a great user experience if users deploy a limited functionality VCH with the demo installer, only to discover that they could have deployed a full VCH in the client.

From a docs perspective, it will also be a lot tidier if we remove all mention of the demo installer.

**Comment by mhagen-vmware** [comment]
@stuclem We are not going to take the PR in #1222 into the 1.3 release, but we should remove all references to the demo VCH wizard and let people know not to use it in 1.3.  Thanks!

**Comment by stuclem** [comment]
We retain mentions of the demo VCH in the OVA installer topic, because it is mentioned in the UI, and in the ports reference, because that service is still running on port 1337. It's marked as deprecated in both places:

- [Deploy VIC Appliance](https://vmware.github.io/vic-product/assets/files/html/1.3/vic_vsphere_admin/deploy_vic_appliance.html) step 8
- [Ports Reference](https://vmware.github.io/vic-product/assets/files/html/1.3/vic_vsphere_admin/security_reference.html#open_ports)

**Comment by mdubya66** [comment]
Removing this from 1.3 after all. @stuclem

**Comment by andrewtchin** [comment]
Cherry pick PR has been merged
