### ISSUE TITLE
Failed to start VIC Machine API 

### ISSUE THREAD

**Issue by lgayatri** [vmware/vic-product#1146]
@mdubya66 @reasonerjt @mhagen-vmware @andrewtchin 
Build: https://storage.googleapis.com/vic-product-ova-releases/vic-v1.3.0-rc1-2601-0ab40094.ova 

1. Deployed OVA 1.3 and registered to VCSA(registration successful)
2  https://vic-st-h2-132.eng.vmware.com:8282/ opened and I downloaded ca.crt
3. After few minutes https://vic-st-h2-132.eng.vmware.com:8282/ page takes forever to load.

journalctl -f says:
```
Nov 27 11:24:32 vic-st-h2-132.eng.vmware.com systemd[1]: Failed to start VIC Machine API.
Nov 27 11:24:32 vic-st-h2-132.eng.vmware.com systemd[1]: vic_machine_server.service: Unit entered failed state.
Nov 27 11:24:32 vic-st-h2-132.eng.vmware.com systemd[1]: vic_machine_server.service: Failed with result 'exit-code'.
Nov 27 11:24:38 vic-st-h2-132.eng.vmware.com systemd[1]: vic_machine_server.service: Service hold-off time over, scheduling restart.
Nov 27 11:24:38 vic-st-h2-132.eng.vmware.com systemd[1]: Stopped VIC Machine API.
Nov 27 11:24:38 vic-st-h2-132.eng.vmware.com systemd[1]: Starting VIC Machine API...
Nov 27 11:24:38 vic-st-h2-132.eng.vmware.com docker[183767]: Error response from daemon: Cannot kill container vic-machine-server: No such container: vic-machine-server
Nov 27 11:24:38 vic-st-h2-132.eng.vmware.com docker[183776]: Error response from daemon: No such container: vic-machine-server
Nov 27 11:24:38 vic-st-h2-132.eng.vmware.com configure_vic_machine_server.sh[183785]: chown: cannot access '/storage/log/vic-machine-server': No such file or directory
Nov 27 11:24:38 vic-st-h2-132.eng.vmware.com systemd[1]: vic_machine_server.service: Control process exited, code=exited status=1
Nov 27 11:24:38 vic-st-h2-132.eng.vmware.com systemd[1]: Failed to start VIC Machine API.
Nov 27 11:24:38 vic-st-h2-132.eng.vmware.com systemd[1]: vic_machine_server.service: Unit entered failed state.
Nov 27 11:24:38 vic-st-h2-132.eng.vmware.com systemd[1]: vic_machine_server.service: Failed with result 'exit-code'.
...
```
Live setup available upon request until 11/29.

Attached journalctl 
[journalctl.zip](https://github.com/vmware/vic-product/files/1505663/journalctl.zip)

**Comment by pstroia** [comment]
Failing for me too.
Nov 27 11:20:43 Photon systemd[1]: Initializing machine ID from random generator.
Nov 27 11:21:44 Photon load-docker-images.sh[650]: Loaded image: gcr.io/eminent-nation-87317/vic-machine-server:v1.3.0-rc1
-- successfully started. Note that this does not mean that the machine is
Nov 27 11:23:17 Photon load-docker-images.sh[650]: Loading vic-machine-server
Nov 27 11:23:17 Photon systemd[1]: vic_machine_server.service: Failed to load environment files: No such file or directory
Nov 27 11:23:17 Photon systemd[1]: vic_machine_server.service: Failed to run 'start-pre' task: No such file or directory
-- Subject: Unit vic_machine_server.service has failed
-- Unit vic_machine_server.service has failed.

**Comment by morris-jason** [comment]
Note that there are two issues here:
 - @lgayatri's issue has a fix in in #1147. The work around is to create the log directory yourself with `mkdir -p /storage/log/vic-machine-server`.
 - @pstroia's issue is that vic-machine-server tried to start before the vic environment variables were set. Working on a fix, but that error should go away the next time the service tires to start, assuming the environment is created.

**Comment by mdubya66** [comment]
@mhagen-vmware cherry pick candidates

**Comment by lgayatri** [comment]
@morris-jason , I created the directory 
mkdir -p /storage/log/vic-machine-server
vic-machine-server.log says:
Nov 27 2017 15:54:38.896Z INFO  Starting Service. Version: "v1.2.0-rc1 git:18841ed-dirty build:2017/11/23@16:22:42 id:15115 runtime:go1.8.3"
Nov 27 2017 15:54:38.962Z INFO  Serving pprof at http://localhost:6060
Nov 27 2017 15:54:38.963Z INFO  Serving vic machine at http://[::]:80
Nov 27 2017 15:54:38.966Z INFO  Serving vic machine at https://[::]:443

IP address and port are showing blank in the log files.

And still https://vic-st-h2-132.eng.vmware.com:8282/ is not opening. Feel free to ssh to 10.197.37.132 with root/Admin!23.

**Comment by morris-jason** [comment]
@lgayatri This seems like a logging problem, the container is online and running at https://10.197.37.132:8443/.

**Comment by morris-jason** [comment]
I restarted admiral/harbor and they came up fine.
Before restart, admiral was continuously throwing:
```
[616][W][2017-11-27T07:03:31.176Z][199][8282/][lambda$verifyTokenInternal$38][Error verifying token: com.vmware.xenon
.common.jwt.Verifier$InvalidTokenException: Separator for header not found]
[617][W][2017-11-27T07:03:31.180Z][199][8282/auth/psc/callback][handlePost][Failed to verify token: com.vmware.xenon.
common.jwt.Verifier$InvalidTokenException: Separator for header not found
	at com.vmware.xenon.common.jwt.Verifier.verify(Verifier.java:49)
	at com.vmware.admiral.auth.idm.psc.service.PscAuthenticationService.handlePost(PscAuthenticationService.java:
293)
	at com.vmware.xenon.common.StatelessService.handleRequest(StatelessService.java:128)
	at com.vmware.xenon.common.StatelessService.handleRequest(StatelessService.java:103)
	at com.vmware.xenon.common.ServiceHost.lambda$queueOrScheduleRequestInternal$44(ServiceHost.java:4277)
	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1402)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
]
```
I assume this means admiral started with an invalid or incomplete psc token.

**Comment by lgayatri** [comment]
@morris-jason , are you able to access https://vic-st-h2-132.eng.vmware.com:8282/   after services restart ?
