### ISSUE TITLE
Clarify that Admiral containers are NOT container VMs?

### ISSUE THREAD

**Issue by stuclem** [vmware/vic-product#1153]
Per comment from @hickeng and @dbarkelew via Slack:

"A question from @dbarkelew today about healthcheck support. He pointed at https://vmware.github.io/vic-product/assets/files/html/1.2/vic_app_dev/provision_containers_portal.html

I'm guessing this is specifically supposed to relate to admiral? however the heading is `container VMs` so it's kind of confusing. We also do not support healthcheck in dockerfile: https://vmware.github.io/vic-product/assets/files/html/1.2/vic_app_dev/dockerfile_support.html

It's not that the instruction cases an error but we do not honor it in the Engine so I think this is misleading."

So, am I to infer from this that the containers that you provision in Admiral/Management Portal are NOT VIC container VMs? Is this the case even if the container host is a VCH? Or, do we need to make a distinction here between containers that you provision in a regular Docker host in Admiral/MP and containers that you provision in a VCH? @sergiosagu and @hickeng can you please clarify? Thanks!

**Comment by sergiosagu** [comment]
I'm not sure I fully understood what exactly to clarify but I'll give it a shot...
- "Infrastructure containers" that run in the OVA (e.g. admiral container, harbor containers, etc.) are not VMs (AFAIK).
- Containers deployed through the portal (Admiral) in VCH are VMs.
- Containers deployed through the portal (Admiral) in standard Docker hosts are not VMs.

IMO, having a section like "Provisioning Container VMs in the Management Portal" can be misleading when you are using standard Docker hosts from the portal for some reason. Maybe it should be just "Provisioning Containersin the Management Portal" and then, if needed, add some note to clarify that containers provisioned in standard Docker hosts are plain containers whereas when they are provisioned in VCH they are VMs behind the scenes...

**Comment by stuclem** [comment]
Thank you for the clarifications @sergiosagu. We definitely need to make this distinction plainly clear in the doc. This is not something that had ever occurred to me before!
