### ISSUE TITLE
Update landing page on vmware.com

### ISSUE THREAD

**Issue by stuclem** [vmware/vic-product#116]
Add a 1.1 section and links to new docs to https://www.vmware.com/support/pubs/vsphere-integrated-containers-pubs.html.

**Comment by stuclem** [comment]
Draft version is at http://wwwcontentdev.vmware.com:9299/support/pubs/vsphere-integrated-containers-pubs.html. 

Note that the doc links don't work yet as the new doc is not yet posted to github.io.

**Comment by stuclem** [comment]
Verify all links once the doc is posted to github.io before closing this.

**Comment by stuclem** [comment]
@alextopuzov please can you do some sanity checking on http://concrete2.vmware.com/support/pubs/vsphere-integrated-containers-pubs.html to make sure that everything is working correctly? Thanks!

**Comment by alextopuzov** [comment]
LGTM.
