### ISSUE TITLE
Deploying the OVA with ovftool results in warnings about file size mismatch

### ISSUE THREAD

**Issue by zjs** [vmware/vic-product#1166]
**VIC Product version:**

`vic-v1.3.0-rc2-2628-9e2a95b6.ova`

**Deployment details:**

vSphere Client version 6.5.0.10000

**Steps to reproduce:**

Use `ovftool` to deploy the OVA.

**Actual behavior:**

The process ends with:
```
Warning:
 - Wrong file size specified in OVF descriptor for 'vic-disk1.vmdk' (specified: 3276522496, actual 3359524864).
 - Wrong file size specified in OVF descriptor for 'vic-disk2.vmdk' (specified: 274432, actual 274944).
Completed successfully
```

**Expected behavior:**

The process does not include any error messages.

**Comment by zjs** [comment]
We need to understand the root cause of this issue before shipping 1.3.0. Once that is understood, we should re-triage and adjust the priority appropriately.

**Comment by andrewtchin** [comment]
I'm pretty sure this is because the ova build does not correctly rewrite the disk size after the vmdks are created. It's cosmetic, lowering priority

**Comment by andrewtchin** [comment]
This is not a ship stopper, don't work on this until all stoppers are cleared

**Comment by mdubya66** [comment]
Removing from 1.3. Adding kind/note.

**Comment by stuclem** [comment]
Release note: 

- <b>Deploying the OVA with ovftool results in warnings about file size mismatch. [#1166](https://github.com/vmware/vic-product/issues/1166)</b><br>If you use `ovftool` to deploy the appliance, the process ends with the error `Wrong file size specified in OVF descriptor for 'vic-disk1.vmdk'` and `'vic-disk2.vmdk'`.  However the deployment succeeds.  

   Workaround:  Ignore the error message.

@zjs @andrewtchin is this OK?

**Comment by stuclem** [comment]
Thanks @zjs and @andrewtchin. Removing kind/note.
