### ISSUE TITLE
The getting started page of the 1.3 OVA references 1.2 documentation

### ISSUE THREAD

**Issue by zjs** [vmware/vic-product#1167]
**VIC Product version:**

`vic-v1.3.0-rc2-2628-9e2a95b6.ova`

**Deployment details:**

N/A

**Steps to reproduce:**

Load the Getting Started page (on port 9443).

**Actual behavior:**

Documentation links refer to the 1.2 documentation

**Expected behavior:**

Documentation links refer to the 1.3 documentation

**Comment by andrewtchin** [comment]
Dupe of #1081
