### ISSUE TITLE
The list of instructions for deploying a VCH on the getting started page does not mention the VCH Creation Wizard

### ISSUE THREAD

**Issue by zjs** [vmware/vic-product#1168]
**VIC Product version:**

`vic-v1.3.0-rc2-2628-9e2a95b6.ova`

**Deployment details:**

N/A

**Steps to reproduce:**

Load the Getting Started page (on port 9443).

**Actual behavior:**

After registering the OVA with vSphere, a green note is displayed "Installation successful. Refer to the Post-install and Deployment tasks below." 

The section referred to by that note mentions two options for deploying VCHs: demo and production, using the CLI.

**Expected behavior:**

The instructions direct users to the new UI, both in the "Post-Install & Deployment Tasks" section and below, under "Infrastructure Deployment Tools".

**Comment by stuclem** [comment]
@zjs I submitted another issue that addresses this. See https://github.com/vmware/vic-product/issues/1081. We're removing the demo VCH link and so the only remaining link will be Deploy VCHs, that will point to information about both UI-based and CLI deployment. @andrewtchin can we close this one as a dup?

**Comment by andrewtchin** [comment]
Sure closing
