### ISSUE TITLE
Create release notes on vmware.com

### ISSUE THREAD

**Issue by stuclem** [vmware/vic-product#117]
New release notes for 1.1. To follow the same pattern as http://pubs.vmware.com/Release_Notes/en/vsphere-integrated-containers/10/vsphere-integrated-containers-10-release-notes.html, in which we just link to the Known Issues on GitHub for the 3 components.

**Comment by stuclem** [comment]
@alextopuzov can you please sanity check the RNs at http://tpub-stg-ic-1.eng.vmware.com:8080/Release_Notes/en/vsphere-integrated-containers/11/vsphere-integrated-containers-11-release-notes.html

**Comment by alextopuzov** [comment]
All reviewed, FB submitted, changes to be implemented where needed.
