### ISSUE TITLE
Document that only vSphere admins can use the Create VCH button

### ISSUE THREAD

**Issue by stuclem** [vmware/vic-product#1176]
Per https://github.com/vmware/vic-ui/issues/129

**Comment by stuclem** [comment]
Actually, per https://github.com/vmware/vic-ui/issues/129#issuecomment-347991195, the button will be visible to all, but will throw an error if someone with insufficient privileges tries to use it.

**Comment by stuclem** [comment]
Removed the note  from that stated that only vSphere Admins can see the button.

**Comment by stuclem** [comment]
The topic [Deploy Virtual Container Hosts in the vSphere Client](https://github.com/stuclem/vic-product/blob/vchui/docs/user_doc/vic_vsphere_admin/deploy_vch_client.md) states "Log in to the HTML5 vSphere Client with a vSphere administrator account..." in the first step of the procedure, so I think that this is covered.

@jak-atx and @zjs is this OK? Thanks!

**Comment by zjs** [comment]
Sounds good to me!
