### ISSUE TITLE
Cannot attach specific networks to containers

### ISSUE THREAD

**Issue by arslanabbasi** [vmware/vic-product#1181]
# For bug reports, please include the information below:

**VIC Product version:**

OVA version: 1.3.0-rc2

**Deployment details:**

Environment where the OVA is deployed

**Steps to reproduce:**
![image](https://user-images.githubusercontent.com/14361444/33507931-7636f294-d6ac-11e7-8c04-f70932f2f4c3.png)

![image](https://user-images.githubusercontent.com/14361444/33507707-1dee23f6-d6ab-11e7-9cb9-5a33bd6928e9.png)

**Actual behavior:**
There is no option to choose a specific networks when spawning containers from public repositories or containers tab in the VIC management portal. However, options are available when using templates. In the attached screenshots above, there is only a field called network mode. Setting this field to 'none' or 'host' results in the errors displayed in the screenshot above

**Expected behavior:**
The user should be able to choose networks, container network or bridge networks, when spawning containers from VIC management portal

![image](https://user-images.githubusercontent.com/14361444/33507852-f7e31594-d6ab-11e7-99cb-0e2485659420.png)

**Logs:**

**Additional details as necessary:**
Please let me know if any additional information is required

**Comment by andrewtchin** [comment]
Issue moved to [vmware/admiral #230](https://github.com/vmware/admiral/issues/230) via [**ZenHub**](https://www.zenhub.com/)

**Comment by andrewtchin** [comment]
@arslanabbasi Thanks for your report. I have moved this to the Admiral project where it will be investigated.
