### ISSUE TITLE
Adding 1 VCH to multiple projects results in Container Network being visible in only 1 Project

### ISSUE THREAD

**Issue by arslanabbasi** [vmware/vic-product#1182]
# For bug reports, please include the information below:

**VIC Product version:**

OVA version: 1.3.0-rc2

**Deployment details:**

**Steps to reproduce:**

**Actual behavior:**
If one VCH is added to multiple projects, the container network attached to this VCH is only visible in one project. 

**Expected behavior:**
Either the container network should be visible in all projects where that VCH is added or we limit the addition of VCH to only one project.

**Logs:**

**Additional details as necessary:**

# For stories, please include the information below:

**User Statement:**

**Details:**

**Acceptance Criteria:**

**Comment by andrewtchin** [comment]
Issue moved to [vmware/admiral #229](https://github.com/vmware/admiral/issues/229) via [**ZenHub**](https://www.zenhub.com/)

**Comment by andrewtchin** [comment]
@arslanabbasi Thanks for your report. I have moved this to the Admiral project where it will be investigated.
