### ISSUE TITLE
[UI] Spawining container using Container Networks not working

### ISSUE THREAD

**Issue by arslanabbasi** [vmware/vic-product#1183]
# For bug reports, please include the information below:

**VIC Product version:**

OVA version: 1.3.0-rc2

**Deployment details:**

Environment where the OVA is deployed

**Steps to reproduce:**

![image](https://user-images.githubusercontent.com/14361444/33508157-7f094056-d6ad-11e7-8742-a679ab57b7d5.png)

![image](https://user-images.githubusercontent.com/14361444/33508138-6e5a1eba-d6ad-11e7-898a-db0c0e232020.png)

![err3](https://user-images.githubusercontent.com/14361444/33403746-6cd86e40-d516-11e7-9b84-85c60bd24088.PNG)

![image](https://user-images.githubusercontent.com/14361444/33508169-93f7839c-d6ad-11e7-8a73-7aa62acbaf2a.png)

**Actual behavior:**
I cannot get a running container which is attached to the container network(name='routable' in my case) from VIC management portal. However, this is working using the CLI with "--net routable" flag. Which leads me to believe that this is a UI bug

**Expected behavior:**
A container should be spawned which is attached to the 'routable' network

**Logs:**

**Additional details as necessary:**
Please let me know if any additional information is required

**Comment by andrewtchin** [comment]
Issue moved to [vmware/admiral #228](https://github.com/vmware/admiral/issues/228) via [**ZenHub**](https://www.zenhub.com/)

**Comment by andrewtchin** [comment]
@arslanabbasi Thanks for your report. I have moved this to the Admiral project where it will be investigated.
