### ISSUE TITLE
Docs: reinforce warning against using networks not available to all hosts

### ISSUE THREAD

**Issue by stuclem** [vmware/vic-product#1189]
Per https://github.com/vmware/vic-ui/issues/73#issuecomment-347995448 we need to reinforce the warning in the docs about not using networks that are not available to all hosts in the cluster.

**Comment by stuclem** [comment]
Beefed up the recommendation about using a DPG for the public network in the following topics:

- [Networking Requirements for VCH Deployment](https://github.com/stuclem/vic-product/blob/vchui/docs/user_doc/vic_vsphere_admin/vic_installation_prereqs.md#vchnetworkreqs)
- [Configure the Public Network](https://github.com/stuclem/vic-product/blob/vchui/docs/user_doc/vic_vsphere_admin/public_network.md#public-network)

@hmahmood is this OK? Thanks!

**Comment by stuclem** [comment]
@hmahmood can you please review the following note?:

------

**IMPORTANT**: All hosts in a cluster must be attached to the port groups that you use for the VCH networks and for any mapped container networks.

------

Also, can you please take another look at the entire section on [Networking Requirements for VCH Deployment](https://github.com/stuclem/vic-product/blob/vchui/docs/user_doc/vic_vsphere_admin/vic_installation_prereqs.md#networking-requirements-for-vch-deployment)? Thanks!

**Comment by hmahmood** [comment]
Shouldn't this be a recommendation instead of a requirement? That note makes it seems like it is a requirement. 

From the section on Networking: "If you use the Create Virtual Container Host wizard to deploy VCHs, you must create and use a port group for the public network." Is this a requirement when using the wizard only or in general? It seems like this should again be a recommendation and we should caution against it, not be an absolute requirement.

**Comment by stuclem** [comment]
Thanks @hmahmood, I only just saw this. In the UI, public network is mandatory and it is a requirement to create a DPG for it. In the CLI, if you don't specify `--public-network`, then it defaults to VM Network. So, it's a requirement in the UI and a recommendation in the CLI. 

For the note about all hosts being attached to PGs, I downgraded it to "All hosts should...." rather than "must".

**Comment by stuclem** [comment]
Merged in https://github.com/vmware/vic-product/pull/1259/
