### ISSUE TITLE
Document that you really should use a DPG for public network

### ISSUE THREAD

**Issue by stuclem** [vmware/vic-product#1190]
Per @hickeng in https://github.com/vmware/vic-ui/issues/124#issuecomment-348033796, it seems that one should not rely on using the default VM Network for `--public-network`, and by extension, the default for `--management-network` and `--client-network`:

"Is VM Network a Distributed Port Group? If it's not and there's more than one host then it really isn't a good idea to chose it as it will prevent vMotion of the endpointVM."

The docs should strongly encourage the creation of a DPG, and detail the requirements.

**Comment by stuclem** [comment]
Added the following in [Deployment Prerequisites for vSphere Integrated Containers](https://github.com/stuclem/vic-product/blob/vchui/docs/user_doc/vic_vsphere_admin/vic_installation_prereqs.md#networking-requirements-for-vch-deployment-) and [Configure the Public Network](https://github.com/stuclem/vic-product/blob/vchui/docs/user_doc/vic_vsphere_admin/public_network.md#public-network-):

---

**NOTE**: It is strongly recommended that you create and use a dedicated port group for the public network. Using the default VM Network for the public network instead of a port group prevents vSphere vMotion from moving the VCH endpoint VM between hosts in the cluster. 

---

@hickeng and @hmahmood is this OK? Thanks!

**Comment by stuclem** [comment]
@hickeng and @hmahmood another question: does the port group that you create for the public network need to be unique to a VCH? Or, can you create one public network DPG and share it between VCHs? Thanks!

**Comment by hmahmood** [comment]
@stuclem you should be able to share a DPG between VCHs for public network. I am not sure why vMotion would not work if VM Network is used.

**Comment by stuclem** [comment]
Thanks @hmahmood. I see that you originally stated in the comment above that using VM Network should not prevent vMotion, but that you subsequently removed that statement. So, is it true that using VM Network DOES prevent vMotion of the VCH? Thanks!

**Comment by stuclem** [comment]
@hmahmood I clarified the statements about the public network port group in https://github.com/vmware/vic-product/pull/1259/commits/fde3a10ac03a0be0c00d95fef34513cc2b5ef00a. Is this OK? Thanks!

**Comment by hmahmood** [comment]
Yes, those statements look fine. 

I didn't read this in the original issue description: "Is VM Network a Distributed Port Group? If it's not and there's more than one host then it really isn't a good idea to chose it as it will prevent vMotion of the endpointVM." VM Network would only prevent vMotion if it was not a DPG, and multiple hosts are present (indicating that vMotion can be utilized).

**Comment by stuclem** [comment]
OK, thanks @hmahmood. Since we are talking about the default VM Network, it is not a DPG, so the statement about vMotion not working is accurate.
