### ISSUE TITLE
Document to escape special chars/whitespace in generated vic-machine command

### ISSUE THREAD

**Issue by stuclem** [vmware/vic-product#1191]
Per https://github.com/vmware/vic-ui/issues/67#issuecomment-347998495, document that the `vic-machine` command generated by the Create VCH wiz does not escape special characters or whitespace in option arguments.

**Comment by stuclem** [comment]
Added the following to the topic on finalizing the Create VCH wizard:

**What to Do Next**

The Create Virtual Container Host wizard does not include any escape characters in the generated `vic-machine` command. Consequently, if any of the values that you specified in the wizard include special characters or spaces, you must edit the saved `vic-machine` command to wrap those values in quotes before you can reuse the command to create similar VCHs. For information about using quotes to escape special characters and spaces, see [Specifying Option Arguments](using_vicmachine.md#args).

**Comment by stuclem** [comment]
@zjs does this cover it? Thanks!

**Comment by zjs** [comment]
Looks good to me!
