### ISSUE TITLE
Gather appliance logs

### ISSUE THREAD

**Issue by andrewtchin** [vmware/vic-product#1197]
**User Statement:**

As a person I want to easily get support logs off the VIC Appliance.

**Details:**
TODO determine what other logs to get
```
date
hostnamectl 
ip addr
cat /etc/vmware/version
cat /storage/data/version
systemctl status
systemctl list-jobs
systemctl list-units --state=failed
journalctl -u admiral_startup
journalctl -u admiral
journalctl -u harbor_startup
journalctl -u harbor
journalctl -u fileserver
files from /storage/log/*
iptables -L -n
df -h
docker ps -a
```
- [x] above done

- [x] check if psc tokens present
- [x] possibly psc config
- [x] possibly config files for admiral and harbor
- [x] environment file with ovfenv values
- [x] possibly fingerprints of certs present (not private keys)

@morris-jason anything else to add?

**Acceptance Criteria:**
- [ ] write and include script to get the logs
- [ ] run the script from the getting started page or through curl like `/register`

**Comment by morris-jason** [comment]
Capturing `ovfenv` output may be useful as well.

**Comment by morris-jason** [comment]
It may be nice to see the logs of any failed units as well, especially in the case of `vic-appliance-load-docker-images` and other `vic-appliance.target` dependencies.

**Comment by andrewtchin** [comment]
need to figure out how to mask secret values in harbor config file

**Comment by andrewtchin** [comment]
@sergiosagu @reasonerjt Are there any other system values you would like to be included in the support bundle? Any commands you would run during troubleshooting to get data that isn't in the logs?

**Comment by reasonerjt** [comment]
In addition to the logs.
The configuration files are in `/etc/vmware/harbor` and `/storage/data/harbor/config/config.json`
But yes, there are some secret values .

**Comment by sergiosagu** [comment]
@andrewtchin - The logs are the main thing.
The content of the files
- /storage/data/admiral/configs/config.properties
- /storage/data/admiral/configs/psc-config.properties
- /storage/data/admiral/8282/serviceHostState.json
can be also handy for verification purposes (everything is configured properly), but they may contain some sensitive data as well.

**Comment by andrewtchin** [comment]
Thanks guys!

**Comment by andrewtchin** [comment]
@reasonerjt Which specific config files in `/etc/vmware/harbor` would be needed?

**Comment by reasonerjt** [comment]
All the files needed are:
```
/storage/data/harbor/harbor.cfg
/storage/data/harbor/config/config.json
/etc/vmware/harbor/*.yml
/etc/vmware/harbor/common/config/**
```

**Comment by andrewtchin** [comment]
@stuclem @dbarkelew @lgayatri this script is at `/etc/vmware/support/get_vic_appliance_logs.sh` on new master builds (it will not be in 1.3)
Here is the help text:
```
Usage:
./get_vic_appliance_logs.sh [--include-private] [--outdir <directory>] [--ignore-disk-space]

--include-private:    includes files containing private values in the log bundle
--outdir <directory>: directory to store the resulting log bundle
--ignore-disk-space:  ignore low disk space warnings for log bundle output
```

By default it stores an archive under `/storage/log` containing the logs and system information
Let me know if you need more info for documentation

**Comment by stuclem** [comment]
Opened https://github.com/vmware/vic-product/issues/1269 for the doc update.
