### ISSUE TITLE
Request for image compatibility list

### ISSUE THREAD

**Issue by dbarkelew** [vmware/vic-product#1198]
Would it be possible to start keeping a list of compatible images that are verified to work with each release. Similar to how ESXi has a list of verified guest OSs for each version. 

Example of verified guest OS to ESXi. 
https://www.vmware.com/resources/compatibility/search.php?deviceCategory=software&testConfig=16

To be clear this would not be an exclusive list of only images that work. Just a list of images already validated to work. If an image is not on the list, just mean the image has not been tested with that release of VIC.

**Comment by andrewtchin** [comment]
Issue moved to [vmware/vic #6913](https://github.com/vmware/vic/issues/6913) via [**ZenHub**](https://www.zenhub.com/)
