### ISSUE TITLE
curl command should require https instead of http

### ISSUE THREAD

**Issue by lcastellano** [vmware/vic-product#1199]
**VIC version:**
vic-v1.3.0-rc2-2628-9e2a95b6.ova
**Deployment details:**
Nimbus deployment, no VCH
**Steps to reproduce:**
Follow instructions to install the plugin, try to run:
_curl -kL  http://vic_appliance_address:9443/files/vic_version.tar.gz -o vic_version.tar.gz_
**Actual behavior:**
The curl command succeeds but it creates an invalid output file
**Expected behavior:**
The curl command should download the appropriate tar file from the OVA.
Replacing http with https fixes the issue.

**Comment by gigawhitlocks** [comment]
I changed the docs so that they instruct the user to use https. Can we close this issue?

**Comment by gigawhitlocks** [comment]
https://github.com/vmware/vic-product/pull/1221

**Comment by anchal-agrawal** [comment]
@stuclem This is already fixed - closing.

**Comment by stuclem** [comment]
I see the fix. Thanks @gigawhitlocks !

**Comment by maxisam** [comment]
We still get incorrect file tho. with https and 1.3
