### ISSUE TITLE
Incorrect error message when VCSA is unreachable from OVA

### ISSUE THREAD

**Issue by lgayatri** [vmware/vic-product#1203]
@mhagen-vmware @mdubya66 

VIC 1.3 RC2: https://storage.googleapis.com/vic-product-ova-releases/vic-v1.3.0-rc2-2628-9e2a95b6.ova 
![image](https://user-images.githubusercontent.com/25006749/33481261-b966ff20-d6b9-11e7-921c-e81eee296be1.png)

journalctl -u fileserver
```
-- Logs begin at Fri 2017-12-01 11:23:19 UTC, end at Fri 2017-12-01 11:34:23 UTC. --
...
Dec 01 11:33:36 vic-st-h2-186.eng.vmware.com start_fileserver.sh[1497]: time="2017-12-01T11:33:36Z" level=info msg="server URL: cloud02-w3.stls.local\n"
Dec 01 11:33:36 vic-st-h2-186.eng.vmware.com start_fileserver.sh[1497]: time="2017-12-01T11:33:36Z" level=info msg="validator: dial tcp: lookup cloud02-w3.stls.local: no such host"
Dec 01 11:33:36 vic-st-h2-186.eng.vmware.com start_fileserver.sh[1497]: time="2017-12-01T11:33:36Z" level=info msg="Validation failed: dial tcp: lookup cloud02-w3.stls.local: no such host"
Dec 01 11:33:36 vic-st-h2-186.eng.vmware.com start_fileserver.sh[1497]: time="2017-12-01T11:33:36Z" level=info msg="render: html/index.html"
...
```

Here OVA is not able to talk to cloud02-w3.stls.local and message in UI should be same as what log says: "..lookup...no such host" instead "incorrect user name and password" is shown which will prompt the user to type the same creds again to see the wrong/confusing message.

**Comment by mdubya66** [comment]
Per @mlh78750 we'd like this in 1.3, depending on complexity. Adding to the release for now.
