### ISSUE TITLE
Scheme `https` not enforced on port 9443 for Getting Started

### ISSUE THREAD

**Issue by gigawhitlocks** [vmware/vic-product#1208]
Testing against `vic-v1.3.0-rc2-2628-9e2a95b6.ova`, when I go to `http://my-vic-install:9443` I receive a little bit of https encrypted data which is displayed as broken unicode icons, rather than being redirected to `https://my-vic-install:9443`

**Comment by andrewtchin** [comment]
This is covered in https://github.com/vmware/vic-product/issues/1005 and needs more investigation for a solution
