### ISSUE TITLE
Custom cert not present in demo installer

### ISSUE THREAD

**Issue by gigawhitlocks** [vmware/vic-product#1209]
I have installed VIC through OVA `vic-v1.3.0-rc2-2628-9e2a95b6.ova`
On that installation I provided a Lets Encrypt cert and pointed DNS name vch.theknown.net to the IP of the OVA VM

The cert is installed successfully for the Getting Started page, and can be seen here
![screen shot 2017-12-01 at 4 52 31 pm](https://user-images.githubusercontent.com/3743903/33507029-10344b70-d6b8-11e7-9ac2-3e251751e7de.png)

Unfortunately, when I click on the `Installer` link, I'm confronted with this:

![screen shot 2017-12-01 at 4 49 31 pm](https://user-images.githubusercontent.com/3743903/33507058-35d37d60-d6b8-11e7-9855-01d4c58a35a7.png)

As you can see, a self-signed certificate is installed in the place of my certificate.

**Comment by andrewtchin** [comment]
Demo VCH installer is deprecated in 1.3 and will be removed soon. Users should use the H5 plugin to create VCHs.
