### ISSUE TITLE
persistent proxy and ntp settings for all docker containers in the appliance

### ISSUE THREAD

**Issue by avomi** [vmware/vic-product#1228]
vic-v1.2.1-4104e5f9.ova
vcsa 65u1 (with sep. psc)
esxi 65u1b

Our environment prohibits direct internet access for systems.
I did not manage to configure persistently ntp and proxy settings for the various docker containers (Harbor, Admiral, Clair).

this leads to the following issues:
1. NTP - internal dns server does not resolve public host names. I get bagged for the fact that the appliance is filling the dns Server log with unresolvable requests.
2. Proxy -  Clair DB update is filling the local log until the appliance is crashing

Would be nice to to have exposed those settings during ova deployment and as settings/option in the ui,
- ntp
- http Proxy
- https Proxy 
Thx

**Comment by andrewtchin** [comment]
Rolling this into #1258 for proxy
Opened https://github.com/vmware/vic-product/issues/1390 for NTP
