### ISSUE TITLE
Clarify NFS docs

### ISSUE THREAD

**Issue by stuclem** [vmware/vic-product#1231]
Per Slack chat with @zjs, @jooskim, @matthewavery:

- The API is just a passthrough to the library, but the UI seems to have a dropdown for selecting a datastore (which is a good thing), but no way to turn that into a free-form text box to supply an NFS server. I think it's an easy thing to add post-1.3
- nfs volumes should show up
- in my dev environment i have one nfs volume attached to a cluster, for which i get an entry under the dropdown
- we haven’t made significant changes to the way we fetch datastores so it should be showing up
- NFS datastores show up, but only in the same way that other datastores do. It looks like there's a lot more flexibility when configuring NFS on the command-line:
- so i thought that once you’ve selected a cluster, one of the hosts under the cluster should have the nfs volume available
- NFS datastores show up, but there's no way to specify an NFS server that isn't a datastore or configure NFS-specific settings (which might be a gap in the API as well).
- no the nfs volume store does not need to be backed by an nfs datastore. An NFS datastore is actually a datastore that is backed by a sharepoint.
- Sounds like we'll have to file issues to fix this in the API and CLI, and have a note directing the user to the command-line for 1.3
- For this reason, the nfs volumestore target is not intended to be a datastore(atleast for now). But rather a sharepoint. If you do use an nfs datastore as the target then we will make vmdks on it, which are not shareable.

So, for 1.3, we need to document that if your NFS sharepoint is not an NFS datastore, you need to do `vic-machine configure` after deployment, to add it. @zjs @matthewavery is this accurate?

**Comment by stuclem** [comment]
@zjs and @matthewavery can I please ask you to take a look at https://github.com/stuclem/vic-product/blob/vchui/docs/user_doc/vic_vsphere_admin/volume_stores.md ? 

Thanks!

**Comment by matthewavery** [comment]
certainly @stuclem. I also believe that the below: 

```
vSphere Integrated Containers Engine creates the volumes folder independently from the folders for VCH files so that you can share volume stores between VCHs. You can assign an existing volume store that already contains data to another VCH by either creating a new VCH or by running vic-machine configure --volume-store on an existing one.
```

needs rewording. This makes it sound like you can have the same volume store attached to two VCH's at once. We do not support that and it is clear in other parts of this document. I figure we could clarify this statement some more to keep from confusing users.

**Comment by stuclem** [comment]
Thanks @matthewavery. Reworded as follows:

-----

vSphere Integrated Containers Engine creates the `volumes` folder independently from the folders for VCH files so that you can attach  existing volume stores to different VCHs. You can assign an existing volume store that already contains data to a VCH by either creating a new VCH or by running `vic-machine configure --volume-store` on an existing one. You can only assign a volume store to a single VCH at a time.

-----

Is this clearer?

**Comment by matthewavery** [comment]
yes, sorry I originally responded to this out of band awhile back.

**Comment by stuclem** [comment]
Reviewed by @matthewavery in https://github.com/vmware/vic-product/pull/1259/
