### ISSUE TITLE
Document increasing appliance disk size

### ISSUE THREAD

**Issue by andrewtchin** [vmware/vic-product#1237]
To expand disk size, shut down guest OS, select Edit Settings, and increase the size of the disk you want. Save the changes and then power on the VIC Appliance. We have a process that will automatically handle the partitioning (resizefs.service) upon boot.

Default mapping:
```
/dev/root        20G  6.0G   13G  32% /                     # Hard disk 1
/dev/sdb1        20G  2.8M   19G   1% /storage/data      # Hard disk 2
/dev/sdc1        20G   44M   19G   1% /storage/db         # Hard disk 3
/dev/sdd1        20G   44M   19G   1% /storage/log        # Hard disk 4
```

@morris-jason please confirm these instructions

**Comment by morris-jason** [comment]
@andrewtchin this is correct. Logs for the resize step can be viewed with `journalctl -eb -u resizefs.service` and `journalctl -eb -u resizefs.service`.

**Comment by stuclem** [comment]
Post-GA task.
