### ISSUE TITLE
Document environment prereqs for OVA

### ISSUE THREAD

**Issue by stuclem** [vmware/vic-product#124]
We to add an environmental requirements for deploying the OVA.

**Comment by anchal-agrawal** [comment]
This section should include the prereqs for Harbor: https://github.com/vmware/harbor/blob/master/docs/installation_guide_ova.md#prerequisites. Particularly,
> 2 vCPUs, 4GB memory and 80GB free disk space in datastore.

**Comment by stuclem** [comment]
Added the above prereqs in https://github.com/stuclem/vic-product/commit/eb170e49f10c7b0377778d95fdf92fa4efbb1e7d.
