### ISSUE TITLE
as a doc user i need specific information on what file to curl

### ISSUE THREAD

**Issue by mdubya66** [vmware/vic-product#1240]
**User Statement:**
As a doc user I need to know what file to curl while setting up the UI Plugin.

**Details:**
Figuring out what filename to curl is difficult, for example in https://vmware.github.io/vic-product/assets/files/html/1.3/vic_vsphere_admin/plugins_vcsa.html

**Acceptance Criteria:**
I can copy and paste the curl command and it just works.

**Comment by stuclem** [comment]
@mdubya66 yes, I have gone back and forth on this a few times. We'll just have to make sure that we update the version for every 1.3.x release.
