### ISSUE TITLE
As a VI Admin I need to know how to uninstall the Appliance VM

### ISSUE THREAD

**Issue by mdubya66** [vmware/vic-product#1242]
**User Statement:**

As a VI Admin I need to know how to uninstall the Appliance VM

**Details:**
What are the exact steps to uninstall the Appliance VM from a running VM to being completely removed

**Acceptance Criteria:**
Specific instructions that remove all traces of the appliance VM

**Comment by pescerosso** [comment]
And revert back all the changes we make to vSphere if any.

**Comment by stuclem** [comment]
I think that I'd need input from @andrewtchin on this, if it's more than just a case of the following:

- Stop any running containers 
- Delete any VCHs using vSphere Client UI or `vic-machine delete`
- Power off and delete appliance VM
- Remove any example users

**Comment by alextopuzov** [comment]
Also delete solution users
- admiral
- harbor
- engine

**Comment by andrewtchin** [comment]
As far as the VIC appliance, power off and delete appliance VM and any attached disks that were potentially in other folders from upgrade
@jooskim @jak-atx can comment on how to remove the plugin
@lcastellano can comment on how to remove any users created
