### ISSUE TITLE
VIC UI Install fails on VCSA

### ISSUE THREAD

**Issue by geggenberger** [vmware/vic-product#1253]
I try to install vic-ui-linux on a VCSA.

When i use vCenter-IP as wanted:

Please provide connection information to the vCenter Server.
-------------------------------------------------------------
Enter **IP** to target vCenter Server: (vCenter-IP)
Enter your vCenter Administrator Username: administrator@vsphere.local
Enter your vCenter Administrator Password: (secret)

I get the following Error:

-------------------------------------------------------------
Checking existing plugins...
-------------------------------------------------------------
failed to connect: Failed to connect to (vCenter-IP): Post https://(vCenter-IP)/sdk/: x509: cannot validate certificate for (vCenter-IP) because it doesn't contain any IP SANs
Error! Failed to check the status of plugin. Please see the message above

When i use vCenter-FQDN:

Please provide connection information to the vCenter Server.
-------------------------------------------------------------
Enter **IP** to target vCenter Server: (vCenter-FQDN)
Enter your vCenter Administrator Username: administrator@vsphere.local
Enter your vCenter Administrator Password: (secret)

I get the following Error:

Incorrect Usage: 
flag needs an argument: 
-thumbprint NAME: vic-ui-linux info 
- Show UI plugin information 
USAGE: vic-ui-linux info [command options] [arguments...] 
OPTIONS: --target value, -t value REQUIRED. 
ESXi or vCenter connection URL, specifying a datacenter if multiple exist e.g. root:password@VC-FQDN/datacenter (default: https://(vCenter-FQDN)/sdk/) [$VIC_MACHINE_TARGET] 
--user value, -u value ESX or vCenter user [$VIC_MACHINE_USER] 
--password value, -p value ESX or vCenter password (default: <secret>) [$VIC_MACHINE_PASSWORD] 
--thumbprint value ESX or vCenter host certificate thumbprint [$VIC_MACHINE_THUMBPRINT] 
--key value Plugin key (required) Dec 12 2017 08:26:37.589+01:00 

ERROR -------------------- Dec 12 2017 08:26:37.589+01:00 
ERROR vic-ui-linux failed: flag needs an argument: -thumbprint
Error! Failed to check the status of plugin. Please see the message above

**VIC Product version:** 1.2.1

**OVA version:** vic-v1.2.1-4104e5f9.ova

**Deployment details:**
VCenter runs on VMWare 6.0 (Build Number: 4600944)
 vic-v1.2.1-4104e5f9.ova runs on VMWare 6.0 (Build Number: 5572656)

**Steps to reproduce:**

ssh root@(vCenter-FQDN)
shell.set --enabled True
shell
curl -kL https://(vic-ip):9443/files/vic_1.2.1.tar.gz -o vic_1.2.1.tar.gz
tar -zxf vic_1.2.1.tar.gz
cd vic/ui/VCSA
./install.sh

**Actual behavior:**
Trows Error about Thumbprint

**Expected behavior:**
Should start with the installation of the Plugin

Could you please tell me how to fix this?

Kind regards
gerald

**Comment by AngieCris** [comment]
@andrewtchin Have we seen similar issue before? Will it be something about the VC configuration?

**Comment by andrewtchin** [comment]
@geggenberger Was the VIC appliance deployed with autogenerated certs (none provided during deploy) or did you provide some certs? The error you encountered when using IP would make sense if you had provided certs. I would expect the FQDN to work also and I believe the thumbprint is supposed to be set automatically in one of the config files.
@jak-atx @jooskim can triage further as they are more familiar with the UI plugin install

**Comment by geggenberger** [comment]
@andrewtchin VirtualCenter was installed with provided Certificates (generated on install)

It would be possible to add IP SAN to the config (/etc/ssl/openssl.cnf) an regenerate the certificate:

[ v3_ca ]
subjectAltName = IP:  (vCenter-IP)

But the default Configuration of VMWare VCSA doesn't provide this entry.

**Comment by jooskim** [comment]
This seems to be an issue that's resolved in 1.3 where the installer fails if the terminal has  environment variable named VIC_MACHINE_THUMBPRINT - see https://github.com/vmware/vic/issues/6161. As a workaround you can unset it and try running the script again:

```
$ unset VIC_MACHINE_THUMBPRINT
$ ./install.sh
```

**Comment by geggenberger** [comment]
@jooskim I've read  [vmware/vic#6161](https://github.com/vmware/vic/issues/6161) before and tested this. But in my case this environment variable doesn't exists.

I will deploy a new Certificate and test if this work.

Thanks for your support so far.

**Comment by andrewtchin** [comment]
@geggenberger please reopen this with additional info if you are still seeing this
