### ISSUE TITLE
Document appliance log gathering script

### ISSUE THREAD

**Issue by stuclem** [vmware/vic-product#1269]
Per https://github.com/vmware/vic-product/issues/1197#issuecomment-352537278. Not in 1.3.

**Comment by stuclem** [comment]
@lgayatri and @dbarkelew do you know if the log gathering script described in https://github.com/vmware/vic-product/issues/1197#issuecomment-352537278 was implemented in 1.4?

**Comment by dbarkelew** [comment]
Yes. The script was moved and renamed since that comment.  

https://github.com/vmware/vic-product/blob/v1.4.2/installer/build/scripts/systemd/scripts/support/appliance-support.sh#L295

**Comment by stuclem** [comment]
OK, thanks @dbarkelew

**Comment by stuclem** [comment]
See [comment](https://github.com/vmware/vic-product/issues/1197#issuecomment-352537278) from @andrewtchin on on Dec 18, 2017 for details.

**Comment by stuclem** [comment]
How to use the script needs to be added to https://vmware.github.io/vic-product/assets/files/html/1.4/vic_vsphere_admin/appliance_logs.html. Probably at the beginning, to state that you can obtain a bundle of all logs by using the script. Then leave the other entries there to show where the individual logs are

**Comment by stuclem** [comment]
Actually, the script is already mentioned in https://vmware.github.io/vic-product/assets/files/html/1.4/vic_vsphere_admin/appliance_logs.html. I has changed name to `appliance-support.sh` since #1197 was filed. But, we do not mention the 3 options listed in Andrew's comment, so we should add them.

**Comment by stuclem** [comment]
Looking at https://vmware.github.io/vic-product/assets/files/html/1.4/vic_vsphere_admin/appliance_logs.html, steps 4 -10 are a mixture of instructions about where to find individual logs, and how to set log retention. I wonder if there isn't a better way of presenting the log locations, possibly in a table after the procedure with headings **Component** | **Location** | **Log files**. People should know how to `cd` into a folder, so we don't need to provide the `cd` command each time.

**Comment by andrewtchin** [comment]
I agree that seems like 4-10 are more for power users if they want to dig into logs. Normal users probably only need instructions to get a support bundle especially if we don't tell how to interpret them.
