### ISSUE TITLE
Harbor CI fails to trigger VIC with downstream.

### ISSUE THREAD

**Issue by wy65701436** [vmware/vic-product#1277]
In Harbor CI, we defined one step to trigger VIC CI with drone downstream plugin.

  trigger:
    image: plugins/downstream
    server: https://ci.vcna.io
    token: ${DOWNSTREAM_TOKEN}
    fork: true
    repositories:
       - vmware/vic-product
    when:
      repo: vmware/harbor
      event: [ push, tag ]
      branch: [ master, release-*, refs/tags/* ]
      status: success

I specified the DRONE_TOKEN of VIC as the value of ${DOWNSTREAM_TOKEN} and I got it from the vic-internal(gitlab.eng.vmware.com). But it still failed with RC 1.  

https://ci.vcna.io/vmware/harbor/1708
 
Can someone help to point me which token should I use or how to debug the trigger error?

**Comment by AngieCris** [comment]
Cc: @andrewtchin

**Comment by andrewtchin** [comment]
@mdharamadas1

**Comment by mdharamadas1** [comment]
@wy65701436 when did this start failing? and can you run `drone secret ls vmware/harbor` cmd and post the results here? I'm not able to execute drone cli against harbor repo due to some reason.

**Comment by wy65701436** [comment]
BUILD_SERVER 
Events: push, tag, deployment, pull_request
SkipVerify: false
Conceal: false

BUILD_USERNAME 
Events: push, tag, deployment, pull_request
SkipVerify: false
Conceal: false

BUILD_PASSWORD 
Events: push, tag, deployment, pull_request
SkipVerify: false
Conceal: false

TEST_URL_ARRAY 
Events: push, tag, deployment, pull_request
SkipVerify: false
Conceal: false

GITHUB_AUTOMATION_API_KEY 
Events: push, tag, deployment, pull_request
SkipVerify: false
Conceal: false

TEST_USERNAME 
Events: push, tag, deployment, pull_request
SkipVerify: false
Conceal: false

TEST_PASSWORD 
Events: push, tag, deployment, pull_request
SkipVerify: false
Conceal: false

TEST_DATASTORE 
Events: push, tag, deployment, pull_request
SkipVerify: false
Conceal: false

TEST_TIMEOUT 
Events: push, tag, deployment, pull_request
SkipVerify: false
Conceal: false

HARBOR_ADMIN 
Events: push, tag, deployment, pull_request
SkipVerify: false
Conceal: false

HARBOR_PASSWORD 
Events: push, tag, deployment, pull_request
SkipVerify: false
Conceal: false

REPORTING_SERVER_URL 
Events: push, tag, deployment, pull_request
SkipVerify: false
Conceal: false

GS_PROJECT_ID 
Events: push, tag, deployment, pull_request
SkipVerify: false
Conceal: false

GS_CLIENT_EMAIL 
Events: push, tag, deployment, pull_request
SkipVerify: false
Conceal: false

CI_DOMAIN 
Events: push, tag, deployment, pull_request
SkipVerify: false
Conceal: false

SERVICE_ACCOUNT_KEY 
Events: push, tag, deployment, pull_request
SkipVerify: false
Conceal: false

GS_PRIVATE_KEY 
Events: push, tag, deployment, pull_request
SkipVerify: false
Conceal: true

SLACK_URL 
Events: push, tag, deployment, pull_request
SkipVerify: false
Conceal: false

GOOGLE_KEY 
Events: push, tag, deployment, pull_request
SkipVerify: false
Conceal: true

DRONE_TOKEN 
Events: push, tag, deployment, pull_request
SkipVerify: false
Conceal: false

DRONE_TOKEN_INTE 
Events: push, tag, deployment, pull_request
SkipVerify: false
Conceal: false

DRONE_SERVER 
Events: push, tag, deployment, pull_request
SkipVerify: false
Conceal: false

MAIL_PWD 
Events: push, tag, deployment, pull_request
SkipVerify: false
Conceal: true

DHCP 
Events: push, tag, deployment, pull_request
SkipVerify: false
Conceal: false

PROTOCOL 
Events: push, tag, deployment, pull_request
SkipVerify: false
Conceal: false

USER 
Events: push, tag, deployment, pull_request
SkipVerify: false
Conceal: false

PASSWORD 
Events: push, tag, deployment, pull_request
SkipVerify: false
Conceal: false

HOST 
Events: push, tag, deployment, pull_request
SkipVerify: false
Conceal: false

DATASTORE 
Events: push, tag, deployment, pull_request
SkipVerify: false
Conceal: false

CLUSTER 
Events: push, tag, deployment, pull_request
SkipVerify: false
Conceal: false

DATACENTER 
Events: push, tag, deployment, pull_request
SkipVerify: false
Conceal: false

AUTH_MODE 
Events: push, tag, deployment, pull_request
SkipVerify: false
Conceal: false

CLAIR_DB_PASSWORD 
Events: push, tag, deployment, pull_request
SkipVerify: false
Conceal: false

MAX_JOB_WORKERS 
Events: push, tag, deployment, pull_request
SkipVerify: false
Conceal: false

HARBOR_ADMIN_PASSWORD 
Events: push, tag, deployment, pull_request
SkipVerify: false
Conceal: false

DB_PASSWORD 
Events: push, tag, deployment, pull_request
SkipVerify: false
Conceal: false

NPM_USERNAME 
Events: push, tag, deployment, pull_request
SkipVerify: false
Conceal: false

NPM_PASSWORD 
Events: push, tag, deployment, pull_request
SkipVerify: false
Conceal: false

DOWNSTREAM_TOKEN 
Events: push, tag, deployment, pull_request
SkipVerify: false
Conceal: false

**Comment by wy65701436** [comment]
@mdharamadas1 I am using DOWNSTREAM_TOKEN as the token to call vic

**Comment by mdharamadas1** [comment]
@wy65701436 That looks good, what command did you use to add that secret?

**Comment by mdharamadas1** [comment]
@wy65701436 pls move this issue to Harbor as this is not an issue with Vic Product (as other builds are able to trigger successfully)

**Comment by andrewtchin** [comment]
Closing as other downstream triggers are working, @wy65701436 please contact us in #vic-product-standup with specific questions if this still doesn't work
