### ISSUE TITLE
Improve automation of ova release process

### ISSUE THREAD

**Issue by morris-jason** [vmware/vic-product#1287]
**User Statement:**

As a release manager for the Vic appliance ova, I want minimal user interaction to spin up and release an appliance ova using drone.

**Details:**

Our release process is far too manual, mostly because we need to provide component dependency versions by hand.  

One possible way to improve the automation is by running a “smarter” build script on pushes to tags, which should use versioned components instead of latest. 

**Acceptance Criteria:**

The release process is less manual, requiring no drone cli interaction. It should be documented in the installer directory.

**Comment by andrewtchin** [comment]
this story also includes improvement on inclusion of UI plugin in the build to specifically define which version to pull in instead of current dependency on engine build

**Comment by andrewtchin** [comment]
this story needs to have a discussion with stakeholders about requirements

**Comment by andrewtchin** [comment]
leaving needs estimate to reevaluate after design discussion

**Comment by zjs** [comment]
The process has been significantly improved. Additional improvements can be tracked separately.
