### ISSUE TITLE
Appliance startup waiting design

### ISSUE THREAD

**Issue by andrewtchin** [vmware/vic-product#1303]
**User Statement:**

As a user I want to know the status of the appliance while it's booting, but not ready.

**Details:**
Currently the appliance webserver does not start until all services are loaded. If users attempt to access the Getting Started Page, they receive a connection timed out error.
Short term we will add a webserver that comes up immediately with a please wait page, but need a longer term design.
This may include an enhanced please wait page or some indication on the DCUI.

Couple of options to investigate how to show this:
1.
- Set an `iptables` rule to redirect 9443, etc. to $newPort.
- Start the "please wait" service on $newPort.
- Start the "real service".
- Remove the `iptables` rule.
- Stop the "please wait" service.

2. nginx setup to route to initial webserver then switch to Getting Started Page when it's ready

**Acceptance Criteria:**
- [x] Design for how to tell the user to wait
- [ ] Implement waiting page

**Comment by lweitzman** [comment]
How about using the same login page but replace the login button with an informational alert indicating the appliance is booting... like this

![screen shot 2018-01-10 at 3 26 37 pm](https://user-images.githubusercontent.com/626032/34793894-e35c553e-f61a-11e7-8fce-1a7cab449e7a.png)

**Comment by andrewtchin** [comment]
What do you think about adding something on the DCUI? Either showing the status or saying view the status in the browser?

**Comment by lweitzman** [comment]
Something like: "When the appliance finishes booting (in approximately 10 minutes), you can reach it at https://...” @stuclem ??

**Comment by stuclem** [comment]
I like @lweitzman 's suggestion of replacing the login button with a message. How about: 

"Please wait while the appliance boots. This can take up to 10 minutes."

**Comment by lweitzman** [comment]
An alternative @pdaigle suggests is to be consistent with vsphere's page ( i like ours better :- )
![image](https://user-images.githubusercontent.com/626032/34833571-c2103a0a-f6bd-11e7-9aa6-9a7b6be39a46.png)

**Comment by andrewtchin** [comment]
Closing this as it will be handled in #1411 and corresponding UI part
