### ISSUE TITLE
Temporary appliance landing page

### ISSUE THREAD

**Issue by andrewtchin** [vmware/vic-product#1304]
**User Statement:**
Same as https://github.com/vmware/vic-product/issues/1179

**Details:**
This should be targeted to 1.3.1 and not depend on systemd overhaul

**Acceptance Criteria:**
- [x] Landing page shows up before getting started page is ready

**Comment by mdubya66** [comment]
for inclusion to 1.3.1 a PR would need to approved, merged and cherry picked by 1/18

**Comment by mdubya66** [comment]
If we have a PR merged by Jan 17 then we can take this fix for 1.3.1
