### ISSUE TITLE
Document that ops-user should have Read-only permissions to create VCH from UI

### ISSUE THREAD

**Issue by stuclem** [vmware/vic-product#1305]
@lgayatri commented on [Fri Jan 05 2018](https://github.com/vmware/vic-ui/issues/292)

Build:  https://storage.cloud.google.com/vic-product-ova-releases/vic-v1.3.0-f8cc7317.ova

./vic-machine-linux --version
vic-machine-linux version v1.3.0-15552-473375a

./vic-ui-linux --version
vic-ui-linux version 15552-473375a0a80f4f91ac445ecb616056fc5cfcbcc7

![image](https://user-images.githubusercontent.com/25006749/34598594-b3a53690-f213-11e7-9b9b-aa4b09903f89.png)

I created a PSC user called lgayatri@vsphere.local on my VCSA and chose to grant necessary permission from the create VCH wizard.

Creation failed
![image](https://user-images.githubusercontent.com/25006749/34599596-3bd0dd58-f219-11e7-8da0-61b111a96faf.png)

Tried the same from CLI and output says:
Command generated:
```
./vic-machine-linux create --name virtual-container-host --compute-resource /Datacenter/host/Cluster --image-store CPBU_2TB_01 --base-image-size 8GB --bridge-network vxw-dvs-3444-virtualwire-1-sid-5000-VCH-LS-1 --bridge-network-range 172.16.0.0/12 --public-network DPortGroup --public-network-ip 10.197.37.192/23 --public-network-gateway 10.197.37.253 --dns-server 10.142.7.21 --tls-cname virtual-container-host --organization virtual-container-host --certificate-key-size 2048 --no-tlsverify --user Administrator@VSPHERE.LOCAL --thumbprint C1:6D:3E:41:A5:89:5E:89:FB:DB:82:2F:32:82:8E:54:53:8B:65:34 --target wdc-stvc3944-146-dhcp15.eng.vmware.com/Datacenter --ops-user lgayatri@vsphere.local --ops-grant-perms
...
INFO[0007]   "/Datacenter/host/Cluster"
ERRO[0007] --------------------
ERRO[0007] Failed to validate operations credentials: ServerFaultCode: Permission to perform this operation was denied.
ERRO[0007] Create cannot continue: configuration validation failed
ERRO[0007] --------------------
ERRO[0007] vic-machine-linux create failed: validation of configuration failed
```

  

---

@lgayatri commented on [Fri Jan 05 2018](https://github.com/vmware/vic-ui/issues/292#issuecomment-355491379)

@AngieCris @mdubya66 @jak-atx 

---

@AngieCris commented on [Fri Jan 05 2018](https://github.com/vmware/vic-ui/issues/292#issuecomment-355605047)

@zjs  Is it related to the session?
@lgayatri Does it work after you refresh the H5 client and create again?

---

@lcastellano commented on [Fri Jan 05 2018](https://github.com/vmware/vic-ui/issues/292#issuecomment-355626859)

In 1.3 the selected ops-user must be configured with read-only permissions on all the the VC objects. Can you please verify that is the case here? Thanks.

---

@lgayatri commented on [Mon Jan 08 2018](https://github.com/vmware/vic-ui/issues/292#issuecomment-355927514)

@AngieCris , This is not related to session timeout but user permission to run the operation

---

@lgayatri commented on [Mon Jan 08 2018](https://github.com/vmware/vic-ui/issues/292#issuecomment-355944119)

@lcastellano , I have created a user and assigned Read-only permissions. Creation from UI succeeds.

![image](https://user-images.githubusercontent.com/25006749/34667905-0ab98aa6-f491-11e7-98b9-8194f0de9c30.png)

Adding @stuclem as FYI

---

@lgayatri commented on [Mon Jan 08 2018](https://github.com/vmware/vic-ui/issues/292#issuecomment-355946371)

We need to add a note that the user SHOULD have permissions assigned.

---

@anchal-agrawal commented on [Mon Jan 08 2018](https://github.com/vmware/vic-ui/issues/292#issuecomment-355951565)

If this is a doc issue, let's work with @lcastellano and @stuclem to move this issue to vic-product and ensure that this requirement is noted in https://vmware.github.io/vic-product/assets/files/html/1.3/vic_vsphere_admin/set_up_ops_user.html.

@lcastellano - the nightly test added in https://github.com/vmware/vic/pull/6774 isn't currently running as part of our nightlies. We should open an issue to do so, and add it to the https://github.com/vmware/vic/issues/6492 epic.

---

@stuclem commented on [Mon Jan 08 2018](https://github.com/vmware/vic-ui/issues/292#issuecomment-356005068)

@anchal-agrawal and @lgayatri I just documented this in the context of https://github.com/vmware/vic-product/issues/1157

---

@anchal-agrawal commented on [Mon Jan 08 2018](https://github.com/vmware/vic-ui/issues/292#issuecomment-356006388)

Perfect! Thanks for the update, Stuart :)

I believe we can close this issue after @lgayatri verifies https://github.com/vmware/vic-product/issues/1157.

---

@hickeng commented on [Wed Jan 10 2018](https://github.com/vmware/vic-ui/issues/292#issuecomment-356734069)

@stuclem @lgayatri 
This is *not* a required step if vmware/vic#6842 is cherry picked into 1.3.1. In that case we should document that it's necessary, but that it will be automatically granted *before* we confirm the ops-user credentials if grant-permissions is enabled.
@lcastellano to correct me if I've got details wrong.

---

@stuclem commented on [Thu Jan 11 2018](https://github.com/vmware/vic-ui/issues/292#issuecomment-356866830)

Cloning this for inclusion in a doc update for 1.3.1.

**Comment by hickeng** [comment]
@stuclem The change to set this automatically was cherry-picked into 1.3.1: https://github.com/vmware/vic/commit/d97c37f0bbbcac2af95732d20ca548053472a79c
