### ISSUE TITLE
2 Issues installing the VIC 1.3 OVA using the HTML Client ( vSphere Client )

### ISSUE THREAD

**Issue by mdubya66** [vmware/vic-product#1308]
@vmwarelab commented on [Thu Jan 11 2018](https://github.com/vmware/vic/issues/7081)

Testing the the new release of VIC 1.3 and while installing the OVA using the HTML client ( vSphere Client ) I encountered two issues : 

1. The password requirement for the example users is set to be not less than 128 Characters :) .. 

![image](https://user-images.githubusercontent.com/19843322/34846022-e30eaa62-f6e4-11e7-8163-d2a77cfae31a.png)

2. While I choose to skip the creation of the example users . the deployment always failed with this error Invalid value 'true' specified for property appliance.permit_root_login.  when i check that i want root to be able to ssh into the VIC appliance 

![image](https://user-images.githubusercontent.com/19843322/34846190-615a59d4-f6e5-11e7-8fd4-c40455e3ff36.png)

the workaround was to simple use the Flash Client ( Web Client )

**Comment by mdubya66** [comment]
was this using the HTML5 client?

**Comment by AngieCris** [comment]
@mdubya66 Yes, the original ticket mentioned it's H5 client
Cc: @andrewtchin

**Comment by mdubya66** [comment]
OVA deploy only works with the flex/flash client in 6.5U1. Looks like the flings have support now for OVA deployments. 

https://labs.vmware.com/flings/vsphere-html5-web-client#changelog as of Fling 3.25 - Build 6929189

**Comment by vmwarelab** [comment]
I can confirm that my home lab vCenter is 6.5U1

**Comment by vmwarelab** [comment]
@AngieCris Yes i see that in the documentation Thank you . so its a know issue 

![image](https://user-images.githubusercontent.com/19843322/34847087-38fb26be-f6e8-11e7-8be4-53ec4c0c9f4b.png)

**Comment by andrewtchin** [comment]
@vmwarelab The current HTML5 client does not support "Customize template" for OVF deploy. We will update our docs when this functionality becomes available.
https://docs.vmware.com/en/VMware-vSphere/6.5/rn/vsphere-client-65-html5-functionality-support.html

**Comment by bobbywaz** [comment]
WHY IS THIS STILL A PROBLEM?! this was TWO YEARS AGO and the OVF still doesn't deploy right.
