### ISSUE TITLE
VIC1.3 Failed to register with PSC. Please check the PSC settings provided and try again

### ISSUE THREAD

**Issue by ajas57** [vmware/vic-product#1328]
# For bug reports, please include the information below:

**VIC Product version:**

OVA version vic-v1.3.0-3033-f8cc731.ova

**Deployment details:**

Environment where the OVA is deployed
vCenter 6.5 aplayanca   

**Steps to reproduce:**
Deploy VIC from OVA - work ok
Start VIC - work OK
Try first Initiate VIC with vCenter 6.5 without external PSC from www web page - error message
(Live field for PSC blank. Like in documentation )

**Actual behavior:**
Recive information:
Failed to register with PSC. Please check the PSC settings provided and try again

**Expected behavior:**
Register VIC to vCenter no error message

**Logs:**
where we can fund logs for registration proces ?

**Additional details as necessary:**
I try register VIC base on IP address and FQDN result is the same.

# For stories, please include the information below:

**User Statement:**

My first VIC deployment 

**Details:**

**Acceptance Criteria:**
VIC register without error massage 
Where are logs for registration process ?

**Comment by andrewtchin** [comment]
Hi @ajas57 thanks for your detailed report - please follow the step with `journalctl -u fileserver` from this guide https://github.com/vmware/vic-product/blob/master/installer/SUPPORT.md#support-information-2
It would also be helpful to try pinging the vCenter IP/FQDN to make sure there is network connectivity to the embedded PSC.
Once we see the log we can try some additional troubleshooting steps.

**Comment by andrewtchin** [comment]
@ajas57 Is your vCenter in ELM?

**Comment by ajas57** [comment]
Hi
This was a simply installation PSC with vCenter on one vm with default configuration, log show nothing

**Comment by andrewtchin** [comment]
Thank you for the environment information. Could you paste the result of `journalctl -u fileserver --no-pager`? This will show us the debug logs from when you saw the PSC registration error.

**Comment by renmaosheng** [comment]
closing this as we didn't observe such failure in recent build.

**Comment by rborhara** [comment]
Im seeing "Installation failed: Failed to register with PSC. Please check the PSC settings provided and try again"this error but im running vCenter 6.0 U3 , 

there is no external PSC on my install its still on windows
