### ISSUE TITLE
VIC Product build failing on Drone 0.8

### ISSUE THREAD

**Issue by mdharamadas1** [vmware/vic-product#1342]
I'm getting following error while trying to run CI build on Drone 0.8.
```
=>(B export images to VMDKs
605s
223
 ->(B exporting vic-disk1.img to vic-disk1.vmdk
605s
224
 ->(B unmount /mnt/ova-root(B
605s
225
 ->(B release loopback device /dev/loop0(B
605s
226
 ->(B converting raw image vic-disk1.img(B into vic-disk1.vmdk(B
605s
227
qemu-img: error while writing sector 2396544: Invalid argument
```

A/C:
- VIC product CI build pass on Drone 0.8

**Comment by mdharamadas1** [comment]
@morris-jason This is the issue we discussed the other day, is there a plan to fix this?
Full log file is attached.
[ci_build.log](https://github.com/vmware/vic-product/files/1668734/ci_build.log)

**Comment by morris-jason** [comment]
@mdharamadas1 I've only been able to reproduce this when my hard disk is full. I'd suggest starting there, making sure you have plenty of free space on your disk.

**Comment by mdharamadas1** [comment]
Ah, that is possible that the new test drone workers i was using may not have the required space. I will try it and let you know. Thanks @morris-jason !

**Comment by andrewtchin** [comment]
Closing per @mdharamadas1, build passing
