### ISSUE TITLE
Latest docker client not able to log into Harbor

### ISSUE THREAD

**Issue by stonezdj** [vmware/vic-product#1346]
Issue https://github.com/vmware/harbor/issues/4142 
We found it in cert:
subject CN=vic-tom.corp.local
Subject Alternative Name
      IP Address:  x.x.x.x

If Golang version <1.9, it is a valid cert
if Golang version >=1.9, it is an invalid cert 

see [godoc](https://golang.org/pkg/crypto/x509/)
Both fields use FQDN(hostname) can avoid this issue.

**Comment by stonezdj** [comment]
`openssl req -newkey rsa:4096 -nodes -sha256 -keyout $key \
    -out $csr -subj \
    "/C=US/ST=California/L=Palo Alto/O=VMware/OU=Containers on vSphere/CN=$hostname"

  echo "Add subjectAltName = IP: $ip_address to certificate"
  echo subjectAltName = IP:"$ip_address" > $ext
  openssl x509 -req -days 1095 -in $csr -CA $ca_cert -CAkey $ca_key -CAcreateserial -extfile $ext -out $cert`

**Comment by stonezdj** [comment]
Use $hostname instead of $ip_address
https://github.com/vmware/vic-product/blob/master/installer/build/scripts/admiral/configure_admiral.sh#L77

**Comment by andrewtchin** [comment]
can't have both IP SAN and CN in the cert.

**Comment by andrewtchin** [comment]
@stonezdj I will post a dev build in #vic-product-standup slack channel for testing this

**Comment by stuclem** [comment]
If this only affects 1.3.0 and not 1.3.1, then I propose that we document it in the 1.3.0 release notes.

**Comment by stuclem** [comment]
Proposed release note:

- <b>Logging into vSphere Integrated Containers Registry from latest versions of Docker client fails. [#1346](
https://github.com/vmware/vic-product/issues/1346)</b><br>Attempts to log in to vSphere Integrated Containers Registry from a Docker client that is of a version greater than 17.09.1-ce fail with the error `Error response from daemon: [...] certificate is not valid for any names, but wanted to match vic-tom.corp.local`.

   Workaround: Use Docker client version 17.09.1-ce or earlier to log in to vSphere Integrated Containers Registry.

@tschwaller and @andrewtchin does this cover it? Thanks!

**Comment by andrewtchin** [comment]
This would affect appliance versions < 1.3.1.
It might also qualify the conditions - this would occur if the registry is using generated self signed certificates and being accessed by hostname
LGTM

**Comment by stuclem** [comment]
Thanks @andrewtchin. Updated to:

- <b>Logging into vSphere Integrated Containers Registry from latest versions of Docker client fails. [#1346](
https://github.com/vmware/vic-product/issues/1346)</b><br>Attempts to log in to vSphere Integrated Containers Registry from a Docker client that is of a version greater than 17.09.1-ce fail with the error `Error response from daemon: [...] certificate is not valid for any names, but wanted to match <cert_common_name>`. This issue occurs if the registry is using generated self-signed certificates and you are using the host name to access it.

   Workaround: Use Docker client version 17.09.1-ce or earlier to log in to vSphere Integrated Containers Registry.
