### ISSUE TITLE
1.3.1 RC : Home screen refers to incorrect access point

### ISSUE THREAD

**Issue by lgayatri** [vmware/vic-product#1352]
Build: 1.3.1 OVA: vic-v1.3.1-rc1-3256-b1b156e5.ova
Home screen on OVA is as:
![image](https://user-images.githubusercontent.com/25006749/35552263-387eba68-05b9-11e8-8d7c-88e0a5535145.png)

The Getting started page shows the address as http://<IP address> which is incorrect. Looks like we regressed from older GA builds.

Build: 1.2.1 GA
![image](https://user-images.githubusercontent.com/25006749/35552279-49333c08-05b9-11e8-9823-266bfcaf36d6.png)

@mdubya66 @anchal-agrawal @mhagen-vmware

**Comment by andrewtchin** [comment]
This is expected as there is a redirect to the getting started page
