### ISSUE TITLE
Post upgrade, unable to download ca.crt

### ISSUE THREAD

**Issue by lgayatri** [vmware/vic-product#1354]
@reasonerjt @stonezdj 
![image](https://user-images.githubusercontent.com/25006749/35564051-dd5216d2-05de-11e8-9039-550f0cc76c76.png)

Upgraded from 1.3.0 to 1.3.1

Setup details:
10.197.37.182 - credentials are shared over slack

**Comment by stonezdj** [comment]
It is a consequence of #1351, the harbor.service fails to start after upgrade, because failed to remove container dch_push

**Comment by lgayatri** [comment]
Related to https://github.com/vmware/vic-product/issues/1351

**Comment by sgairo** [comment]
@morris-jason can you confirm if this is a duplicate issue and close or otherwise estimate? Thanks!

**Comment by andrewtchin** [comment]
probably as a result of harbor failing to start. i will verify on upgraded system in a minute

**Comment by morris-jason** [comment]
@stonezdj I just logged into the machine and everything is running fine. Harbor and Admiral both started with no errors in journalctl or systemd. 
@lgayatri I accessed https://vic-st-h2-182.eng.vmware.com:8282/#/administration/configuration and I can see the root cert there.

**Comment by andrewtchin** [comment]
Upgrading 1.3.0 to 1.3.1-rc2 it looks like this screen takes a while to initialize. At first after upgrade it looks like the screenshot above, but after refreshing cert download does show up
![screen shot 2018-02-01 at 1 27 05 pm](https://user-images.githubusercontent.com/1649165/35698811-cf758b40-0753-11e8-89e7-ce75319e4126.jpg)
Closing as no repro

**Comment by andrewtchin** [comment]
Maybe open a UI issue for Harbor if this takes too long to come up
