### ISSUE TITLE
Document 1.3.0 to 1.3.1 upgrade

### ISSUE THREAD

**Issue by stuclem** [vmware/vic-product#1382]
Following Slack chat with @andrewtchin, there are differences between upgrading from 1.2.x to 1.3.x and upgrading from 1.3.0 to 1.3.1. This is due to the migration from 2 disks to 4 disks during upgrade from 1.2.x, meaning that in 1.3.x to 1.3.y upgrades, different disks need to be added/removed from the appliances.

@andrewtchin and @morris-jason can you please point me to any existing issues that provide details of the 1.3.x to 1.3.y procedure? 

Thanks!

**Comment by lgayatri** [comment]
Thanks @stuclem for the information.
I was always deleting the HD 2 from the newly deployed 1.3.1 OVA and adding the HD2 of 1.3.0/1.2.x.

**Comment by andrewtchin** [comment]
### Upgrade procedure
### 1.2.1 to 1.3.1
- Power down old appliance
- Detach Hard Disk 2 (data disk)
- On new appliance detach Hard Disk 2, delete from datastore
- Move detached data disk `_1` to new appliance datastore folder
- Attach data disk `_1` from old appliance to new appliance, controller `(0:1)`
- Power on new appliance
- Run `/etc/vmware/upgrade/upgrade.sh`

### 1.3.0 to 1.3.1
- Power down old appliance
- Detach Hard Disk 2 (data disk)
- Detach Hard Disk 3 (database disk)
- Detach Hard Disk 4 (log disk) (optional if user wants to keep logs or not)
- On new appliance, detach Hard Disk 2, Hard Disk 3, Hard Disk 4 (if user wants to keep logs), delete from datastore
- Move detached disks `_1`, `_2`, `_3` to new appliance datastore folder
- Attach data disk `_1` to new appliance, controller `(0:1)`
- Attach database disk `_2` to new appliance, controller `(0:2)`
- Optionally if retaining logs, attach logs disk `_3` to new appliance, controller `(0:3)`
- Power on new appliance
- Run `/etc/vmware/upgrade/upgrade.sh`

@morris-jason, please confirm these directions

**Comment by stuclem** [comment]
@andrewtchin and @morris-jason I have slightly conflicting information in the docs about which disk is which. In the topic on [Back Up and Restore the vSphere Integrated Containers Appliance](https://vmware.github.io/vic-product/assets/files/html/1.3/vic_vsphere_admin/backup_vic_appliance.html), we have disk 3 as the logs disk and disk 4 as the DB disk. You have these the other way around in your comment above. 

Can you please confirm that the DB and log disks are definitely 3 and 4, and not 4 and 3? Thanks!

**Comment by andrewtchin** [comment]
My post above is correct 
```
/dev/sdb1        20G  127M   19G   1% /storage/data
/dev/sdc1        20G  626M   18G   4% /storage/db
/dev/sdd1        20G   49M   19G   1% /storage/log
```
```
root@Photon [ /storage/data/certs ]# cat /usr/lib/systemd/system/storage-db.mount
[Unit]
Description=Mount Harbor Database disk
Before=umount.target
Wants=repartition.service resizefs.service
After=repartition.service resizefs.service

[Mount]
What=/dev/disk/by-path/pci-0000:03:00.0-scsi-0:0:2:0-part1
Where=/storage/db
```

```
root@Photon [ /storage/data/certs ]# cat /usr/lib/systemd/system/storage-log.mount
[Unit]
Description=Mount Harbor Log Disk
Before=umount.target
Wants=repartition.service resizefs.service
After=repartition.service resizefs.service

[Mount]
What=/dev/disk/by-path/pci-0000:03:00.0-scsi-0:0:3:0-part1
Where=/storage/log
```

**Comment by stuclem** [comment]
OK, thanks @andrewtchin. I'll update [Back Up and Restore the vSphere Integrated Containers Appliance](https://vmware.github.io/vic-product/assets/files/html/1.3/vic_vsphere_admin/backup_vic_appliance.html) accordingly.
