### ISSUE TITLE
open_source_license.txt needs to be updated to show 1.3.1

### ISSUE THREAD

**Issue by lgayatri** [vmware/vic-product#1401]
Build: https://storage.googleapis.com/vic-product-ova-releases/vic-v1.3.1-3409-132fb13d.ova 

open source license file needs to be updated to 1.3.1 instead of 1.3.0
@mdubya66 @mhagen-vmware @andrewtchin @anchal-agrawal 

```
open_source_licenses.txt

vSphere Integrated Containers version 1.3.0 GA

--vSphere Integrated Containers Engine version 1.3.0 GA
--Admiral version 1.3.0 GA
--Harbor version 1.3.0 GA
--Integrated containers UI for vSphere 1.3

This product is licensed to you under the Apache License version 2.0
(the "License"). You may not use this product except in compliance
with the License.
```

**Comment by andrewtchin** [comment]
No new licenses were added in 1.3.1

**Comment by lgayatri** [comment]
Version should get updated to 1.3.1 right?

**Comment by mdubya66** [comment]
If we don't make changes to the OSS payload we don't need to rev the VIC version on patches.
