### ISSUE TITLE
Scale upgrade failed from 1.2.1 to 1.3.1

### ISSUE THREAD

**Issue by lgayatri** [vmware/vic-product#1407]
@reasonerjt @stonezdj @mdubya66 @anchal-agrawal 
##### For bug reports, please include the information below:

Basic information (REQUIRED)
----------------------------

- Did you read the VIC Appliance Troubleshooting Guide? (Y/N) Y
- vCenter Server version: 6.5U1 GA
- Embedded or external PSC: Embedded
- Filename of the OVA you deployed: 
1.2.1 -   vic-v1.2.1-4104e5f9.ova
1.3.1 -   vic-v1.3.1-3409-132fb13d.ova

- IP address of VIC appliance: 10.197.37.189
- Hostname of VIC appliance: vic-st-h2-189.eng.vmware.com
- IP address of vCenter Server: 10.133.146.15
- Hostname of vCenter Server: wdc-stvc3944-146-dhcp15.eng.vmware.com

- What operation was being performed when the failure was noticed? Upgrade from 1.2.1 to 1.3.1

Detailed information (REQUIRED)
-------------------------------
```
root@vic-st-h2-189 [ /etc/vmware/upgrade ]# ./upgrade.sh
Enter vCenter Server FQDN or IP: wdc-stvc3944-146-dhcp15.eng.vmware.com
Enter vCenter Administrator Username: administrator@vsphere.local
Enter vCenter Administrator Password:
If using an external PSC, enter the FQDN of the PSC instance (leave blank otherwise):
If using an external PSC, enter the PSC Admin Domain (leave blank otherwise):

-------------------------
Starting upgrade 2018-02-07 07:31:35 +0000 UTC
Detected old appliance's version as 1.1.x or older.If the old appliance's version is not detected correctly, please contact VMware support.
```
Steps followed: https://github.com/stuclem/vic-product/blob/131upgrade/docs/user_doc/vic_vsphere_admin/upgrade_appliance.md

This is Scale upgrade with 50 VCHs , 750 containers, 50 projects , 10 project repos.

Please feel free to SSH to OVA - 10.197.37.189- root/Admin!23 for any additional information.

**Comment by sergiosagu** [comment]
@gmuleshkov - Could you take a look at it?
cc @lazarin @martin-borisov

**Comment by lgayatri** [comment]
@andrewtchin

**Comment by gmuleshkov** [comment]
It looks like it is not related to admiral. @andrewtchin can you please take a look?

**Comment by andrewtchin** [comment]
@lgayatri on 10.197.37.189 
The way the upgrade script determines the version is looking at this file:
```
root@vic-st-h2-189 [ /storage/data ]# cat version
admiral=vmware/admiral:vic_v1.3.0 6f1d13decebe
vic-machine-server=gcr.io/eminent-nation-87317/vic-machine-server:latest 44e47c4b40ab
```

The one on this system is missing some parts - what steps were done to this appliance before running the upgrade script?

On a newly deployed 1.3.1 system with the `/data` disk moved from a 1.2.1 system, I would expect the version file to look like this:
```
root@localhost [ /data ]# cat version
appliance=v1.2.1
harbor=harbor-offline-installer-v1.2.0.tgz
admiral=vmware/admiral:vic_v1.2.1 1fa8a0f5ec6d
engine=vic_1.2.1.tar.gz
```

If you have the 1.2.1 system, please check `/data/version` before moving the disk to perform the upgrade

**Comment by stuclem** [comment]
Just out of curiosity, what would happen if you were to upgrade a 1.2.x appliance that you had previously upgraded from 1.1.x?

**Comment by andrewtchin** [comment]
@lgayatri it looks like on the test system the 1.2.1 appliance was not initialized through the Getting Started Page before being powered down and having its disk moved to the 1.3.1 appliance. The upgrade script checks for the `psc-config.properties` file, which is not present on this system.  

This is what it should look like:
```
root@localhost [ /data/admiral/configs ]# ls
config.properties  psc-config.keystore  psc-config.properties  server.crt  server.key  trustedcertificates.jks
root@Photon [ ~ ]# cat /storage/data/version
appliance=v1.2.1
harbor=harbor-offline-installer-v1.2.0.tgz
admiral=vmware/admiral:vic_v1.2.1 1fa8a0f5ec6d
engine=vic_1.2.1.tar.gz
admiral=vmware/admiral:vic_v1.3.0 6f1d13decebe
vic-machine-server=gcr.io/eminent-nation-87317/vic-machine-server:latest 44e47c4b40ab
root@Photon [ ~ ]# cd /etc/vmware/upgrade/
root@Photon [ /etc/vmware/upgrade ]# ls
upgrade-admiral.sh  upgrade-harbor.sh  upgrade.sh  util.sh
root@Photon [ /etc/vmware/upgrade ]# ./upgrade.sh
Enter vCenter Server FQDN or IP: 10.160.34.28
Enter vCenter Administrator Username: administrator@vsphere.local
Enter vCenter Administrator Password:
If using an external PSC, enter the FQDN of the PSC instance (leave blank otherwise):
If using an external PSC, enter the PSC Admin Domain (leave blank otherwise):

-------------------------
Starting upgrade 2018-02-07 18:07:13 +0000 UTC
Detected old appliance's version as v1.2.1
Detected valid upgrade path. Upgrade will perform data migration, but previous component logs won't be transferred.
If the old appliance's version is not detected correctly, please enter "n" to abort the upgrade and contact VMware support.
Do you wish to proceed with upgrade? [y/n]
y
Continuing with upgrade

Preparing upgrade environment
Disabling and stopping Admiral and Harbor path startup
Finished preparing upgrade environment

-------------------------
Starting Admiral Upgrade 2018-02-07 18:07:13 +0000 UTC

Performing pre-upgrade checks
Starting Admiral upgrade
Updating Admiral configuration
Restarting Admiral

-------------------------
Starting Harbor Upgrade 2018-02-07 18:07:13 +0000 UTC

Performing pre-upgrade checks
Starting Harbor upgrade
[=] Shutting down Harbor
[=] Migrating Harbor data
[=] Finished migrating Harbor data
[=] Migrating Harbor configuration
[=] Finished migrating Harbor configuration
Harbor upgrade complete
Starting Harbor
Enabling and starting Admiral and Harbor path startup
Upgrade script complete. Exiting.
```

**Comment by andrewtchin** [comment]
@stuclem a previously upgraded appliance would have the correct files present and register correctly as a 1.2.1 appliance for a valid upgrade path

**Comment by lgayatri** [comment]
@andrewtchin , I added the disk HARD DISK2 again to OVA 1.2.1 and checked /data/version

![image](https://user-images.githubusercontent.com/25006749/35957556-1e82e872-0cc2-11e8-9f2c-524af700b8d7.png)

This is not the right data as we pulled the disk from 1.3.1.

Please let me know what to expect here so that I will add it like a pre-upgrade check.

**Comment by andrewtchin** [comment]
When you boot and initialize a 1.2.1 appliance you should see this in `/data/version`
```
appliance=v1.2.1
harbor=harbor-offline-installer-v1.2.0.tgz
admiral=vmware/admiral:vic_v1.2.1 1fa8a0f5ec6d
engine=vic_1.2.1.tar.gz
```
If the appliance is initialized correctly, this file should be present `/data/admiral/configs/psc-config.properties`
Once those are checked on 1.2.1, you can move the disk to the 1.3.1 appliance and begin upgrade

**Comment by lgayatri** [comment]
Thanks @andrewtchin . Testbed had network latency causing the register call to fail, hence this bug. Closing as no code change is needed.

**Comment by andrewtchin** [comment]
Awesome thanks!

**Comment by hickeng** [comment]
@andrewtchin Is there any possibility of images or similar being present in the old version if `Getting Started` hasn't been completed?

**Comment by andrewtchin** [comment]
I don't think it is likely there would be user data present as Admiral and Harbor would not have functioned if the appliance was never initialized properly
