### ISSUE TITLE
Create appliance admin API

### ISSUE THREAD

**Issue by andrewtchin** [vmware/vic-product#1411]
**User Statement:**
As a developer I want to create a Swagger spec to define the appliance admin API.

**Details:**
Depends on API endpoint requirements

**Acceptance Criteria:**
- [ ] Swagger spec written
- [ ] Swagger server generated
- [ ] Packaged as container
- [ ] Container built by CI
- [ ] Container pulled into appliance and starts
- [ ] Documentation

@jooskim @jak-atx

**Comment by zjs** [comment]
Closing as it is not clear that this is needed given the current product direction. This can be reopened if needed.
