### ISSUE TITLE
Implement appliance admin API

### ISSUE THREAD

**Issue by andrewtchin** [vmware/vic-product#1412]
**User Statement:**
As a developer I want the appliance admin API to function.

**Details:**
Make calls to SSO
Store settings
Handle service restart upon updated settings
Handle appliance re initialization
Handle downloading log bundle
Ability to poll for status of systemd unit (docker images loaded) and give not ready/ready (#1303)

**Acceptance Criteria:**
- [ ] API is implemented
- [ ] Tests
- [ ] Documentation
- [ ] Appropriate HTTP headers (Bugzilla 2087060)

**Comment by zjs** [comment]
Closing as it is not clear that this is needed given the current product direction. This can be reopened if needed.
