### ISSUE TITLE
VIC appliance SSO research

### ISSUE THREAD

**Issue by andrewtchin** [vmware/vic-product#1413]
**User Statement:**
As a user I want to be able to use SSO provided by PSC.

**Details:**
Research how to use SSO for authentication
Would need to validate provided vSphere credentials as valid/invalid and make the verdict available for use

**Acceptance Criteria:**
- [ ] Know how to interface with PSC
- [ ] Documentation

**Comment by zjs** [comment]
Closing as it is not clear that this is needed given the current product direction. This can be reopened if needed.
