### ISSUE TITLE
Document that vic-machine configure doesn't regenerate TLSverify-enabled self-signed certificates

### ISSUE THREAD

**Issue by stuclem** [vmware/vic-product#1445]
Per https://github.com/vmware/vic/issues/7378. Info required from @gigawhitlocks.

**Comment by gigawhitlocks** [comment]
The basic situation is that without certificate regeneration, users should generate a certificate manually using the OpenSSL command line tool and then use `vic-machine configure --tls-server-cert` and `--tls-server-key` to load the new certificate. It would actually be ideal if they kept the output from when they ran `vic-machine install` and just renewed the same certificates.
