### ISSUE TITLE
request failed with 405

### ISSUE THREAD

**Issue by Amjadf** [vmware/vic-product#1452]
- Did you read the VIC Appliance Troubleshooting Guide? Y
- vCenter Server version: vCenter Server 6.5 Update 1e and some newer as beta version.
- Embedded or external PSC: embedded
- Filename of the OVA you deployed: vic-v1.3.1-3409-132fb13d
- Hash (MD5, SHA-1, or SHA-256) of the OVA you deployed: MD5: 6BE0060932D8844F02D1C1EB72154274
- IP address of VIC appliance: 192.168.1.75
- Hostname of VIC appliance:
- IP address of vCenter Server: 192.168.1.73
- Hostname of vCenter Server: vcenter.amarzo.com
- What operation was being performed when the failure was noticed?
during installation process 

error masg:
https://192.168.1.75:8282/auth/psc/callback/token

{"message":"request failed with 405, no additional details provided","stackTrace":["com.vmware.xenon.common.Operation.fail(Operation.java:1250)","com.vmware.admiral.auth.idm.psc.service.PscAuthenticationService.handleGet(PscAuthenticationService.java:404)","com.vmware.xenon.common.StatelessService.handleRequest(StatelessService.java:120)","com.vmware.xenon.common.StatelessService.handleRequest(StatelessService.java:103)","com.vmware.xenon.common.ServiceHost.lambda$queueOrScheduleRequestInternal$44(ServiceHost.java:4292)","java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1402)","java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)","java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)","java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)","java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)"],"statusCode":405,"documentKind":"com:vmware:xenon:common:ServiceErrorResponse","errorCode":0}

**Comment by andrewtchin** [comment]
Hi @Amjadf thank you for your report - we will investigate this. 
Could you provide the appliance support bundle by running `/etc/vmware/support/appliance-support.sh`? You can email it to andrewchin@vmware.com

**Comment by andrewtchin** [comment]
@Amjadf It looks like this error is caused by the endpoint receiving a GET instead of an expected POST. Could you provide the appliance support bundle so that we can see what happens before this error?

**Comment by Amjadf** [comment]
Andrew, thank you very much for your support. I will send you right away the information to your email. Again Thank you!

**Comment by andrewtchin** [comment]
Logs show that appliance initialization was not completed successfully, still investigating.
