### ISSUE TITLE
Doc: Adding a self signed registry cert in Docker for mac

### ISSUE THREAD

**Issue by karthik-narayan** [vmware/vic-product#146]
[This page](https://stuclem.github.io/vic-product/assets/files/html/1.1/vic_app_dev/configure_docker_client.html#registry) details the steps necessary to add a self signed registry cert for Linux and Windows. We should also document this for OSX. 

The details can be found below: 
http://container-solutions.com/adding-self-signed-registry-certs-docker-mac/

**Comment by stuclem** [comment]
Thanks @karthik-narayan.

**Comment by stuclem** [comment]
Dup of https://github.com/vmware/vic-product/issues/167
