### ISSUE TITLE
Document a Do Not Use docker rm -v against a container using named image volumes for 1.3.0

### ISSUE THREAD

**Issue by matthewavery** [vmware/vic-product#1463]
see: https://github.com/vmware/vic/issues/7138

This ticket dealt with a bug in our implementation of `docker run --rm` which caused the invocation of said command to delete named volumes which were superseding the anonymous creation of the image volume. 

THIS WILL LEAD TO CUSTOMER DATA LOSS!

We need to updated the release nots for vic product `1.3` as well as vic-engine `1.3` to reflect this behavior as it could definitely be customer critical. In the release notes our recommended remediation should definitely be an immediate upgrade to `1.3.1` if possible, and otherwise customers should not use `docker run --rm` if they intend to use volumes.

Generally, if a user goes through the effort of superseding an image volume with a named one it indicates that they desire to keep that data. The most common use case I have see for this would be for databases and their storage disk.

**Comment by stuclem** [comment]
Should be mentioned in https://vmware.github.io/vic-product/assets/files/html/1.3/vic_app_dev/using_volumes_with_vic.html too

**Comment by stuclem** [comment]
Added to known issues for vic and vic-product 1.3.0: -
- https://github.com/vmware/vic/releases/tag/v1.3.0#knownissues
- https://github.com/vmware/vic-product/releases/tag/v1.3.0#knownissues

Also added as a resolved issue in 1.3.1: 
- https://github.com/vmware/vic-product/releases/tag/v1.3.1#resolvedissues
- https://github.com/vmware/vic/releases/tag/v1.3.1#resolvedissues
