### ISSUE TITLE
Harbor fails to start after hard OVA power off

### ISSUE THREAD

**Issue by pdaigle** [vmware/vic-product#1466]
REQUIRED:

- vCenter Server version: 6.5.0.12000
- Embedded or external PSC: embedded
- Filename of the OVA you deployed: vic-v1.3.1-3409-132fb13d.ova
- Does the VIC appliance recieve configuration by DHCP? No
- What stage of the Appliance Lifecycle is the VIC appliance in? Running
- Attach the VIC appliance support bundle [vic_appliance_logs_2018-03-06-18-54-08.tar.gz](https://github.com/vmware/vic-product/files/1786816/vic_appliance_logs_2018-03-06-18-54-08.tar.gz)
  
  If you are not comfortable with posting this publicly, please email it to andrewchin@vmware.com
  and reference the created issue number in the subject

OPTIONAL, but helpful:

- IP address of VIC appliance: 192.168.100.21
- Hostname of VIC appliance: registry.corp.local
- IP address of vCenter Server: 192.168.110.22
- Hostname of vCenter Server: vcsa-01a.corp.local

Bug Report Detailed Information
-------------------------------

- What operation was being performed when the failure was noticed?

Powering on the appliance after a hard power off operation (host crash).

- Provide information from the `Support Information` section of the appropriate Appliance Lifecycle stage:

Admiral service is running, vic-machine-server service is running.
Harbor fails to start. Seeing these (and similar) errors in Harbor logs:

`Mar  6 18:12:56 172.18.0.1 ui[488]: 2018-03-06T18:12:56Z [ERROR] [utils.go:102]:                                            failed to connect to tcp://adminserver:8080, retry after 2 seconds :dial tcp: lookup adminserver: Temporary failure in name resolution`

- Provide additional detail as necessary:

After some troubleshooting, I managed to correct the issue by removing a stopped container (`dch-push`) that had not been properly cleaned up, causing `docker-compose` to fail. This could be seen in the output from `journalctl -u harbor`:

![harbor_error_fix](https://user-images.githubusercontent.com/8586715/37059932-c15eea9c-215c-11e8-9110-577abb63852a.png)

After clean up, I ran `systemctl restart harbor` and the service came up.

**Comment by andrewtchin** [comment]
```
Mar 06 18:42:52 registry.corp.local systemd[1]: harbor.service: Main process exited, code=exited, status=125/n/a
Mar 06 18:42:53 registry.corp.local docker-compose[8252]: Removing network harbor_harbor
Mar 06 18:42:53 registry.corp.local docker-compose[8252]: Network harbor_harbor not found.
Mar 06 18:42:53 registry.corp.local docker-compose[8252]: Removing network harbor_notary-mdb
Mar 06 18:42:53 registry.corp.local docker-compose[8252]: Network harbor_notary-mdb not found.
Mar 06 18:42:53 registry.corp.local docker-compose[8252]: Removing network harbor_notary-sig
Mar 06 18:42:53 registry.corp.local docker-compose[8252]: Network harbor_notary-sig not found.
Mar 06 18:42:53 registry.corp.local docker-compose[8252]: Removing network harbor_harbor-clair
Mar 06 18:42:53 registry.corp.local docker-compose[8252]: Network harbor_harbor-clair not found.
Mar 06 18:42:53 registry.corp.local docker-compose[8252]: Removing network harbor_harbor-notary
Mar 06 18:42:53 registry.corp.local docker-compose[8252]: Network harbor_harbor-notary not found.
Mar 06 18:42:53 registry.corp.local docker-compose[8259]: No stopped containers
Mar 06 18:42:53 registry.corp.local systemd[1]: harbor.service: Unit entered failed state.
Mar 06 18:42:53 registry.corp.local systemd[1]: harbor.service: Failed with result 'exit-code'.
Mar 06 18:42:58 registry.corp.local systemd[1]: harbor.service: Service hold-off time over, scheduling restart.
Mar 06 18:42:58 registry.corp.local systemd[1]: Stopped Harbor Container Registry.
Mar 06 18:42:58 registry.corp.local systemd[1]: Started Harbor Container Registry.
Mar 06 18:42:58 registry.corp.local start_harbor.sh[8280]: docker: Error response from daemon: Conflict. The container name "/dch-push" is already in use by container "42096b236ab4a823cb5c7e002421de09a299e20b0da90a17bb3f382a8679b559". You have to remove (or rename) that container to be able to reuse that name.
Mar 06 18:42:58 registry.corp.local start_harbor.sh[8280]: See 'docker run --help'.
Mar 06 18:42:58 registry.corp.local systemd[1]: harbor.service: Main process exited, code=exited, status=125/n/a
```
This happens since we do the dch-push container cleanup after the push finishes. In master we have added a preemptive cleanup so this behavior will not happen in versions greater than 1.3.1.
Thanks for the report @pdaigle
