### ISSUE TITLE
Doc: broken links in DevOps user doc

### ISSUE THREAD

**Issue by anchal-agrawal** [vmware/vic-product#147]
The links in https://github.com/vmware/vic-product/blob/master/docs/user_doc/vic_dev_ops/vchs_and_mgmt_portal.md are broken. They have an extra `vic_dev_ops` prepended to the URL.

cc @stuclem

**Comment by stuclem** [comment]
Thanks @anchal-agrawal. @alextopuzov this is for you.

**Comment by stuclem** [comment]
Fixed in https://github.com/vmware/vic-product/pull/173
