### ISSUE TITLE
Document 1.4.0 Upgrade changes

### ISSUE THREAD

**Issue by morris-jason** [vmware/vic-product#1470]
Issue #1450 and it's accompanying PRs #1469 and #1337 make improvements to upgrade behavior for 1.4.0. 
Summary of changes:
- [ ] Disk movement is now automated by default, but the user can revert to old behavior with `--manual-disks` flag on the upgrade script.
- [ ] Using the default automated disk upgrade, the user will be asked for the ip address and username of their old appliance, and the old disks will be copied to the new appliance.
- [ ] The old vic appliance will be left untouched by the upgrade, keeping it intact as a backup.
- [ ] There is a new required prompt for which the user must supply the target vCenter data center of the old/new appliance.
- [ ] We now support 1.3.0 and 1.3.1 upgrades to 1.4.0. ~~Support for 1.2.1 upgrades has been discontinued.~~

@andrewtchin do you see anything else to add?

**Comment by andrewtchin** [comment]
Since the upgrade copies the disks, the user must make sure there is enough space available on the datastore. 
@morris-jason The upgrade is available only within the same datacenter? What about between clusters?
Confirming valid upgrade paths now. I'll update this later.

**Comment by andrewtchin** [comment]
Valid upgrade paths will be 1.2.1 and 1.3.x to 1.4.0

**Comment by stuclem** [comment]
Thanks for the info @morris-jason and @andrewtchin
