### ISSUE TITLE
VIC 1.4 registration fails with VCSA 6.7

### ISSUE THREAD

**Issue by lgayatri** [vmware/vic-product#1490]
##### For bug reports, please include the information below:

Please fill out both the Basic Information and Detailed Information sections.

Bug Report Basic Information
----------------------------

REQUIRED:

- vCenter Server version: 6.7 , 7989256
- Embedded or external PSC: Embedded 
- Filename of the OVA you deployed: https://storage.googleapis.com/vic-product-ova-builds/vic-dev-v1.4.0-dev-4105-e1b1972c.ova 
- Does the VIC appliance recieve configuration by DHCP? No static
- What stage of the Appliance Lifecycle is the VIC appliance in? Registration failed
  https://github.com/vmware/vic-product/blob/master/installer/docs/SUPPORT.md#appliance-lifecycle
- Attach the VIC appliance support bundle (e.g. vic_appliance_logs_2018-01-01-00-01-00.tar.gz)
  https://github.com/vmware/vic-product/blob/master/installer/docs/SUPPORT.md
[vic_appliance_logs_2018-03-20-10-20-17.tar.gz](https://github.com/vmware/vic-product/files/1828759/vic_appliance_logs_2018-03-20-10-20-17.tar.gz)

Bug Report Detailed Information
-------------------------------
![registrationfailed](https://user-images.githubusercontent.com/25006749/37648064-e6749ab4-2c53-11e8-8259-4f13c1d16b5b.png)

- What operation was being performed when the failure was noticed?
Was registering VIC with VCSA

@mdubya66 @mhagen-vmware

**Comment by lazarin** [comment]
Are all clocks in sync? (probably between appliance and PSC)?
I see following when registergin solution user in the logs:
```
The time now Tue Mar 20 09:28:37 UTC 2018 does not fall in the request lifetime interval extended with clock tolerance of 600000 ms: [ Tue Mar 20 09:41:20 UTC 2018; Tue Mar 20 10:11:20 UTC 2018). This might be due to a clock skew problem. Please see the server log to find more detail regarding exact cause of the failure
```
there's some time tolerance of 10min but the diff is ~42min

**Comment by lgayatri** [comment]
VIC appliance somehow jumped clock. Setting it back and checking

**Comment by lgayatri** [comment]
Issue moved to [vmware/admiral #259](https://github.com/vmware/admiral/issues/259) via [**ZenHub**](https://www.zenhub.com/)
