### ISSUE TITLE
Document support for VM-Host Affinity

### ISSUE THREAD

**Issue by zjs** [vmware/vic-product#1494]
Update documentation to reflect the work under vmware/vic#6461. See also vmware/vic#7548.

**Comment by zjs** [comment]
https://github.com/vmware/vic/pull/7565/files#r176178371

**Comment by AngieCris** [comment]
potential VM group membership lost when fixing VM from invalid state:
VM group membership lost when unregister the VM: https://github.com/vmware/vic/issues/7558#issuecomment-379347409

**Comment by AngieCris** [comment]
OOB VM group rename: https://github.com/vmware/vic/pull/7735#issuecomment-382171898

**Comment by stuclem** [comment]
Looks like the affinity work is not in RC1. Waiting for RC2.

**Comment by stuclem** [comment]
See PRs https://github.com/vmware/vic/pull/7784 and https://github.com/vmware/vic/pull/7735

**Comment by stuclem** [comment]
This adds `vic-machine create --affinity-vm-group`

**Comment by stuclem** [comment]
Look like the affinity rules settings are not in the UI.

**Comment by zjs** [comment]
Correct; UI work didn't make it into 1.4.
