### ISSUE TITLE
Add landing server to master

### ISSUE THREAD

**Issue by andrewtchin** [vmware/vic-product#1501]
**User Statement:**
As a user I want feedback while the appliance services are starting after boot.

**Details:**
Didn't get to appliance admin app for 1.4, so need to add in the temporary landing server
https://github.com/vmware/vic-product/pull/1310

**Acceptance Criteria:**
- [ ] landing server

**Comment by mdubya66** [comment]
Removing p1, not a 1.4 requirement

**Comment by andrewtchin** [comment]
not putting this in would be a regression from 1.3.1 and this almost as simple as a cherry pick

**Comment by mdubya66** [comment]
why is it a regression?

**Comment by andrewtchin** [comment]
we have the landing server only in 1.3.1 but not in master since we were planning a revamp for 1.4 but that didn't make it in 1.4 so we would be back to no feedback right after startup

**Comment by mdubya66** [comment]
OK, Making a p1. Do the cherry pick this sprint.
