### ISSUE TITLE
Document how to handle expired password

### ISSUE THREAD

**Issue by stuclem** [vmware/vic-product#151]
Per https://github.com/vmware/vic/issues/4214, which is implemented in PR https://github.com/vmware/vic/pull/4679. 

@hickeng confirms that this is in 1.1.

**Comment by stuclem** [comment]
From @hickeng via Slack: 

You should see a message short of like:
```
Warning: your password will expire in 0 days
root@ [ ~ ]# date
Wed Apr 12 17:08:28 UTC 2017
```

when you log in

If the password has expired then you will no longer be able to log in by ssh key

If the password has expired an you try to log in interactively then you'll be prompted to change it (i.e. it doesn't lock the account)

If you rerun --enableSSH without specifying --rootpw then the password expiration will be set to 1 day in the future (using calendar maths, so around midnight that could be a very short period - I've not played with this to find out exact behaviour) but the current password value will be preserved - i.e. just updates expiration (edited)
 
If a longer expiration is required then it _should_ be possible to change it via `passwd` once you're logged in and get a 90 day expiry set - (unconfirmed)

**Comment by stuclem** [comment]
Attempted to add the above to the topics on debug. Change is in https://github.com/stuclem/vic-product/commit/a8a9cab01b8c18212a2772901d716cec9e209166.

**Comment by stuclem** [comment]
Changes merged in https://github.com/vmware/vic-product/issues/158, but leaving this open for final verification by @hickeng.

**Comment by hickeng** [comment]
@stuclem I've added a comment to the PR - it's correct, but I thought I'd expand on one point a little. Up to you if you want to add it to the docs.
