### ISSUE TITLE
VCH UI deployment - DNS server is replaced with DHCP settings

### ISSUE THREAD

**Issue by David-VTUK** [vmware/vic-product#1515]
Bug Report Basic Information
----------------------------

REQUIRED:

- vCenter Server version: **6.5.0.14000**
- Embedded or external PSC: **Embedded**
- Filename of the OVA you deployed: **vic-v1.3.1-3409-132fb13d**
- Does the VIC appliance receive configuration by DHCP? **No**
- What stage of the Appliance Lifecycle is the VIC appliance in? **Running**
- Attach the VIC appliance support bundle 
[vic_appliance_logs_2018-03-27-19-13-55.tar.gz](https://github.com/vmware/vic-product/files/1853445/vic_appliance_logs_2018-03-27-19-13-55.tar.gz)

OPTIONAL, but helpful:

- IP address of VIC appliance: 172.16.10.38 
- Hostname of VIC appliance: vic.virtualthoughts.co.uk
- IP address of vCenter Server: 172.16.10.31
- Hostname of vCenter Server: vcsa.virtualthoughts.co.uk

Bug Report Detailed Information
-------------------------------

- What operation was being performed when the failure was noticed?

**Deployment of a VCH from the Web UI**

- Provide information from the `Support Information` section of the appropriate Appliance Lifecycle stage:

Are you able to view the web page at http://vic.virtualthoughts.co.uk: **yes**
Did you attempt to initialize the VIC appliance by entering information in the Getting Started page?: **yes**
Are you able to SSH into the VIC appliance?: **yes**

- Provide additional detail as necessary:

Deployment of the VCH from the Web UI wizard on step 4 permits the option to specify a DNS server. However, this is not used when the VCH deploys. In my environment, I have a DHCP server running in that network that assigns public DNS server addresses as part of the scope options. The deployed VCH uses the DNS servers provided by the scope options instead of what's specified in the UI.

However, deploying a VCH from the command line using vic-machine yields the correct result. @hickeng  kindly guided me through some troubleshooting exercises and has identified that VCH's deployed from the Web UI are missing certain options from the corresponding .vmx file, namely from the guestinfo.vice./init/networks namespace, but those deployed from the CLI have these configured.

**Comment by mdubya66** [comment]
Workaround in place. Making a p2.

**Comment by andrewtchin** [comment]
triage to determine if this is in UI or API

**Comment by AngieCris** [comment]
Bug identified on UI: The DNS server option did not get propagated to request header
Moved this to UI repo:
https://github.com/vmware/vic-ui/issues/439

**Comment by AngieCris** [comment]
@David-VTUK 
Did you select the `static` option from step 4 of create wizard? If not, can you select `static`, provide a DNS setting, and try deploy from the wizard again?
