### ISSUE TITLE
Update networking diagram

### ISSUE THREAD

**Issue by andrewtchin** [vmware/vic-product#1517]
**User Statement:**
As a user I want to know networking requirements for VIC.

**Details:**
https://vmware.github.io/vic-product/assets/files/html/1.3/vic_vsphere_admin/graphics/Network-protocols.png does not include 8443 for VIC machine API.

**Acceptance Criteria:**
- [ ] Updated diagram

@stuclem are you the right person for this?

**Comment by stuclem** [comment]
@andrewtchin, yep, and @alextopuzov, who is co-located with our graphic designer.

**Comment by stuclem** [comment]
@andrewtchin, this diagram represents VIC after deployment, so `vic-machine` doesn't feature here, in its 1.3 version. At least not for 1.3.x. Are you talking about 1.4, with the UI-based `vic-machine configure` commands? In that case, we're going to need a new line from VIC appliance to the VCH, with a vSphere admin character added.

**Comment by zjs** [comment]
I believe the line we're missing is from "vCenter Server" to "VIC Appliance" labeled "https (tcp:8443)", to represent the communication which occurs when a user accesses the VIC UI Plugin.

**Comment by andrewtchin** [comment]
Zach is correct. Sorry I missed this.

**Comment by alextopuzov** [comment]
If we are positive that this is the only change required for this graphic for 1.4 i can take it to the graphics designer right now. If more changes might be required i'll have to wait. @andrewtchin can you confirm this will be the only change for that release? Thanks.

**Comment by andrewtchin** [comment]
There's that change, but also I noticed that there isn't a direct line from Developer to the VIC appliance for tcp/443 - couldn't the developer directly use harbor?

**Comment by alextopuzov** [comment]
May be @zjs can have a second look on that Dev to Harbor over 443?

**Comment by alextopuzov** [comment]
@zjs sorry for bothering again, can you confirm?

**Comment by zjs** [comment]
I don't know if it's accurate, but the [repo](https://github.com/vmware/harbor/blob/master/docs/installation_guide.md#network-ports) suggests that the developer could use port 80 for http traffic in addition to port 443 for https traffic.

**Comment by andrewtchin** [comment]
Harbor on the VIC appliance only listens on 443 and 4443. This is simply a question of whether we should show that a developer can directly use harbor on 443. I think the answer is yes since the diagram also already shows the developer directly using notary on 4443 and other docker hosts using harbor on 443.
