### ISSUE TITLE
Document unified appliance certificate

### ISSUE THREAD

**Issue by stuclem** [vmware/vic-product#1553]
The option to provide a custom certificate for management portal during OVA deployment has moved into the general appliance configuration section. I assume that this is now a single cert for all of the appliance services. @andrewtchin and @morris-jason, are there any special requirements for this certificate?

We currently state "If you intend to use custom certificates, vSphere Integrated Containers Management Portal requires the TLS private key to be supplied as a PEM-encoded PKCS#8-formatted file. " I assume that this restriction is now lifted?

**Comment by andrewtchin** [comment]
doc details in comments here https://github.com/vmware/vic-product/issues/881

**Comment by stuclem** [comment]
Fixed in https://github.com/vmware/vic-product/pull/1565
