### ISSUE TITLE
Remove option to "install standalone registry" from OVA

### ISSUE THREAD

**Issue by akshayl** [vmware/vic-product#157]
In 1.1 we have the option in the OVA to install Harbor only, but in 1.2 we should remove that option since as far as the user is concerned, there is only VIC. If they would like to install another VIC Registry (e.g. for replication use cases), then they would need to install another instance of VIC.

**Comment by akshayl** [comment]
@mdubya66

**Comment by andrewtchin** [comment]
![screen shot 2017-08-10 at 2 20 30 pm](https://user-images.githubusercontent.com/1649165/29187951-1aff3f40-7dd7-11e7-8b9e-252b53c00e58.jpg)
@akshayl Do you mean "3.1 Deploy Registry" here or something else?
