### ISSUE TITLE
Fix failing harbor test

### ISSUE THREAD

**Issue by morris-jason** [vmware/vic-product#1576]
#### Details:

Vic-product CI builds are failing `4-01-Harbor :: Navigate To Registries Page` with

The text of element 'css=.content-area .title' should have been 'Registries' but in fact it was 'Global Registries'. |  
-- | --

Failed builds: https://ci-vic.vmware.com/vmware/vic-product/4401, https://ci-vic.vmware.com/vmware/vic-product/4402

#### Acceptance Criteria:
- [ ] Passing ci build

**Comment by stonezdj** [comment]
This title is created by admiral, not by harbor.

**Comment by stonezdj** [comment]
Found "Global Registries"  in https://github.com/vmware/admiral/blob/cb39c141332ba6e253ccae081ccc46c1c6124c1e/ui/ng-app/src/assets/i18n/admiral.en.json#L164

**Comment by morris-jason** [comment]
Closed by @mdharamadas1 in #1578
