### ISSUE TITLE
Add tests for OVA upgrade script manual disk move

### ISSUE THREAD

**Issue by mdharamadas1** [vmware/vic-product#1583]
Create tests for upgrade script.

Add them here: https://github.com/vmware/vic-product/tree/master/tests/manual-test-cases/Group2-OVA-Features

This is to test the manual disk move option in the 1.4.0 upgrade script 

**Acceptance Criteria:**
- [ ] 1.2.1 to 1.4.0 tested
- [ ] 1.3.0 to 1.4.0 tested
- [ ] 1.3.1 to 1.4.0 tested
- [ ] Stretch goal to automate these tests

**Comment by andrewtchin** [comment]
https://github.com/vmware/vic-product/pull/1593/files

**Comment by andrewtchin** [comment]
Transferring to Manjunath. Branch is updated.
