### ISSUE TITLE
A container is not showing up in VCH but vCenter is still correctly showing it

### ISSUE THREAD

**Issue by arslanabbasi** [vmware/vic-product#1596]
- vCenter Server version: 6.5.0.10000
- Embedded or external PSC: Embedded
- Filename of the OVA you deployed: vic-v1.3.1-3409-132fb13d
- Does the VIC appliance receive configuration by DHCP? No, Static
- What stage of the Appliance Lifecycle is the VIC appliance in?
  https://github.com/vmware/vic-product/blob/master/installer/docs/SUPPORT.md#appliance-lifecycle
- Attach the VIC appliance support bundle (e.g. vic_appliance_logs_2018-01-01-00-01-00.tar.gz)
[vic_appliance_logs_2018-04-13-21-42-46.tar.gz](https://github.com/vmware/vic-product/files/1909589/vic_appliance_logs_2018-04-13-21-42-46.tar.gz)

  https://github.com/vmware/vic-product/blob/master/installer/docs/SUPPORT.md#appliance-support-bundle
  Note: The support bundle may contain private information. If you are not comfortable with posting this publicly, please contact VMware GSS.

OPTIONAL, but helpful:

- IP address of VIC appliance: 10.40.206.187
- Hostname of VIC appliance: vic.tpm.com
- IP address of vCenter Server: 10.40.206.195
- Hostname of vCenter Server: N/A

Bug Report Detailed Information
-------------------------------

- What operation was being performed when the failure was noticed?
Was checking something else when I realized that a container was not showing up.

- Provide information from the `Support Information` section of the appropriate Appliance Lifecycle stage:
  https://github.com/vmware/vic-product/blob/master/installer/docs/SUPPORT.md#appliance-lifecycle

The problematic VCH is "vch2-performance". "Log Bundle" and "Log bundle with container logs" for this VCH is attached. The Container VM that is not showing up in "docker --tls ps -a" is bbc-2.

[container-logs.zip](https://github.com/vmware/vic-product/files/1909673/container-logs.zip)
[logs.zip](https://github.com/vmware/vic-product/files/1909674/logs.zip)

ubuntu@ubuntu:~/vic/vic-bundle/vic⟫ docker --tls ps -a
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS                                                              NAMES
19b7f0018b17        ubuntu              "/bin/bash"         2 hours ago         Up 2 hours          192.168.11.32:22->22/tcp, 192.168.11.32:5000-6000->5000-6000/tcp   u1
4d844997150f        ubuntu              "/bin/bash"         2 hours ago         Up 2 hours          192.168.11.31:22->22/tcp, 192.168.11.31:5000-6000->5000-6000/tcp   u2
7d8b50d601e9        ubuntu              "/bin/bash"         2 hours ago         Up 2 hours                                                                             festive_leavitt
4ee83acc6d9a        busybox             "sh"                3 hours ago         Up 3 hours                                                                             bbc-1
d95121491421        busybox             "sh"                3 hours ago         Up 3 hours                                                                             upbeat_hawking

Let me know if anything else is required.

**Comment by mdubya66** [comment]
Issue moved to [vmware/vic #7743](https://github.com/vmware/vic/issues/7743) via [**ZenHub**](https://www.zenhub.com/)
