### ISSUE TITLE
Proper network diagram for complete solution of VIC, Harbor and Admiral

### ISSUE THREAD

**Issue by muravsky** [vmware/vic-product#16]
I was trying to deploy this solution in corporate network, but due to a lot of security constrains, it's very hard to make it operations. Taking into account, that local internal infrastructure have almost 200 VLAN's, blocked direct access to Internet, distributed topology and a lot of other security measurements, lacking of proper graphical network diagram - makes it almost impossible to deploy and make operational all 3 components.
It's be great to see, what interfaces, needs what accesses. What components communicates to other internal or external components and on what port and protocol.

**Comment by mreferre** [comment]
Thanks @muravsky. This is good feedback and something other users have raised as a point of attention. Have you seen this page in the online documentation? Does this help at all with your struggle? 

https://vmware.github.io/vic-product/assets/files/html/0.8/vic_installation/networks.html

**Comment by muravsky** [comment]
Hi, @mreferre 
Thanks for prompt reply. Indeed, I've missed this page. It's something to start with.
I was looking for a diagram like this http://go.microsoft.com/fwlink/p/?LinkId=550989 for whole set of tools (VIC, Harbor, Admiral). It looks logical for me, as only full set of this tools have strong competitive advantage t enterprise market.
I understand, that it's probably not the correct place for request like this, as people here working hard on VIC. Maybe you can advice, if there is any appropriate separate thread, where this tools discussed as a one solution?

**Comment by mreferre** [comment]
Thanks @muravsky your feedback is being considered.
