### ISSUE TITLE
Add new required ops-user permissions

### ISSUE THREAD

**Issue by stuclem** [vmware/vic-product#1604]
Per PR https://github.com/vmware/vic/pull/7752#issuecomment-381764664, that fixes https://github.com/vmware/vic/issues/7714.

**Comment by stuclem** [comment]
Done in https://github.com/vmware/vic-product/pull/1617/commits/d2b91a233dfb48e46ebd7f81199b8919c1c3df9d

**Comment by stuclem** [comment]
Additional required permissions are listed in https://github.com/vmware/vic/issues/7831

**Comment by stuclem** [comment]
Also, per a Slack chat with @anchal-agrawal, we need to mention that `--ops-grant-perms` does not work with standalone hosts.

**Comment by stuclem** [comment]
@anchal-agrawal do the permissions for `docker cp` need to be added to the 1.3 docs too?

**Comment by stuclem** [comment]
Added the docker cp permissions in https://github.com/vmware/vic-product/pull/1617/commits/8068d45ffd66c4e320bf1545ba6cef057c8fb379.

**Comment by anchal-agrawal** [comment]
> do the permissions for docker cp need to be added to the 1.3 docs too?

@stuclem Yes please.

**Comment by stuclem** [comment]
1.3 updates are tracked in https://github.com/vmware/vic-product/issues/1649. For 1.4 this was fixed in https://github.com/vmware/vic-product/commit/8068d45ffd66c4e320bf1545ba6cef057c8fb379.
