### ISSUE TITLE
VIC Engine version is different in VIC bundle and UI, and UI still enforces DRS requirement

### ISSUE THREAD

**Issue by stuclem** [vmware/vic-product#1616]
- vCenter Server version: **6.5**
- Embedded or external PSC: **embedded**
- Filename of the OVA you deployed: `vic-v1.4.0-rc1-4516-9894ccaa.ova`
- Does the VIC appliance recieve configuration by DHCP? **Yes**
- What stage of the Appliance Lifecycle is the VIC appliance in? **Running**

OPTIONAL, but helpful:

- IP address of VIC appliance: 10.1
- Hostname of VIC appliance: 10.160.10.175
- IP address of vCenter Server: 10.160.234.158
- Hostname of vCenter Server: sc-rdops-vm08-dhcp-234-158.eng.vmware.com

Bug Report Detailed Information
-------------------------------
Deployed two VCHs using the RC1 OVA:

![rc1-versions.png](https://images.zenhubusercontent.com/56afa3216caf56c9d38c1ecf/25d29df2-71ed-4127-9fd9-12257725e3c4)

In the image above, `virtual-container-host` was deployed from the UI, `vch2` from the CLI. They are not the same version.

Also, because of Robo, DRS is no longer a firm requirement on clusters. I disabled DRS on my cluster. `vic-machine` gives a warning when I deploy a VCH, but allows deployment to succeed. UI fails:

![drs-required.png](https://images.zenhubusercontent.com/56afa3216caf56c9d38c1ecf/cb25d120-9872-4be3-bfc8-30e9c7bef763)

**Comment by mdharamadas1** [comment]
Here are the component versions..
```
BUILD_HARBOR_FILE=harbor-offline-installer-v1.5.0-rc1.tgz
BUILD_HARBOR_URL=https://storage.googleapis.com/harbor-releases/release-1.5.0/harbor-offline-installer-v1.5.0-rc1.tgz
BUILD_VICENGINE_FILE=vic_v1.4.0-rc1.tar.gz
BUILD_VICENGINE_URL=https://storage.googleapis.com/vic-engine-releases/vic_v1.4.0-rc1.tar.gz
BUILD_VIC_MACHINE_SERVER_REVISION=dev
BUILD_ADMIRAL_REVISION=v1.4.0-rc1
BUILD_OVA_REVISION=v1.4.0-rc1-4516-9894ccaa
BUILD_DCHPHOTON_VERSION=1.13
DRONE_BUILD_NUMBER=4516
```

I guess we built it with incorrect `BUILD_VIC_MACHINE_SERVER_REVISION` tag, I think we should be using `latest` tag instead of `dev`.

**Comment by andrewtchin** [comment]
I did use `dev` for rc1. We will use `latest` for rc2

**Comment by jak-atx** [comment]
I don't see any issue from UI side here, as both VCH versioning and that enforcement error come from the API side.

**Comment by zjs** [comment]
Based on the version number of the VCH deployed via the UI (which ends in 359ba90), it does seem like the API was using a pre-ROBO version (from last Thursday).

**Comment by andrewtchin** [comment]
Looks like this is only caused by building with the wrong vic-machine-server container. I'll keep this open until we build RC2 and we can verify at that time.

**Comment by stuclem** [comment]
Undoubtedly related to the use of the old build, but I just deployed a VCH from the CLI to a cluster with DRS disabled, which worked fine. But if you look at that VCH in the UI, you see the following:

![not-rp](https://user-images.githubusercontent.com/16718369/38979985-f1772d94-43bb-11e8-9ecb-35a4bc33eece.png)

Same thing happens if you deloy VCHs to a DRS-enabled cluster using either the CLI or the UI, and then disable DRS on the cluster (although I'm not sure that this is something that anyone would ever realistically do). Turning off DRS turns the RPs into folders, and the UI can no longer find the VCHs.

If you try to delete the VCHs from the UI, you can't:

![cant-delete](https://user-images.githubusercontent.com/16718369/38980210-8118f0ae-43bc-11e8-81f0-28c453c7fa3b.png)

Am sure that all this will be remedied by using the correct build, but mentioning it all here as it's something to check in RC2.

**Comment by stuclem** [comment]
Tested with RC3. VCHs from CLI and UI are now of the same version. DRS is not enforced in UI.
