### ISSUE TITLE
VHC Deploy from Admiral shows all clusters in each datacenter (6.7 with 1.4RC1)

### ISSUE THREAD

**Issue by SemperFu** [vmware/vic-product#1623]
Bug Report Basic Information
----------------------------

REQUIRED:

- vCenter Server version: 6.7
- Embedded or external PSC: Embedded
- Filename of the OVA you deployed: vic-v1.4.0-rc1-4516-9894ccaa.ova
- Does the VIC appliance recieve configuration by DHCP? Static IP
- What stage of the Appliance Lifecycle is the VIC appliance in? Running Stage
- Attach the VIC appliance support bundle : Attached. Not sure if it will show anything

Bug Report Detailed Information
-------------------------------

- What operation was being performed when the failure was noticed?
Deploying a new VHC

- Provide additional detail as necessary:

When deploying a new VHC it was erroring out at the end but showing the wrong datacenter for my cluster. I went back to look at the compute options and the clusters in each datacenter show up in both.

I updated to both 6.7 and 1.4RC1 so I do not know which the issue is with. I have attached screenshots of my vCenter showing the datacenters and the hosts as well as screenshots of what the compute list shows.

[container-logs.zip](https://github.com/vmware/vic-product/files/1929890/container-logs.zip)
![1](https://user-images.githubusercontent.com/1786698/39020359-904d2200-43fa-11e8-9ca0-a65e735cf23c.PNG)
![2](https://user-images.githubusercontent.com/1786698/39020360-905e8504-43fa-11e8-8aaa-b7c9ea74a3d5.PNG)
![3](https://user-images.githubusercontent.com/1786698/39020361-9069c3a6-43fa-11e8-98bf-785f67613f56.PNG)

**Comment by javierfz1980** [comment]
Fixed in https://github.com/vmware/vic-ui/issues/428

**Comment by SemperFu** [comment]
Sorry I searched in a couple of them but not that.
