### ISSUE TITLE
Update comment about copying to NFS datastores

### ISSUE THREAD

**Issue by stuclem** [vmware/vic-product#1641]
Per comment from @matthewavery, this statement is inaccurate: https://github.com/vmware/vic-product/pull/570/files#diff-352f1c98d560d524ad10934c42aa6850R44

It should be more like “you cannot copy to a moutned nfs volume when the container is offline.”

**Comment by matthewavery** [comment]
George has also recommended the wording: "**"You cannot copy to an NFS volume that is not in use by a running container"**

**Comment by stuclem** [comment]
Fixed in https://github.com/vmware/vic-product/pull/1524
