### ISSUE TITLE
Document how whitelists on VCHs and in VIC Managment Portal interact

### ISSUE THREAD

**Issue by stuclem** [vmware/vic-product#1651]
- vCenter Server version: **6.5**
- Embedded or external PSC: **Embedded**
- Filename of the OVA you deployed: `vic-v1.4.0-rc1-4516-9894ccaa.ova`
- Does the VIC appliance recieve configuration by DHCP? Yes
- What stage of the Appliance Lifecycle is the VIC appliance in? **Running**

Bug Report Detailed Information
-------------------------------

This issue results from a question that @alextopuzov posted to Slack:

"AFAIK Admiral will now work in Whitelist mode only, meaning that only images from registries, that are added either as "global" or "project" in admiral, can be provisioned. VCHs also have whitelist option to allow certain registries that is configured separately. How are VCHs and Admiral syncing their whitelists? May be one takes precedence? Which one? If this is written somewhere, please point me to that doc."

Further to this, we did a little experiment. I deployed a VCH with whitelist mode enabled, and added the registry from VicAppliance#1 as the only entry in that whitelist. We then added the VCH to the default project in Management Portal in VicAppliance#2, which is set up with the standard list of registries at the global level (and as @alextopuzov says above, this list is now enforced as a whitelist). We tried to provision a `busybox` container from dockerhub to this VCH from the VIC MP, and deployment failed:        

![whitelistfail.png](https://images.zenhubusercontent.com/56afa3216caf56c9d38c1ecf/47ccb131-db1a-4c16-bf0a-89c06ff479f2)        

So, how do we reconcile the whitelists configured at the VCH level (by the vSphere admin) with the global whitelists configured in MP (by the cloud admin) and the whitelists configured at the project level (by the devops admin)?

In other words, if a VCH is running in whitelist mode, and if the devops admin wants to add a new project-level registry, does the devops admin have to ask the vSphere admin to reconfigure the VCH to add this new registry to the VCH's whitelist?

Actually, looking at `vic-machine configure --help`, there is no option to reconfigure the whitelist of a VCH after deployment. You can add new certs for secure registries, but once a VCH is configured in whitelist mode, there's no way of reversing that or of adding new insecure registries to the whitelist. 

I foresee a lot of customer confusion about this. We could document that if you use Management Portal to manage the registries that you can access from a project, then you shouldn't activate the whitelist mode on the VCH. But, nothing then prevents users from using the VCH directly, pulling down images from forbidden registries, then pushing them into a project in VIC Registry, because the VCH is not subject to the restrictions of the whitelist defined in Management Portal.

In the initial Slack conversation, @mdubya66 requested that @lazarin @reasonerjt and @hickeng                         should review this. We also probably need input from @pdaigle about what approach we should take in the docs.

**Comment by AngieCris** [comment]
Cc: @andrewtchin

**Comment by hickeng** [comment]
@stuclem The VCH whitelist should be the _most_ permissive of the registry whitelists. For example this could be a domain wildcard, e.g. *.eng.vmware.com.
The ‘content trust enabled’ checkbox could then configure the VCH with the specific registry for the project, e.g. myproj.eng.vmware.com. Because the whitelist pushed for the project is a _subset_ of that configured for the VCH it is acceptable as a dynamic configuration and is adopted as the active configuration _for the VCH_.
If the project registry is not a subset of the VCH whitelist then it will be rejected - this was done deliberately to protect VCHs against a compromised VIC appliance. This was done in the expectation that other configuration elements could/would be dynamically adjustable in the same manner but only with the limits set by the viadmin when the VCH was deployed.
This has been true since we added the initial portions of content trust and, to my knowledge, hasn’t changed since then.

**Comment by stuclem** [comment]
From @hickeng via email: "There also needs to a clarification between Admiral whitelist (which the VCH is completely unaware of to my knowledge), VCH whitelist, and a VCH in a project with content trust enabled (is this the same as admiral whitelist?).
In that last the VCH will be locked down to only pull from the primary project registry, _so long as that registry is a subset of the existing VCH whitelist_. If it is not a subset then the configuration will not be applied to the VCH but the content trust checkbox will still be checked."

**Comment by stuclem** [comment]
Thanks @hickeng. This is the first that I have heard of content trust in the context of the management portal whitelists. You seem to be suggesting that activating content trust on a project pushes the admiral whitelist to the VCHs in that project. But you also say that if content trust is enabled, the VCHs can only pull from the default repository. Either I am very confused (which is probable) or we're talking about different things here. To come to your statement "...a VCH in a project with content trust enabled (is this the same as admiral whitelist?)", my opinion is that it is not the same thing.

@lazarin or @gmuleshkov  can you please explain how activating content trust modifies the VCHs, and whether this is related to the new admiral whitelists? Thanks!

**Comment by stuclem** [comment]
I think that there is some confusion here. The Admiral developers have never mentioned content trust in the context of the new whitelist feature. @lazarin and @gmuleshkov can you please confirm that this is completely unrelated to content trust?

**Comment by lazarin** [comment]
Yes, content trust is something between harbor and vch. It is not related with the admiral registry whitelisting

**Comment by stuclem** [comment]
Opened #1688 to improve the docs about content trust, which I think is entirely independent of this issue about VCH/Admiral whitelists.

**Comment by stuclem** [comment]
So, if we remove content trust from the equation, @lazarin @hickeng @pdaigle @mdubya66 @martin-borisov can we proceed as follows in the docs?:

1. Document that the global and project lists of registries are de facto whitelists, and you cannot pull images from elsewhere when using Admiral.
2. Document that if you intend to use a VCH with Admiral, if you enable the whitelist mode on the VCH, the whitelist should be broader in scope than the lists that you configure in Admiral.
3. Document that if the whitelist on the VCH is more restrictive than the lists in Admiral, then you will not be able to provision containers from the registries that are not whitelisted by the VCH, even if they are present in the Admiral lists.
4. Document that if the whitelist on the VCH is less restrictive than the whitelists configured in Admiral, if you connect directly to the VCH, you will be able to pull images from registries that Admiral would not permit.
5. Document that after you deploy the VCH, if you get a conflict, mismatch, or other general SNAFU because of unsynchronized whitelists between the VCH and Admiral, your only option is to redeploy the VCH with either no whitelist, a more permissive whitelist, or a whitelist that exactly matches Admiral's. This is because you CANNOT MODIFY a VCH whitelist after initial deployment in 1.4.

**Comment by lazarin** [comment]
@stuclem Sounds OK from admiral pov when using VCH.
1 Is the general rule; 2,3 and 4 are consequence of it; 5 is vch related

**Comment by stuclem** [comment]
Thanks @lazarin

**Comment by pdaigle** [comment]
@stuclem The proposed documentation approach seems accurate. OK from my end.
