### ISSUE TITLE
Document whether adding the same VCH to multiple projects is supported or not 

### ISSUE THREAD

**Issue by stuclem** [vmware/vic-product#1659]
We need to follow the discussion in https://github.com/vmware/admiral/issues/264 and document whether or not it is supported to add the same VCH to multiple projects.

**Comment by alextopuzov** [comment]
According to the behavior tests me and Stu conducted and the reassurance by @martin-borisov adding single VCH to multiple projects is supported.

**Comment by alextopuzov** [comment]
The current 1.4 doc also confirms this behavior: "You can add the same VCH to multiple projects."

Closing as not an issue.

**Comment by stuclem** [comment]
My findings about what happens to a VCH when you enable content trust are documented in https://github.com/vmware/vic-product/issues/1688#issuecomment-395753647 onwards. In the light of those findings, @pdaigle should we document that you should not use a VCH in more than one project if you intend to use content trust? Or at all? Thanks!

**Comment by stuclem** [comment]
Per Slack chat with @pdaigle, we should recommend using VCHs in only one project.

**Comment by stuclem** [comment]
Fixed in https://github.com/vmware/vic-product/pull/1850.
