### ISSUE TITLE
mac user docs: setup ca.crt for VCH

### ISSUE THREAD

**Issue by frapposelli** [vmware/vic-product#167]
@tompscanlan commented on [Fri Apr 14 2017](https://github.com/vmware/vic/issues/4798)

**User Statement:**

As a mac user, connecting to existing VCH, I want to be able to docker login and docker push.  

Running docker login fails with `Error response from daemon: Head https://harbor.yyy.org/v2/: x509: certificate signed by unknown authority`

**Details:**

Add mac specific details at: 
https://vmware.github.io/vic-product/assets/files/html/latest/vic_installation/deploy_vch_harbor.html

something like: sudo security add-trusted-cert -d -r trustRoot -k /Library/Keychains/System.keychain harbor-ca.crt

may do the trick.

Alternatively, indicate that making a new VCH with the registry ca.crt achieves the same goal.

**Acceptance Criteria:**

A mac user with a pre-existing VCH can read the doc and successfully do a `docker login && docker push ...`

---

@frapposelli commented on [Mon Apr 17 2017](https://github.com/vmware/vic/issues/4798#issuecomment-294506079)

moving this to `vic-product`

**Comment by stuclem** [comment]
Comment from @karthik-narayan on the same subject:

----

[This page](https://stuclem.github.io/vic-product/assets/files/html/1.1/vic_app_dev/configure_docker_client.html#registry) details the steps necessary to add a self signed registry cert for Linux and Windows. We should also document this for OSX. 

The details can be found below: 
http://container-solutions.com/adding-self-signed-registry-certs-docker-mac/

-----

Closed https://github.com/vmware/vic-product/issues/146 as a dup of this one.

**Comment by stuclem** [comment]
We also need to update the topic on configuring the Docker client with Windows/Mac commands for configuring Notary and other config.

**Comment by stuclem** [comment]
Won't make it into 1.1.1

**Comment by stuclem** [comment]
No one else has asked for this. Closing.
