### ISSUE TITLE
Initial VIC appliance deployment fails to complete when behind proxy.  Specifically the harbor service.

### ISSUE THREAD

**Issue by sidrew** [vmware/vic-product#1680]
- vCenter Server version:
6.7
- Embedded or external PSC:
External
- Filename of the OVA you deployed:
vic-v1.4.0-rc2-4741-f02b3258.ova
- How was the OVA deployed? (Flex client, HTML5 client, ovftool):
Flex
- Does the VIC appliance recieve configuration by DHCP? 
Static
- What stage of the Appliance Lifecycle is the VIC appliance in?  
Dev

- What operation was being performed when the failure was noticed?

After deployment of the VIC appliance, initial service configuration.  According to the logs, Harbor was unable to download the container image: vmware/registry:2.6.2-photon

Since none of the proxy configurations system to work... (https://github.com/vmware/vic-product/issues/1258) I chose to configure a proxy for the docker service itself and manually download the container image that harbor wanted.  To do this, I created this file:

/etc/systemd/system/docker.service.d/http-proxy.conf

Added this content to make it work:

[Service]
Environment="HTTP_PROXY=http://myproxy.foo.bar:3128"
Environment="NO_PROXY=localhost,127.0.0.0/8,foo.bar"

Then I ran:

systemctl daemon-reload
systemctl restart docker

Then I merely pulled the image:

docker pull vmware/registry:2.6.2-photon

And restarted admiral:

systemctl restart admiral

Once that was done... admiral and harbor were able to finish configuring... and the registry was finally available on 443.

**Comment by morris-jason** [comment]
This issue will be fixed for 1.4.0 by https://github.com/vmware/vic-product/pull/1716.
If you run into the issue again when the 1.4.0 ova is available, please re open the issue.
