### ISSUE TITLE
[Question] Support for Windows container hosts planned?

### ISSUE THREAD

**Issue by megamorf** [vmware/vic-product#17]
Hey, I'd like to know if you plan to support Windows container hosts in VIC. We have a heterogenous environment and being able to support Windows and Linux docker containers via VIC would be a tremendous value to our business.

Thanks in advance.

- Sebastian

**Comment by mdubya66** [comment]
https://github.com/vmware/vic/issues/3578

**Comment by stuclem** [comment]
Since there's an issue in the VIC repo for Windows container hosts, closing this one.
