### ISSUE TITLE
configuration files in /etc/vmware/harbor/common should be 0644 by default

### ISSUE THREAD

**Issue by reasonerjt** [vmware/vic-product#1707]
As Harbor containers are run as non-root, the `0600` will cause permission issue when the configuration files in `/etc/vmware/harbor/common` are mounted into the containers.

In previous releases in the container it will call `chown` to the files but there are failures when the `chown` is removed on master branch

**Comment by mdubya66** [comment]
Is this a ship stop @reasonerjt

**Comment by reasonerjt** [comment]
No it's not, this impacts master branch only

**Comment by zjs** [comment]
@reasonerjt, has this been fixed?

**Comment by reasonerjt** [comment]
@zjs  given we don't see permission issue in VIC 1.5 I believe this has been fixed.  Closing.
