### ISSUE TITLE
Clarify descriptions of registry-ca and insecure-registry options

### ISSUE THREAD

**Issue by stuclem** [vmware/vic-product#171]
Per long Slack conversation with @jzt, the descriptions of the `--registry-ca` and `--insecure-registry` options, while not exactly wrong, are not exactly right either. Basically, by setting `--insecure-registry`, one is instructing the VCH not to verify the clients who attempt to pull from that Registry. My write up suggests that `--insecure-registry` is for registries with no security whatsoever, which is not the case.

**Comment by jzt** [comment]
@stuclem In summary: `--insecure-registry $REGISTRY` instructs the VCH to skip cert verification for `$REGISTRY` (as opposed to clients attempting to pull from `$REGISTRY`). It also allows the puller to attempt to fall back from `https` to `http` if the `https` attempt did not succeed. The VCH should also skip the cert verification step attempted during `docker login $REGISTRY`, but this is currently broken (see https://github.com/vmware/vic/issues/4681).

Sorry, just wanted to be clear, and I know it's really late where you are right now. :)
