### ISSUE TITLE
Test the vic appliance without internet connectivity

### ISSUE THREAD

**Issue by morris-jason** [vmware/vic-product#1714]
##### For feature requests/user stories, please include the information below:

**User Statement:**

**Details:**

Add a vic-product nightly test to deploy an ova on a port group without a wan connection.
See https://github.com/vmware/vic/blob/master/tests/manual-test-cases/Group5-Functional-Tests/5-28-VICAdmin-Isolated.robot.

**Acceptance Criteria:**

**Comment by renmaosheng** [comment]
Lu, has we covered this in nsx-t scenario? thanks.

**Comment by luwang-vmware** [comment]
@renmaosheng  Our nsxt-t scenario is not private-network. We leverage hack-nimbus to deploy private network and succeed to deploy VIC OVA, install VIC UI plugin and deploy VCH. Close it now.
