### ISSUE TITLE
Automated UI Plugin Script Update

### ISSUE THREAD

**Issue by morris-jason** [vmware/vic-product#1740]
**User Statement:**
As an administrator I want functional scripts to interact with the lifecycle of the vic ui plugin.

**Details:**

**Acceptance Criteria:**
- [ ] Update the linux bash as a curl wrapper for the register api.
- [ ] Update the windows powershell scripts as a curl wrapper for the register api.

**Comment by mdharamadas1** [comment]
estimate for linux only.

**Comment by morris-jason** [comment]
Closing this. Per conversation with @zjs, customer interaction should be through the plugin install apis directly. As a consequence of removing this, robot tests need to be updated to use curl (tracked in #1771).
