### ISSUE TITLE
Add more detailed info about MP and file server logs

### ISSUE THREAD

**Issue by stuclem** [vmware/vic-product#1741]
Following a conversation with @dbarkelew, in [Access and Configure Appliance Logs](https://vmware.github.io/vic-product/assets/files/html/1.4/vic_vsphere_admin/appliance_logs.html) we provide details of the different logs for Registry (see step 4), but not for the other services.              

@lazarin @zjs @morris-jason could you please provide the info for the other services running in the appliance?

Thanks!

**Comment by stuclem** [comment]
@lazarin what info does `xenonHost.0.log` contain? Are these all of the logs for Admiral? Thanks!

**Comment by stuclem** [comment]
@morris-jason we seem to have two conflicting statements in the doc:

6. To access logs for the `vic-machine-server` service, navigate to `/storage/log/vic-machine-server`.<pre>$ cd /storage/log/vic-machine-server</pre>The `/storage/log/vic-machine-server` folder contains a file named `vic-machine-server.log`, that includes all of the logs for the `vic-machine-server` service. **The default configuration allows 10 files, up to 1GB each.**
7. To configure the `vic-machine-server` service log retention, edit the `/etc/logrotate.d/vic-machine-server` file.<pre>$ vi /etc/logrotate.d/vic-machine-server</pre>**The default configuration allows 50 files, up to 200MB each per service.**

Which one is accurate?

**Comment by morris-jason** [comment]
The configuration file located in `/etc/logrotate.d/vic-machine-server` *is* the default, and specifies the default configuration allowing 10 files, up to 1GB each.

Not sure where #2 came from.

**Comment by stuclem** [comment]
OK, thanks @morris-jason. I think that the second one is a cut-n-paste error from the entry about Harbor logs.
