### ISSUE TITLE
Automated VIC UI Plugin - Nightly/Integration Tests

### ISSUE THREAD

**Issue by morris-jason** [vmware/vic-product#1770]
**User Statement:**
As a developer I want automated testing of the automated VIC UI plugin install.

**Details:**

**Acceptance Criteria:**
- [ ] Nightly or Integration test for install through UI
- [ ] Nightly test for install through API

**Comment by morris-jason** [comment]
See #1701 for original test story.

**Comment by zjs** [comment]
We now have test code which verifies that the initialization process completes, but we do not verify that the plugin was successfully installed as a part of that process. 

Eventually, we want to have Selenium code which verifies that:
1. The plugin is available in the expected place in the H5 UI.
2. The plugin can successfully connect to the OVA.
3. The plugin can use the OVA to perform some basic operation (e.g., delete a VCH).

In the short term (i.e., for 1.4.3), we could simply use `govc` or a `curl` command against the MOB to verify that VC reports that the plugin in installed. If we go this route, we will need to supplement this basic automation with manual testing.

**Comment by renmaosheng** [comment]
There is one test against Firefox always failed due to the thumbprint window not pop up. raising to p0 to fix it before 1.4.3 rtm

**Comment by wjun** [comment]
We have PR #2004 and #1979 to address UI and API tests respectively.

**Comment by zjs** [comment]
> We have PR #2004 and #1979 to address UI and API tests respectively.

Do these PRs include the verification described in https://github.com/vmware/vic-product/issues/1770#issuecomment-415315940?
