### ISSUE TITLE
Automated VIC UI Plugin - Updated Tests

### ISSUE THREAD

**Issue by morris-jason** [vmware/vic-product#1771]
**User Statement:**
As a developer I want automated testing of the automated VIC UI plugin install.

**Details:**

**Acceptance Criteria:**
- [ ] Update `vmware/vic-ui/tests/test-cases` and `/vmware/vic-product/tests/manual-test-cases/Group18-VIC-UI` to invoke the plugin install api not the install script.
- [ ] Update `/vmware/vic-product/tests/` to send a thumbprint to the register api.

**Comment by zjs** [comment]
Fixed in #1911
