### ISSUE TITLE
Simplify log collection directions.

### ISSUE THREAD

**Issue by dbarkelew** [vmware/vic-product#1774]
https://vmware.github.io/vic-product/assets/files/html/1.4/vic_vsphere_admin/log_bundles.html

The directions for collecting the VCH logs is not clear for someone who is not already familiar. Sometimes there are admins covering for the person who setup VIC that need to collect logs for support issues. 
Requesting to have directions in a step by step format that can be followed by anyone including users who are seeing VIC for the first time. Maybe something like.

1. Open https://IP:2378 in a browser. If needed, directions to find the VCH IP can be found at <link to documentation that explains this>.
2. login with an account that has access to (whatever requirements the login account needs to work)
3. next steps......
4. .....

See the following article at https://kb.vmware.com/kb/2032892 for an example direction format for log collection directions that vcenter is explain in.

**Comment by stuclem** [comment]
We should convert https://vmware.github.io/vic-product/assets/files/html/1.4/vic_vsphere_admin/log_bundles.html from a bunch of bullets into an ordered procedure, as proposed by @dbarkelew.
