### ISSUE TITLE
Issue with upgrade from VIC 1.0 (harbor Virtual Appliance) and with LDAP Authentication on 1.1

### ISSUE THREAD

**Issue by fduranti** [vmware/vic-product#178]
I'm trying to upgrade our VIC 1.0 installation that use harbor 0.5 virtual appliance.
Our Harbor is configured to use LDAP on AD (just 3 users are using it at this moment) and it seems that the upgrade/migration process have some problem with this.

I've tried in various way but it seems I cannot have it to work:
Installed new VA, attached disks, run the migration script: I see that in the admin page the User Database remain on "Database" and cannot be changed to LDAP. I see my 3 users defined as if they was internal user.

Installed new VA, attached disks, configured LDAP and done some test login. Some of my use don't have an email defined and without an Email on LDAP it seems that harbor is not allowing them to login. On my personal user i see it just with the email without user name after the first login (uid is configured as sAMAccountName because ldap is an Active Directory). 
![image](https://cloud.githubusercontent.com/assets/1173084/25229094/2b2c4dc8-25cf-11e7-946a-a45281849636.png)
Trying to configure the user as an administrator will give correctly admin permission to that user (after the login I don't see my user name but admin in the right corner... is this correct) ? 
Revoking the admin permission seems to have no effect my user still get the admin console and see himself as Admin.

At this point I tried to run the migration script. After the migration it seems that ldap configuration got something wrong and I had to reconfigure the connection (as it was getting a bad username/password) and LDAP test is now ok.
This is the user table after the migration:
![image](https://cloud.githubusercontent.com/assets/1173084/25229753/ccc4af34-25d1-11e7-8b53-e60e30cc1150.png)
I cannot login with any of those users.
Changing on ldap the 2 users without an email to have one I was able to login with them but still not able to login with fduranti (my user).
On the user table now there's one (only one) of those user's with the email and without username... 
![image](https://cloud.githubusercontent.com/assets/1173084/25230360/f04e7348-25d3-11e7-9b6f-01c27de88f3e.png)

There's something strange on LDAP management on 1.1 I think.

**Comment by reasonerjt** [comment]
@fduranti Thanks for reporting this is a known issue:
https://github.com/vmware/harbor/issues/2034

**Comment by fduranti** [comment]
@reasonerjt Thanks, I think I should wait for a fix before upgrading :)
