### ISSUE TITLE
Support appliance 1.4.1 Upgrade

### ISSUE THREAD

**Issue by morris-jason** [vmware/vic-product#1806]
##### For feature requests/user stories, please include the information below:

**User Statement:**

As a vSphere admin I'd like to upgrade the VIC 1.4.0 ova to VIC 1.4.1.

**Details:**

The upgrade script needs to be edited to support the vic 1.4.0 tag as a recognized upgrade path.

**Acceptance Criteria:**
- [ ] Upgrade 1.4.0 to 1.4.1 is a recognized path
- [ ] Nightly upgrade test added for 1.4.0 to 1.4.1

**Comment by morris-jason** [comment]
@stuclem Possible doc change needed to state that v.1.4.0 is a valid upgrade path for the vic appliance. https://vmware.github.io/vic-product/assets/files/html/1.4/vic_vsphere_admin/upgrade_appliance.html looks fine to me, but wanted to let you know.

**Comment by stuclem** [comment]
Thanks @morris-jason, I added https://github.com/vmware/vic-product/issues/1817 to track the doc update.
