### ISSUE TITLE
Provide mechanism for changing appliance TLS certs after deployment 

### ISSUE THREAD

**Issue by chriscrowe** [vmware/vic-product#1810]
I've pored over the docs and I cannot find a way to change my TLS certs after the VIC appliance has already been deployed -- seems we only have a mechanism to do this in the OVA customizations during the initial deployment.

**Comment by andrewtchin** [comment]
Hi @chriscrowe you should be able to shutdown the guest OS of the VIC appliance, edit settings, and edit the vApp settings. This will display the same style menu as OVA customizations during initial deployment and you can update the values there. Let me know if that works!

**Comment by renmaosheng** [comment]
@ading007 @luwang-vmware let's test this in 1.5.3 if there is any issue found, let's fix it.

**Comment by luwang-vmware** [comment]
We manually tested in internally already and it works as expected.
