### ISSUE TITLE
Document 1.4.0 to 1.4.1 as a supported upgrade path

### ISSUE THREAD

**Issue by stuclem** [vmware/vic-product#1817]
According to @morris-jason in https://github.com/vmware/vic-product/issues/1806#issuecomment-393681374, the only change to the upgrade docs required for 1.4.1 is to add 1.4.0 as a supported upgrade path.

**Comment by stuclem** [comment]
Actually, we already have this covered: 

- [Upgrading vSphere Integrated Containers](https://vmware.github.io/vic-product/assets/files/html/1.4/vic_vsphere_admin/upgrading_vic.html): "_You can only upgrade vSphere Integrated Containers from version 1.2.x or 1.3.x to 1.4.x, or from 1.4.x to a later 1.4.y update release._"
- [Upgrade the vSphere Integrated Containers Appliance](https://vmware.github.io/vic-product/assets/files/html/1.4/vic_vsphere_admin/upgrade_appliance.html): "_If you have a 1.2.1 or 1.3.x version of the vSphere Integrated Containers appliance, you can upgrade your existing installation to 1.4.x. You can also upgrade a 1.4.x release to a later 1.4.y update release._"

@morris-jason are you happy that this covers it?

**Comment by morris-jason** [comment]
Yupp, that's what I thought, thanks!!

**Comment by stuclem** [comment]
OK, thanks @morris-jason. Closing.
