### ISSUE TITLE
Add troubleshooting doc for orphaned vCMs

### ISSUE THREAD

**Issue by stuclem** [vmware/vic-product#1827]
Per https://github.com/vmware/vic/issues/8015

**Comment by stuclem** [comment]
@vidya-v can you please take a look at this one? Details are in https://github.com/vmware/vic/issues/8015#issuecomment-395522974. Thanks!

**Comment by vidya-v** [comment]
Documented - [vmware/vic-product#2341](https://github.com/vmware/vic-product/pull/2341)
