### ISSUE TITLE
Document how to mix signed and unsigned images in a project 

### ISSUE THREAD

**Issue by stuclem** [vmware/vic-product#1863]
Comment from @hickeng in https://github.com/vmware/vic-product/pull/1850#discussion_r199024279: "I'm not actually sure how best to do that; the implication is that a separate project is required, but given a project is also an RBAC boundary that may mean creating two projects for a given set of users. Can ask admiral or harbor if the public/private/global mechanisms provide a path for this."

@martin-borisov @reasonerjt can you please help? Thanks!

**Comment by stuclem** [comment]
@martin-borisov and @reasonerjt can you please confirm that the only way to mix signed and unsigned images is to create two projects and assign the same users to both projects?

**Comment by reasonerjt** [comment]
@vidya 
AFAIK there's no restriction one project cannot **store** the signed and unsigned images.
The only restriction is that if project admin enables the "content trust" policy, only signed image can be pulled.

**Comment by vidya-v** [comment]
Thanks @reasonerjt , I have updated the document (PR: vmware/vic-product#2467)
