### ISSUE TITLE
Road test the VIC docs with the 1.1 GA version

### ISSUE THREAD

**Issue by stuclem** [vmware/vic-product#187]
@alextopuzov, to give you a broader introduction to VIC that goes beyond the Management Portal, and to test the validity and comprehensibility of the docs, could you please work through the VIC docs posted at https://vmware.github.io/vic-product/assets/files/html/1.1/ and attempt to set up a working deployment of VIC? 

Please record observations, corrections, and questions in this issue. Thanks!

**Comment by alextopuzov** [comment]
Done, fb collected. Closing.
