### ISSUE TITLE
Test 3-01 Admiral UI failing with "Element locator 'css=.modal-title' did not match any elements after 30 seconds"

### ISSUE THREAD

**Issue by zjs** [vmware/vic-product#1878]
Failures:
 - https://ci-vic.vmware.com/vmware/vic-product/5557
 - https://ci-vic.vmware.com/vmware/vic-product/5558
 - https://ci-vic.vmware.com/vmware/vic-product/5559
 - https://ci-vic.vmware.com/vmware/vic-product/5565
 - https://ci-vic.vmware.com/vmware/vic-product/5566
 - https://ci-vic.vmware.com/vmware/vic-product/5567
 - https://ci-vic.vmware.com/vmware/vic-product/5568
 - https://ci-vic.vmware.com/vmware/vic-product/5569
 - https://ci-vic.vmware.com/vmware/vic-product/5570

The failures seem unrelated to code changes on `master` as the first run where this failure occurred was previously tested successfully:
 - https://ci-vic.vmware.com/vmware/vic-product/5553
 - https://ci-vic.vmware.com/vmware/vic-product/5554
 - https://ci-vic.vmware.com/vmware/vic-product/5555
 - https://ci-vic.vmware.com/vmware/vic-product/5556

**Comment by zjs** [comment]
When the test fails, the screen looks like this:
![selenium-screenshot-1](https://user-images.githubusercontent.com/408880/43120695-bdfbe85a-8f4d-11e8-9214-a9d0c89a729c.png)

The test is looking for an element matching the CSS locator `.modal-title`, but failing to find it.

**Comment by DanielXiao** [comment]
Can we skip them? OVA build is blocked by this issue.

**Comment by zjs** [comment]
It seems like we should prioritize fixing these tests. Fortunately, the breakage does not affect the 1.4.x release branches.

**Comment by zjs** [comment]
This appears to have been fixed.
