### ISSUE TITLE
Enable nightly test again vsphere 6.7 u1 build on branch 1.4.1

### ISSUE THREAD

**Issue by DanielXiao** [vmware/vic-product#1881]
**User Statement:**
Need to enable nightly tests again vsphere 6.7 u1 build and run tests for VIC 1.4.1 GA build.

**Details:**
vsphere 6.7 u1 Build:
ESXi: 9036443
vCenter: 9121219

VIC build: 5547

**Acceptance Criteria:**
Enable  vic and vic-product nightly tests on vsphere 6.7 u1. 
VIC 1.4.1 GA build pass tests.

**Comment by renmaosheng** [comment]
is this done? thanks.

**Comment by DanielXiao** [comment]
Yes. It 's done. https://vic-jenkins.eng.vmware.com/view/Yifeng-Test/job/vic-scenario-test-manual-trigger-staging
