### ISSUE TITLE
Document VIC requirements for vRA integration

### ISSUE THREAD

**Issue by stuclem** [vmware/vic-product#1894]
Per email thread started by @dbarkelew.

**Comment by stuclem** [comment]
Apparently vRA 7.5 supports VIC 1.4.x.

**Comment by stuclem** [comment]
@martin-borisov will vRA 7.5 support all  VIC 1.4.3 releases, or just 1.4.3? Thanks!

**Comment by stuclem** [comment]
@vidya-v can you please follow up with @martin-borisov (Admiral dev mgr) about this one? Thanks!

**Comment by martin-borisov** [comment]
vRA 7.5 supports VIC 1.3.x and VIC 1.4.x, up to and including 1.4.2.

**Comment by stuclem** [comment]
We must wait until vRA 7.5 GA before we mention this in the VIC docs.

**Comment by stuclem** [comment]
vRA 7.5 is now live: https://docs.vmware.com/en/vRealize-Automation/index.html
