### ISSUE TITLE
Fix the backup docs for ≤1.4.x

### ISSUE THREAD

**Issue by stuclem** [vmware/vic-product#1896]
Per an email thread started by @dbarkelew, the current recommendations/instructions for [backing up and restoring the VIC appliance](https://vmware.github.io/vic-product/assets/files/html/1.4/vic_vsphere_admin/backup_vic_appliance.html) are not reliable. In the short term, we need to fix the existing docs to provide a valid backup/restore solution. For this, we need input from @zjs and @hickeng.

Longer term, according to @lgayatri, code changes are required in the appliance in order to make proper backup/restore possible. When those changes are made, we must update the docs accordingly.

**Comment by stuclem** [comment]
See https://github.com/vmware/vic-product/issues/1897 for details of the engineering fix for future versions.

**Comment by stuclem** [comment]
Moving back to backlog pending ongoing investigations by dev and QE about how to back up the current versions.

**Comment by stuclem** [comment]
@zjs and @hickeng what should we do about the current (incorrect) doc about backup, pending the ongoing investigation into a better backup solution?

**Comment by stuclem** [comment]
According to @hickeng we need to document the following for the existing releases:

Current backup solution:

1. shut down the appliance (to quiesce database)
2. back up via whatever mechanism (snapshot)
3. extract ovfEnv config (manually as VM backup)

Current restore solution:

1. restore appliance (via whatever means)
2. convert restored VM into vApp (hopefully possible)
3. restore the ovfEnv.
4. power on appliance

Point 2 in the restore solution requires verification before I can document this.

**Comment by stuclem** [comment]
@renmaosheng do we still need to update the backup docs for 1.4.x releases, or has everyone upgraded to 1.5.x by now?

**Comment by renmaosheng** [comment]
Hi Stuart, customers won't upgrade so aggressively, we still have 1.4.x customers. let's enhance our documents. thanks.

**Comment by stuclem** [comment]
@renmaosheng confirmed by Slack that we do need to make this update.

**Comment by stuclem** [comment]
This update has been made in the 1.5.x docs in https://github.com/vmware/vic-product/pull/2361. We need to port these changes into 1.4.x.

**Comment by stuclem** [comment]
Updated 1.4 docs are live: https://vmware.github.io/vic-product/assets/files/html/1.4/vic_vsphere_admin/backup_vic_appliance.html
