### ISSUE TITLE
Doc overhaul for VIC 1.1

### ISSUE THREAD

**Issue by stuclem** [vmware/vic-product#19]
This is a proposal for an overhaul of the VIC docs for the next major release:

- We currently have the VIC Engine docs that were authored by @npakrasi and myself for 0.8, and Harbor and Admiral docs that were authored by the Harbor and Admiral engineers. There is little to no crossover between them. There is no overarching doc about how to put the three products together.
  **Proposal**: Create a unified VIC doc set that covers all three components. The emphasis will be on using all 3 components together, rather than using them independently of each other. 
  **Potential issue**: The use-cases for Harbor and Admiral go beyond the VIC use case. These use-cases will not be documented in the VIC docs.

- The VIC Engine, Harbor, and Admiral docs don’t currently do a very good job of identifying their respective target audiences.
  **Proposal**: Reorganize into persona-based docs:
  - **VIC Overview**: description of VIC, description of the different user roles/personas.
   - **VIC for vSphere Admins**: deploy and manage VCHs, deploy Harbor, deploy Admiral, so that they all work together. 
  - **VIC for Dev Ops Users**: Use Harbor to create and manage projects, create users, set up access to VCHs, manage images. Use Admiral to provision and manage containers and manage the lifecycle of VCHs. Use Admiral to create and deploy containerized apps (or is this the job of the vRA docs?).
  - **VIC for Container Developers**: supported Docker commands, use and limitations of VIC, using volumes, using private registries, container networking, docker compose examples.
 **Potential issue**: Would these persona-based docs make it more difficult to find information if you only use one of the components without the other two?  

- The docs for Engine, Harbor and Admiral all currently reside in their respective Github repos. Generated PDF/HTML versions of the VIC Engine docs are published to http://vmware.github.io/vic-product via the `gh-pages` branch of this `vic-product` repo. 
  **Proposal**: Migrate the Markdown doc files for all 3 components into this repo. Continue to publish PDF/HTML versions for each tagged release to http://vmware.github.io/vic-product.
  **Potential Issue**: If VIC Engine, Harbor and Admiral do not tag releases at the same time, this might get messy. 

-  Issue tracking for VIC Engine docs is done in the VIC Engine Github repo. Doc issues do not appear to exist for Harbor or Admiral. 
  **Proposal**: Migrate the VIC Engine doc issues to the `vic-product` repo. Start creating doc issues for Harbor/Admiral in the `vic-product` repo.
  **Potential Issue**: Referencing issues in other repos works. It is also possible to add assignees working in other repos to issues in this repo, e.g. to request doc reviews from Engine/Harbor/Admiral developers. However, if those developers are used to only looking at their assigned issues in the boards for the other repos, any issues in this repo that are assigned to them will not show up in those boards. 

- The `vic-product` repo currently only serves to host the `vic-product` landing page, http://vmware.github.io/vic-product, and the HTML/PDF versions of the VIC Engine docs. 
  **Proposal**: If the doc source files migrate to the `vic-product` repo, and if there will be no cross-component code in this repo, rename it to **`vic-docs`**. This might help to clarify the confusion between the `vic` and `vic-product` repos.
  **Potential issue**: Will there be any cross-component code, and if so, would it go into the `vic-product` repo?

**Comment by stuclem** [comment]
Assignees, and anyone else who's watching this repo, please take a look at the proposal above and provide feedback in this issue.

Thanks!

**Comment by mdubya66** [comment]
I don't think you can rename repos. Just an FYI. Eventually there will be code and tests and they will need a place to land. 

I approve this plan.

**Comment by mhagen-vmware** [comment]
This sounds good, main concern is that we have good links from the sub-projects back to the vic-product docs. So that when people come into the VIC domain from any of the sub-projects then they have clear direction to vic-product for the official docs.

**Comment by stuclem** [comment]
@hickeng I forgot to add you to the list of assignees. Sorry!

**Comment by mlh78750** [comment]
I'd be okay with a repo called vic-docs, or with using the product repo. I think that we will likely end up with code for things like installers and integration in here. I also expect we'll start seeing issues pop up here as well. We've already seen a few. 

I like the plan. Thanks for taking the time to write all this up @stuclem!

**Comment by stuclem** [comment]
Thanks @mlh78750. In that case, I think that we should have the docs here, rather than creating a vic-docs repo. 

I'd definitely like to hear from at least @karthik-narayan, @martin-borisov, and @hainingzhang before I proceed with this.

**Comment by stuclem** [comment]
It looks like https://github.com/google/github-issue-mover might make life easier when it comes to moving doc issues out of /vic and into /vic-product. 

Does anyone see a reason why I shouldn't use this?

**Comment by stuclem** [comment]
Removed those assignees who have approved the plan, added Alex.

**Comment by stuclem** [comment]
Just tested https://github.com/google/github-issue-mover by creating a test issue, https://github.com/vmware/vic/issues/3869, in the `/vic` repo and moved it here. It successfully created #20 in this repo. However it didn't close https://github.com/vmware/vic/issues/3869, as advertised. Assignee and label were copied over, and cross-references inserted, but the pipeline was copied. But, for a one-time operation, this tool will probably speed things up a lot.

**Comment by hickeng** [comment]
@stuclem I think having the doc issues in vic-product makes sense.

For the organisation I have found that the current persona based organisation makes it awkward on occasion to find doc that I know exists. My thoughts are that a lot of our organisation complexity comes from thinking of the docs as a book form/reference first and hyperlinked graph second. I think the docs break down as:
* tasks/workflows (e.g. deploy a VCH)
* references (e.g. the specific details of security options)

We can have multiple indexes into the documentation:
  * persona based
  * goal based - e.g. deploy a VCH, or deploy an entire VIC environment
  * tasks
  * reference

I do think that we are in desperate need of a very concise or graphical introduction to:
* how VIC is expected to be used - i.e. the dev->CI pipeline -> production diagrams
* which parts of the VIC product exist where in that deployment

If we have interns we could even look at something really cool such as:
* embed doc fragments in tasks so it's a constructed page rather than lots and lots of links
* templates for command line examples/output, e.g. enter some of your parameters into fields in the doc where noted and have the CLI examples adjust appropriately.

**Comment by stuclem** [comment]
@hickeng the multi-index doc that you suggest above (and in a private Slack chat) is exactly the kind of direction that VMware is moving towards in the usual DITA doc toolchain. Whether it's achievable with Gitbook/Markdown is another matter. We aren't tied to Gitbook, but when I was first looking a year ago it was the only thing that I could find that allows you to build multi-file docs from Markdown (short of creating such a tool oneself, which is beyond my skill set). The main limitation of Gitbook (or so I understand) is that it works on a one folder, one document basis. You can't pull files in from other folders, which means that you can't share topics between publications. However, Gitbook is an open source tool. I have already talked to the doc team's tools developer about modifying Gitbook so that its output would be acceptable to the next-generation publishing platform that VMware is rolling out later in the year. I can also ask him if it's possible to hack gitbook so that it would allow topic-sharing between folders/docs.

**Comment by stuclem** [comment]
Since we now have the unified installer and unified UI in the plans, I propose to hold off documenting anything about Harbor/Admiral installation and usage until we have this installer and UI.

@karthik-narayan @mdubya66 @martin-borisov @hainingzhang, is this acceptable?

**Comment by akshayl** [comment]
@stuclem yes from harbor team

**Comment by stuclem** [comment]
Thanks @akshayl!

**Comment by stuclem** [comment]
@hickeng, regarding your suggestions above, we (the docs team) are going to be looking into how best to get our MD-sourced docs into the normal VMware doc publishing mechanism later this year. Things like issues with single-sourcing will be addressed then.

**Comment by stuclem** [comment]
@hickeng, many of your points above might be addressed by upgrading the version of Gitbook that we use from 2.6.7 to 3.2.2. I am testing this at the moment. See https://github.com/vmware/vic-product/issues/24.

**Comment by karthik-narayan** [comment]
A unified document that covers the overall use cases and workflows makes a lot of sense. 

For the persona based, docs, based on the recent PRD and discussions, I recommend the following:

- Add the overview section to all documents, instead of creating a standalone doc
- Update the Devops doc as follows: 
VIC for Dev Ops **Administrators: Configure / Reconfigure Harbor and Admiral** + Use Harbor to create and manage projects, create users, set up access to VCHs, manage images. Use Admiral to provision and manage containers and manage the lifecycle of VCHs. Use Admiral to create and deploy containerized apps (or is this the job of the vRA docs?).

**Comment by stuclem** [comment]
@bradmeiseles any suggestions that you have about post-installation Harbor workflows that we need to write up would be most appreciated. Thanks!

**Comment by stuclem** [comment]
Here's a first attempt at a unified, persona-based doc. This was generated with Gitbook 3.2.2, so has collapsible TOCs and a far better search facility. Also, since all of the previous install/admin/dev docs are now part of the same doc, you can search the whole doc set rather than one pub at a time.

https://stuclem.github.io/vic-product/assets/files/html/test/index.html

**Comment by stuclem** [comment]
This Epic was mainly to track the reorg, although it did become a bit of an incomplete holdall for many 1.1 related activities. But, I think that its usefulness is at an end.
