### ISSUE TITLE
1.1 - update RBAC privilege requirements for endpoint role

### ISSUE THREAD

**Issue by hickeng** [vmware/vic-product#190]
The release doc needs to be updated to add the following privileges to the endpoint role:
```
VirtualMachine.Config.AddExistingDisk
VirtualMachine.Config.EditDevice
VirtualMachine.Config.Rename
```

AddExistingDisk - required for volume usage.
EditDevice - was accidentally dropped from the old docs I think. Needed for `docker attach`.
Rename - new requirement added by `docker rename` support.

Reference RBAC config: vmware/vic#1689

**Comment by stuclem** [comment]
Closed as dup of https://github.com/vmware/vic-product/issues/191
