### ISSUE TITLE
DCH Deployment not enabling TLS when it is deployed with -tlsverify parameter

### ISSUE THREAD

**Issue by yuyangbj** [vmware/vic-product#1903]
**VIC Product version:**
dch-photon:1.13

**Problem description:**
Creating a DCH container with -tlsverify flag, creates the container but the certs check requirement for docker client are not enforced

**Steps to reproduce:**

1. Deploy DCH container

docker -H <VCH>:2376 --tls run -d -p 12376:2376 --name test-tlsveriify vmware/dch-photon -tlsverify -vic-ip <VCH-IP>

2. docker -H <VCH-IP>:12376 --tls info

The information is shown, but it should be refusing due to certs validation based on documents below.

https://vmware.github.io/vic-product/assets/files/html/1.4/vic_app_dev/dchphoton_options.html

**Actual behavior**

The docker engine information is show like below.

Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 0
Server Version: 17.06.0-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
.....

**Expected behavior**

Check the certification

bug 2166270

**Comment by hickeng** [comment]
Marked as sev2 as there's no viable workaround.

**Comment by yuyangbj** [comment]
I validated the new image manually, it is working well.

docker -H <VCH>:2376 --tls run -d -p 12386:2376 --name test-tls <Harbor>/default-project/dch-photon:test-tls -tlsverify -vic-ip <VCH>

docker -H <VCH>:12386 --tls info
The server probably has client authentication (--tlsverify) enabled. Please check your TLS client certification settings: Get https://192.168.111.51:12386/v1.37/info: remote error: tls: bad certificate
