### ISSUE TITLE
Update doc for endpoint role

### ISSUE THREAD

**Issue by stuclem** [vmware/vic-product#191]
From @hickeng via Slack:

George Hicken [10:25 PM] 
Hey stuart - is it possible to update the 1.1 docs to add the following to the endpoint role to address the recent customer found issues:
`VirtualMachine.Config.Rename` (rename support)
`VirtualMachine.Config.AddExistingDisk` (volume support)
`VirtualMachine.Config.EditDevice` (attach)

**Comment by stuclem** [comment]
Done in https://github.com/stuclem/vic-product/commit/4981509bac489c3a3c0438822203d6c3b7d9411f

**Comment by hickeng** [comment]
@stuclem I think #190 can be closed with this PR as well. I'll try to remember to send links to issues raised if I'm also pinging you on slack.
