### ISSUE TITLE
VIC plugin requirements for port 9443 to the VIC Appliance

### ISSUE THREAD

**Issue by dbarkelew** [vmware/vic-product#1917]
VIC 1.4.x documentation does not include the requirement for the port 9443 to be open between the vCenter and VIC Appliance. The vCenter downloads the VIC plugin zip over port 9443 from the file-server service.
- https://vmware.github.io/vic-product/assets/files/html/1.4/vic_vsphere_admin/install_vic_plugin.html
- https://vmware.github.io/vic-product/assets/files/html/1.4/vic_vsphere_admin/plugins_vc_windows.html
https://vmware.github.io/vic-product/assets/files/html/1.4/vic_vsphere_admin/plugins_vcsa.html

The networking overview diagrams should also be updated with this as well or mention the diagrams are not conclusive for all connections to prevent confusion. 

- https://vmware.github.io/vic-product/assets/files/html/1.4/vic_vsphere_admin/vch_networking.html
- https://vmware.github.io/vic-product/assets/files/html/1.4/vic_vsphere_admin/graphics/Network-protocols.png

**Comment by stuclem** [comment]
Submitted request to the graphics department to add the line to the image.
