### ISSUE TITLE
Use capital T for boolean defaults in OVA to satisfy H5 Client requirements

### ISSUE THREAD

**Issue by hickeng** [vmware/vic-product#1929]
@zjs commented on [Fri Jun 22 2018](https://github.com/vmware/vic-tasks/issues/62)

We are unable to deploy the OVA via the H5 client as the current H5 client is not happy with lower case string boolean values. i.e. requires `True` instead of `true`.

**Comment by hickeng** [comment]
This should be checked to see if H5 still shows the behaviour and fixed for 1.5.1. We should not be forcing use of the flex client to deploy OVAs.

**Comment by renmaosheng** [comment]
we can deploy using html5. closing this.
