### ISSUE TITLE
DCH: document how to configure proxy servers for a DCH

### ISSUE THREAD

**Issue by hickeng** [vmware/vic-product#1932]
Add documentation and example to the DCH usage for how to configure a proxy server for the DCH.

I think we should document two approaches:
1. Create the DCH container with the appropriate environment variables set, e.g:
```
docker run -d -e https_proxy=https://proxy.server.com:3128 -e http_proxy=http://proxy.server.com:3128 -p 12376:2376 vmware/dch-photon:1.13 -tls -vic-ip 192.168.78.127
```
2. Build an new DCH image, based on the official one, that bakes in proxy environment variables:
```Dockerfile
# untested!!! need tested dockerfile example
FROM vmware/dch-photon:1.13

ENV http_proxy http://proxy.server.com:8080
ENV https_proxy https://proxy.server.com:8080
```

bug2179859

**Comment by stuclem** [comment]
Internal bug 2180643.

See also https://github.com/vmware/vic-planning/issues/115.

**Comment by stuclem** [comment]
Fixed in https://github.com/vmware/vic-product/pull/1989
