### ISSUE TITLE
Fix remaining tests for initial release branch specific testing

### ISSUE THREAD

**Issue by hickeng** [vmware/vic-product#1936]
Having moved to allow differentiated testing for specific branches we now have branch specific failures.
While longer term any test failures are like to become individual issues, this is an epic for grouping the potentially multiple issues that need to be addressed before we can have a clean test run.

It's not expected for this epic to stay open after the branch specific tests are running cleanly.

Current test failures needing investigation, grouping and creation of child epics from the [test run here](https://vic-jenkins.eng.vmware.com/view/Scenario/job/vic-product-1.4.3-scenario/11/robot/report/log.html):
```
Manual-Test-Cases.Group2-OVA-Features.2-05-Static-IP.Deploy OVA With Static IP
Manual-Test-Cases.Group5-Interoperability-Tests.5-06-1-VSAN-Simple.Simple VSAN
Manual-Test-Cases.Group5-Interoperability-Tests.5-09-Network-Folder.Test
Manual-Test-Cases.Group5-Interoperability-Tests.5-12-Multiple-VLAN.Test
Manual-Test-Cases.Group5-Interoperability-Tests.5-16-vMotion-VCH-Appliance.Test
Manual-Test-Cases.Group7-Upgrade.7-01-Upgrade-1.2.1.Upgrade OVA 1.2.1
Manual-Test-Cases.Group7-Upgrade.7-02-Upgrade-1.3.0.Upgrade OVA 1.3.0
Manual-Test-Cases.Group7-Upgrade.7-03-Upgrade-1.3.1.Upgrade OVA 1.3.1
Manual-Test-Cases.Group7-Upgrade.7-04-Upgrade-1.4.0.Upgrade OVA 1.4.0
Manual-Test-Cases.Group8-Manual-Upgrade.8-01-Manual-Upgrade-1.3.1.Upgrade from v1.3.1
Manual-Test-Cases.Group8-Manual-Upgrade.8-01-Manual-Upgrade-1.4.0.Upgrade from v1.4.0
```

Tasks:
- [ ] initial triage and grouping of these failures - it's anticipated that multiple tests will fail due to a single root cause
- [ ] open child issues to address each root cause

**Comment by renmaosheng** [comment]
> Manual-Test-Cases.Group2-OVA-Features.2-05-Static-IP.Deploy OVA With Static IP
we should cherry-pick 
git show 2680b5ce3
commit 2680b5ce312f33b538268bf14dea573113c490a8
Author: Manjunath Dharamadas <30418983+mdharamadas1@users.noreply.github.com>
Date:   Tue May 8 17:34:03 2018 -0500

    Fix nightly static ip test (#1721)
from master to 1.4.3 to fix the failure.
