### ISSUE TITLE
Remove links to plug-in installation docs from Getting Started page

### ISSUE THREAD

**Issue by stuclem** [vmware/vic-product#1942]
Watching the demo of the automated client plug-in installation, I noticed that the link to the documentation about installing the plug-ins is still present in the Getting Started page:

![plugindoc.png](https://images.zenhubusercontent.com/56afa3216caf56c9d38c1ecf/a02044f7-28c1-4216-9f3b-bc0cd95acb66)

This link should be removed from the Getting Started page in 1.4.3.

@renmaosheng can we add this issue to Epic https://github.com/vmware/vic-product/issues/1432?

**Comment by renmaosheng** [comment]
Hi Stuart,
    Sure, we will look into this. 
Steven
