### ISSUE TITLE
Enforce some kind of doc-impact assessment on engineering issues

### ISSUE THREAD

**Issue by stuclem** [vmware/vic-product#195]
@alextopuzov and I are now monitoring all activity in all 4 GitHub repos (`vic`, `admiral`, `harbor`, `vic-product`). This results in a huge volume of notifications, which are piling up and things that affect doc are getting missed in the deluge.

So, we are wondering whether it would be possible to enforce some kind of doc-impact assessment on engineering issues. This ties in with something that @mlh78750 suggested in Austin in January, but that was never acted upon. @bradmeiseles volunteered @mdubya66 and @mhagen-vmware as the go-to gurus for all things Github-related. @hickeng has also raised the issue of doc-related issues being missed. I would also like the opinions of @martin-borisov and @hainingzhang as this applies to Admiral and Harbor too.

So, here's a proposal:

- Add new **no-doc-impact** and **doc-impact** labels to all four repos.
- When devs are assigned to an issue, they consider whether the implementation of the issue will result in a customer-visible change in behavior.
   - If yes, they add the **doc-impact** label to the engineering issue when they start work on it. @alextopuzov and I create a doc issue in `vic-product` for every engineering issue with that label.
   - If no, they add the **no-doc-impact** label. If they aren’t sure, they reach out to @alextopuzov or myself to check.
- When the dev work is done and the issue is verified, **GitHub will not allow the issue to be closed if it does not have one of the two doc impact labels**. @bradmeiseles says that this can probably be done by using Githooks.

The issue with this arrangement is that the onus is on the devs to decide what should be doc’d and what shouldn’t, which is not ideal, but at least it forces the question to be asked. 

Other proposals:

1. @alextopuzov and I stop watching the repos for all notifications, and only receive notifications for issues that @mention us specifically. However, this depends on devs @mentioning us. Not brilliant.
2. We stop watching the repos for all notifications, and only receive notifications for issues that @mention us. We stop trying to identify doc impact for all issues as they are created or updated, especially since some of the issues might never be implemented. Instead, we monitor ZenHub and only assess doc impact at moment when issues move into the **In Progress** column. At this point, we can potentially add the **no-doc-impact** or **doc-impact** labels. The problem is if something moves from **To Do** to **Verify** without stopping in **In Progress**.
3. We stop watching the repos for all notifications. Add a new **Doc Assessment** column in ZenHub, possibly between **In Progress** and **Verify**, at which stage we add the **no-doc-impact** or **doc-impact** labels. This makes the docs a potential bottleneck for engineering work, however, but is similar to the QE check that is done at the **Verify** stage.

What do you think? I think that my preferred option is #3.

**Comment by mlh78750** [comment]
I don't think it's too much to ask the dev's to put the labels on and then enforce that as part of the close. Another alternative is to do the #3 option above, but have the doc-verify _after_ the verify work. Of all of them, I like the dev adding the tag early the best. That gives the doc team more insight into what's going on and more time to respond. If we implement #3 or some variation, then towards the end, docs is going to get even more overloaded than they already are.

**Comment by mdubya66** [comment]
I concur, let's give this a go. We need to open an issue for the githook.

**Comment by stuclem** [comment]
Great, thanks @mlh78750 and @mdubya66. I opened https://github.com/vmware/vic/issues/4991 for the labels and the Githook.

**Comment by stuclem** [comment]
Moving back to Not Ready following Slack chat with @mdubya66

**Comment by stuclem** [comment]
Hi all, is there any chance that we can take another look at this? Thanks!

**Comment by zjs** [comment]
We can look into some options here as a part of the other GitHub label improvement efforts.

**Comment by stuclem** [comment]
@zjs and @renmaosheng, @vidya-v has a great idea. Is there a way in which we could automate the creation of doc issues? Namely, as soon as the `impact/doc/user` label is applied to an engineering issue in any repo, the issue is cloned into `vic-product` and automatically has the `area/pub` label applied to it? 

I have no idea whether this is technically possible, but @vidya-v says that Confluence does something like this when you use the `doc-impact` checkbox. Obviously, this would help us out enormously. 

Thanks!

**Comment by stuclem** [comment]
Actually, I think that making a full clone of an engineering issue might lead to confusion, given that it involves the duplication of titles and content. I'm [just speculating about a hypothesis](https://www.youtube.com/watch?v=-BnNvIPKaE8) here, rather than basing my thoughts on any known facts, but could the following scenario possibly be envisaged through the use of Github issue templates?

1. Someone opens an engineering issue in any one of the repos associated with VIC.
2. After assessing the issue, the person doing triage, or the assignee, adds the `impact/doc/user` label.
3. On detecting that the `impact/doc/user` label has been applied to an issue, by some automated process, a new issue is created in the `vic-product` repo, as follows:
    - Title: "Document `title_from_engineering_issue`"
    - Content: "Per `repo`/#`issue_number`"
    - Pipeline: Needs Triage
    - Label: `area/pub`
    - Release: If the engineering issue as a release flag, duplicate this release flag on the doc issue, or even better, replace "VIC X.Y All" with "VIC X.Y Documentation".
4. Doc person sees new doc issue in the New Issues column, edits title as necessary, and applies more labels to the issue.

Steps 1-3 are what I currently do manually, _when_ I see that an engineering issue requires a corresponding doc issue.

@zjs @renmaosheng am I living in the realms of magical thinking here, or is this something that could be feasible?

cc. @vidya-v

**Comment by stuclem** [comment]
@renmaosheng is there any possibility that this might happen, or should we close this one?

**Comment by stuclem** [comment]
Beijing team has been good at adding the `impact/doc/user` flag to issues, so I think that this is now unnecessary.
