### ISSUE TITLE
integration test failed on master: Test-Cases.Group4-Harbor.4-01-Harbor :: Test 4-01 Harbor 

### ISSUE THREAD

**Issue by renmaosheng** [vmware/vic-product#1953]
Detailed logs: 

https://ci-vic.vmware.com/vmware/vic-product/5800/13

**Comment by yuyangbj** [comment]
From the original guess, the harbor service is not started correctly on OVA. But I change the code to log the docker push error, it show me:

The push refers to a repository [10.158.214.5/default-project/busybox]
f9d9e4e6e2f0: Preparing
denied: requested access to the resource is denied

So it should be the namespace default-project is not existing? I need to figure out further.

**Comment by yuyangbj** [comment]
The Admiral API is changed occasionally. They have already fixed it. So close the bug.

https://10.158.214.5:8282/projects?filter=name eq 'default-project'
{
    "documentLinks": [
        "/projects/default-project",
        "/projects/ffc8706d79ebd675574110a1b3ac2"
    ],
    "documentCount": 2,
    "queryTimeMicros": 995,
    "documentVersion": 0,
    "documentUpdateTimeMicros": 0,
    "documentExpirationTimeMicros": 0,
    "documentOwner": "31f2749d-81cf-45db-be3b-3111eccaf35e"
}
 
The expected response:
 
the expected results:
GET <host>:<port>/projects?$filter=customProperties.propertyName eq 'propertyValue'
 
Response: 200 OK
Response body:
{
  "totalCount": 1,
  "documentLinks": [
    "/projects/d7bee8b5fe0d875550abb91b6bc8"
  ],
  "documents": {
    "/projects/d7bee8b5fe0d875550abb91b6bc8": {
      "isPublic": false,
      "description": "This is a test project.",
      "administratorsUserGroupLink": "/core/authz/user-groups/d7bee8b5fe0d875550abb91b96c1",
      "membersUserGroupLink": "/core/authz/user-groups/d7bee8b5fe0d875550abb91b96c4",
      "id": "5f0b83fa-6475-4033-96c8-9bb151703788",
      "name": "testProject",
      "customProperties": {
        "propertyName ": "propertyValue",
        "otherProperty": "some-value"
      },
      "documentVersion": 1,
      "documentEpoch": 0,
      "documentKind": "com:vmware:admiral:auth:project:ProjectService:ProjectState",
      "documentSelfLink": "/projects/d7bee8b5fe0d875550abb91b6bc8",
      "documentUpdateTimeMicros": 1496073456162000,
      "documentUpdateAction": "PATCH",
      "documentExpirationTimeMicros": 0,
      "documentOwner": "e5cce490-137d-4e3c-a684-79080ad00683",
      "documentAuthPrincipalLink": "/core/authz/users/administrator@xenon.local"
   }
  },
  "documentCount": 1,
  "queryTimeMicros": 1999,
  "documentVersion": 0,
  "documentUpdateTimeMicros": 0,
  "documentExpirationTimeMicros": 0,
  "documentOwner": "e5cce490-137d-4e3c-a684-79080ad00683"
}
