### ISSUE TITLE
Refactor test structures for  VIC appliance web pages  

### ISSUE THREAD

**Issue by wjun** [vmware/vic-product#1996]
Because of the current ova build approach, we copy directory by directory into ova OS. This means the test cases related files under installer/fileserver/html should be moved into a directory parallel with html if possible. We also need to reuse index.html for test if possible.

**Comment by zhoumeina** [comment]
@wjun ,I am not quite clear about this description, I will ping you when available.

**Comment by zhoumeina** [comment]
fixed by :#2026
