### ISSUE TITLE
READ MORE link in thumbprint validation step should open in new tab

### ISSUE THREAD

**Issue by stuclem** [vmware/vic-product#2006]
- vCenter Server version: **6.7**
- Embedded or external PSC: **embedded**
- Filename of the OVA you deployed: `vic-dev-v1.4.3-dev-5974-b7033624.ova`
- How was the OVA deployed? (Flex client, HTML5 client, ovftool): **Flex client**
- Does the VIC appliance recieve configuration by DHCP? **Yes**
- What stage of the Appliance Lifecycle is the VIC appliance in? **Initialization**
  https://github.com/vmware/vic-product/blob/master/installer/docs/SUPPORT.md#appliance-lifecycle
- What operation was being performed when the failure was noticed? **Verification of thumbprint during initialization**

**To reproduce:**

1. In the new thumbprint verification step when initializing the appliance, click READ MORE...

    ![vcthumb.png](https://images.zenhubusercontent.com/56afa3216caf56c9d38c1ecf/f3336c67-cf03-4d36-936f-45239f8b3ebe)
    The (correct) documentation page opens in the same tab as the one in which you opened the Getting Started page. 
2. After you finish reading the doc, clicking Back in your browser sends you back to the beginning of the initialization process, and you have to re-enter your password: 

    ![password.png](https://images.zenhubusercontent.com/56afa3216caf56c9d38c1ecf/ae85927f-c537-48c5-84c7-6a23ae74cae0) 

This is a bit annoying. Ideally, the doc page should open in a new tab when you click READ MORE...

**Comment by renmaosheng** [comment]
@zhoumeina @wjun could you please take a look? thanks
