### ISSUE TITLE
Issue with VIC 1.4.3 Admiral APIs

### ISSUE THREAD

**Issue by jitinkumar2018** [vmware/vic-product#2011]
Bug Report Basic Information
----------------------------

REQUIRED:

- vCenter Server version: 6.5 U2
- Embedded or external PSC: No
- Filename of the OVA you deployed: vic-dev-v1.4.3-dev-5974-b7033624
- How was the OVA deployed? Flex client
- Does the VIC appliance recieve configuration by DHCP? No
- What stage of the Appliance Lifecycle is the VIC appliance in? Application
- [vic_appliance_logs_2018-09-03-11-38-48.tar.gz](https://github.com/vmware/vic-product/files/2345439/vic_appliance_logs_2018-09-03-11-38-48.tar.gz)
  https://github.com/vmware/vic-product/blob/master/installer/docs/SUPPORT.md#appliance-support-bundle 

Bug Report Detailed Information
-------------------------------

- What operation was being performed when the failure was noticed? Testing UI Plugin APIs and Admiral APIs

DETAILS:
 -Curl commands returning "Connection refused error" 
- while trying to install/upgrade/uninstall vSphere Client Plugins 
 `curl -k -X POST https://10.197.37.192:9443/plugin/remove -H "accept: application/json" -H "Content-Type: application/json" -d "{ \"vc\":{\"target\":\"${vc}\",\”user”:\”${usern}\”,\”password\”:\”${vc_pass}\”,\"thumbprint\":\"${vc_thumbprint}\"},\"plugin\":{\"preset\":\"H5\"}}"`
- while trying to create projects on Admiral
`curl -k -X POST "https://vic-st-h2-192.eng.vmware.com/api/projects" -u administrator@vsphere.local:'Admin!23' -H "accept: application/json" -H "Content-Type: application/json" -d "{ \"project_name\": \"project-p46\", \"public\": 0, \"enable_content_trust\": true, \"prevent_vulnerable_images_from_running\": true, \"prevent_vulnerable_images_from_running_severity\": \"string\", \"automatically_scan_images_on_push\": true}"`

-Error : 
    curl: (7) Failed to connect to vic-st-h2-192.eng.vmware.com port 443: Connection refused

**Comment by renmaosheng** [comment]
@martin-borisov could you please ask someone to take a look? thanks.

**Comment by jitinkumar2018** [comment]
@wjun @martin-borisov @renmaosheng 
APIs work when json content is stored in a json file and curl command is structured like:
`curl -k  -X POST --data @test.json --header 'Content-Type: application/json' https://10.197.37.192:9443/plugin/install -v`
Thanks to Jun for pointing this out
