### ISSUE TITLE
VIC 1.4.3 OVA has old version of UI

### ISSUE THREAD

**Issue by stuclem** [vmware/vic-product#2013]
- vCenter Server version: **6.7**
- Embedded or external PSC: **Embedded**
- Filename of the OVA you deployed: `vic-dev-v1.4.3-dev-5974-b7033624.ova`
- How was the OVA deployed? (Flex client, HTML5 client, ovftool): **Flex**
- Does the VIC appliance recieve configuration by DHCP? **DHCP**
- What stage of the Appliance Lifecycle is the VIC appliance in? **Running**

1. Uninstalled 1.4.1 UI by running `uninstall.sh`
2. Powered off and deleted VIC 1.4.2 appliance.
3. Performed fresh install of VIC 1.4.3 build 5974.
4. Saw new steps in deployment procedure, and automated UI deployment was successful.
5. But, client plug-in is at version v1.4.1.1319:

    ![oldui.png](https://images.zenhubusercontent.com/56afa3216caf56c9d38c1ecf/e9699123-2fe4-445d-8d7c-de8fdde4099f)

@renmaosheng says that the build needs to be updated to pick up the latest UI build.

**Comment by wjun** [comment]
We only update ui plugin version for tagged commits, so rc or release builds will get correct version.
