### ISSUE TITLE
RC1 VIC engine bundle is empty

### ISSUE THREAD

**Issue by vidya-v** [vmware/vic-product#2027]
- Filename of the OVA you deployed: vic-v1.4.3-rc1-6033-2fe6aa5f.ova
- How was the OVA deployed? (Flex client, HTML5 client, ovftool): Flex client

- What stage of the Appliance Lifecycle is the VIC appliance in? Running
- Attach the VIC appliance support bundle (e.g. vic_appliance_logs_2018-01-01-00-01-00.tar.gz)
 [vic_appliance_logs_2018-09-06-08-19-57.tar.gz](https://github.com/vmware/vic-product/files/2356238/vic_appliance_logs_2018-09-06-08-19-57.tar.gz)

- IP address of VIC appliance: 10.161.77.222
- Hostname of VIC appliance: 10.161.73.128
- IP address of vCenter Server: 10.161.94.52

Bug Report Detailed Information
-------------------------------

I deployed the OVA (fresh install), initialized, downloaded the VIC Engine bundle and it was empty.
@stuclem  saw the same thing. @renmaosheng @zjs

**Comment by renmaosheng** [comment]
could you please try https://storage.googleapis.com/vic-product-ova-releases/vic-v1.4.3-rc1-6053-e7623444.ova?

**Comment by renmaosheng** [comment]
@wjun  please take a look.

**Comment by wjun** [comment]
PR #2023 should fix it.
