### ISSUE TITLE
Document that special characters are permitted in user passwords

### ISSUE THREAD

**Issue by stuclem** [vmware/vic-product#204]
I just created a user with a password that includes $ and !, and it worked. @reasonerjt can you please confirm that special characters are now permitted in passwords? Thanks!

**Comment by reasonerjt** [comment]
It is, there was a bug some special chars are not allowed, and it's fixed in 1.1.1

**Comment by stuclem** [comment]
OK, thanks @reasonerjt. Fix is in https://github.com/vmware/vic-product/issues/216.
