### ISSUE TITLE
VIC 1.4.3 RC1 has a new folder autocomplete

### ISSUE THREAD

**Issue by lgayatri** [vmware/vic-product#2059]
Build : vic-v1.4.3-rc1-6053-e7623444.ova
Extracting vic_v1.4.3-rc1.tar.gz gives a folder called autocomplete which was not in 1.4.2. 
Is this folder required? @renmaosheng @zjs 
``` tree autocomplete/
autocomplete/
├── bash
│   ├── vic-machine-darwin
│   ├── vic-machine-linux
│   └── vic-machine-windows.exe
└── zsh
    ├── vic-machine-darwin
    ├── vic-machine-linux
    └── vic-machine-windows.exe
```
FYI @stuclem @vidya-v

**Comment by stuclem** [comment]
@lgayatri this is documented in https://github.com/vmware/vic-product/pull/2045

**Comment by lgayatri** [comment]
Thanks @stuclem

**Comment by zjs** [comment]
Thanks for filling this issue! In this case, it's expected (as Stuart notes), but it's definitely good to confirm new files in the .tar.gz were intentionally included!
