### ISSUE TITLE
Scan vic-product integration tests for masked failures

### ISSUE THREAD

**Issue by zjs** [vmware/vic-product#2073]
@hickeng commented on [Thu Jun 28 2018](https://github.com/vmware/vic-tasks/issues/70)

vmware/vic-product#1278 added logic to re-run failed tests - this is in addition to all of the various nimbus retry logic.

This blends the output of the attempts, so if tests pass on the second attempt the overall status of the result is passed. The failed run is still available in the output, but it's non-obvious that it's present.

As such this could mask:
* legitimate intermittent product bugs
* intermittent infra issues in need of fixing

This needs to be coupled with a check that denotes whether this second run occurred and reports the original failures so they remain visible.

**Comment by hickeng** [comment]
This approach of retrying tests and masking failures is _going_ to result in escapes eventually. If this is still an issue then more effort needs to be invested in improving the stability of individual tests and test steps.

**Comment by renmaosheng** [comment]
we have fixed the vic-product failure recently.
