### ISSUE TITLE
Document that you can deploy VCH to a specific host in a cluster

### ISSUE THREAD

**Issue by stuclem** [vmware/vic-product#209]
Per https://github.com/vmware/vic/issues/4982. We currently state that you can deploy to a specific standalone host, or to a specific resource pool in a cluster, but not to a specific host in a cluster.

**Comment by stuclem** [comment]
Not in 1.2.

**Comment by stuclem** [comment]
Not in 1.3.

**Comment by stuclem** [comment]
Not in 1.4.x.

**Comment by stuclem** [comment]
https://github.com/vmware/vic/issues/4982 is possibly made redundant by the VM-affinity option.

**Comment by zjs** [comment]
> vmware/vic#4982 is possibly made redundant by the VM-affinity option.

Yes.

Closing this as vmware/vic#4982 has been closed and VM-Host affinity has already been documented.
