### ISSUE TITLE
Add link to Reconfigure Appliance in the Upgrade Appliance doc

### ISSUE THREAD

**Issue by KeithRichardLee** [vmware/vic-product#2098]
Currently in the upgrade appliance doc, https://vmware.github.io/vic-product/assets/files/html/1.4/vic_vsphere_admin/upgrade_appliance.html, it has the following...

_If you deployed the old version of the vSphere Integrated Containers appliance with a static IP address, and you want the new appliance to retain the same IP address after the upgrade, reconfigure the old appliance to use a temporary IP address before you start the upgrade procedure._

I believe it would be an improvement if a link is provided to the Reconfigure Appliance doc,  https://vmware.github.io/vic-product/assets/files/html/1.4/vic_vsphere_admin/reconfigure_appliance.html to aid the reader in how to perform this.

**Comment by stuclem** [comment]
This is already fixed in 1.5: https://vmware.github.io/vic-product/assets/files/html/1.5/vic_vsphere_admin/upgrade_appliance.html
