### ISSUE TITLE
vSphere HTML5 client blank after VIC upgrade

### ISSUE THREAD

**Issue by KeithRichardLee** [vmware/vic-product#2106]
Bug Report Basic Information
----------------------------
- vCenter Server version: 6.5.0 build 8307201
- Embedded or external PSC: Embedded
- Filename of the OVA you deployed: vic-v1.4.3-6240-deedb985.ova
- How was the OVA deployed? (Flex client, HTML5 client, ovftool): Flex
- Does the VIC appliance receive configuration by DHCP? No
- What stage of the Appliance Lifecycle is the VIC appliance in? Running

Bug Report Detailed Information
-------------------------------
GA v1.4.1 upgraded to GA v1.4.3 where auto-upgrade client plugin was performed. On logging into HTML5 client with Chrome 69.0.3497.100 after upgrade I was presented with a blank screen for the inventory and main pain (not sure if that is correct terminology). Issue remained after logging in and out several times and also restarting Chrome. Issue resolved by resetting Chrome (settings -> advanced -> reset and cleanup). While the issue was present in chrome, it was not in Firefox. I have seen this same issue in Firefox on a different occasion and resetting Firefox resolved it.

Unfortunately I have lost the screengrab of it but will add one when I hit the issue again. Below I have highlighted in red what was blank/white.

![image](https://user-images.githubusercontent.com/41379304/46080330-9213f400-c191-11e8-88e5-1fc4289473d8.png)

**Comment by KeithRichardLee** [comment]
Hit issue again of blank screen, as seen below. This time there was no action (I'm aware of) leading to it, eg no upgrade.

![image](https://user-images.githubusercontent.com/41379304/46130264-c38fcc80-c230-11e8-8f73-9675eca95e77.png)

**Comment by KeithRichardLee** [comment]
Hi @zhoumeina the env where it was observed is firewalled off, a remote session would be needed but currently the env is not demonstrating the issue. On next occurrence I will leave the env as is and update ticket.

**Comment by zhoumeina** [comment]
@KeithRichardLee , do you mind if I close this issue, if you find this issue again, you can reopen it.
