### ISSUE TITLE
VCH guest OS still showing 1.4.1 after upgrade to 1.4.3

### ISSUE THREAD

**Issue by KeithRichardLee** [vmware/vic-product#2107]
Bug Report Basic Information
----------------------------
- vCenter Server version: 6.5.0 build 8307201
- Embedded or external PSC: Embedded
- Filename of the OVA you deployed: vic-v1.4.3-6240-deedb985.ova
- How was the OVA deployed? (Flex client, HTML5 client, ovftool): Flex
- Does the VIC appliance receive configuration by DHCP? No
- What stage of the Appliance Lifecycle is the VIC appliance in? Running

Bug Report Detailed Information
-------------------------------
After successful appliance and VCH upgrade from GA 1.4.1 to GA 1.4.3, the guest OS of a VCH still reports as 1.4.1 as seen below. Same after a restart of the VCH. 

![image](https://user-images.githubusercontent.com/41379304/46082625-698ef880-c197-11e8-8baa-a7f78187cfbe.png)

**Comment by zjs** [comment]
We should investigate to _at least_ ensure that this issue does not affect 1.5.0.

**Comment by renmaosheng** [comment]
Wending,
       Could you please check the upgrading from 1.4.4 to 1.5 the VCH version is upgraded? thanks.

**Comment by luwang-vmware** [comment]
Feel sorry to give wrong info. The issue still exists after upgrading from 1.4.3 to 1.5.0. So reopen it.
![image](https://user-images.githubusercontent.com/43165500/50140638-60b64a80-02e0-11e9-9a8e-abd95d915a29.png)

**Comment by DanielXiao** [comment]
Only see this issue in upgraded VCH.

**Comment by YanzhaoLi** [comment]
This is fixed by vic's PR 8427.

**Comment by renmaosheng** [comment]
https://github.com/vmware/vic/pull/8427
