### ISSUE TITLE
Improve the VIC Appliance backup and restore process.

### ISSUE THREAD

**Issue by dbarkelew** [vmware/vic-product#2108]
**User Statement:**
Current back up method is more difficult than needed on restore causing production deployments to be down longer. 

Backups require down time to have a stable disk to restore from.

**Details:**
Restore currently involves deploying a new VIC Appliance and attaching the restored disks to the new VIC Appliance due to the ovfEnv requirements.

Do to the need to have the file system and databases in a consistent state the VIC Appliance needs to be shutdown before backing up the underlying disks. 

**Acceptance Criteria:**
**Current need:**
1. Better handling ovfEnv backup and restore for current releases.
- Steps to backup/export the ovfEnv settings from the VIC Appliance using one or more of the following tools:
                 MOB browser
                 govc
                 PowerCLI

- Steps to restore the ovfEnv settings to the VIC Appliance using one or more of the following tools:
                MOB browser
                govc
                PowerCLI

**Future need:**
1. Handling the backup and restore of the ovfEnv internally. This should not automatically restore over a blank ovfEnv on the vCenter end to avoid overwriting during HA scenarios. User should confirm overwrite first. This would assume until the overwrite is confirmed the settings cannot be changed from the VM settings UI meaning the VIC Appliance would default to the last known good configuration at boot.
2. Handling if the VIC Appliance powers on with out ovfEnv like in an HA type event where the ovfEnv would not be present until the VIC Appliance is rebooted again from vCenter. Probably need a warning to schedule a reboot before changes to the VIC appliance IP and certificates can be made.
3. Ability for snapshot based backups workflows to be used with the VIC Appliance that quiesces the base file system as well as flushing the databases to ensure restores do not result in corrupt disks or databases.

**Comment by renmaosheng** [comment]
we have already updated the back/restore document in 1.5.1, please reopen if the newer version doesn't work.

**Comment by dbarkelew** [comment]
@renmaosheng I don't see that improvements have been implemented particularly around backing up and restoring the ovfenv values to the VIC Appliance VM. Should this still be open for that?
