### ISSUE TITLE
Include COMPOSE_TLS_VERSION variable in VCH environment file

### ISSUE THREAD

**Issue by arslanabbasi** [vmware/vic-product#2127]
##### For bug reports, please include the information below:

Please fill out both the Basic Information and Detailed Information sections.

Bug Report Basic Information
----------------------------

REQUIRED:

- vCenter Server version:
- Embedded or external PSC:
- Filename of the OVA you deployed:
- How was the OVA deployed? (Flex client, HTML5 client, ovftool):
- Does the VIC appliance recieve configuration by DHCP?
- What stage of the Appliance Lifecycle is the VIC appliance in?
  https://github.com/vmware/vic-product/blob/master/installer/docs/SUPPORT.md#appliance-lifecycle
- Attach the VIC appliance support bundle (e.g. vic_appliance_logs_2018-01-01-00-01-00.tar.gz)
  https://github.com/vmware/vic-product/blob/master/installer/docs/SUPPORT.md#appliance-support-bundle
  Note: The support bundle may contain private information. If you are not comfortable with posting this publicly, please contact VMware GSS.

OPTIONAL, but helpful:

- IP address of VIC appliance:
- Hostname of VIC appliance:
- IP address of vCenter Server:
- Hostname of vCenter Server:

Bug Report Detailed Information
-------------------------------

- What operation was being performed when the failure was noticed?

- Provide information from the `Support Information` section of the appropriate Appliance Lifecycle stage:
  https://github.com/vmware/vic-product/blob/master/installer/docs/SUPPORT.md#appliance-lifecycle

- Provide additional detail as necessary:

##### For feature requests/user stories, please include the information below:

**User Statement:**
We tell users that we can also use docker-compose to deploy containers on VIC. However, everytime tls authentication is enabled, we have to manually export "COMPOSE_TLS_VERSION=TLSv1_2" variable as docker-compose does not support earlier tls versions. Can we add this variable with other variables that are displayed to be exposed after the VCH creation

**Details:**

**Acceptance Criteria:**
cat vch1.env
DOCKER_TLS_VERIFY=1 DOCKER_CERT_PATH=/home/ubuntu/vic/vic-bundle/v1.4.3/vic/vch1 DOCKER_HOST=10.40.206.186:2376 COMPOSE_TLS_VERSION=TLSv1_2

**Comment by zjs** [comment]
Putting this into the env file seems entirely reasonable. Including it in the CLI output may not be, as it may clutter the output.

**Comment by YanzhaoLi** [comment]
This is fixed by vic's pr #8440
