### ISSUE TITLE
Integrating with new harbor/admiral with updated clarity 0.12 version.

### ISSUE THREAD

**Issue by renmaosheng** [vmware/vic-product#2136]
Harbor and admiral is updating clarity version to v0.12. 
Once this is done, we need to do integration testing on vic-product to make sure there is no regression changes.

**Comment by zhoumeina** [comment]
@DanielXiao , we can use: 
https://hub.docker.com/r/vmware/admiral/tags/
vic-dev 
in docker hub to do this. 
However, I have no idea how to do the integration. Maybe we can discuss today.

**Comment by renmaosheng** [comment]
this has been done. VIC 1.5 now picks the latest harbor and admiral.
