### ISSUE TITLE
Clean up vic-product CI testbed regularly

### ISSUE THREAD

**Issue by DanielXiao** [vmware/vic-product#2144]
**User Statement:**
There are orphan VMs left in vic-product testbed 10.158.214.107,  we need to clean up them every week to ensure there are enough resource for CI testing.

**Details:**

**Acceptance Criteria:**
Orphan VMs are cleaned up automatically every week without affecting running CI.

**Comment by DanielXiao** [comment]
I already push script to https://github.com/DanielXiao/vic-tools/blob/release-test/jenkins/jobs/clean-up/clean_up_vic_product_ci.sh.
We need to add a job in Jenkins to manually trigger it when there is no job running.

**Comment by zjs** [comment]
When cleaning up the testbed, we should record information about the resources being deleted. We should use that information to identify which test(s) are leaking resources and fix those tests.

**Comment by renmaosheng** [comment]
the scripts are checked in  as well.
