### ISSUE TITLE
Document that vCenter Server HA is supported

### ISSUE THREAD

**Issue by stuclem** [vmware/vic-product#2163]
Per https://github.com/vmware/vic-ui/issues/506

**Comment by stuclem** [comment]
Looks like this is not in 1.5.0

**Comment by stuclem** [comment]
Looks like https://github.com/vmware/vic-ui/issues/506 is fixed.

**Comment by stuclem** [comment]
Upped the severity as this is newly confirmed functionality.

**Comment by stuclem** [comment]
Per conversation with @luwang-vmware, this is for 1.5.3.

**Comment by stuclem** [comment]
Actually, @luwang-vmware says that this is for 1.5.4.

**Comment by stuclem** [comment]
@luwang-vmware is VC HA supported in 1.5.4? Thanks!

**Comment by luwang-vmware** [comment]
@stuclem This item is in our queue. I will update once we finish validation.

**Comment by stuclem** [comment]
OK, thanks @luwang-vmware

**Comment by luwang-vmware** [comment]
@stuclem  We have validated it with 67U3 with our incoming VIC1.5.4 bits.

**Comment by stuclem** [comment]
Thanks @luwang-vmware, I have added it to the 1.5.4 doc release.
