### ISSUE TITLE
Release notes need to better explain that the Clair issue causing DOS to NIST is resolved

### ISSUE THREAD

**Issue by dbarkelew** [vmware/vic-product#2179]
#### Summary

The release note are not clear that VIC 1.4.4 correct the issue behind Clair causing DOS issues to the NIST servers due to getting stuck in a CVE loop. 

#### Details

The resolved issues in Harbor and the pull do not make this clear enough for customer. 

https://docs.vmware.com/en/VMware-vSphere-Integrated-Containers/1.4.4/rn/vSphere-Integrated-Containers-144-Release-Notes.html
https://github.com/goharbor/harbor/releases/tag/v1.5.4#resolvedissues
https://github.com/goharbor/harbor/pull/6016
##### Section reference(s)

https://docs.vmware.com/en/VMware-vSphere-Integrated-Containers/1.4.4/rn/vSphere-Integrated-Containers-144-Release-Notes.html

##### Product version(s)

1.4.4

#### See also

Bug 2238412

**Comment by renmaosheng** [comment]
I will drive this in the bugzilla for Harbor. closing the github ticket.
