### ISSUE TITLE
VCH deletion fails with context deadline exceeded error or vmdk file not found error

### ISSUE THREAD

**Issue by jitinkumar2018** [vmware/vic-product#2197]
**Bug Report Basic Information**
**REQUIRED**:

vCenter Server version: 6.5 p03
Embedded or external PSC: No
Filename of the OVA you deployed: vic-v1.4.4-6375-0a6da3d4
How was the OVA deployed? ovftool
Does the VIC appliance recieve configuration by DHCP? No
What stage of the Appliance Lifecycle is the VIC appliance in? Application
Vic Appliance Logs: Unable to upload Log bundle as it exceeded 10MB

**Bug Report Detailed Information**
What operation was being performed when the failure was noticed?
VCH deletion using vic-machine-linux delete CLI 

**DETAILS:**
- 10 VCH's were created with persistent volume store and left empty ( Did not create docker volume using the persistent volume) 
- 40  VCH's were created without persistent volume stores. 
- While performing concurrent VCH delete on all 50 VCH's, the VCH's that have persistent volume stores take much longer to delete than the rest of the VCH's
- It successfully deletes all except one VCH and throws context deadline exceeded error.
- Noticed failure in VCH delete only when VCH's are created with persistent volume store

@lgayatri @renmaosheng

**Comment by jitinkumar2018** [comment]
@lgayatri @renmaosheng

**Comment by renmaosheng** [comment]
Jitin,
      do you have the environment or logs for us to take a look?

**Comment by jitinkumar2018** [comment]
I shall send the vic_appliance_logs via slack. The environment was cleaned. I shall recreate it again and provide you the VC and VIC ip

**Comment by jitinkumar2018** [comment]
I have recreated the testbed. 10 VCH's ( U-VIC-0001 - U-VIC-00010) have persistent volumes and the rest don't. We use a script that performs concurrent VCH deletion (50 threads that each perform vic-machine-linux delete).
Will send the VC and VIC login credentials to @wjun.

**Comment by jitinkumar2018** [comment]
Thanks Jun

**Comment by zjs** [comment]
Issue moved to [vmware/vic #8464](https://github.com/vmware/vic/issues/8464) via [**ZenHub**](https://www.zenhub.com/)
