### ISSUE TITLE
Document supported upgrade paths for 1.5.0

### ISSUE THREAD

**Issue by stuclem** [vmware/vic-product#2205]
@renmaosheng @zjs @lgayatri do we support upgrade from 1.2.x and 1.3.x?

Also, is the procedure for upgrading by manually copying disks still supported in 1.5? 

Thanks!

**Comment by stuclem** [comment]
@renmaosheng informed me that we support upgrade from 1.3.x and 1.4.x to 1.5.0.

**Comment by stuclem** [comment]
@lgayatri informed me that she will be testing the upgrade by manually moving disks as well as the script-based upgrade.

**Comment by lgayatri** [comment]
@stuclem below are the paths which will be tested

1.3.x to 1.5
1.4.x to 1.5
1.3.x to 1.4.x to 1.5

We wont have 1.2.x being covered for upgrade.

**Comment by stuclem** [comment]
Great, thanks @lgayatri !
