### ISSUE TITLE
Update links in Getting Started page to point to 1.5 docs

### ISSUE THREAD

**Issue by stuclem** [vmware/vic-product#2212]
All of the links in the Getting Started page need to point to the 1.5 version of the docs. 

I have posted a placeholder version of the 1.5 docs at https://vmware.github.io/vic-product/assets/files/html/1.5/.

@renmaosheng can you please assign this accordingly?

**Comment by renmaosheng** [comment]
Yanzhao, could you please fix this? thanks.
