### ISSUE TITLE
Document supported version of dch-photon in VIC 1.5.0

### ISSUE THREAD

**Issue by stuclem** [vmware/vic-product#2217]
@renmaosheng @yuyangbj if we are bumping `dch-photon` up to Photon OS 2.0 in 1.5.0, what will be the new version number for the `dch-photon` image that ships in the default-project? Thanks!

**Comment by stuclem** [comment]
Per https://github.com/vmware/vic-product/pull/2218#pullrequestreview-185498014, the `dch-photon` version in 1.5 is 17.06.

**Comment by DanielXiao** [comment]
Yes. 17.06 is the correct version that ships in the default-project.

**Comment by stuclem** [comment]
This was fixed in https://github.com/vmware/vic-product/pull/2218
