### ISSUE TITLE
Manual upgrade from VIC 1.4.4 to VIC 1.5 failed because the new VIC appliance failed to register with VC

### ISSUE THREAD

**Issue by jitinkumar2018** [vmware/vic-product#2237]
- Embedded or external PSC: No
- How was the OVA deployed? (Flex client, HTML5 client, ovftool): Flexclient
- Does the VIC appliance recieve configuration by DHCP? No, Static 
- IP address of VIC appliance: 10.197.37.182
- Hostname of VIC appliance: vic-st-h2-182.eng.vmware.com
- IP address of vCenter Server: w2hs2-rdp04.eng.vmware.com

##### Actual behavior
Failed to upgrade as the VIC appliance failed to register with the VC

##### Expected behavior
Successful manual upgrade from VIC 1.4.4 to VIC 1.5

#### Logs
Log Bundle: 
[vic_appliance_logs_2018-12-14-06-37-57-ManualUpgradeFail.tar.gz](https://github.com/vmware/vic-product/files/2678914/vic_appliance_logs_2018-12-14-06-37-57-ManualUpgradeFail.tar.gz)

Upgrade Log: 
[upgrade.log](https://github.com/vmware/vic-product/files/2678918/upgrade.log)

**Comment by stuclem** [comment]
See also https://github.com/vmware/vic-product/issues/2234

**Comment by wjun** [comment]
We add a new parameter into upgrade.sh for security reason: --upgrade-password. The value is the ova appliance's root password. @luwang-vmware will generate a new build with upgrade tests passed.

**Comment by lgayatri** [comment]
@wjun, do we need an additional parameter? We already take the root password of old OVA as an input.

**Comment by stuclem** [comment]
@wjun, I agree with @lgayatri. It doesn't seem like a good user experience to have to enter the root password twice.

**Comment by wjun** [comment]
@stuclem @lgayatri The new parameter is for the new vic appliance's root password, which can be different from the old appliance's root password. It is introduced by a security issue that an attacker may mimic a vc, and if we do not ask for vic root password, the attacker can locate vic registration to this mimic vc.

**Comment by stuclem** [comment]
@wjun thanks for the explanation. I opened https://github.com/vmware/vic-product/issues/2247 for the doc update.

**Comment by lgayatri** [comment]
Thanks @wjun .
