### ISSUE TITLE
Document that only 1.5.3 supports 6.7u2

### ISSUE THREAD

**Issue by stuclem** [vmware/vic-product#2248]
Per https://github.com/vmware/vic-product/issues/2196#issuecomment-448073499, we won't support running 1.4.x on 6.7u2 when it comes out. 

Doc update must wait until 6.7u2 is released, after 1.5.0 GA.

**Comment by zjs** [comment]
Note: https://github.com/vmware/vic-ui/issues/652#issuecomment-450800619 suggests that support will be included in 1.5.1, not 1.5.0.

**Comment by stuclem** [comment]
This update needs to go into the 1.4.x docs, not in 1.5.x.

**Comment by stuclem** [comment]
Fixed in https://github.com/vmware/vic-product/pull/2430

**Comment by stuclem** [comment]
Actually, this needs to be updated to state that only 1.5.3 supports vSphere 6.7u2.
