### ISSUE TITLE
Support bundle of integrated OVA should collect Admiral logs

### ISSUE THREAD

**Issue by angel-ivanov** [vmware/vic-product#225]
Support bundle should collect Admiral container(vic-admiral) logs.
Also it might be useful if logs of the docker which is running in the integrated OVA, to be collected too for more debugging information.

**Comment by andrewtchin** [comment]
Is this something I need to do or will this be functionality in Admiral?

**Comment by angel-ivanov** [comment]
This is not part of Admiral functionality. I am not aware how support bundle is created, but it should collect Admiral's container logs.

**Comment by bradmeiseles** [comment]
Let's make sure the Harbor logs and the logs for new components that are introduced in 1.2 are also collected as part of the support bundle.

**Comment by andrewtchin** [comment]
Workaround is to manually collect the logs off of Admiral
See also https://github.com/vmware/vic/issues/4680

**Comment by mdubya66** [comment]
This needs to be prioritized for 1.3 or beyond? @karthik-narayan

**Comment by stuclem** [comment]
Added a pretty pitiful release note in https://github.com/vmware/vic-product/releases/tag/v1.2.0.

@angel-ivanov and @andrewtchin how do we a) download the OVA support bundle in the first place and b) download the Admiral logs manually? 

This really needs to go in the core doc too: https://github.com/vmware/vic-product/issues/318

**Comment by stuclem** [comment]
Here's the release note entry:

----

- <b>vSphere Integrated Containers appliance support bundle does not include Management Portal logs. [#225](https://github.com/vmware/vic/issues/225)</b><br>Workaround: Download the Management Portal logs manually. 

----

**Comment by andrewtchin** [comment]
Repurposing this story to cover creating the support bundle and making sure all logs are under `/var/log/vmware`
vmware/vic#4680 can probably also be closed when this is resolved
We need to get the admiral logs off of the container

**Comment by stuclem** [comment]
@andrewtchin is the release note above OK? Thanks!

**Comment by andrewtchin** [comment]
@stuclem release note lgtm

**Comment by stuclem** [comment]
Thanks @andrewtchin !

**Comment by andrewtchin** [comment]
Closing this as we have an alternative method for gathering all appliance state information https://github.com/vmware/vic-product/issues/1197

**Comment by stuclem** [comment]
@andrewtchin do we need to keep the release note entry about this from 1.3.0 in the 1.3.1 release notes?

**Comment by andrewtchin** [comment]
No, the release note can be removed as in 1.3.1 we have the `appliance-support.sh` script
