### ISSUE TITLE
New Registry Certificate download button not showing up correctly and download not working

### ISSUE THREAD

**Issue by stuclem** [vmware/vic-product#2258]
@stuclem commented on [Wed Dec 19 2018](https://github.com/vmware/admiral/issues/290)

@stuclem commented on [Wed Dec 19 2018](https://github.com/vmware/vic-ui/issues/641)

1. Deployed vic-dev-v1.5.0-dev1-6723-dc7489d3.ova, fresh install, not upgrade.
2. Logged into Management Portal as vSphere Admin.
3. Went to **Administration** > **Projects** > **Internal Repositories**.

    Button to download registry certificate is not showing up properly: 

    ![repos-admin.png](https://images.zenhubusercontent.com/56afa3216caf56c9d38c1ecf/7fdce5e5-1753-4b49-86fb-ea4786b7e4bc)

4. Clicking the link does not work:

    ![cert-dl.png](https://images.zenhubusercontent.com/56afa3216caf56c9d38c1ecf/c129bafd-cfea-48d0-9ea6-eca5a237aec2)

5. Logged out, logged in as developer.
6. Went to **Home** > **Built-in Repositories** and saw the same thing.

    ![repos-dev.png](https://images.zenhubusercontent.com/56afa3216caf56c9d38c1ecf/848bb72f-a35a-44fe-b160-255339b1ca0f)

Other views seem OK. 

@lgayatri @jitinkumar2018 are you seeing the same thing?

---

@stuclem commented on [Wed Dec 19 2018](https://github.com/vmware/vic-ui/issues/641#issuecomment-448657593)

Actually, this is not a vic-ui issue. Moving to admiral.

---

@stuclem commented on [Wed Dec 19 2018](https://github.com/vmware/admiral/issues/290#issuecomment-448657953)

Here's the log bundle:

[vic_appliance_logs_2018-12-19-16-24-34.tar.gz](https://github.com/vmware/admiral/files/2695697/vic_appliance_logs_2018-12-19-16-24-34.tar.gz)

---

@stuclem commented on [Thu Dec 20 2018](https://github.com/vmware/admiral/issues/290#issuecomment-448925860)

Seeing the same behaviour with vic-dev-v1.5.0-dev1-6732-50c22cb2.ova.

---

@jitinkumar2018 commented on [Thu Dec 20 2018](https://github.com/vmware/admiral/issues/290#issuecomment-448928346)

Yes, We can observe the same behavior for vic1.5 build: vic-dev-v1.5.0-dev1-6723-dc7489d3.ova

---

@lazarin commented on [Thu Dec 20 2018](https://github.com/vmware/admiral/issues/290#issuecomment-448935199)

I've notified @zhoumeina with ask to check that one.
The content for the 'Internal repositories' view is coming from Harbor (maybe Harbor project is the right repo for this issue), so probably it's a matter of some config/feature toggle or sth else to make Harbor return the right link and label

---

@stuclem commented on [Thu Dec 20 2018](https://github.com/vmware/admiral/issues/290#issuecomment-448942466)

Thanks @lazarin!

---

@stuclem commented on [Thu Dec 20 2018](https://github.com/vmware/admiral/issues/290#issuecomment-448950087)

This issue seems to span components. Moving it to vic-product, just to be sure.

**Comment by stuclem** [comment]
I'm also seeing bad formatting in the Registry Replication view:

![reg_rep](https://user-images.githubusercontent.com/16718369/50279764-fbcb3380-044a-11e9-96ce-4306d84569c0.png)

**Comment by stuclem** [comment]
Same problem in Admin > Configuration:

![admin-config](https://user-images.githubusercontent.com/16718369/50292873-8ffcc100-0472-11e9-8268-faae60539c0f.png)

**Comment by stuclem** [comment]
Same for replication rules:

![rep-rules](https://user-images.githubusercontent.com/16718369/50292995-de11c480-0472-11e9-9fbc-45727d8fb492.png)

**Comment by zhoumeina** [comment]
@stuclem , could you please try to hard reload the page? It seems the resource files are not correctly show.

**Comment by zhoumeina** [comment]
@stuclem , we just found it is because harbor globalization api not provided now. Harbor will generate a 1.7.1 release to fix this.

**Comment by stuclem** [comment]
Thanks @zhoumeina !

**Comment by zhoumeina** [comment]
fixed by: #2268
