### ISSUE TITLE
Fail to deploy VCH by GUI when input required vSphere user name with blank space in the tail

### ISSUE THREAD

**Issue by danfengliu** [vmware/vic-product#2269]
* VIC Engine (VCHs, Container VMs, and their lifecycles)

#### Summary
When creating VCH in vSphere client, at the last step, vSphere client user credential was needed, if blank space was attached by accident, there will be a failure of creating VCH. Please add trim function in GUI to tolerant this kind of input. 

##### vSphere and vCenter Server version
vSphere Client version 6.7.0

https://storage.googleapis.com/vic-product-ova-builds/vic-dev-v1.5.0-rc1-6773-d72fd6e5.ova

**Comment by pureshine** [comment]
fixed by pr vic-ui- #642 (https://github.com/vmware/vic-ui/pull/642)

**Comment by pureshine** [comment]
fixed by pr  (vmware/vic-ui#642)
