### ISSUE TITLE
OVA build result path from CI not consistent with google ova builds. 

### ISSUE THREAD

**Issue by zhoumeina** [vmware/vic-product#2272]
I submitted a pr to generate a ova. 
From the ci console out put , the ova path is : 
![image](https://user-images.githubusercontent.com/4946616/50498668-abbd2400-0a7d-11e9-859d-b740bb95d90b.png)

Actually, when I try to deploy this ova, I found this url is not correct. 
the correct url is : 
![image](https://user-images.githubusercontent.com/4946616/50498682-cee7d380-0a7d-11e9-9cbd-4265156c26b6.png)

**Comment by DanielXiao** [comment]
PR will not generate ova build and the step "bundle dev builds" is only for push and tag. If you modify .drone.yml to generate PR build for personal testing, you should print the artifact URL in your PR.
