### ISSUE TITLE
VMware CA is missing in VIC appliance ova

### ISSUE THREAD

**Issue by DanielXiao** [vmware/vic-product#2304]
#### Summary

When you deploy VIC appliance from web client, you will see "No certificate present" in Publisher property. See the screenshot.
<img width="959" alt="screen shot 2019-01-11 at 11 18 13 am" src="https://user-images.githubusercontent.com/1393804/51017318-a5b36100-15ae-11e9-8a52-863151fbe263.png">

##### VIC Appliance version

Any version.

#### Details

The ova should include a VMware Certificate file.

##### Steps to reproduce

Deploy VIC ova from H5 or Flex webclient.

##### Actual behavior

"No certificate present" shows in Publisher property.

##### Expected behavior

Show a green check.

**Comment by renmaosheng** [comment]
Hi Stuart，
      we don't plan to fix it, as there is no customer complained such issue, there is no functional impact. we don't need to document it either. thanks.
