### ISSUE TITLE
Wrong vIC Plugin network source in Network diagram

### ISSUE THREAD

**Issue by dukesrg** [vmware/vic-product#2317]
#### Summary
The network diagram in Ports and Protocols section
https://vmware.github.io/vic-product/assets/files/html/1.5/vic_vsphere_admin/network_reqs.html#
contains wrong network path from vCenter to vIC: vIC Plugin actually runs in client browser, so arrow with https (tcp:8443) must be originated from the Cloud admin, but not vCenter.

**Comment by dukesrg** [comment]
Another not mentioned network flow is from VCH Management interface to vIC 443 & 8282

**Comment by zjs** [comment]
@renmaosheng: It looks like this issue from last month has not been triaged.

**Comment by stuclem** [comment]
Thanks @dukesrg and @renmaosheng. I'll look into this.

**Comment by stuclem** [comment]
@renmaosheng can you please confirm whether the following statement is accurate? 

"The network diagram in Ports and Protocols section
https://vmware.github.io/vic-product/assets/files/html/1.5/vic_vsphere_admin/network_reqs.html#ports-and-protocols-
contains wrong network path from vCenter to vIC: vIC Plugin actually runs in client browser, so arrow with https (tcp:8443) must be originated from the Cloud admin, but not vCenter."

My suspicion is that if the connection is between the VIC appliance and the plug-in, then the current diagram is actually correct. Can you please confirm? 

Also, do we need to add connections between the VCH management interface and the appliance? I thought that the management interface was only for connections between VCHs and vSphere.

**Comment by dukesrg** [comment]
@stuclem All of my statements above was checked on the working configuration with network isolation - I can definitely see what really happens in NSX DFW logs.

**Comment by stuclem** [comment]
Thanks for confirming @dukesrg. The cloud admin and the vSphere admin are not necessarily the same person, though. So, do you think that we need a new box for connections to the appliance from the vSphere Client?

**Comment by dukesrg** [comment]
@stuclem Yes it looks like admin and developer access arrows should be explicitly split with client apps.

**Comment by renmaosheng** [comment]
> @renmaosheng can you please confirm whether the following statement is accurate?
> 
> "The network diagram in Ports and Protocols section
> https://vmware.github.io/vic-product/assets/files/html/1.5/vic_vsphere_admin/network_reqs.html#ports-and-protocols-
> contains wrong network path from vCenter to vIC: vIC Plugin actually runs in client browser, so arrow with https (tcp:8443) must be originated from the Cloud admin, but not vCenter."
> 
> My suspicion is that if the connection is between the VIC appliance and the plug-in, then the current diagram is actually correct. Can you please confirm?
Yes, the VIC ui plugin is part of vCenter, it will call the APIs of VIC appliance to manipulate VCHs

**Comment by stuclem** [comment]
Thanks @renmaosheng. Closing per comment above.
