### ISSUE TITLE
docker run --label supported?

### ISSUE THREAD

**Issue by stuclem** [vmware/vic-product#2321]
@malikkal commented on [Fri Dec 14 2018](https://github.com/vmware/vic/issues/8412)

As per documentation [here](https://vmware.github.io/vic-product/assets/files/html/1.4/vic_app_dev/container_operations.html), it seems docker run --label is not supported. However, in practice it does seem to work. Please see below.

`docker run -itd --net=blah01 --label="traefik.enable=true" --label="traefik.frontend.rule=Host:blah.blue.com" --label="traefik.backend=nginx1" --label="traefik.port:80" --label="traefik.frontend.entryPoints=http" registry/project/nginx:1.13.5-alpine`

docker inspect <container>

```
  "Labels": {
                "com.docker.compose.config-hash": "b75471c855439f022fed77d3c950b7d674939853cd7496ebacf94765e1413f94",
                "com.docker.compose.container-number": "1",
                "com.docker.compose.oneoff": "False",
                "com.docker.compose.project": "docker",
                "com.docker.compose.service": "web",
                "com.docker.compose.version": "1.22.0",
                "maintainer": "NGINX Docker Maintainers <docker-maint@nginx.com>",
                "nginxcvm": "",
                "traefik.backend": "nginx1",
                "traefik.docker.network:blah01": "",
                "traefik.enable": "true",
                "traefik.enable:true": "",
                "traefik.frontend.entryPoints": "http",
                "traefik.frontend.passHostHeader": "true",
                "traefik.frontend.passHostHeader:true": "",
                "traefik.frontend.rule": "Host:blah.blue.com",
		"traefik.network:blah01": "",
                "traefik.port:80": "",
                "traefik.port:8001": ""
            }

```

May I know if this docker run --labels are officially supported, please? Thanks.

---

@aviratna commented on [Wed Jan 02 2019](https://github.com/vmware/vic/issues/8412#issuecomment-450827942)

Official Support for Docker label will be really helpful as we can use this field for many use cases like Chargeback, categorization, mapping, load balancing as mentioned by @malikkal  above.

---

@wjun commented on [Wed Jan 30 2019](https://github.com/vmware/vic/issues/8412#issuecomment-458856219)

@malikkal  Yes, --label or --label-file is officially supported in 'docker create' and 'docker run' commands since vic 1.0. Users can use 'docker inspect' to check labels or 'docker ps --filter="label=..." to filter out containers with certain labels. @stuclem   Could you please to update vic documents to include these 2 options into 'docker create' and 'docker run' commands? Thanks. Once the document completes, we can close it.

---

@meeximum commented on [Wed Jan 30 2019](https://github.com/vmware/vic/issues/8412#issuecomment-458860650)

it would be great, when the label option would be integrated in the GUI?

---

@stuclem commented on [Wed Jan 30 2019](https://github.com/vmware/vic/issues/8412#issuecomment-458900602)

Thanks @wjun and @meeximum. Moving this to the vic-product repo, now that this is a doc issue.

**Comment by kkuphal** [comment]
Is it possible set the label during provisioning in the VIC GUI or is this only supported from docker run?

**Comment by wjun** [comment]
@kkuphal No this (labels) is currently not supported in the VIC GUI, and only supported from docker run CLI.
