### ISSUE TITLE
vSphere Integrated Container Appliance Proxy Configuration

### ISSUE THREAD

**Issue by schindlerd** [vmware/vic-product#2323]
#### Summary

Add proxy configuration support for VIC appliance.

#### User statement(s)

It would be great to have some proxy configuration support for VIC appliance itself so that for example Clair can sync its vulnerability database over the proxy and without direct firewall access to the different URLs.

#### Details

We would like to prevent allowing direct firewall access for VIC appliance to the different vulnerability databases (https://vmware.github.io/vic-product/assets/files/html/1.5/vic_cloud_admin/vulnerability_scanning.html).

#### See also

https://kb.vmware.com/s/article/52332

**Comment by zjs** [comment]
@renmaosheng: It looks like this issue from Feb 1 has not been triaged.

**Comment by schindlerd** [comment]
The internally configured Clair update interval seems pretty high...

When the firewall is not opened we see about 100.000 denies per hour where it tries to access http://static.nvd.nist.gov! The other URLs (Oracle, Debian, Red Hat, etc.) are not queried that often.

When I look at https://github.com/coreos/clair/blob/master/config.yaml.sample the interval should be configurable. Is there a Clair config somewhere in the vic-product project?

**Comment by wjun** [comment]
@reasonerjt Any possibility to set the Clair update interval? @schindlerd proxy configuration has been added since VIC 1.5.0.

**Comment by schindlerd** [comment]
@wjun Where can I configure such global proxy setting? I see that proxy setting scan be configured for VCHs but how would I configure it for the VIC appliance?

**Comment by wjun** [comment]
@schindlerd When you deploy ovf template from vsphere web client, you can fill http(s) proxy:
![image](https://user-images.githubusercontent.com/1091832/54579587-16f41200-4a3f-11e9-9c96-a7b90c23937b.png)

**Comment by schindlerd** [comment]
Thanks @wjun our vSphere admins must have overlooked that - or may be because we started with VIC 1.4

**Comment by reasonerjt** [comment]
@wjun there is a configuration in `harbor.cfg` to set the interval of the updaters in Clair:
https://github.com/goharbor/harbor/blob/master/make/harbor.cfg#L177

**Comment by wjun** [comment]
@schindlerd May I close this issue and use Clair to track that issue?

**Comment by schindlerd** [comment]
@wjun Please feel free to close this issue. Thanks a lot for your feedback guys!
