### ISSUE TITLE
VCH deletion fails because it cannot find VCH vm

### ISSUE THREAD

**Issue by jitinkumar2018** [vmware/vic-product#2340]
**Bug Report Basic Information**
**REQUIRED**:

vCenter Server version: 6.7 U1
Embedded or external PSC: No
Filename of the OVA you deployed: vic-v1.5.1-6995-a6158aac.ova
How was the OVA deployed? ovftool
Does the VIC appliance recieve configuration by DHCP? No
What stage of the Appliance Lifecycle is the VIC appliance in? Application
Appliance Logs : 
[vic_appliance_logs_2019-02-19-08-44-13.tar.gz](https://github.com/vmware/vic-product/files/2879171/vic_appliance_logs_2019-02-19-08-44-13.tar.gz)

**Bug Report Detailed Information**
What operation was being performed when the failure was noticed?
VCH deletion using vic-machine-linux delete CLI 

**DETAILS:**
- 50 VCH's were created 
- 50 containers were deployed in each VCH resource pool (2000 containers in total)
- While performing concurrent VCH delete (using -f parameter ) on all 50 VCH's, failure occurred because it could not find VCH vm. (VCH vm was deleted before containers )
- Rerun of deletion fails with the same error.
- Final state: Resource Pools along with powered down containers remain and VCH vms are not present in those resource pools

**Comment by jitinkumar2018** [comment]
@renmaosheng @luwang-vmware

**Comment by wjun** [comment]
@jitinkumar2018 -f parameter will ignore container deletion failures and continue to delete VCH vm. You may not use -f option next time, and the vic-machine-linux command will stop when there is any error during container deletion. You can post vic-machine.log for that failed command to better understand why container deletion fails.

**Comment by jitinkumar2018** [comment]
Thanks for the clarification @wjun.

**Comment by wjun** [comment]
It is consistent with current design.
