### ISSUE TITLE
Manual upgrade from 1.5.0 to 1.5.2 failed during Harbor Upgrade

### ISSUE THREAD

**Issue by jitinkumar2018** [vmware/vic-product#2360]
**Bug Report Basic Information**
**REQUIRED**:

vCenter Server version: 6.7 U1
Embedded or external PSC: No
Filename of the OVA you deployed: vic-dev-v1.5.2-rc1-7059-ac1d9122.ova
How was the OVA deployed? ovftool
Does the VIC appliance recieve configuration by DHCP? No
What stage of the Appliance Lifecycle is the VIC appliance in? Application
Appliance Logs :
[vic_appliance_logs_2019-03-01-06-40-24.tar.gz](https://github.com/vmware/vic-product/files/2918189/vic_appliance_logs_2019-03-01-06-40-24.tar.gz)
Upgrade Log:
[upgrade.log](https://github.com/vmware/vic-product/files/2918191/upgrade.log)

**Bug Report Detailed Information**
What operation was being performed when the failure was noticed?
VIC appliance upgrade from 1.5.0 to 1.5.2

**DETAILS:**

Correctly detected Old VIC appliance version and began upgrade 
Admiral Upgrade was successful.
Failed during Backing up Harbor Data 
Able to see VCHs, containers and projects in VIC 1.5.2 Admiral

###########################################################
Starting Harbor Upgrade 2019-03-01 06:26:38 +0000 UTC
2019-03-01 06:29:39 [=] Back up harbor data to : /storage/data/harbor_backup
tar: Removing leading `/' from member names
tar: /storage/db/harbor/database/base/12406/16545: file changed as we read it
tar: /storage/db/harbor/database/base/12406: file changed as we read it
tar: /storage/db/harbor/database/base: file changed as we read it
tar: /storage/db/harbor/database: file changed as we read it
2019-03-01 06:30:11 [=]
2019-03-01 06:30:11 [=] -------------------------
2019-03-01 06:30:11 [=] Upgrade failed.
2019-03-01 06:30:11 [=] Please save /var/log/vmware/upgrade.log and contact VMware support.
2019-03-01 06:30:11 [=] -------------------------
2019-03-01 06:30:11 [=]

@renmaosheng @luwang-vmware

**Comment by DanielXiao** [comment]
It seems the new appliance was registered to PSC, see `journalctl -u fileserver.service`
```
Mar 01 06:27:11 vic-st-h2-182.eng.vmware.com start_fileserver.sh[1356]: Mar  1 2019 06:27:11.560Z INFO  op=1358.3: Validation succeeded
Mar 01 06:27:12 vic-st-h2-182.eng.vmware.com start_fileserver.sh[1356]: Mar  1 2019 06:27:12.035Z DEBUG op=1358.3: successfully attached the product tag
Mar 01 06:27:12 vic-st-h2-182.eng.vmware.com start_fileserver.sh[1356]: Mar  1 2019 06:27:12.041Z INFO  op=1358.3: vCenter user: Administrator@vsphere.local
Mar 01 06:27:12 vic-st-h2-182.eng.vmware.com start_fileserver.sh[1356]: Mar  1 2019 06:27:12.041Z INFO  op=1358.3: PSC instance: w2hs2-vrops08.eng.vmware.com
Mar 01 06:27:12 vic-st-h2-182.eng.vmware.com start_fileserver.sh[1356]: Mar  1 2019 06:27:12.041Z INFO  op=1358.3: PSC domain: vsphere.local
Mar 01 06:27:12 vic-st-h2-182.eng.vmware.com start_fileserver.sh[1356]: Mar  1 2019 06:27:12.042Z INFO  op=1358.3: PSC Out of the box users. CreateUsers: True
, FoundCreateUsers: true, Prefix: vic
Mar 01 06:27:30 vic-st-h2-182.eng.vmware.com start_fileserver.sh[1356]: Mar  1 2019 06:27:30.774Z INFO  op=1358.3: Successfully registered harbor with PSC
Mar 01 06:27:34 vic-st-h2-182.eng.vmware.com start_fileserver.sh[1356]: Mar  1 2019 06:27:34.841Z INFO  op=1358.3: Successfully registered engine with PSC
Mar 01 06:27:43 vic-st-h2-182.eng.vmware.com start_fileserver.sh[1356]: Mar  1 2019 06:27:43.841Z INFO  op=1358.3: Successfully registered admiral with PSC
```

Harbor was stopped at  06:27:10, see upgrade.log
```
2019-03-01 06:27:10 [=] Disabling and stopping Admiral and Harbor
Removed /etc/systemd/system/vic-appliance.target.wants/admiral.service.
Removed /etc/systemd/system/vic-appliance.target.wants/harbor.service.
```
But it started again at 06:28:41:
```
● harbor.service - Harbor Container Registry
   Loaded: loaded (/lib/systemd/system/harbor.service; disabled; vendor preset: enabled)
   Active: active (running) since Fri 2019-03-01 06:28:41 UTC; 1h 12min ago
     Docs: https://vmware.github.io/vic-product/index.html#getting-started
  Process: 2206 ExecStartPre=/usr/bin/python /etc/vmware/harbor/prepare --conf /storage/data/harbor/harbor.cfg --with-notary --with-clair (code=exited, status
=0/SUCCESS)
  Process: 2139 ExecStartPre=/usr/bin/bash /etc/vmware/harbor/configure_harbor.sh (code=exited, status=0/SUCCESS)
  Process: 2132 ExecStartPre=/usr/bin/docker rm dch-push (code=exited, status=1/FAILURE)
  Process: 2125 ExecStartPre=/usr/bin/docker stop dch-push (code=exited, status=1/FAILURE)
  Process: 2121 ExecStartPre=/usr/local/bin/docker-compose -f /etc/vmware/harbor/docker-compose.yml -f /etc/vmware/harbor/docker-compose.notary.yml -f /etc/vm
ware/harbor/docker-compose.clair.yml rm -f (code=exited, status=1/FAILURE)
  Process: 2096 ExecStartPre=/usr/local/bin/docker-compose -f /etc/vmware/harbor/docker-compose.yml -f /etc/vmware/harbor/docker-compose.notary.yml -f /etc/vm
ware/harbor/docker-compose.clair.yml down -v (code=exited, status=1/FAILURE)
 Main PID: 2223 (start_harbor.sh)
    Tasks: 17 (limit: 4915)
   Memory: 64.3M
      CPU: 38.210s
   CGroup: /system.slice/harbor.service
           ├─2223 /usr/bin/bash /etc/vmware/harbor/start_harbor.sh
           ├─2944 /usr/local/bin/docker-compose -f /etc/vmware/harbor/docker-compose.yml -f /etc/vmware/harbor/docker-compose.notary.yml -f /etc/vmware/harbor
/docker-compose.clair.yml up
           └─2946 /usr/local/bin/docker-compose -f /etc/vmware/harbor/docker-compose.yml -f /etc/vmware/harbor/docker-compose.notary.yml -f /etc/vmware/harbor
/docker-compose.clair.yml up
```

**Comment by jitinkumar2018** [comment]
Upgrade from 1.5.0 to 1.5.2 worked when I tried again with the same steps. Not sure what caused it to fail the first time.
