### ISSUE TITLE
Document support for pkcs1 format private key in ui wizard

### ISSUE THREAD

**Issue by stuclem** [vmware/vic-product#2366]
Per https://github.com/vmware/vic-ui/pull/657

**Comment by stuclem** [comment]
@zhoumeina and @wjun, is this limited to the UI change in https://github.com/vmware/vic-ui/pull/657, or is there a change in the underlying implementation? 

I ask because in the topic on VCH certificate requirements, we currently state that private keys should be in  PKCS#8 format if you use custom PKCS#1 server certificates for VCHs:

https://vmware.github.io/vic-product/assets/files/html/1.5/vic_vsphere_admin/vch_cert_reqs.html#custom

Do I need to changes the VCH certificates docs to state that PKCS#1 private keys are supported?

**Comment by wjun** [comment]
> @zhoumeina and @wjun, is this limited to the UI change in [vmware/vic-ui#657](https://github.com/vmware/vic-ui/pull/657), or is there a change in the underlying implementation?
> 
> I ask because in the topic on VCH certificate requirements, we currently state that private keys should be in PKCS#8 format if you use custom PKCS#1 server certificates for VCHs:
> 
> https://vmware.github.io/vic-product/assets/files/html/1.5/vic_vsphere_admin/vch_cert_reqs.html#custom
> 
> Do I need to changes the VCH certificates docs to state that PKCS#1 private keys are supported?

I saw PKCS#1 is listed in the document link above already. Is this another document you mean? Basically, the underlying implementation does not change, and UI fixed to support PKCS#1 private keys which are supported from vic-machine command line already.

**Comment by stuclem** [comment]
Thanks @wjun. In that case I don't think that we need any doc changes. Closing.
