### ISSUE TITLE
Documentation: check doc impact of shared image store fix

### ISSUE THREAD

**Issue by stuclem** [vmware/vic-product#2369]
Check that the fix for https://github.com/vmware/vic/issues/8455 doesn't affect the docs on sharing the image store.

**Comment by stuclem** [comment]
Here's what we currently document about sharing an image store between VCHs:

---

By specifying a datastore folder, you can designate the same datastore folder as the image store for multiple VCHs. Only one VIC folder is created in the datastore, but it contains one vch_uuid/images folder for each VCH that you deploy. By creating one vch_uuid/images folder for each VCH, vSphere Integrated Containers Engine limits the potential for conflicts of image use between VCHs, even if you share the same image store folder between multiple hosts.

---

@DanielXiao can you please confirm that the fix for https://github.com/vmware/vic/issues/8455 does not affect this documentation? Thanks!

**Comment by DanielXiao** [comment]
@wjun @luwang-vmware I did the bug triage and didn't verify it, can you confirm the documentation?

**Comment by wjun** [comment]
@stuclem Yes, I confirmed the fix does not affect this documentation.

**Comment by stuclem** [comment]
Thanks @wjun ! Closing this one.
