### ISSUE TITLE
Add a new check point in the OVA appliance upgrade

### ISSUE THREAD

**Issue by luwang-vmware** [vmware/vic-product#2372]
The current OVA appliance upgrade case is doing upgrade.sh when the new OVA appliance is ssh-able. The automation need to wait till the service landing_server.service is in dead state.

root@localhost [ /etc/vmware/upgrade ]# systemctl status landing_server.service
● landing_server.service - VIC Appliance Landing Page Server
   Loaded: loaded (/lib/systemd/system/landing_server.service; enabled; vendor preset: enabled)
   Active: inactive (dead) since Wed 2019-03-06 08:29:22 UTC; 1h 12min ago
     Docs: https://github.com/vmware/vic-product
 Main PID: 332 (code=killed, signal=TERM)
      CPU: 6ms

Mar 06 08:29:18 localhost systemd[1]: Started VIC Appliance Landing Page Server.
Mar 06 08:29:22 localhost systemd[1]: Stopping VIC Appliance Landing Page Server...
Mar 06 08:29:22 localhost systemd[1]: Stopped VIC Appliance Landing Page Server.

**Comment by renmaosheng** [comment]
the code is merged. please add the pull request then close.

**Comment by luwang-vmware** [comment]
PR is https://github.com/vmware/vic-product/pull/2362, the code change is in tests/resources/OVA-Util.robot.
