### ISSUE TITLE
Containers will not get ip from NSX-T Logical switch to which DHCP server is attached to, if DNS is not specified in the DHCP server (although it's optional) 

### ISSUE THREAD

**Issue by jitinkumar2018** [vmware/vic-product#2375]
@stuclem 

#### Summary
While deploying containers by specifying the DHCP network in the docker run command (--network dhcpNetwork ) , containers will not receive DHCP ip and the command will time out if no DNS server is specified in the NSXT DHCP server.

#### Details

In NSXT (2.3.1) Manager, DHCP server is created with ip, subnet mask, default gateway and ip pool but DNS server is not specified as it is optional according to NSXT documentation : https://docs.vmware.com/en/VMware-NSX-T/2.1/com.vmware.nsxt.admin.doc/GUID-A7F8F3DF-C84C-4E96-A98E-E2D8EF38B083.html 

VCH is created with container-network parameter and assigned a name called 'routable':
`--container-network <NSXT-Logical-Switch>:routable`

Docker run command which attaches its network adapter 1 to the DHCP network:
`docker run -itd --network routable photon`

Container will fail to get to ip and command will timeout with error:
`docker: Error response from daemon: Server error from portlayer: unable to wait for process launch status`

Only if DNS server is specified in the DHCP server, the containers will get ip from DHCP server

##### Section reference(s)

This can be added in the container network section as a Note.
https://vmware.github.io/vic-product/assets/files/html/1.5/vic_vsphere_admin/container_networks.html

##### Product version(s)
VIC 1.5.0 onward

**Comment by jitinkumar2018** [comment]
Thanks to @yuyangbj for pointing out the solution

**Comment by stuclem** [comment]
Thanks @jitinkumar2018 and @yuyangbj

**Comment by stuclem** [comment]
@vidya-v can you please take a look at this one?
