### ISSUE TITLE
Admiral web link does not show correctly after the OVA appliance gets a new DHCP address

### ISSUE THREAD

**Issue by luwang-vmware** [vmware/vic-product#2384]
The issue is found in vic 1.5.1.

Steps:
1. Deploy a OVA appliance and power it on, which gets DHCP address, e.g. DCHP_IP1. Visit web page https://DHCP_IP1:9443 everything goes well, and admiral page can be showed expected after click 'Go to the vSphere Integrated Containers Management Portal'.

2.  OVA appliance is powered off for a few days.

3. Power the OVA appliance on and it gets a new DHCP address, e.g DHCP_IP2. Visit web page https://DHCP_IP2:9444 everything goes well, but when click 'Go to the vSphere Integrated Containers Management Portal', the new page link shows the old DHCP_IP1, such as https://**DHCP_IP1:8282**/auth/psc/callback/token . Since DHCP_IP1 is not used any more, so the link can not be visitable.

**Comment by wjun** [comment]
This is expected. Re-initialize from OVA VM's web page will resolve it.
