### ISSUE TITLE
Document that users can add customized configuration for Admiral

### ISSUE THREAD

**Issue by stuclem** [vmware/vic-product#2415]
Per https://github.com/vmware/vic-product/issues/2391.

**Comment by stuclem** [comment]
New functionality in 1.5.3. Setting to severity 1.

**Comment by stuclem** [comment]
Pushed out to 1.5.4

**Comment by stuclem** [comment]
Actually, looking at https://github.com/vmware/vic-product/pull/2478, I'm not sure that there is a doc impact here. @DanielXiao do we need to document anything in relation to https://github.com/vmware/vic-product/pull/2478 and https://github.com/vmware/vic-product/issues/2391? Thanks!

**Comment by DanielXiao** [comment]
/storage/data/admiral/custom.conf is used for customized configuration, but it is flushed out every time admiral restart. Fix in #2478 is to persist this file and combine with automatically generated configurations.

**Comment by stuclem** [comment]
OK, thank you @DanielXiao. I think that this is a release note issue.

**Comment by stuclem** [comment]
@VinodJIsaac can you please check with @DanielXiao if there is indeed a doc update to make here? Thanks!

**Comment by stuclem** [comment]
Fixed in https://github.com/vmware/admiral/releases/tag/vic_v1.5.5#resolvedissues
