### ISSUE TITLE
OVA deploy wizard allows for passwords longer than the 30 character limit of the plugin installer which causes the installer to fail

### ISSUE THREAD

**Issue by wjun** [vmware/vic-product#2443]
The OVA allows and instructions say passwords of a length 128 characters can be used. However this then fails to install the plugin due to 30 character limit.

Bugzilla#2327306

**Comment by wjun** [comment]
@stuclem The bugzilla#2327306 found OVA intallers allows the password to be 128 at maximum, so we need to update the ova-product's initialization web page to support 128 at maximum as well. Thanks.

**Comment by stuclem** [comment]
Thanks @wjun. I opened https://github.com/vmware/vic-product/issues/2447 for the doc update.
