### ISSUE TITLE
Automatic Upgrade fails from 1.5.0 to 1.5.2 if you specify the parameters in the command line options

### ISSUE THREAD

**Issue by jitinkumar2018** [vmware/vic-product#2454]
Bug Report Basic Information
REQUIRED:

vCenter Server version: 6.7 U2  (Might be interop bug)
Embedded or external PSC: Embedded
Filename of the OVA you deployed: vic-v1.5.2-7206-92ebfaf5.ova
How was the OVA deployed? ovftool
Does the VIC appliance recieve configuration by DHCP? No
What stage of the Appliance Lifecycle is the VIC appliance in? Upgrade

Bug Report Detailed Information
What operation was being performed when the failure was noticed?
VIC appliance upgrade from 1.5.0 to 1.5.2 using command line options

DETAILS:
Command used to upgrade:
/etc/vmware/upgrade/upgrade.sh --target $vcFqdn --username $vcUsername --password $vcPassword --fingerprint '$vcFqdn $vcThumbprint' --dc Datacenter --embedded-psc --appliance-target $oldVicIp --appliance-username root --appliance-password $vicPassword --ssh-insecure-skip-verify --appliance-version v1.5.0 --upgrade-ui-plugin n

The upgrade script fails with the following details:
2019-04-26 06:53:35 [=]
2019-04-26 06:53:35 [=] -------------------------
2019-04-26 06:53:35 [=] Upgrade failed.
2019-04-26 06:53:35 [=] Please save /var/log/vmware/upgrade.log and contact VMware support.
2019-04-26 06:53:35 [=] -------------------------
2019-04-26 06:53:35 [=]

But there is no upgrade.log that is generated
Normal upgrade works if the parameters are supplied while running ./upgrade.sh. interactively.
Will provide credentials of VIC appliance and VC through slack

**Comment by jitinkumar2018** [comment]
@DanielXiao @luwang-vmware

**Comment by wjun** [comment]
Please try --upgrade-ui-plugin without "n"

**Comment by jitinkumar2018** [comment]
It worked when i removed the n. But that means the upgrade script will upgrade the UI plugin right?

**Comment by wjun** [comment]
Yes, in the script mode.
