### ISSUE TITLE
Mount command used to mount an NFS share point from within VCH vm is incorrect

### ISSUE THREAD

**Issue by jitinkumar2018** [vmware/vic-product#2455]
Section : Mount an NFS Share Point in the VCH Endpoint VM (https://vmware.github.io/vic-product/assets/files/html/1.5/vic_vsphere_admin/vch_mount_nfsshare.html)

In the Procedure section, the final command which is used to mount the NFS share point should be:
mount.nfs nfs_sharepoint_url -o vers=3 
instead of
mount -t nfs nfs_sharepoint_url -o vers=3

**Comment by jitinkumar2018** [comment]
@stuclem @vidya-v

**Comment by YanzhaoLi** [comment]
@jitinkumar2018  The `mount` manual doc says `mount -t nfs` will call `mount.nfs`.

**Comment by jitinkumar2018** [comment]
root@ [ ~ ]# mount -t nfs
-bash: mount: command not found
root@ [ ~ ]# mount.nfs
mount.nfs: no mount point provided
usage: mount.nfs remotetarget dir [-rvVwfnsh] [-o nfsoptions]
options:
        -r              Mount file system readonly
        -v              Verbose
        -V              Print version
        -w              Mount file system read-write
        -f              Fake mount, do not actually mount
        -n              Do not update /etc/mtab
        -s              Tolerate sloppy mount options rather than fail
        -h              Print this help
        nfsoptions      Refer to mount.nfs(8) or nfs(5)
