### ISSUE TITLE
Document that container-network needs network name as well as port group name

### ISSUE THREAD

**Issue by stuclem** [vmware/vic-product#247]
Per https://github.com/vmware/vic/issues/5066.

Applies to 1.1.x docs as well as 1.2.

**Comment by morris-jason** [comment]
More specifically, a network name is mandatory if the port group name contains a space. Otherwise, the network name is optional. In both cases the network name cannot contain a space.

**Comment by stuclem** [comment]
Fix is in https://github.com/vmware/vic-product/pull/346/commits/3529b828a74216f9326a0a5b747b08dcb3fc38fe.
