### ISSUE TITLE
Upgrade from VIC 1.5.2 to 1.5.3 RC3 fails during registration of appliance with VC

### ISSUE THREAD

**Issue by jitinkumar2018** [vmware/vic-product#2495]
Bug Report Basic Information
REQUIRED:

vCenter Server version: 6.7 U2
Embedded or external PSC: Embedded
Filename of the OVA you deployed: vic-v1.5.3-rc3-7486-30200689.ova
How was the OVA deployed? ovftool
Does the VIC appliance recieve configuration by DHCP? No
What stage of the Appliance Lifecycle is the VIC appliance in? Upgrade

Bug Report Detailed Information
What operation was being performed when the failure was noticed?
VIC appliance upgrade from 1.5.2 to 1.5.3 RC3 using command line options. Fails after waiting for appliance registration.

VIC appliance Logs:
[vic_appliance_logs_2019-06-17-15-26-40.tar.gz](https://github.com/vmware/vic-product/files/3300044/vic_appliance_logs_2019-06-17-15-26-40.tar.gz)

DETAILS:
Command used to upgrade:

/etc/vmware/upgrade/upgrade.sh --target $vcFqdn --username $vcUsername --password $vcPassword --fingerprint \'$vcFqdn $thumbPrint\' --dc Datacenter --embedded-psc --appliance-target $oldVicIp --appliance-username root --appliance-password Admin\!23 --ssh-insecure-skip-verify --appliance-version $oldVicVersion --upgrade-ui-plugin --upgrade-password Admin\!23

**Comment by DanielXiao** [comment]
Error logs:
```

**Comment by DanielXiao** [comment]
@jitinkumar2018 please check if time is synched between VC and VIC appliance.

**Comment by jitinkumar2018** [comment]
Upgrade worked after redeploying scale and verifying whether VIC appliance time is synced with the VC before running upgrade. Thanks @DanielXiao. (Reason: NTP service had stopped on the ESXi on which VC was running on)
