### ISSUE TITLE
Unified OVA still shows the old version number in the OVF deploy template summary before clicking finish to deploy

### ISSUE THREAD

**Issue by dbarkelew** [vmware/vic-product#252]
VIC 1.1.1 OVA shows 1.1.0 version in the details confirmation screens before clicking finish to start deploying the unified OVA. 

Seems strictly a cosmetic issue with the OVA packing. Versions after deployment match correctly for the 1.1.1 release as expected.

Bug 1881541

**Comment by andrewtchin** [comment]
https://github.com/vmware/vic/issues/5192
