### ISSUE TITLE
Container VMs do not get DHCP IP 

### ISSUE THREAD

**Issue by jitinkumar2018** [vmware/vic-product#2551]
Bug Report Basic Information

VC Build: https://buildweb.eng.vmware.com/ob/15610183/
ESX Build: https://buildweb.eng.vmware.com/ob/15525992/
NSXT Build: https://buildweb.eng.vmware.com/ob/15314292/

Embedded or external PSC: Embedded
Vic Builds used: vic-dev-v1.5.5-rc1-7701-fb00e93c.ova
How was the OVA deployed? ovftool
Does the VIC appliance recieve configuration by DHCP? No
What stage of the Appliance Lifecycle is the VIC appliance in? 

Bug Report Detailed Information
What operation was being performed when the failure was noticed?

Container creation was failing with context deadline error after issuing the docker command:
`root@jumphost#  docker -H 10.197.37.135:2376 --tls run --network routable -itd --label app.name=photon photon

a38169f1971025051b27ef83a446994fba64954b0cf9ee125c21fed98a20103c
docker: Error response from daemon: Server error from portlayer: unable to wait for process launch status: Post https://w2hs2-rdp04.eng.vmware.com/sdk: context deadline exceeded.`

Steps to reproduce error:

1. Created NSXT Logical Switch/Segment ( Name:  CN-new ) and attached DHCP server (Name: DHCP-Server) and configured DNS as 12.12.0.3 and DHCP IP range as 12.12.0.10-12.12.15.254

![image](https://user-images.githubusercontent.com/42163572/74932926-f4b20380-5408-11ea-9dbe-b0a42ae2b296.png)

2. Created Tier 1 Gateway with interface (Name: new-Interface) IP : 12.12.0.1/20 connected to above segment

3. Verified that dummy VM deployed on one of the hosts in the cluster was receiving DHCP ip 

4. Created VCH with following command. 

`./vic-machine-linux create --force -t w2hs2-rdp04.eng.vmware.com --user Administrator@vsphere.local --password 'Admin!23' -r Cluster/Resources                                                    -i CPBU_2TB_02 --no-tlsverify --timeout 60m --public-network-gateway 10.197.37.253 --dns-server 10.142.7.21 --public-network 1025VLAN --bridge-network BridgeNetwork-LS --container-netwo                                                   rk CN-new:routable --container-network-firewall CN-new:open --registry-ca=/etc/docker/certs.d/10.197.37.181/ca.crt --public-network-ip 10.197.37.135/23 -n VCH135`

5. Able to see bridge and container network via docker network ls

`4# docker -H 10.197.37.135:2376 --tls network ls
NETWORK ID          NAME                DRIVER              SCOPE
9e5f0dcaec8a        bridge              bridge
58cc404c0f21        routable            external
`

6. Tried deploying container with below command but command times out:

`# docker -H 10.197.37.135:2376 --tls run --network routable -itd --label app.name=nginx nginx
Unable to find image 'nginx:latest' locally
latest: Pulling from library/nginx
bc51dd8edc1b: Pull complete
a3ed95caeb02: Pull complete
66ba67045f57: Pull complete
bf317aa10aa5: Pull complete
Digest: sha256:62f787b94e5faddb79f96c84ac0877aaf28fb325bfc3601b9c0934d4c107ba94
Status: Downloaded newer image for library/nginx:latest
ccf0c0f5127ab46efb34aff2d4fc5e3c1184df3f3ef7066d0c069e2e34611f5b
docker: Error response from daemon: Server error from portlayer: unable to wait for process launch status: Post https://w2hs2-rdp04.eng.vmware.com/sdk: context deadline exceeded.
`

VIC support bundle: 
[vic_appliance_logs_2020-02-20-12-23-40.tar.gz](https://github.com/vmware/vic-product/files/4230652/vic_appliance_logs_2020-02-20-12-23-40.tar.gz)

VC IP: 10.197.37.104 root/Administrator@vsphere.local/Admin!23
VIC IP: 10.197.37.132 root/Admin!23
NSXT IP: 10.197.37.204 admin/Admin!23Admin!23
ESXI creds: root/ca$hc0w

@yuyangbj @luwang-vmware @renmaosheng

**Comment by yuyangbj** [comment]
I checked your environment, the dhcp server does not configure the default gateway. VIC assumes the default gateway information will be returned from DHCP reply packet.

**Comment by jitinkumar2018** [comment]
Thanks @yuyangbj.  As of now in NSXT grindcore, there is a NSXT Manager UI issue wrt configuring default gateway  for DHCP server. Will work with NSBU team on this

**Comment by jitinkumar2018** [comment]
After configuring gateway CIDR in the segment attached to the local DHCP server, container VMs started getting DHCP IP. 
![image](https://user-images.githubusercontent.com/42163572/75750511-354b3000-5cd9-11ea-99dd-25bd453a853d.png)
