### ISSUE TITLE
Size of volumes for containers

### ISSUE THREAD

**Issue by BurningTheSky** [vmware/vic-product#2552]
#### Question
I'm looking for help with working out how to size volumes, I created them using the docker volume create command but it has only created 1gb volumes. How do I make them at a bigger size? All the information I can find on docker references files which don't appear to exist for me.

#### See also
root@18b01f72f791:/# df -h
Filesystem                           Size  Used Avail Use% Mounted on
none                                 985M     0  985M   0% /dev
none                                1003M     0 1003M   0% /dev/shm
/dev/disk/by-label/containerfs       7.9G  314M  7.1G   5% /
tmpfs                                 70M   62M  8.1M  89% /.tether
/dev/disk/by-label/03e33b8b9996a753  976M  331M  579M  37% /.tether/.filesystem-by-label/03e33b8b9996a753
/dev/disk/by-label/9fd105971130c579  976M  2.6M  907M   1% /.tether/.filesystem-by-label/9fd105971130c579
/dev/disk/by-label/aea0befb51d3e956  976M  2.6M  907M   1% /.tether/.filesystem-by-label/aea0befb51d3e956

**Comment by YanzhaoLi** [comment]
Did you create volume-store when you created your VCH?  If yes, you can see your volumes with `docker volume ls`.
Here is the doc: https://vmware.github.io/vic-product/assets/files/html/1.5/vic_vsphere_admin/backup_volumes.html

**Comment by BurningTheSky** [comment]
I did, that article is exactly what I couldn't find! --opt Capacity=5G solved all my issues, thank you!
