### ISSUE TITLE
After VIC Appliance v1.5.6 is deployed, Harbor failed to start.

### ISSUE THREAD

**Issue by hdytc** [vmware/vic-product#2594]
#### Summary

After VIC Appliance v1.5.6 is deployed, some container will not work.
![image](https://user-images.githubusercontent.com/25548735/110568713-67b22780-818e-11eb-8b4c-488ac2326ae2.png)
It looks like the root password in the container has expired.
![image](https://user-images.githubusercontent.com/25548735/110570103-61bd4600-8190-11eb-8205-d7bfe9a884e9.png)

##### vSphere and vCenter Server version

6.7U3
##### VIC Appliance version

https://storage.googleapis.com/vic-product-ova-releases/vic-v1.5.6-7849-bd6fe58a.ova
##### Configuration

- Embedded or external PSC: Embedded
- How was the OVA deployed? (Flex client, HTML5 client, ovftool): Flex client
- Does the VIC appliance recieve configuration by DHCP? static IP
- What [stage of the Appliance Lifecycle][1] is the VIC appliance in? Running Stage

[1]:https://github.com/vmware/vic-product/blob/master/installer/docs/SUPPORT.md#appliance-lifecycle

#### Logs

[vic_appliance_logs_2021-03-10-02-55-51.tar.gz](https://github.com/vmware/vic-product/files/6112874/vic_appliance_logs_2021-03-10-02-55-51.tar.gz)

**Comment by chb88** [comment]
See this issue:

https://github.com/vmware/vic/issues/8651
