### ISSUE TITLE
Doc: Break up the vic-machine create options topic and merge in the examples

### ISSUE THREAD

**Issue by stuclem** [vmware/vic-product#26]
The `vic-machine create` [options reference](https://github.com/vmware/vic/blob/master/doc/user_doc/vic_installation/vch_installer_options.md) is becoming too large to be easily maintainable or navigable. Also, much of the information is duplicated between the options reference and the [examples](https://github.com/vmware/vic/blob/master/doc/user_doc/vic_installation/vch_installer_examples.md) topic. 

I propose that we break up the options reference into separate topics that match the sections in vch_installer_options.md, and merge the relevant examples from vch_installer_examples.md into those smaller topics.

**Comment by stuclem** [comment]
@hickeng has objected in the past to breaking up the options reference topic. However, I believe that by doing so and incorporating the examples into the smaller sections, we will get closer to the scenario-based doc that @hickeng wants, as opposed to the current reference-heavy doc that we currently have. 

@mlh78750 @karthik-narayan @corrieb what do you think?

**Comment by corrieb** [comment]
Agreed. I would break it up into Compute, Network, Storage and Authentication. That pretty much covers all of it and helps the users to think about what high-level categories are required when creating a VCH

**Comment by hickeng** [comment]
@stuclem my primary objection to breaking it up (iirc) was that you cease to be able to search within a single document for an option. I'm all for breaking the detail out into scenario-based doc, and referencing those from a very concise index style reference.

**Comment by stuclem** [comment]
@hickeng OK, thanks for clarifying. I don't think that we'll manage this for 1.1, though, as the potential for link breakage and content loss is too great to be doing it at this late stage of the release.

**Comment by stuclem** [comment]
Too big a job for the 1.1.1 doc refresh. Moving to 1.2.
