### ISSUE TITLE
broken links in vch_installer_options.html

### ISSUE THREAD

**Issue by mdubya66** [vmware/vic-product#260]
From https://vmware.github.io/vic-product/assets/files/html/1.1/vic_vsphere_admin/vch_installer_options.html#adv-mgmt

Click on Allocate Memory Resources or Allocate CPU resources leads to a 404 error

**Comment by stuclem** [comment]
Strange. It looks like certain external links (e.g. to pubs.vmware.com) have had their `.html` suffixes changed to `.md` suffixes the source files, maybe during the HTML generation. I ran a link checker and found a few more cases. I will check whether there are known issues with Gitbook. Doesn't seem to happen consistently. I just rebuilt and the now links seem fine in my local version.

**Comment by stuclem** [comment]
Updated https://vmware.github.io/vic-product/assets/files/html/1.1/ in https://github.com/vmware/vic-product/pull/271.
