### ISSUE TITLE
Enforce reviews on PRs in vic-product

### ISSUE THREAD

**Issue by stuclem** [vmware/vic-product#266]
I would like to enforce the rule that all PRs on the `vic-product` repo must have at least 1 if not 2 reviewers, as is the case with the `vic` repo. This is mostly because reviewing doc PRs ensures technical accuracy of the doc.

I would like to extend this rule to the `gh-pages` branch as well as `master`, as we have had some problems whereby Web marketing keeps on overwriting changes that I make to files in that branch.

@frapposelli @mdubya66 who would be able to do this? 

Thanks!

**Comment by frapposelli** [comment]
I can do it

**Comment by stuclem** [comment]
Fabulous, thanks @frapposelli !

**Comment by frapposelli** [comment]
done

**Comment by stuclem** [comment]
Great, thanks @frapposelli

**Comment by stuclem** [comment]
I just did a PR to the master branch and a reviewer was indeed required. However, it is still possible to push to the gh-pages branch without a reviewer. @frapposelli can you enforce reviews on gh-pages as well, please? Thanks!

**Comment by frapposelli** [comment]
sure, fixed it now

**Comment by stuclem** [comment]
Thanks!

**Comment by stuclem** [comment]
Will leave this one in Verify until next time I need to do a PR on gh-pages.

**Comment by stuclem** [comment]
Verified.
