### ISSUE TITLE
Add descriptions of the files on the OVA download page

### ISSUE THREAD

**Issue by stuclem** [vmware/vic-product#311]
Update https://vmware.github.io/vic-product/assets/files/html/1.1/vic_vsphere_admin/deploy_vic_appliance.html to make it clear what the two plugin packages are.

**Comment by ali5ter** [comment]
@stuclem Would very much like to include this content in a design for the VIC appliance 9443 page. Rough concept might look like 
![screen shot 2017-06-15 at 8 14 04 am](https://user-images.githubusercontent.com/265869/27181551-0478de14-51a6-11e7-8960-c0a23fc77271.png)

**Comment by ali5ter** [comment]
another rev of the 9443 page with Stuart's content...
![screen shot 2017-06-15 at 12 45 58 pm](https://user-images.githubusercontent.com/265869/27192284-bc0d3d46-51c8-11e7-822f-c487b7463d24.png)

**Comment by stuclem** [comment]
Hi @ali5ter these look great. However, this issue is to clarify what the different downloads are in 1.1.x.

**Comment by stuclem** [comment]
Fixes are in https://github.com/vmware/vic-product/pull/343/commits/767190044d15967ab76600b580ddd86c1a982770.
