### ISSUE TITLE
Document that you cannot delete Admin user

### ISSUE THREAD

**Issue by stuclem** [vmware/vic-product#312]
Per https://github.com/vmware/harbor/issues/2527.

**Comment by ywk253100** [comment]
In standalone mode, the admin user will not be shown on the web page in 1.2. And in integration mode, user management isn't owned by Harbor.

**Comment by stuclem** [comment]
Thanks @ywk253100 - for some reason I'm only noticing your comment now. This issue is not relevant to the bundled Registry in the OVA.
