### ISSUE TITLE
Document location of admiral/harbor logs

### ISSUE THREAD

**Issue by stuclem** [vmware/vic-product#318]
Per https://github.com/vmware/vic/issues/5266. Might not be in 1.2. TBC.

**Comment by stuclem** [comment]
Found the appliance logs in `/var/log` on the appliance. 

@andrewtchin where do I find the Harbor and Admiral logs? Thanks!

**Comment by andrewtchin** [comment]
I believe Admiral is `docker logs vic-admiral` and Harbor is `/var/log/harbor`
@reasonerjt @sergiosagu please correct me if I'm wrong

**Comment by stuclem** [comment]
Admiral logs are moving in 1.3. See https://github.com/vmware/vic-product/issues/885.

**Comment by stuclem** [comment]
Tracking the 1.3 update in https://github.com/vmware/vic-product/issues/978. This issue is for 1.2.x.
