### ISSUE TITLE
VIC and a pull through cache

### ISSUE THREAD

**Issue by PhoenixMage** [vmware/vic-product#32]
Is it possible to configure VIC to use a pull through cache as per https://docs.docker.com/registry/recipes/mirror/

There is no --registry-mirror option when deploying VIC.

**Comment by stuclem** [comment]
This looks like it belongs in the `vic` repo, as it relates to `vic-machine`.

**Comment by stuclem** [comment]
Issue moved to [vmware/vic #4957](https://github.com/vmware/vic/issues/4957) via [**ZenHub**](https://www.zenhub.com/)
