### ISSUE TITLE
Document dch-photon

### ISSUE THREAD

**Issue by stuclem** [vmware/vic-product#324]
Per https://github.com/vmware/vic/issues/4852. This might become an Epic.

**Comment by stuclem** [comment]
See also https://github.com/vmware/vic/issues/4868

**Comment by stuclem** [comment]
Also https://github.com/vmware/vic/issues/4859

**Comment by stuclem** [comment]
Per https://github.com/vmware/vic-product/pull/544, DinV is now called `dch-photon`.

**Comment by stuclem** [comment]
Comment from @andrewtchin via Slack:

Andrew Chin [1:40 AM] 
i was testing dch-photon and wanted to make sure we have documented that the vch is required to be deployed with --registry-ca to be able to use images from harbor
[1:41] 
also depending on this result we may need a doc https://github.com/vmware/admiral/issues/192

**Comment by andrewtchin** [comment]
I confirmed with mavery that ANY container that requires anonymous volumes requires a VCH that has a volume store with the label `default` specified otherwise the error from vmware/admiral#192 happens. This should be documented in the DCH docs and with other volume docs

**Comment by stuclem** [comment]
Ok, thanks @andrewtchin
