### ISSUE TITLE
Document that Admiral fails if using RSA key format

### ISSUE THREAD

**Issue by stuclem** [vmware/vic-product#347]
Per comment from @dbarkelew via Slack:

"Found that Admiral fails if using RSA key format and needs to be converted first. Harbor and file server works with RSA format."

**Comment by nlowe** [comment]
I just encountered this as well. For future reference, here's what I did to convert it:

```bash
openssl pkcs8 -in my.key -topk8 -nocrypt -out my.key.pkcs8.pem
```

Also, it appears admiral will refuse to start if there is a blank line at the end of the key (after the `-----END PRIVATE KEY-----`). I ssh'd into the appliance and removed the extra line and the container started right up.

**Comment by stuclem** [comment]
Comment from @andrewtchin via Slack: 

for the ova deployment i think we should clearly document that admiral requires the TLS private key to be in PKCS8 format as admiral startup will fail otherwise

pkcs8 has `-----BEGIN PRIVATE KEY-----` while i often see pkcs1 format which begins with `-----BEGIN RSA PRIVATE KEY-----`"

**Comment by andrewtchin** [comment]
Also here's a howto https://github.com/andrewtchin/til/blob/master/sysadmin/openssl.md#pem-to-pkcs8
