### ISSUE TITLE
DX recommendation: kov help output

### ISSUE THREAD

**Issue by ali5ter** [vmware/vic-product#375]
Recommendations based on evaluation of version 3fef72f: https://confluence.eng.vmware.com/display/~bowena/kov+CLI+DX+evaluation#kovCLIDXevaluation-Recommendations

For all help output
* Usage sting should read, 'kov [global options] [command [command options] ]'
* 'Available commands' should read 'Commands'
* We talk about options, not flags.

Specifically for 'kov' help output:
* First line should read 'Create and manage Kubernetes ov vSphere'

**Comment by casualjim** [comment]
Issue moved to [vmware/kov #225](https://github.com/vmware/kov/issues/225) via [**ZenHub**](https://www.zenhub.com/)
