### ISSUE TITLE
DX recommendation: Show thumbprint

### ISSUE THREAD

**Issue by ali5ter** [vmware/vic-product#376]
Recommendations based on evaluation of version 3fef72f: https://confluence.eng.vmware.com/display/~bowena/kov+CLI+DX+evaluation#kovCLIDXevaluation-Recommendations

Provide explanation of how to get the thumbprint or generate it for user

**Comment by casualjim** [comment]
Issue moved to [vmware/kov #226](https://github.com/vmware/kov/issues/226) via [**ZenHub**](https://www.zenhub.com/)
