### ISSUE TITLE
Document OVA upgrade to 1.2

### ISSUE THREAD

**Issue by stuclem** [vmware/vic-product#377]
See https://github.com/vmware/vic/issues/5464 for automated upgrade.

**Comment by andrewtchin** [comment]
Redirecting to #384

**Comment by stuclem** [comment]
As confirmed by @andrewtchin, we won't support upgrading the Harbor 0.5 appliance (shipped with VIC 1.0) to 1.2.

**Comment by stuclem** [comment]
Per demo by @andrewtchin, the new upgrade procedure includes running a script on the appliance after the currently documented steps, as was the case for upgrading from Harbor 0.5 to VIC Registry 1.1.

**Comment by stuclem** [comment]
We must also document that after the upgrade, the VIC Registry address that appears in Management Portal at **Administration** > **Registries** is the old address. The user must edit the registry manually to insert the address of the new VIC appliance.

**Comment by andrewtchin** [comment]
The registry address that appears in the new Management Portal after upgrade is the migrated IP address, so if the IP address of the new appliance is different than that of the old appliance, the migrated IP address will no longer be valid as a registry. The user should delete the now invalid IP address listed as a registry. The Management Portal automatically adds as a registry the Harbor registry running on the appliance, so no action is needed from the user to add the new appliance IP as a registry.

**Comment by stuclem** [comment]
Thanks @andrewtchin
