### ISSUE TITLE
VIC Appliance OVA Deployment Single Host Failure 

### ISSUE THREAD

**Issue by codyde** [vmware/vic-product#395]
Deploying the VIC appliance OVA (vic-v1.1.1_56a309fb.ova) against a single host with no vCenter being used results in no prompt's for what network ports to use for the harbor and admiral services. This results in no ports being assigned during OVA deployment and the appliance being left not functional to pull down extract the VIC engine binaries. 

Neither the Admiral, Harbor, or Fileserver (9443 by default) are able to be browsed from a standard borwser. Screenshot of console UI is attached. 

![vic problem](https://user-images.githubusercontent.com/17350652/27566018-ea348928-5a96-11e7-85ca-d04785f6b3ce.PNG)

**Comment by andrewtchin** [comment]
Hi @codyde could you provide more details about how you deployed this OVA? Did you use `ovftool` or the ESXi web interface?

**Comment by codyde** [comment]
This is specifically leveraging the HTML5 browser directly on the host (https://hostiporfqdn/ui). I imagine OVFTool will work since you're able to "force" the properties that way but i havent tried it. Basically, the network port screens are missing; see the below 2 items for comparison. 

Flash Client Example (vCenter 6.5; working) - 
![java-port-exists](https://user-images.githubusercontent.com/17350652/27605877-dc8b91f8-5b32-11e7-8429-c5c4dededb74.JPG)
![java-port-exists2](https://user-images.githubusercontent.com/17350652/27605876-dc89d78c-5b32-11e7-9a05-547949c847bc.JPG)

HTML5 Client Example (ESXi 6.5; not working) - 
![html5 - port missing](https://user-images.githubusercontent.com/17350652/27605889-e24fe7b0-5b32-11e7-9677-08181fc315c7.JPG)
![html5 - port missing2](https://user-images.githubusercontent.com/17350652/27605888-e24dab4e-5b32-11e7-9b35-7a8d1bb223f3.JPG)

**Comment by andrewtchin** [comment]
The 1.1.1 build had an issue with being deployed directly on ESXi so if you have a vCenter, you can use the `vSphere Web Client (Flash)` to deploy the OVA.
I'm closing this as a known issue that has been resolved. Thank you for submitting this issue - please open a new issue if you find any other bugs.
