### ISSUE TITLE
Harbor and Admiral services should communicate via internal network on .ova

### ISSUE THREAD

**Issue by reasonerjt** [vmware/vic-product#419]
Harbor needs to call PMS API hosted on Admiral endpoint, and Admiral UI backend will wrap Harbor's API for UI to render registry related components.

Currently they communicate via the external IP, which works so far, but ideally they should communicate via an internal network.

In bootstrap it maybe possible to call "docker network create/connect" to address this issue.

**Comment by andrewtchin** [comment]
@reasonerjt what settings would we need to change so that harbor uses the internal network?

**Comment by reasonerjt** [comment]
add Harbor's `ui` container and `admiral` container to a network and they can communicate.

**Comment by andrewtchin** [comment]
Are there any configuration changes that need to be made?

**Comment by reasonerjt** [comment]
I think yes, see my previous comment, after starting the Harbor and admiral, the script on vic .ova can issue `docker network` commands to create a network and attach Harbor and admiral containers to it, so they can communicate via http in this internal network

**Comment by andrewtchin** [comment]
OK thanks what about anything in harbor.cfg or any other harbor config files?
@sergiosagu any changes for Admiral?

**Comment by reasonerjt** [comment]
@andrewtchin yep when attaching the containers to network you should assign aliases to the containers and then make according update in cfg file to point Harbor to the internal address of Admiral.

**Comment by sergiosagu** [comment]
@andrewtchin - Whether we use the external IP or the internal IP, the SSL settings should be OK (I mean the SSL certificate for the Harbor endpoint should be valid for the internal IP as well, if we use the hostname probably we're fine). Another thing to keep in mind is that the URL that Admiral uses to communicate with Harbor is visible in the UI, not sure if that really matters for this change though.
cc @lazarin

**Comment by lazarin** [comment]
- yep, the harbor certificate should be valid
- `harbor.tab.url` should contain the address to use when talking with harbor (/storage/data/admiral/configs/config.properties)

**Comment by morris-jason** [comment]
@reasonerjt @lazarin Can either of you confirm if `harbor.tab.url` is used to set the default-vic-registry in the Harbor Registry tab?

If so, we need to find a work around, because the registry url should remain the public ip/hostname of the appliance.

**Comment by lazarin** [comment]
Yes, the `default-vic-registry` is the value of the `harbor.tab.url` property. 

> Another thing to keep in mind is that the URL that Admiral uses to communicate with Harbor is visible in the UI, not sure if that really matters for this change though.

Probably the only workaround I see is passing hostname for `harbor.tab.url` and overwrite admiral container's hosts file to map the internal network ip. This however is not tests and may or may not have side effects.

**Comment by reasonerjt** [comment]
@lazarin Could Admiral just use two different properties?
One of them is for internal communication and the other is for setting `default-vic-registry` to point to external hostname?

**Comment by lazarin** [comment]
@reasonerjt I'm not getting fully the purpose for that change:

> Currently they communicate via the external IP, which works so far, but ideally they should communicate via an internal network.

Having setup with `harbor.tab.url=<some internal ip>` and `default-vic-registry=<external ip>` will still require admiral to access harbor with the external address when making image queries. 
What are the benefits of the internal network except that it's 'internal'?

**Comment by andrewtchin** [comment]
@lazarin I believe this is security related due to certificate validation between Harbor and Admiral. An alternative I have proposed is that since both Harbor and Admiral have access to the same TLS certificate on disk, the applications can simply verify that the remote they are communicating with is presenting that same certificate. This will avoid cert validation errors while maintaining secure communication when using auto generated certs.

**Comment by morris-jason** [comment]
@lazarin, @reasonerjt  I have a few questions:
>Having setup with harbor.tab.url=<some internal ip> and default-vic-registry=<external ip> will still require admiral to access harbor with the external address when making image queries.

Why is this the case?

What is the technical effort needed to separate these two options? 

As a follow up, why does admiral need to set the value for default-vic-registry? Can we purpose a change to have that option set in the harbor configuration instead?

**Comment by lazarin** [comment]
Thanks @andretchin, we can explore that
@morris-jason: `harbor.tab.url` was used from admiral to 'talk' with harbor - show harbor ui components, then there was a need to automatically create record for the harbor registry used in the appliance - default-vic-registry.
Now, when an image is requested, a query for it is sent to the existing registries, so what ever the address is set for the default-vic-registry, it will be used. Then when sending commands to docker remote api this address is used and the docker host should be able to contact it. That means there's still a need for connecting harbor through the external network

**Comment by andrewtchin** [comment]
@lazarin Everything you've mentioned so far is Admiral -> Harbor communication. Is there any Harbor -> Admiral connection?

**Comment by morris-jason** [comment]
Even with `harbor.tab.url` set to an internal hostname, the `registry_url` from `/api/systeminfo` returns the external ip. Why not use that for image queries?

**Comment by reasonerjt** [comment]
@andrewtchin There are cases that Harbor will connect Admiral, for example decoding token.

@morris-jason If you want to connect to harbor-ui container directly, please use port `8080`

**Comment by andrewtchin** [comment]
Closing as Admiral and Harbor will implement certificate pinning

Golang example:
http://www.hydrogen18.com/blog/your-own-pki-tls-golang.html
https://github.com/hydrogen18/test-tls

With both user provided and self generated certificates, we have the CA certificate so we can add that to the CertPool for the connection

https://tam7t.com/key-pinning-in-golang/
https://golang.org/pkg/crypto/tls/#ConnectionState
Another option is looking at ConnectionState.PeerCertificates and verifying that the remote presents the same server cert as we load from disk

Certificate location on the appliance is documented here https://github.com/vmware/vic-product/blob/master/installer/docs/DESIGN.md#security
