### ISSUE TITLE
PDF documentation makes strange use of section numbers

### ISSUE THREAD

**Issue by zjs** [vmware/vic-product#423]
Example: https://vmware.github.io/vic-product/assets/files/html/1.1/pdf/vic_11_vsphere_admin.pdf

The table of contents lists section name and section number, but not page number. Sections within the document do not include section numbers. This makes it difficult to navigate a printed copy.

I would suggest:
1. Including page numbers in the table of contents.
2. Including section numbers in the document body.

**Comment by stuclem** [comment]
@zjs thanks for spotting this. Very strange indeed. This definitely was not the case previously. The TOC should definitely use page numbers. I'll investigate what's up with Gitbook...

**Comment by stuclem** [comment]
@zjs it looks like this is a known issue with Gitbook: https://github.com/GitbookIO/gitbook/issues/507.

The issue above provides a workaround, but it'll require a bit of experimentation on my part.

**Comment by stuclem** [comment]
Moving this back to backlog.

**Comment by stuclem** [comment]
This is a bug in Gitbook. I don't think that we can do anything about this for 1.2

**Comment by stuclem** [comment]
See also https://github.com/GitbookIO/gitbook/issues/1223

**Comment by stuclem** [comment]
It seems that https://github.com/lwchkg/gitbook-pdfgen might resolve this issue.

**Comment by stuclem** [comment]
Changing the PDF generator might be a major faff. To be investigated after 1.4.3 GA.

**Comment by stuclem** [comment]
Looks like there's a gitbook plugin that could remedy this:
https://www.npmjs.com/package/gitbook-plugin-page-numbering

**Comment by stuclem** [comment]
The plug-in above does not fix the issue with the TOC numbering. It seems that this is a well-known issue with Gitbook. Solution is not straightforward. No one else has complained. Closing.
