### ISSUE TITLE
PDF documentation is available in A4 instead of letter

### ISSUE THREAD

**Issue by zjs** [vmware/vic-product#425]
Other VMware PDF documentation seems to be available in letter (perhaps because it's easy to print letter documents on A4 paper, but not vice versa ― especially at the font size the PDF is using for in-line monospace text).

**Comment by stuclem** [comment]
@zjs being European, it had never even occurred to me that this could be a problem! To confirm, printing letter docs on A4 doesn't seem to cause any problems. I had no idea that the opposite would be problematic. I will tinker with the Gitbook settings.

**Comment by stuclem** [comment]
Found that this is a setting in the Gitbook `book.json` file.
