### ISSUE TITLE
Recommendations about bridge network differ from section to section

### ISSUE THREAD

**Issue by zjs** [vmware/vic-product#426]
We give slightly different recommendations about the bridge network in different sections of the documentation:

> Do not use the bridge network for any other VM workloads, or as a bridge for more than one VCH.

https://vmware.github.io/vic-product/assets/files/html/1.1/vic_vsphere_admin/networks.html#bridge

> Do not share the bridge network interface with with any other network, unless you ensure that the bridge IP ranges do not conflict with other VCHs or VMs on that network. It is highly recommended that a bridge network be solely for use by only one VCH.

https://vmware.github.io/vic-product/assets/files/html/1.1/vic_vsphere_admin/vic_installation_prereqs.html#general_networkreqs

>Do not assign the same bridge-network port group to multiple VCHs. Sharing a port group between VCHs might result in multiple container VMs being assigned the same IP address.

https://vmware.github.io/vic-product/assets/files/html/1.1/vic_vsphere_admin/vch_installer_options.html#networking

This inconsistency is problematic in and of itself, but I think this is a symptom of a larger problem: networking information is fragmented across several sections, with overlap between the sections.

**Comment by stuclem** [comment]
@zjs, I agree. This situation can possibly be alleviated in the context of the consolidation of options descriptions/examples tracked in https://github.com/vmware/vic-product/issues/26.
