### ISSUE TITLE
"Use Different User Accounts for VCH Deployment and Operation" presents manual instructions for a process that could be automated

### ISSUE THREAD

**Issue by zjs** [vmware/vic-product#430]
[Use Different User Accounts for VCH Deployment and Operation](https://vmware.github.io/vic-product/assets/files/html/1.1/vic_vsphere_admin/set_up_ops_user.html) describes a lengthy, manual, error-prone process with steps like creating a 5 roles, with a 1-19 permissions each, or assigning those roles to specific inventory objects with specific propagation settings.

This seems like an incredibly painful hoop to make new customers jump through, and like something that could be at least partially automated. (E.g., by providing a sample script that could be used to perform these actions.)

**Comment by stuclem** [comment]
Hi @zjs I agree completely. However, unless things have changed greatly since 1.1, this doc reflects how the product is. As such, this isn't so much a doc issue as a feature request. I believe that this is already tracked in https://github.com/vmware/vic/issues/635, but @hickeng can confirm.

**Comment by zjs** [comment]
If solving this in the main product is hard (and based on vmware/vic#635, it looks like it is), I think partial automation could be provided via documentation. For example, perhaps someone could provide a short sequence of `govc` commands the user could run to achieve the same effect as performing these steps via the UI.

**Comment by stuclem** [comment]
@zjs that sounds like a good idea. @hickeng who could provide such `govc` commands?

**Comment by stuclem** [comment]
It looks like this is being addressed on the dev side in https://github.com/vmware/vic/issues/6492, but it's not obvious whether that will be in 1.3. Pending the implementation of https://github.com/vmware/vic/issues/6492, @lcastellano do you know what the govc commands that @zjs mentions might be? Thanks!

**Comment by stuclem** [comment]
Given that https://github.com/vmware/vic/issues/6033 is creating a service account for VCHs, this issue is quite probably redundant. 

@zjs and @lcastellano, given the work that is being done in 1.3 on `--ops-user` and the service account, do we still need to document manual `govc` commands to create the `--ops-user` account?

**Comment by zjs** [comment]
> given the work that is being done in 1.3 on --ops-user and the service account, do we still need to document manual govc commands to create the --ops-user account?

There's a longer explanation at https://github.com/vmware/vic-product/issues/930#issuecomment-337418522, but the short answer is that I don't think so.

**Comment by stuclem** [comment]
Thanks @zjs. I'll leave this one open, just in case, given your response in https://github.com/vmware/vic-product/issues/930#issuecomment-337418522.

**Comment by stuclem** [comment]
It looks like this work is going ahead in 1.3, so closing this one as it is now redundant.
