### ISSUE TITLE
VCH Deployment Options, Examples, and Help are presented in a disjointed way

### ISSUE THREAD

**Issue by zjs** [vmware/vic-product#431]
Understanding a the available deployment options, what they mean, and how to use them currently requires flipping through three different sources of information, with little interlinking: [VCH Deployment Options](https://vmware.github.io/vic-product/assets/files/html/1.1/vic_vsphere_admin/vch_installer_options.html), [Advanced Examples of Deploying a VCH](https://vmware.github.io/vic-product/assets/files/html/1.1/vic_vsphere_admin/vch_installer_examples.html) (and [Deploy a VCH to an ESXi Host with No vCenter Server](https://vmware.github.io/vic-product/assets/files/html/1.1/vic_vsphere_admin/deploy_vch_esxi.html) and [Deploy a VCH to a Basic vCenter Server Cluster](https://vmware.github.io/vic-product/assets/files/html/1.1/vic_vsphere_admin/deploy_vch_vcenter.html)), and `vic-machine`'s help output.

It might be helpful to de-duplicate information about a given topic. For example, it's not clear why we have an example of [specifying volume stores](https://vmware.github.io/vic-product/assets/files/html/1.1/vic_vsphere_admin/vch_installer_examples.html#volume-stores) separately from the examples in  the documentation about the [`--volume-store`](https://vmware.github.io/vic-product/assets/files/html/1.1/vic_vsphere_admin/vch_installer_options.html#datastore) option.

It would be helpful to organize related `vic-machine` arguments into groups.

As an alternate model, [`git help commit`](https://git-scm.com/docs/git-commit) provides a similar amount of information in a consolidated way: by describing the command, enumerating it's options, expanding on more complicated topics, and then giving examples.

As an even smaller, but still significant, change: `docker help create` sorts and vertically aligns option short names, long names, and descriptions, making the output much easier to skim.

**Comment by stuclem** [comment]
@zjs I agree completely. I already have https://github.com/vmware/vic-product/issues/26 open to try to address this. 

Can I close this one as a dup?
