### ISSUE TITLE
"Upgrade a VCH" section could explain how to check for NAT based port forwarding

### ISSUE THREAD

**Issue by zjs** [vmware/vic-product#432]
[Upgrade a VCH](https://vmware.github.io/vic-product/assets/files/html/1.1/vic_vsphere_admin/upgrade_vch.html) states that during upgrade "NAT based port forwarding is unavailable".

Oddly, this is the only place where the string "NAT based port forwarding" appears in the documentation. ("NAT" is mentioned in a few places, including the section on the [Public Network](https://vmware.github.io/vic-product/assets/files/html/1.1/vic_vsphere_admin/networks.html#public), but it's not obvious whether that's what this warning refers to.

It would be helpful to provide administrators with instructions for determining what workloads would be impacted by the unavailability of NAT based port forwarding.

**Comment by stuclem** [comment]
@hmahmood do you have any insight here? Thanks!

**Comment by hmahmood** [comment]
Basically "NAT based port forwarding" refers to ports that are exposed through the VCH (i.e. the docker host). Any container that is on a bridge network and uses `-p` with run/create to forward ports would be affected. Containers that are on container networks (i.e. "external" networks) are not affected.

**Comment by stuclem** [comment]
We have the information in https://github.com/vmware/vic-product/issues/432#issuecomment-355092700 above.

**Comment by stuclem** [comment]
@vidya-v I think that we have the required information for this one. Can you please take a look?
