### ISSUE TITLE
Admiral startup service failed during VIC 1.2 Upgrade process- "keytool error: java.lang.Exception: Certificate not imported

### ISSUE THREAD

**Issue by singhshwetaQE** [vmware/vic-product#447]
Issue is happening due to existing certificate from install and while upgrade it's trying to install certificate again.

Admiral startup service log:

Starting Admiral Startup Configuration...
localhost.localdomain bash[706]: Signature ok
localhost.localdomain bash[706]: subject=/C=US/ST=California/L=Palo Alto/O=VMware/OU=Containers on vSphere/CN=10.160.188.174
localhost.localdomain bash[706]: Getting CA Private Key
localhost.localdomain bash[706]: unable to write 'random state'
localhost.localdomain bash[706]: Copy CA certificate to /data/admiral/ca_download
localhost.localdomain bash[706]: creating java keystore with self-signed CA
localhost.localdomain bash[706]: keytool error: java.lang.Exception: Certificate not imported, alias already exists
localhost.localdomain bash[706]: java.lang.Exception: Certificate not imported, alias already exists
localhost.localdomain bash[706]: at sun.security.tools.keytool.Main.addTrustedCert(Main.java:2647)
localhost.localdomain bash[706]: at sun.security.tools.keytool.Main.doCommands(Main.java:1009)
localhost.localdomain bash[706]: at sun.security.tools.keytool.Main.run(Main.java:343)
localhost.localdomain bash[706]: at sun.security.tools.keytool.Main.main(Main.java:336)
localhost.localdomain systemd[1]: admiral_startup.service: Main process exited, code=exited, status=1/FAILURE
localhost.localdomain systemd[1]: Failed to start Admiral Startup Configuration.
localhost.localdomain systemd[1]: admiral_startup.service: Unit entered failed state.
localhost.localdomain systemd[1]: admiral_startup.service: Failed with result 'exit-code'.

============================================================
Refer to code : https://github.com/vmware/vic-product/blob/master/installer/packer/scripts/admiral/configure_admiral.sh

line no 91-93
echo "creating java keystore with self-signed CA"
$javadir/keytool -import -noprompt -v -trustcacerts -alias selfsignedca -file $ca_cert -keystore $jks -keypass changeit -storepass changeit
}

=================================================================

**Comment by andrewtchin** [comment]
Keystore is persisted after upgrade so `configure_admiral.sh` needs to check if there is a cert already present before attempting to generate self signed certs. 
` keytool -list -v -keystore /data/admiral/cert/trustedcertificates.jks`

**Comment by andrewtchin** [comment]
Actually the full log shows we're trying to regenerate the self signed certificate because `cert_gen_type` isn't present since it's in `/etc/vmware/admiral` so we need to determine if we should be regenerating and clear the keystore before doing so

```
root@localhost [ ~ ]# journalctl -u admiral_startup
-- Logs begin at Wed 2017-07-19 20:15:39 UTC, end at Thu 2017-07-20 19:09:29 UTC. --
Jul 19 21:09:04 localhost.localdomain systemd[1]: Starting Admiral Startup Configuration...
Jul 19 21:09:04 localhost.localdomain bash[706]: Hostname is null, set it to IP
Jul 19 21:09:04 localhost.localdomain bash[706]: The file which records the way generating certificate does not exist, will generate a new self-signed certificate
Jul 19 21:09:04 localhost.localdomain bash[706]: Generating a 4096 bit RSA private key
Jul 19 21:09:04 localhost.localdomain bash[706]: .....................++
Jul 19 21:09:04 localhost.localdomain bash[706]: ......................................................................................................++
Jul 19 21:09:04 localhost.localdomain bash[706]: writing new private key to '/data/admiral/cert/server.key'
Jul 19 21:09:04 localhost.localdomain bash[706]: -----
Jul 19 21:09:04 localhost.localdomain bash[706]: Add subjectAltName = IP: 10.160.188.174 to certificate
Jul 19 21:09:04 localhost.localdomain bash[706]: Signature ok
Jul 19 21:09:04 localhost.localdomain bash[706]: subject=/C=US/ST=California/L=Palo Alto/O=VMware/OU=Containers on vSphere/CN=10.160.188.174
Jul 19 21:09:04 localhost.localdomain bash[706]: Getting CA Private Key
Jul 19 21:09:04 localhost.localdomain bash[706]: unable to write 'random state'
Jul 19 21:09:04 localhost.localdomain bash[706]: Copy CA certificate to /data/admiral/ca_download
Jul 19 21:09:04 localhost.localdomain bash[706]: creating java keystore with self-signed CA
Jul 19 21:09:05 localhost.localdomain bash[706]: keytool error: java.lang.Exception: Certificate not imported, alias <selfsignedca> already exists
Jul 19 21:09:05 localhost.localdomain bash[706]: java.lang.Exception: Certificate not imported, alias <selfsignedca> already exists
Jul 19 21:09:05 localhost.localdomain bash[706]: at sun.security.tools.keytool.Main.addTrustedCert(Main.java:2647)
Jul 19 21:09:05 localhost.localdomain bash[706]: at sun.security.tools.keytool.Main.doCommands(Main.java:1009)
Jul 19 21:09:05 localhost.localdomain bash[706]: at sun.security.tools.keytool.Main.run(Main.java:343)
Jul 19 21:09:05 localhost.localdomain bash[706]: at sun.security.tools.keytool.Main.main(Main.java:336)
Jul 19 21:09:05 localhost.localdomain systemd[1]: admiral_startup.service: Main process exited, code=exited, status=1/FAILURE
Jul 19 21:09:05 localhost.localdomain systemd[1]: Failed to start Admiral Startup Configuration.
Jul 19 21:09:05 localhost.localdomain systemd[1]: admiral_startup.service: Unit entered failed state.
Jul 19 21:09:05 localhost.localdomain systemd[1]: admiral_startup.service: Failed with result 'exit-code'.
```
