### ISSUE TITLE
Document ESX firewall configuration mechanism

### ISSUE THREAD

**Issue by stuclem** [vmware/vic-product#45]
_From @stuclem on February 21, 2017 15:39_

Per https://github.com/vmware/vic/issues/3979. 

_Copied from original issue: vmware/vic#3991_

**Comment by stuclem** [comment]
See also https://github.com/vmware/vic/issues/3801, specifically about VIBs.

**Comment by stuclem** [comment]
See also https://github.com/vmware/vic/issues/3927 and https://github.com/vmware/vic/issues/3643

**Comment by stuclem** [comment]
Looks like https://github.com/vmware/vic/issues/3979 has priority over the VIB idea.

**Comment by stuclem** [comment]
_From @andrewtchin on March 7, 2017 19:9_

```
### vic-machine update firewall
                                                                                                         
The `vic-machine update firewall` command can be used to modify the firewall on the ESXi host or the ESXi hosts in a cluster. 

With the flags `--allow` and `--deny` this tool enables and disables the ruleset "vSPC", respectively. When enabled, "vSPC" rule allows all outbound TCP traffic from the target host or hosts. If the rule is disabled, the firewall must be configured via another method to allow outbound 2377/tcp or VIC Engine will not function.

The firewall is not modified by `vic-machine create` or `vic-machine delete`. This command may be used before `vic-machine create` and after `vic-machine delete` to configure the firewall. 

To enable the rule, which permits all outbound TCP traffic from the host, use `--allow`:
<pre>vic-machine-<i>operating_system</i> update firewall
--target 'Administrator@vsphere.local':<i>password</i>@<i>vcenter_server_address</i>/dc1
--compute-resource cluster1
--thumbprint=<i>thumbprint</i>
--allow
</pre>

To disable the rule, use `--deny`:
<pre>vic-machine-<i>operating_system</i> update firewall
--target 'Administrator@vsphere.local':<i>password</i>@<i>vcenter_server_address</i>/dc1
--compute-resource cluster1
--thumbprint=<i>thumbprint</i>
--deny
</pre>
```

Also update https://github.com/vmware/vic/blob/master/doc/user_doc/vic_installation/ts_firewall_error.md

**Comment by stuclem** [comment]
There is an ongoing discussion in https://github.com/vmware/vic/pull/4165 about whether this should be `vic-machine infra` or `vic-machine update`.

**Comment by stuclem** [comment]
_From @andrewtchin on March 8, 2017 17:48_

Updated the above to reflect use of `vic-machine update`

**Comment by stuclem** [comment]
PR https://github.com/vmware/vic/pull/4165 is merged. This didn't make it into 0.9.

**Comment by stuclem** [comment]
Incidentally, the configuration does not persist through a host reboot.

**Comment by andrewtchin** [comment]
On my fusion ESXi and other systems I used during testing it seems to persist

**Comment by stuclem** [comment]
Added `vic-machine-windows update firewall` to the TS topic on the firewall error.
