### ISSUE TITLE
Document that H5 plugin requires vSphere 6.5.0d as a minimum

### ISSUE THREAD

**Issue by stuclem** [vmware/vic-product#467]
Per conversation with @jooskim, in order for the H5 to work correctly, you need at least vSphere 6.5.0d. Earlier versions result in the Summary, VCHs and Containers tabs showing up empty.

**Comment by jooskim** [comment]
I feel that any version higher than 6.5.0 GA should be able to run the plugins fine but I'm okay with stating 6.5.0d as minimum. Actually that will save us from potential troubles.
