### ISSUE TITLE
Remove the registry reference on landing page of ova

### ISSUE THREAD

**Issue by ywk253100** [vmware/vic-product#480]
Harbor can't be accessed directly in ova, so the reference on the landing page should be removed.
```
Access the Container Registry at: 
https://ip:443
```

**Comment by andrewtchin** [comment]
This is done in master a few days ago, you'll see it when we have a new OVA

**Comment by anchal-agrawal** [comment]
Fixed in https://github.com/vmware/vic-product/pull/489.
