### ISSUE TITLE
Document how to encrypt container configuration

### ISSUE THREAD

**Issue by stuclem** [vmware/vic-product#497]
@stuclem commented on [Tue May 31 2016](https://github.com/vmware/vic/issues/875)

Per https://github.com/vmware/vic/issues/475. This might not get implemented.

---

@stuclem commented on [Fri Jun 03 2016](https://github.com/vmware/vic/issues/875#issuecomment-223610097)

https://github.com/vmware/vic/issues/475 is in the icebox, so moving this one there too.

---

@stuclem commented on [Wed Dec 14 2016](https://github.com/vmware/vic/issues/875#issuecomment-267083981)

https://github.com/vmware/vic/issues/475 is still in the Icebox with no milestone, so leaving this doc issue in icebox too.

**Comment by stuclem** [comment]
Doesn't look like this is in 1.3.

**Comment by zjs** [comment]
Closing as vmware/vic#475 has been closed.
