### ISSUE TITLE
Document the VCH config log bundle

### ISSUE THREAD

**Issue by stuclem** [vmware/vic-product#498]
@stuclem commented on [Thu Aug 04 2016](https://github.com/vmware/vic/issues/1806)

Per https://github.com/vmware/vic/issues/1366. This appears to be in addition to the other logs on vicadmin. We need to doc how to find and interpret it.

---

@stuclem commented on [Wed Sep 21 2016](https://github.com/vmware/vic/issues/1806#issuecomment-248571142)

https://github.com/vmware/vic/issues/1366 is now in the icebox.

---

@stuclem commented on [Wed Dec 14 2016](https://github.com/vmware/vic/issues/1806#issuecomment-267073456)

https://github.com/vmware/vic/issues/1366  is still in the Icebox with no milestone, so leaving this doc issue in icebox too.

**Comment by stuclem** [comment]
Doesn't look like this is in 1.3.

**Comment by stuclem** [comment]
Not in 1.4.x

**Comment by zjs** [comment]
Closing as vmware/vic#1366 has been closed.
