### ISSUE TITLE
Document that volume store must either be specified explicitly or disabled

### ISSUE THREAD

**Issue by stuclem** [vmware/vic-product#503]
@stuclem commented on [Thu Nov 10 2016](https://github.com/vmware/vic/issues/3091)

Per whatever the final conclusion is to the debate in https://github.com/vmware/vic/issues/2899. That issue is in the icebox but might come out of it.

**Comment by stuclem** [comment]
Doesn't look like this is in 1.3.

**Comment by stuclem** [comment]
Not in 1.4.x

**Comment by zjs** [comment]
Closing as vmware/vic#2899 was closed.
