### ISSUE TITLE
Document per personality labels

### ISSUE THREAD

**Issue by stuclem** [vmware/vic-product#504]
@stuclem commented on [Thu Sep 22 2016](https://github.com/vmware/vic/issues/2429)

Per https://github.com/vmware/vic/issues/2424

---

@stuclem commented on [Fri Nov 11 2016](https://github.com/vmware/vic/issues/2429#issuecomment-259990739)

https://github.com/vmware/vic/issues/2424 is in the icebox.

**Comment by stuclem** [comment]
Not in 1.3.

**Comment by stuclem** [comment]
Not in 1.4.x.

**Comment by zjs** [comment]
Closing as vmware/vic#2424 was closed.
