### ISSUE TITLE
Document docker swarm

### ISSUE THREAD

**Issue by stuclem** [vmware/vic-product#507]
@stuclem commented on [Thu Nov 24 2016](https://github.com/vmware/vic/issues/3309)

Per https://github.com/vmware/vic/issues/2943.

---

@stuclem commented on [Wed Dec 14 2016](https://github.com/vmware/vic/issues/3309#issuecomment-267078954)

https://github.com/vmware/vic/issues/2943  is still in the Icebox with no milestone, so leaving this doc issue in icebox too.

**Comment by stuclem** [comment]
It seems that Docker swarm is possible if you use dch-photon, per https://github.com/vmware/vic-product/tree/master/tutorials/dch-swarm.

@pdaigle is this something that we want to add to the core docs?

**Comment by stuclem** [comment]
Added links to @pdaigle 's blog about implementing Swarm through `dch-photon` as a short-term fix. To be documented properly in 1.3.

**Comment by stuclem** [comment]
We provide a link to an existing document on this, so marking as medium. Ideally, we should include this in the docs on using `dch-photon`.

**Comment by stuclem** [comment]
To be addressed in the next major release.

**Comment by zjs** [comment]
Closing as vmware/vic#2943 has been closed.
