### ISSUE TITLE
No way to download vic-machine binaries from latest OVA

### ISSUE THREAD

**Issue by shadjiiski** [vmware/vic-product#516]
After deploying the latest OVA, I navigated to the getting started page (https://[host]:9443) and entered my vCenter info and credentials when prompted. Then I tried to download the bundled vic-machine binaries by using the links provided:
![image](https://user-images.githubusercontent.com/4493115/28965748-533cb2cc-791b-11e7-8d01-5f69f00fc929.png)

1. The *Download the vSphere Integrated Containers Engine bundle* link opens **[host]:9443/#** in a new tab and prompts for vCenter address and credentials again. After dismissing the window, no download starts.
1. The *Download* link in the lower left does nothing
1. The *Read more* link leads to the documentation which tells me that I should be able to download vic-machine binaries from the previous page ([host]:9443)

OVA used: https://storage.googleapis.com/vic-product-ova-builds/vic-28d18602-dev-2.ova (from 03 Aug)

**Comment by anchal-agrawal** [comment]
@shadjiiski Please access `https://$host:9443/files` directly - see https://github.com/vmware/vic-product/issues/482.

Closing as dup of #482.
