### ISSUE TITLE
Admiral data does not survive container restart

### ISSUE THREAD

**Issue by lazarin** [vmware/vic-product#520]
Currently (vic-28d18602-dev-2.ova) is configured without mounted volume for data, and the admiral.service is removing the container in case it is stopped or crashed and deploying it again from image.

That means that if the machine is restarted, powered off (power outage, etc..) all the admiral data will be lost.

**Comment by anchal-agrawal** [comment]
@lazarin Would supplying an additional mount `-v $ADMIRAL_DATA_LOCATION:/<saved_data_dir_in_container>` be sufficient? If so, please tell us what the name of the directory in the container should be. `$ADMIRAL_DATA_LOCATION=/data/admiral` on the OVA host here.

**Comment by anchal-agrawal** [comment]
Per @lazarin:
> The storage path is defined by property ADMIRAL_STORAGE_PATH=/var/admiral/

**Comment by lazarin** [comment]
Yes, mounting such volume will preserve the xenon storage with container recreation.
