### ISSUE TITLE
The installer has to import the Harbor SSL certificate into the Admiral trust store as part of the post installation procedure

### ISSUE THREAD

**Issue by martin-borisov** [vmware/vic-product#531]
Admiral has to accept the SSL certificate from Harbor when Harbor is configured to communicate over HTTPS.
The OVA has to import the Harbor SSL certificate into the Admiral trust store as part of the post installation procedure and Admiral will automatically accept it.

**Comment by andrewtchin** [comment]
@martin-borisov Does that mean another statement like this https://github.com/vmware/vic-product/blob/master/installer/packer/scripts/admiral/configure_admiral.sh#L115 with the Harbor CA cert?

**Comment by lazarin** [comment]
Yes, that should be enough

**Comment by andrewtchin** [comment]
@martin-borisov @lazarin does it matter what the alias is?

**Comment by lazarin** [comment]
@andrewtchin Alias doesn't matter for admiral

**Comment by andrewtchin** [comment]
@martin-borisov @lazarin is this required for admiral to startup? Can we defer until 1.3? This would be much cleaner once https://github.com/vmware/vic/issues/5640 is done

**Comment by lazarin** [comment]
It won't prevent admiral to start, but then it won't be able to talk to harbor. It's a security stuff and the cert is a required for ssl communication with harbor

**Comment by martin-borisov** [comment]
@andrewtchin, this is required for 1.2 since the communication with the Harbor API is done over HTTPS.

**Comment by andrewtchin** [comment]
@martin-borisov @lazarin For what reason does Admiral not recognize certs that are added to the keystore during runtime? Systems I've seen in the past query the keystore at time of use so that they can recognize updated trusted certs.

**Comment by martin-borisov** [comment]
@andrewtchin We rely on a trust store manager based on the standard JVM libraries. Dynamic reloading of the trust store is not supported at this point in time and is currently not on the roadmap.
