### ISSUE TITLE
OVA DHCP misconfiguration when using static IP

### ISSUE THREAD

**Issue by lgayatri** [vmware/vic-product#549]
Build: https://storage.googleapis.com/vic-product-ova-builds/vic-b5fc5989-dev.ova
Post deployment with static IP and 9443 configuration, admiral service did not start for me.  So filed: https://github.com/vmware/vic-product/issues/548
On deeper investigation, I saw below file:
root@vic-st-h2-132 [ /etc/systemd/network ]# cat 10-dhcp-en.network
[Match]
Name=e*

[Network]
DHCP=yes

As the DHCP flag is turned to yes and Match name starts with e* even eth0 seeks to get additional DHCP address which is why two IPs are written to 
 cat  /data/admiral/cert/extfile.cnf
subjectAltName = IP:10.197.37.132
10.197.36.248

Admiral expects exactly one IP address here and seeing the second IP, the service exits.  Please consider this fix has high priority.

**Comment by anchal-agrawal** [comment]
@pdaigle also encountered this on his setup.

**Comment by lgayatri** [comment]
journalctl says:
Aug 10 10:48:39 vic-st-h2-132.eng.vmware.com systemd[1]: Time has been changed
Aug 10 10:48:57 vic-st-h2-132.eng.vmware.com start_fileserver.sh[603]: time="2017-08-10T10:48:57Z" level=info msg="server URL: vic-st-h2-191.eng.vmware.com\n"
Aug 10 10:48:57 vic-st-h2-132.eng.vmware.com start_fileserver.sh[603]: time="2017-08-10T10:48:57Z" level=info msg="Validation succeeded"
Aug 10 10:49:06 vic-st-h2-132.eng.vmware.com start_fileserver.sh[603]: time="2017-08-10T10:49:06Z" level=info msg="Successfully registered harbor with PSC"
Aug 10 10:49:09 vic-st-h2-132.eng.vmware.com start_fileserver.sh[603]: time="2017-08-10T10:49:09Z" level=info msg="Successfully registered engine with PSC"
Aug 10 10:49:17 vic-st-h2-132.eng.vmware.com systemd[1]: Starting Admiral Startup Configuration...
Aug 10 10:49:17 vic-st-h2-132.eng.vmware.com dbus[236]: [system] Activating via systemd: service name='org.freedesktop.hostname1' unit='dbus-org.freedesktop.hostname1.service'
Aug 10 10:49:17 vic-st-h2-132.eng.vmware.com systemd[1]: Starting Hostname Service...
Aug 10 10:49:17 vic-st-h2-132.eng.vmware.com dbus[236]: [system] Successfully activated service 'org.freedesktop.hostname1'
Aug 10 10:49:17 vic-st-h2-132.eng.vmware.com systemd[1]: Started Hostname Service.
Aug 10 10:49:17 vic-st-h2-132.eng.vmware.com bash[703]: Get hostname from command 'hostnamectl status --static': vic-st-h2-132.eng.vmware.com
Aug 10 10:49:17 vic-st-h2-132.eng.vmware.com bash[703]: Hostname: vic-st-h2-132.eng.vmware.com
Aug 10 10:49:17 vic-st-h2-132.eng.vmware.com start_fileserver.sh[603]: time="2017-08-10T10:49:17Z" level=info msg="Successfully registered admiral with PSC"
Aug 10 10:49:17 vic-st-h2-132.eng.vmware.com start_fileserver.sh[603]: time="2017-08-10T10:49:17Z" level=info msg="render: html/index.html"
Aug 10 10:49:17 vic-st-h2-132.eng.vmware.com start_fileserver.sh[603]: time="2017-08-10T10:49:17Z" level=info msg="render: /opt/vmware/fileserver/html/index.html"
Aug 10 10:49:18 vic-st-h2-132.eng.vmware.com start_fileserver.sh[603]: time="2017-08-10T10:49:18Z" level=info msg="render: html/index.html"
Aug 10 10:49:18 vic-st-h2-132.eng.vmware.com start_fileserver.sh[603]: time="2017-08-10T10:49:18Z" level=info msg="render: /opt/vmware/fileserver/html/index.html"
Aug 10 10:49:18 vic-st-h2-132.eng.vmware.com start_fileserver.sh[603]: time="2017-08-10T10:49:18Z" level=info msg="render: html/index.html"
Aug 10 10:49:18 vic-st-h2-132.eng.vmware.com start_fileserver.sh[603]: time="2017-08-10T10:49:18Z" level=info msg="render: /opt/vmware/fileserver/html/index.html"
Aug 10 10:49:18 vic-st-h2-132.eng.vmware.com start_fileserver.sh[603]: time="2017-08-10T10:49:18Z" level=info msg="render: html/index.html"
Aug 10 10:49:18 vic-st-h2-132.eng.vmware.com start_fileserver.sh[603]: time="2017-08-10T10:49:18Z" level=info msg="render: /opt/vmware/fileserver/html/index.html"
Aug 10 10:49:18 vic-st-h2-132.eng.vmware.com start_fileserver.sh[603]: time="2017-08-10T10:49:18Z" level=info msg="render: html/index.html"
Aug 10 10:49:18 vic-st-h2-132.eng.vmware.com start_fileserver.sh[603]: time="2017-08-10T10:49:18Z" level=info msg="render: /opt/vmware/fileserver/html/index.html"
Aug 10 10:49:18 vic-st-h2-132.eng.vmware.com bash[703]: CA, Certificate or key file does not exist, will generate a self-signed certificate
Aug 10 10:49:18 vic-st-h2-132.eng.vmware.com bash[703]: Generating a 4096 bit RSA private key
Aug 10 10:49:18 vic-st-h2-132.eng.vmware.com bash[703]: ........................................................................................................++
Aug 10 10:49:19 vic-st-h2-132.eng.vmware.com bash[703]: .............................................................................................................................................
............................................................++
Aug 10 10:49:19 vic-st-h2-132.eng.vmware.com bash[703]: writing new private key to '/data/admiral/cert/ca.key'
Aug 10 10:49:19 vic-st-h2-132.eng.vmware.com bash[703]: -----
Aug 10 10:49:19 vic-st-h2-132.eng.vmware.com bash[703]: Generating a 4096 bit RSA private key
Aug 10 10:49:21 vic-st-h2-132.eng.vmware.com bash[703]: .............................................................................................................................................
......................................................................................................................++
Aug 10 10:49:21 vic-st-h2-132.eng.vmware.com bash[703]: ....................................................++
Aug 10 10:49:21 vic-st-h2-132.eng.vmware.com bash[703]: writing new private key to '/data/admiral/cert/server.key'
Aug 10 10:49:21 vic-st-h2-132.eng.vmware.com bash[703]: -----
Aug 10 10:49:21 vic-st-h2-132.eng.vmware.com bash[703]: Add subjectAltName = IP: 10.197.37.132
Aug 10 10:49:21 vic-st-h2-132.eng.vmware.com bash[703]: 10.197.36.248 to certificate
Aug 10 10:49:21 vic-st-h2-132.eng.vmware.com bash[703]: error on line 2 of config file '/data/admiral/cert/extfile.cnf'
Aug 10 10:49:21 vic-st-h2-132.eng.vmware.com bash[703]: unable to write 'random state'
Aug 10 10:49:21 vic-st-h2-132.eng.vmware.com systemd[1]: admiral_startup.service: Main process exited, code=exited, status=1/FAILURE
Aug 10 10:49:21 vic-st-h2-132.eng.vmware.com systemd[1]: Failed to start Admiral Startup Configuration.
Aug 10 10:49:21 vic-st-h2-132.eng.vmware.com systemd[1]: admiral_startup.service: Unit entered failed state.
Aug 10 10:49:21 vic-st-h2-132.eng.vmware.com systemd[1]: admiral_startup.service: Failed with result 'exit-code'.
Aug 10 10:49:24 vic-st-h2-132.eng.vmware.com sshd[700]: Accepted keyboard-interactive/pam for root from 10.197.37.90 port 50915 ssh2
