### ISSUE TITLE
OVA  - Disable login button once you click on it

### ISSUE THREAD

**Issue by karthik-narayan** [vmware/vic-product#555]
With my setup running on onecloud, it can be slow at times. When I put in my creds and click the "Login" button, it takes a few seconds at which point I keep clicking the button multiple times. 

When the login button is clicked once, it should be disabled until response to that click is received.

**Comment by ali5ter** [comment]
As mentioned in #567...

The original mocks I delivered used a Clarity spinner in the dialog (see image)
![screen shot 2017-08-14 at 2 56 45 pm](https://user-images.githubusercontent.com/265869/29286706-f4f13c90-8100-11e7-8c7b-3d39bbfb13b6.png)

InVision link to specific mockups: https://vmware.invisionapp.com/share/QYD37KV84

Link to the InVision project that contains these mocks: https://vmware.invisionapp.com/share/9ABZ94N57

**Note: That the designs show a Continue button not a Login button. The point is that you are continuing with the VIC appliance installation.**

**Comment by ali5ter** [comment]
This looks like a dupe of #567
