### ISSUE TITLE
Add some progress/activity indication after first login to appliance

### ISSUE THREAD

**Issue by stuclem** [vmware/vic-product#567]
When you first go to https://**vic-appliance-address**:9443 and enter the vCenter Server credentials, the only indication that anything is happening is the Connecting... message in the browser tab.

![login](https://user-images.githubusercontent.com/16718369/29269954-9d881700-80f4-11e7-8ba2-61d581a034a9.png)

It would be nice if there were some indication in the login screen to indicate that the login/configuration is in progress.

**Comment by stuclem** [comment]
Related to https://github.com/vmware/vic-product/issues/554, but not exactly the same.

**Comment by andrewtchin** [comment]
@ali5ter @lweitzman Could you comment? We were thinking of putting a spinner to the left of the login button

**Comment by ali5ter** [comment]
The original mocks I delivered used a Clarity spinner in the dialog (see image)
![screen shot 2017-08-14 at 2 56 45 pm](https://user-images.githubusercontent.com/265869/29286706-f4f13c90-8100-11e7-8c7b-3d39bbfb13b6.png)

InVision link to specific mockups: https://vmware.invisionapp.com/d/main#/projects/boards/5321651/162480836

Link to the InVision project that contains these mocks: https://vmware.invisionapp.com/share/9ABZ94N57

**Comment by mdubya66** [comment]
not a stopper for 1.2. feature as well, so medium
