### ISSUE TITLE
Improve "Deploy a VCH" heading in Getting Started page

### ISSUE THREAD

**Issue by stuclem** [vmware/vic-product#568]
I'm not sure that the difference between the **Deploy a VCH** and **Deploy a Demo VCH** headings is sufficiently clear.

![deploy_vch](https://user-images.githubusercontent.com/16718369/29270206-e8d585c0-80f5-11e7-9e55-ec10d8703fab.png)

Could we change **Deploy a VCH** to **Deploy Production VCHs**, or something similar, just to make it 100% apparent that we're talking about two different things?

@ali5ter and @lweitzman what do you think?

**Comment by andrewtchin** [comment]
Please also comment on #551  as it is related

**Comment by ali5ter** [comment]
@stuclem I'm not completely opposed to this idea and very much agree with using consistent language for the demo VCH installer mentioned in #551.

Regarding the 2nd point: Out of the list that @morris-jason mentions, my vote is 'Demo VCH installer wizard' but I submit to @stuclem wordsmith'ing.

As to the first point: The vic-machine method (and the vSphere Plugin VCH wizard) do indeed allow you to stand up a production ready VCH but I don't think we can presume that's what the VCH will be. A vSphere Admin will almost definitely still be testing how to deploy and operate a VCH in their datacenter, and probably set up a sandbox env to test with a restricted set of users before designing a production level VCH.

If, we didn't use 'production' then what might be the opposite to 'demo'? If it's not obvious from the description below the title, then what would the title be? "Deploy a full VCH" as opposed to a limited (demonstration) VCH? Do we really need to qualify this if the description explains the difference?

**Comment by andrewtchin** [comment]
@stuclem @ali5ter @lweitzman So I'll change all references to be `Demo VCH Installer Wizard`. What was the conclusion for the Deploy a Demo VCH vs Deploy a VCH?

**Comment by stuclem** [comment]
@andrewtchin I updated https://github.com/vmware/vic-product/issues/551 to vote for **Demo VCH installer wizard**.

@ali5ter, I think that your comment "The vic-machine method (and the vSphere Plugin VCH wizard) do indeed allow you to stand up a production ready VCH" only applies to 1.3. In 1.2 the wizard is definitely for demo purposes only, and the vSphere plug-in wizard isn't there. So, in the Getting Started page for 1.2 (the subject of this issue), I think that we definitely need to make the distinction very clear.

Looking at the Getting Started page again now, I am now starting to think that the global layout is a bit confused/confusing. The white boxes contain links to tools whereas the bulleted lists are links to doc pages. For the VCH deployment links, we have two sets of two links with (almost) identical texts, one of which goes to the doc, the other of which goes to the tool. The white boxes also repeat those same doc links. So, I think that we can merge and consolidate this content into two sections: **Post-Installation & Deployment Tasks** and **vSphere Integrated Containers Management Portal**.

Below is a proposal. Each of the subheadings would be a white box.

-------

#  vSphere Integrated Containers Management Portal

Go to the vSphere Integrated Containers Management Portal to perform configuration tasks and to run container development projects.

## Configuration Tasks

**Cloud administrators** use the Management Portal to configure vSphere Integrated Containers, create development projects, manage registries, and manage users. 

**OPEN** | **[READ MORE](https://vmware.github.io/vic-product/assets/files/html/1.2/vic_cloud_admin/)** 

## Developer Tasks

**DevOps administrators** use the Management Portal to manage development projects. **Container application developers** use the Management Portal to see which projects they are assigned to and to obtain information about the resources that are available to those projects.

**OPEN** | **[READ MORE](https://vmware.github.io/vic-product/assets/files/html/1.2/vic_app_dev/)** 


-------

# Post-Installation & Deployment Tasks

Install the vSphere plug-ins and deploy and manage virtual container hosts (VCHs). These tasks are usually performed by the **vSphere administrator**. 

## Deploy a Demo VCH
Go to the demo VCH installer wizard to deploy a demo VCH. This VCH implements a limited set of features. It is for demonstration purposes only, to allow you to start experimenting with vSphere Integrated Containers. 

**INSTALLER**  |  **[READ MORE](https://vmware.github.io/vic-product/assets/files/html/1.2/vic_vsphere_admin/deploy_demo_vch.html)**

## Deploy a VCH with Full Functionality

Download the vSphere Integrated Containers Engine bundle. vSphere Integrated Containers Engine provides a command-line utility named vic-machine. The vic-machine utility allows you to implement the full set of features when deploying VCHs.

**DOWNLOAD**  |  **[READ MORE](https://vmware.github.io/vic-product/assets/files/html/1.2/vic_vsphere_admin/deploy_vch.html)**

## Install the vSphere Client Plug-Ins

vSphere Integrated Containers provides plug-ins for the vSphere Client that provide information about the VCHs and containers that are running in your virtual infrastructure. 

**[READ MORE](https://vmware.github.io/vic-product/assets/files/html/1.2/vic_vsphere_admin/install_vic_plugin.html)**


## Administrate VCHs

Use vic-machine to perform day-to-day administration of VCHs. 

**[READ MORE](https://vmware.github.io/vic-product/assets/files/html/1.2/vic_vsphere_admin/vch_admin.html)**

------

**Comment by ali5ter** [comment]
@stuclem digesting your content and will post a design shortly.
quick thoughts... 
* I like calling out 'Full Functionality' for deplying a non-demo VCH
* I wonder with the task cards if we've lost some value by not listing the tasks. I understand that this might be easier to maintain and assume the Read More links to the tasks in the documentation. Thoughts?

**Comment by stuclem** [comment]
Thanks @ali5ter.

The tasks/doc links currently listed under Post-Install & Deployment Tasks are all covered by the READ MORE links in each subheading under Post-Installation & Deployment Tasks in my version above (the READ MORE links in my proposal are live links that point to the relevant topics). So, for everything vSphere admin-related, we have the same doc links as currently, but without duplication and without having similarly worded links that point to both a tool/download and a doc.

But yes, my proposal does not include the links currently listed under Configuration Tasks (Add hosts, Create users, etc.).  The READ MORE links in my Configuration Tasks and Developer Tasks sections go to the top levels of the Cloud Admin and Developer docs respectively. I am trying to think of a way of providing more granular links.

**Comment by stuclem** [comment]
How about something like this?

-------

#  vSphere Integrated Containers Management Portal

Go to the vSphere Integrated Containers Management Portal to perform configuration tasks and to run container development projects.

## Configuration Tasks

**Cloud administrators** use the Management Portal to configure vSphere Integrated Containers, create development projects, manage registries, and manage users. 

**OPEN** 

**READ MORE**: [Configure](https://vmware.github.io/vic-product/assets/files/html/1.2/vic_cloud_admin/configure_registry.html)  |  [Create projects](http://localhost:4000/vic_cloud_admin/creating_projects_registry.html) | [Add Registries](https://vmware.github.io/vic-product/assets/files/html/1.2/vic_cloud_admin/configure_registry.html) | [Add Hosts](https://vmware.github.io/vic-product/assets/files/html/1.2/vic_cloud_admin/vchs_and_mgmt_portal.html) | [Manage Users](https://vmware.github.io/vic-product/assets/files/html/1.2/vic_cloud_admin/creating_users_registry.html)

## Developer Tasks

**DevOps administrators** use the Management Portal to manage development projects. **Container application developers** use the Management Portal to see which projects they are assigned to and to obtain information about the resources that are available to those projects.

**OPEN** 

**READ MORE**: [Manage Projects](https://vmware.github.io/vic-product/assets/files/html/1.2/vic_cloud_admin/manage_projects.html) | [Provision Containers](https://vmware.github.io/vic-product/assets/files/html/1.2/vic_app_dev/provision_containers_portal.html) | [Access VCH](https://vmware.github.io/vic-product/assets/files/html/1.2/vic_app_dev/obtain_vch.html)


-------

Incidentally, the links above will definitely have to change, as the reorg of the management portal and registry content resulting from the unified UI is still ongoing....

**Comment by ali5ter** [comment]
A couple of layouts to illustrate your content proposal @stuclem 
![screen shot 2017-08-17 at 9 43 10 am](https://user-images.githubusercontent.com/265869/29415276-89f89b22-8330-11e7-97d4-237307fe6941.png)

Again, I likes the direct guided approach to an ordered list of tasks to perform which appear in the original design.

We were careful not to declare roles in the previous design if you remember because not all users may understand what they mean or understand how they fit into such abstractions. However, we seem to be going down the road of organizing the docs using these roles (which is not a bad thing) so consistency wins here I think.

**Comment by andrewtchin** [comment]
Closing since we're going to remove demo vch
