### ISSUE TITLE
Management Portal still says "Admiral" in browser tab

### ISSUE THREAD

**Issue by stuclem** [vmware/vic-product#569]
In chin-vic-c2506807-dev-upgrade.ova the main title bar of the Management Portal now correctly includes **vSphere Integrated Containers**, but the text in the browser tab is still **Admiral**. Also, the favicon is the Clarity logo, rather than the VIC logo:

![admiral](https://user-images.githubusercontent.com/16718369/29270663-29eab89e-80f8-11e7-84a6-c6bc3546f10e.png)

**Comment by andrewtchin** [comment]
@stuclem can you reopen this is the Admiral repo and close this one?

**Comment by stuclem** [comment]
Issue moved to [vmware/admiral #168](https://github.com/vmware/admiral/issues/168) via [**ZenHub**](https://www.zenhub.com/)
