### ISSUE TITLE
Feature request:  OVA installed VM auto time synced on startup 

### ISSUE THREAD

**Issue by sflxn** [vmware/vic-product#580]
As a user of the OVA, I expect a vic-product VM deployed to self generate certificates to be fully time synced on start, even if my host VC is out of sync.

---

In a production environment, this is usually not an issue as admins probably have every server time sync'd as a checklist item.  For development and for evaluation purposes, if I deploy the OVA with self generated certs but my VC is not properly time sync'd, the cert generated by Harbor may not work.  If the vic product VM started up and was able to sync itself then the cert it generate would be fine.  This has bitten me with the 1.1.1 OVA.

It would also be great if the install UI presented the option to specify time server.

**Comment by zjs** [comment]
NTP is now configurable: #2232
