### ISSUE TITLE
Getting Started page: Fix UX of the 'initialize VIC App..' button

### ISSUE THREAD

**Issue by ali5ter** [vmware/vic-product#591]
Currently a Clarity outline button is displayed to the right of the Getting Started page title if the continued installation process from this page fails. (see image)

![screen shot 2017-08-17 at 11 29 11 am](https://user-images.githubusercontent.com/265869/29428740-451ccfe2-835c-11e7-8553-09de7b292d4c.png)

(Note: The Document button should be aligned to the right with a gutter of 24px from the right edge of the view-port and 24px under the header or alert component)

The correct interaction should be to show a Clarity alert, inform the user of the issue and offer the action to fix this issue in the alert. (see image)

![screen shot 2017-08-17 at 3 12 55 pm](https://user-images.githubusercontent.com/265869/29429418-a0d11dd2-835e-11e7-8bd8-fa14ea5f918c.png)

As a precaution, the Clarity flat button used in this alert should also appear at the bottom of the Getting Started page, in case there is any need (say a request from Support) for the vSphere Admin to restart the initialization again when the alert is not shown. (see image above)

Ref: Specific InVision mockups at https://vmware.invisionapp.com/share/QYD37KV84

cc: @andrewtchin @stuclem

**Comment by andrewtchin** [comment]
@ali5ter Could you also provide a mockup that includes the equivalent of the Initialize VIC Appliance button that's not in the Clarity alert? This functionality is required because this operation may be required later even if the initialization succeeds the first time.

**Comment by ali5ter** [comment]
In my earlier explanation there is a Clarity flat button at the bottom of the page. This is intended as a tertiary action.

**Comment by andrewtchin** [comment]
Tasks for this issue:
- [ ] Remove Initialize VIC Appliance button
- [ ] Add clarity alert with reinitialize link
- [ ] Add link at bottom to reinitialize

**Comment by ali5ter** [comment]
Clarity flat button for re-initializing the Appliance does not appear in the latest RC1 build

**Comment by jooskim** [comment]
by the way code is frozen now for 1.2

**Comment by andrewtchin** [comment]
@jooskim We can get this into master and pull it into the release branch for rc2 as I think this functionality is required

**Comment by jooskim** [comment]
@andrewtchin good to know. @cristianfalcone is now on it.

**Comment by andrewtchin** [comment]
Thanks amigos
