### ISSUE TITLE
'Getting Started' page: Icons not showing

### ISSUE THREAD

**Issue by ali5ter** [vmware/vic-product#593]
Clarity Icons on the Getting Started page are not showing up.

InVision link to specific mockups: https://vmware.invisionapp.com/share/QYD37KV84

Link to the InVision project that contains these mocks: https://vmware.invisionapp.com/share/9ABZ94N57

Clarity icons: https://vmware.github.io/clarity/documentation/iconography

**Comment by jooskim** [comment]
For some reason necessary JS files are missing from /opt/vmware/fileserver/ (see the screenshots below). FYI those files exist in the master branch of this repo. @morris-jason @andrewtchin @jialin-li 

![image](https://user-images.githubusercontent.com/3834071/29434225-c4e0ab62-8367-11e7-8e85-1a16549aadbf.png)

![image](https://user-images.githubusercontent.com/3834071/29434249-dc692c3c-8367-11e7-9f62-ae2a1178f8cc.png)

**Comment by morris-jason** [comment]
Are you using the latest build? I fixed this yesterday in #581

**Comment by jooskim** [comment]
Regarding the console error above, the server returns the content of the `index.html` instead of returning a 404 error state. This is another bug to be resolved.

**Comment by jooskim** [comment]
@morris-jason just found that issue. did not know it was closed. yeah i haven't had a chance to deploy any latest ova, but it's good that it got resolved. thanks!
