### ISSUE TITLE
Move doc about restarting VC client services into a separate topic

### ISSUE THREAD

**Issue by stuclem** [vmware/vic-product#604]
Because of https://github.com/vmware/vic-product/issues/554, we need to move the docs about restarting the VC client services out of the install/upgrade plugins topics and into a topic of their own.

**Comment by jooskim** [comment]
I noticed that this has release label `VIC Product 1.2 Docs`, but the feature (automated UI plugin installation) will actually be implemented in 1.3. Should this be relabeled?

**Comment by stuclem** [comment]
This is for 1.3. Removing from the 1.2 release and sending back to Not Ready.

**Comment by stuclem** [comment]
Restarting services is already documented as a standalone topic:
https://vmware.github.io/vic-product/assets/files/html/1.3/vic_vsphere_admin/restart_services.html

It is still included in the procedures for installing/upgrading UI, but I will remove those steps as/when the procedure changes. Am pretty sure that automatic installation of UI plugin is not in 1.3.
