### ISSUE TITLE
Update links in Getting Started page

### ISSUE THREAD

**Issue by stuclem** [vmware/vic-product#605]
@jooskim and @andrewtchin, I have done some reorganization of the docs that means that some of the links on the Getting Started page are now broken.

We need to update the following links:

**2. Add hosts to the manage the management portal** The link is OK but the text should be **2. Add hosts to the management portal**.
**4. Create users** should be **4. Add users**, and the link should be https://vmware.github.io/vic-product/assets/files/html/1.2/vic_cloud_admin/add_users.html
**5. Create projects** link should be https://vmware.github.io/vic-product/assets/files/html/1.2/vic_cloud_admin/create_projects.html

Apologies for the extra work, but the unification of the Registry and Management Portal UIs made it necessary to move and rename certain topics.

**Comment by jooskim** [comment]
Pinging also @jak-atx @cristianfalcone

**Comment by mdubya66** [comment]
making high. stopper for 1.2
