### ISSUE TITLE
Have a common suffix between admiral,harbor and engine for solution users 

### ISSUE THREAD

**Issue by lgayatri** [vmware/vic-product#608]
![image](https://user-images.githubusercontent.com/25006749/29512077-db0bda64-867e-11e7-9cdb-404ef1c30a3b.png)
From this screenshot, it is very hard for me to identify the mapping between the solution users that get created for  admiral,harbor and engine. I had about 200+ such solution users on PSC and as I could not find the mapping, had to delete all of them.

The highlighted text shows how vpxd represents the solution user names map.

**Comment by lgayatri** [comment]
vic-73d10421-dev.ova

**Comment by sergiosagu** [comment]
You can use the "Valid To" column to identify the solution users created, approximately, at the same time (i.e. same deployment).
The suffix of those solution users is just another UUID to distinguish a particular instance, like PSC itself does with users like vpxd-*, vpxd-extension-* and so on.
