### ISSUE TITLE
Do not create Solution users again if OVA is registered already with VCSA

### ISSUE THREAD

**Issue by lgayatri** [vmware/vic-product#609]
vic-73d10421-dev.ova
I registered OVA more than once and noticed that 3 solution users get created each time. For a given OVA, if we have registered with VCSA once, then we should not be creating solution users again.  At one point of time, I had about 200+ solution users for admiral, engine and harbor.

![image](https://user-images.githubusercontent.com/25006749/29512572-1eedfaae-8680-11e7-968c-4f1cacdadfe1.png)

**Comment by lcastellano** [comment]
Solutions users are created with randomized ids, this was done to allow multiple instances of Admiral to run against the same vSphere (PSC) instance. To change the behavior we need to change the Admiral bits that register with the PSC.

**Comment by sergiosagu** [comment]
Probably it's better to try to delete the old solution user when you want to register a component again. In any case, it looks like an enhancement and you can always clean up the unnecessary solution user from the PSC UI.

**Comment by zjs** [comment]
While this is an annoying issue internally, as we have high churn with OVA installation, it seems unlikely to have significant impact on customers. As noted above, a workaround exists.
