### ISSUE TITLE
Reregister with new PSC

### ISSUE THREAD

**Issue by lgayatri** [vmware/vic-product#610]
OVA build: vic-73d10421-dev
OVA IP :10.197.37.132 - root/Admin!23
PSC: 6.5U1 GA build

Steps:
1 . https://10.197.37.132:9443/ was registered with PSC: sc-rdops-vm01-dhcp-29-66.eng.vmware.com-10.160.29.66 on 8/18
2.  PSC went down on 8/18 after few hours
3.  I registered https://10.197.37.132:9443/ with new PSC: 10.133.146.15. The solution users got created successfully
![image](https://user-images.githubusercontent.com/25006749/29507449-c898b2fa-866d-11e7-87f4-14fd005182da.png)
4. Accessing :8282 after 5 minutes, shows the request getting redirected to old PSC instead of new one
![image](https://user-images.githubusercontent.com/25006749/29507487-effac9be-866d-11e7-8039-8e1ec2543e2b.png)
5. 9443 reports "Failed to locate productVM, trusted content is not available"

Logs:
[journalctl.zip](https://github.com/vmware/admiral/files/1238073/journalctl.zip)

[harbor (2).zip](https://github.com/vmware/admiral/files/1238064/harbor.2.zip)
[admiral.zip](https://github.com/vmware/admiral/files/1238070/admiral.zip)

**Comment by sergiosagu** [comment]
See https://github.com/vmware/admiral/issues/174#issuecomment-323723537.

**Comment by andrewtchin** [comment]
@sergiosagu I'm not clear on what the OVA needs to do here - could you please clarify?

**Comment by sergiosagu** [comment]
@andrewtchin - Basically make sure at least that if the VIC deployment tries to be re-registered with a different PSC:
- Admiral is stopped before the re-registration starts (maybe Harbor needs to be stopped as well).
- The re-registration process of Admiral & Harbor updates/overrides the original configuration files.
- Admiral & Harbor are properly started after that.

**Comment by stuclem** [comment]
This will require some documentation. @sergiosagu are we talking about 1.2 here? Thanks!

**Comment by andrewtchin** [comment]
@sergiosagu Thanks, how often would this be an issue? If it's often we should update the upgrade script to perform the actions you described.

**Comment by andrewtchin** [comment]
@lgayatri @sergiosagu Under what cases does the PSC change? Does this mean that the appliance was moved to a new vCenter or something?

**Comment by sergiosagu** [comment]
@andrewtchin - The ability of re-registering VIC with a different PSC is there, in case a customer needs it, but I'm not sure if that's because any particular use-case (which we could declare as unsupported anyway). PMs may answer your questions.

**Comment by andrewtchin** [comment]
@lgayatri Was the appliance moved to a different vCenter after the first PSC went down? What does it mean the PSC went down?

**Comment by lgayatri** [comment]
@andrewtchin , PSC can be repointed from Embedded to external and from one external to another external. This can also happen in scenarios where we have PSC-HA, in upgrade. 
PSC went down means the VM on which PSC was running got powered off.

**Comment by andrewtchin** [comment]
@anchal-agrawal will document the workaround for this

**Comment by stuclem** [comment]
This is being documented in the core docs in https://github.com/vmware/vic-product/issues/644 and https://github.com/vmware/vic-product/issues/681. Removing kind/note from this one.

**Comment by andrewtchin** [comment]
Documented in #681. Closing.
