### ISSUE TITLE
Upgrade script should automatically get Harbor password

### ISSUE THREAD

**Issue by andrewtchin** [vmware/vic-product#629]
As an admin upgrading the VIC appliance I want to not have to manually provide the Harbor database user/password values to the upgrade script.

Acceptance criteria:
- [ ] Get the password from harbor.cfg

@stuclem

**Comment by stuclem** [comment]
I could document how to find the password in the config files, but I'm not really comfortable with that, so pulling it in automatically would definitely be better.
