### ISSUE TITLE
Improve repository description

### ISSUE THREAD

**Issue by gucarreira** [vmware/vic-product#630]
Could you improve the description and what are the differences between vic-product and vic in the vmware repository?

thanks,

Gustavo

**Comment by andrewtchin** [comment]
@gucarreira Is there something specific you would like added? The readme in vic-product describes that vic-product includes three components, including VIC Engine from vmware/vic

**Comment by gucarreira** [comment]
At first I opened an issue in the VIC project and should have opened it in vic-product, because it was something related to the OVA properties.
I've tried before opening in which project I should have done, but in readme it does not make it clear what the vic-project project is using via OVA or features core stay in vic and productization in vic-project.

But on second thought might be better vmware technical analysis to decide where such requests should be.

**Comment by andrewtchin** [comment]
I see. I'll look at adding a notice about that to the default issue template in vmware/vic

**Comment by andrewtchin** [comment]
Would this text in the issue template for vmware/vic meet your needs? 
```
Issues in this repository are for VIC Engine only 
Please submit issues related to the VIC Appliance or other components at https://github.com/vmware/vic-product/issues
```

**Comment by gucarreira** [comment]
It's good, in the future should help others peoples.
Thanks

**Comment by mdubya66** [comment]
We should also add admiral and harbor issues @andrewtchin
