### ISSUE TITLE
Getting Started Page verifies thumbprint

### ISSUE THREAD

**Issue by andrewtchin** [vmware/vic-product#637]
As an administrator I want to verify that vCenter credentials are sent to the authentic vSphere API endpoint only.

- [ ] Prefetch and show the remote thumbprint for vCenter for user verification
- [ ] Use the thumbprint in for API connection in the registration

**Comment by lweitzman** [comment]
you can follow the workflow by clicking on the application installation link in the first box from here https://vmware.invisionapp.com/share/VBDLQ5QYQ#/254613570_Project_TOC after inputing the vcenter credentials, verification of the thumbprint is presented.

**Comment by lweitzman** [comment]
Updated the mockup https://vmware.invisionapp.com/share/T2D63MPMR#/249821530_Landing_Page__-_thumbprint 
the user can continue if the thumbprint is ok or cancel if not. a link to the documentation is provided.
