### ISSUE TITLE
Document how to register VIC Appliance with a new PSC and install/upgrade plug-ins after deployment

### ISSUE THREAD

**Issue by stuclem** [vmware/vic-product#644]
Per https://github.com/vmware/vic-product/issues/610. 

@karthik-narayan is this something that we need to support?

**Comment by stuclem** [comment]
Details of how to do this are in https://github.com/vmware/vic-product/issues/681

**Comment by stuclem** [comment]
Actually, this one is now redundant because of https://github.com/vmware/vic-product/issues/681.

**Comment by stuclem** [comment]
In fact, although I documented registering with a new PSC in the context of https://github.com/vmware/vic-product/issues/681 and PR https://github.com/vmware/vic-product/pull/852, I removed this on request from @anchal-agrawal in PR https://github.com/vmware/vic-product/pull/852, due to problems that occur after performing the procedure. We can revert the changes in https://github.com/vmware/vic-product/pull/852/commits/6163c4936e7762712eb37c3c76189d310fa56cc6 and https://github.com/vmware/vic-product/pull/852/commits/fcb32b7404de66dc6f5b0f871c7f2caa97cb4ad0 to restore this content once the procedure has been validated and fixed.

**Comment by stuclem** [comment]
@anchal-agrawal I'm putting this into the 1.3 doc update. Is registering with a new PSC likely to be validated before then? Thanks!

**Comment by stuclem** [comment]
@anchal-agrawal confirmed via Slack that no work is being done on verifying this procedure in 1.3, so this topic should stay out of the doc. I have attached the MD file of the topic here, for safekeeping:

[register_different_psc.zip](https://github.com/vmware/vic-product/files/1495560/register_different_psc.zip)

**Comment by stuclem** [comment]
@anchal-agrawal, while looking at https://github.com/vmware/vic-product/issues/1162 (updating PSC registration info), I was reminded of this one. Are there plans to test/verify the procedure to migrate to a completely different PSC in the upcoming releases? Thanks!

**Comment by anchal-agrawal** [comment]
@stuclem - @morris-jason merged https://github.com/vmware/vic-product/pull/1300 which should automatically handle registration with a new PSC when the `Re-initialize the VIC appliance` is used and new PSC credentials are provided (Jason can confirm). However, #1300 is not part of 1.3.0 or 1.3.1.

**Comment by stuclem** [comment]
@anchal-agrawal that's excellent news. So, for 1.3.x, should we keep registration with another PSC as an undocumented impossibility and close this issue?

**Comment by anchal-agrawal** [comment]
Sounds good to me. @andrewtchin can confirm.

**Comment by andrewtchin** [comment]
I'm cool with that

**Comment by stuclem** [comment]
Actually, thinking about this, we still need to update [Reinitialize the vSphere Integrated Containers Appliance](https://vmware.github.io/vic-product/assets/files/html/1.3/vic_vsphere_admin/reinitialize_appliance.html) to say that you can use the Reinitialize button to register with a new PSC, so reopening this one.

**Comment by andrewtchin** [comment]
just to make sure, you mean only update it for appliances version 1.4.0 and greater?

**Comment by stuclem** [comment]
@andrewtchin yes, that's exactly what I mean. I have left the 1.3.x docs unchanged.

**Comment by andrewtchin** [comment]
Cool

**Comment by stuclem** [comment]
Looks like this should be in 1.4.x and that it slipped through the net.

**Comment by stuclem** [comment]
We basically just need to add a 3rd bullet in https://vmware.github.io/vic-product/assets/files/html/1.4/vic_vsphere_admin/reinitialize_appliance.html that states that you can use the Reinitialize button to register the appliance with a new PSC if vCenter Server moves to a different PSC.

**Comment by stuclem** [comment]
We also need to mention the **Install UI Plugin** checkbox and the thumbprint verification step.

**Comment by stuclem** [comment]
We should also add another bullet that says that if you deselected the **Install UI Plugin** checkbox during deployment, you can use the Reinitialize button to install the plug-in after deployment. I just tested this and it works. 

See https://github.com/vmware/vic-product/issues/2037.
