### ISSUE TITLE
Document pre-upgrade checks for Admiral projects

### ISSUE THREAD

**Issue by stuclem** [vmware/vic-product#649]
Per Slack chat with @gmuleshkov, before you attempt to upgrade from 1.1.1 to 1.2, you must make sure that any Admiral projects that you created in 1.1.1 only have lower-case characters in their names. Otherwise, upgrade fails.

**Comment by stuclem** [comment]
Another comment from @gmuleshkov:

If the name of the default project was changed in admiral before upgrade in the new admiral the name will be reset to default-project.

**Comment by angel-ivanov** [comment]
Hello, the allowed characters for valid project name are: alhpha-numeric characters, periods, dashes and underscores, lowercase only and length <= 254. The regular expression we use to validate the project name is "[a-z0-9]+(?:[._-][a-z0-9]+)*".

**Comment by stuclem** [comment]
Thanks @angel-ivanov. I added this information in https://github.com/vmware/vic-product/pull/632/commits/ce4028fa36cbcc51678c666f15289dd2204cef78.

**Comment by angel-ivanov** [comment]
Great, thank you, @stuclem !

**Comment by stuclem** [comment]
These changes were merged in https://github.com/vmware/vic-product/pull/632.
