### ISSUE TITLE
Inconsistencies in OOTB user names and descriptions between UI, PSC and OVA

### ISSUE THREAD

**Issue by stuclem** [vmware/vic-product#651]
The out-of-the-box users that come with the appliance use names that do not match the user roles that you can select in the UI.

![users](https://user-images.githubusercontent.com/16718369/29717655-2fbb3440-89b0-11e7-8b05-837c2a77080d.png)

The role names used in the default user names and descriptions do not match the names as they are defined in the UI. Specifically, the UI uses **DevOps Administrator** whereas the default user name is **vicdef-project-admin**. 

![uinames](https://user-images.githubusercontent.com/16718369/29718450-2211966a-89b3-11e7-9603-74aa53b828a3.png)

Also, the descriptions of the users that appear in PSC  include "VIC Product" and "Admiral", which are not official product names. The use of "default" for the cloud admin and project admin users is also misleading, especially since the OVA wizard uses "out-of-the-box". 

I think that we need some consistency between how the users are named/described between the OVA installer, the PSC, and the VIC UI. My understanding is that these user accounts are actually examples, for experimentation purposes.

**Suggested default user names:**

I think that the `vicdef` prefix is not at all intuitive, especially if we don't use the word "default" anywhere in the OVA text. Also, `project-admin` should be `devops`, to match the roles as they are in the UI.

- `vic-cloud-admin`
- `vic-developer`
- `vic-devops-admin`

**Suggested descriptions for the users in PSC:**

- Example vSphere Integrated Containers cloud admin
- Example vSphere Integrated Containers developer
- Example vSphere Integrated Containers DevOps admin

**Suggested texts for OVA installer:**

Note capitalization of first letters, and that there should be no hyphen between "box" and "users".

- Out-of-the-box-users configuration ==> **Configure Out-of-the-Box Users** or **Configure Example Users** 
- Create out-of-the-box-users ==> **Create Out-of-the-Box Users** or **Create Example Users** 
- Out-of-the-box-users prefix ==> **Out-of-the-Box Username Prefix** or **Example Username Prefix** 
- Out-of-the-box-users password ==> **Out-of-the-Box User Password** or **Example User Password** 

cc. @alextopuzov

**Comment by alextopuzov** [comment]
Also, what's the default password for the users?
The password text box shows with predefined symbols, so there must be a default password?

May be it's best to have the box empty and leave it to the user to define one?

**Comment by alextopuzov** [comment]
Giving this a more serious thought, I'd say that from UX, security, product, documentation point of view, for these OOTB users, if a customer decides to create them (select the checkbox), than we'd better make the password box mandatory and leave it blank so that the customer enters the password.

Can we do that for 1.2, it shouldn't be a big deal?

**Comment by lcastellano** [comment]
As far as I know there is no way to avoid requiring the password all the times in the ovf form. So if we leave it empty the user will have to provide a password even when creation is unchecked. Which I think is really confusing.
