### ISSUE TITLE
Document troubleshooting for appliance startup failure

### ISSUE THREAD

**Issue by andrewtchin** [vmware/vic-product#668]
## Prerequisites
- Deployed a VIC appliance OVA successfully
- Found in VIC appliance v1.1.1

## Symptoms
- Cannot login to VIC appliance root account from DCUI or SSH using password set during OVA deploy

## Cause
- An early startup process failed, causing user provided password to not be set

## Identifying the issue
- Login to the appliance from the DCUI or SSH using `root` account with the default password `2RQrZ83i79N6szpvZNX6`

## Solution
- Upon logging in with the default password you will be prompted to change the root password. Set it to the same password you set during OVA deploy. 
  - If the password you choose is not accepted, set it to a password that is accepted. After the password is set, execute the command `reboot now`. After reboot, the password will be set to the password you set during OVA deploy.
- Use the password you set during OVA deploy when logging into the VIC appliance
  - This password will expire in 90 days by default

**Comment by andrewtchin** [comment]
Hold on this until I update again this week, Fabio and I found new info

**Comment by andrewtchin** [comment]
Updated, please review @frapposelli

**Comment by frapposelli** [comment]
LGTM
