### ISSUE TITLE
Document the different debug levels

### ISSUE THREAD

**Issue by stuclem** [vmware/vic-product#68]
_From @stuclem on May 30, 2016 15:14_

Per https://github.com/vmware/vic/issues/709.

_Copied from original issue: vmware/vic#852_

**Comment by stuclem** [comment]
https://github.com/vmware/vic/issues/709 is in GA release.

**Comment by stuclem** [comment]
When implemented, will require an update to the existing section on `--debug` in the topic on vic-machine create options, and a section in Admin about how to access and understand the information.

**Comment by stuclem** [comment]
https://github.com/vmware/vic/issues/709 is implemented in PRs https://github.com/vmware/vic/issues/1216 and https://github.com/vmware/vic/issues/1217.

**Comment by stuclem** [comment]
According to Faiyaz, https://github.com/vmware/vic/pull/1216 is internal.

**Comment by stuclem** [comment]
According to @hickeng in https://communities.vmware.com/message/2626719#2626719, setting debug to 3 suppresses the restart of failed components. We need to find out and document the exact effect of setting debug to 1, 2, 3 ... n. Currently we just talk about setting debug to a value >1.

**Comment by stuclem** [comment]
Not required for 0.7, so moving back to backlog.

**Comment by stuclem** [comment]
In https://github.com/vmware/vic/issues/3081#issuecomment-259751868 @hickeng says that debug >2 automatically enables SSH.

@hickeng are these debug levels spec'd anywhere?

**Comment by stuclem** [comment]
Added more info to https://github.com/stuclem/vic/blob/master/doc/user_doc/vic_installation/vch_installer_options.md#--debug: "For example, setting `--debug` to 2 or greater automatically enables SSH access to the VCH endpoint VM. Setting `--debug` to 3 suppresses the restart of failed components." I do feel that this is very incomplete, though. I would really like to obtain a proper list of what each logging level does.

@hickeng do you have more info about what each logging level does? I have a snippet for 2 and 3, but what about 4, 5, ... _n_? How high can _n_ be?

**Comment by stuclem** [comment]
Nice to have for 1.1, but might not make the cut.

**Comment by stuclem** [comment]
Still no info about this. Moving out of 1.1.

**Comment by hickeng** [comment]
@stuclem Not spec'd as such - I've opened https://github.com/vmware/vic/issues/4575 to do a better job of this. But the basics are:

1: extra verbosity, no changes to behaviour
2: changes to behaviour - exposes servers on more interfaces, launches pprof in containerVMs
3: disable recovery logic, log sensitive data - disables component restart in appliance, and containerVM shutdown. Logs environment and details for user application, and collects application output in log bundle.

**Comment by stuclem** [comment]
Great, thanks @hickeng!

**Comment by stuclem** [comment]
Added the info from the comment  above to the description of the` vic-machine create --debug` option.

Change is in https://github.com/stuclem/vic-product/commit/3ab8c2ba1ef2a85f2cdea2658b20bf6334186e15. @hickeng is this OK? Thanks!

**Comment by stuclem** [comment]
Changes merged in https://github.com/vmware/vic-product/issues/158, but leaving this open for final verification by @hickeng.

**Comment by hickeng** [comment]
@stuclem We're going to vet the code where the debug levels are used to confirm current behaviour - what I described was original intent but unverified.
There's an issue open (vmware/vic#4575) for a more structured and enforced approach.

I presume you just need current behaviour for this - what level of detail?

**Comment by stuclem** [comment]
@hickeng yes, we need the behaviour as it is in 1.1. I don't think that we need masses of detail - just enough to let people know why they might need or want to set a level higher than 1, and what impact that will have on their setup. Thanks!

**Comment by stuclem** [comment]
This change is merged, but leaving this issue open pending the code vetting by @hickeng.

**Comment by stuclem** [comment]
To be verified in 1.2.

**Comment by stuclem** [comment]
Given @chengwang86 's comments in https://github.com/vmware/vic-product/pull/532, I think that it's safe to finally close this one.
