### ISSUE TITLE
Automate H5 client plugin install

### ISSUE THREAD

**Issue by andrewtchin** [vmware/vic-product#705]
**User Statement:**
As a user I want the H5 client plugin to be installed automatically when I initialize the VIC appliance.

**Details:**
Currently the VIC UI plugins are installed manually by the user by:

1. Downloading the VIC Engine tar ball file from the OVA appliance
2. Navigating to ui/VCSA (or ui/vCenterForWindows) and run install.sh (or install.bat)

This process can be improved by automatically installing the plugins when the OVA appliance is initialized. Also in case there is an issue or the user wishes to reinstall the plugin 

**Acceptance Criteria:**
- [ ] Script to automatically install the UI plugin
- [ ] Verify VC thumbprint in Getting Started page (see #637)
- [ ] A button in the Getting Started page to trigger reinstalling the plugins
- [ ] Integrated with OVA initialization and re-initialization hooks
- [ ] Documentation

**Comment by jooskim** [comment]
@andrewtchin @ali5ter @jak-atx please review the acceptance criteria above

**Comment by zjs** [comment]
Is this the same as vmware/vic#6890?

**Comment by andrewtchin** [comment]
yup closing in favor of https://github.com/vmware/vic/issues/6890
