### ISSUE TITLE
Close Window does not work for "Complete VIC appliance installation"

### ISSUE THREAD

**Issue by lgayatri** [vmware/vic-product#713]
![image](https://user-images.githubusercontent.com/25006749/29957903-98c7583a-8f0d-11e7-9f4d-5fadfa063920.png)
Build: 
https://storage.googleapis.com/vic-product-ova-builds/vic-43c30f96-dev.ova
Admiral aade1955c87d
Engine vic_1.2.0-rc1.tar.gz
Harbor harbor-offline-installer-v1.2.0-rc3.tgz

**Comment by andrewtchin** [comment]
The UI team is aware of this and has an issue opened, closing this one
