### ISSUE TITLE
Provisioning of dch-photon fails with Invalid image format

### ISSUE THREAD

**Issue by mshipkovenski** [vmware/vic-product#718]
When trying to provision containers based on the `default-project/vmware/dch-photon` image, I get the error `Invalid image format: 10.160.94.153:443/default-project/vmware/dch-photon`. The image name should be changed to \<namespace\>/<repo_name>:\<tag\> or \<project\>/<repo_name>:\<tag\> in https://github.com/vmware/vic-product/blob/524510a28da216ba95c86c70e3f7717371794079/installer/packer/scripts/provision_harbor.sh#L56

**Comment by andrewtchin** [comment]
@mshipkovenski when do you see that? 

```
chin@ubuntu:~/Desktop|⇒  sudo cp ca.crt /etc/docker/certs.d/10.192.186.10
chin@ubuntu:~/Desktop|⇒  docker login 10.192.186.10
Username: administrator@vsphere.local
Password: 
Login Succeeded
chin@ubuntu:~/Desktop|⇒  docker pull 10.192.186.10/default-project/vmware/dch-photon:1.13
1.13: Pulling from default-project/vmware/dch-photon
ce66dce42617: Pull complete 
Digest: sha256:25db0e8f6724cd303b3982be8105c94ca79155ee52f71f173c2c3647e7c036ed
Status: Downloaded newer image for 10.192.186.10/default-project/vmware/dch-photon:1.13
chin@ubuntu:~/Desktop|⇒  docker create 10.192.186.10/default-project/vmware/dch-photon:1.13
29cc559a79da724a678d42dc8ff8644fca5ca6633655cf11b380309bc5857f5b
```

**Comment by reasonerjt** [comment]
I just tried and I'm not seeing the error.  I can provision the image without problem with vanilla docker
```
root@jt-dev:~# docker pull 10.160.98.138/default-project/vmware/dch-photon:1.13
1.13: Pulling from default-project/vmware/dch-photon
ce66dce42617: Pull complete
Digest: sha256:25db0e8f6724cd303b3982be8105c94ca79155ee52f71f173c2c3647e7c036ed
Status: Downloaded newer image for 10.160.98.138/default-project/vmware/dch-photon:1.13
root@jt-dev:~# docker run 10.160.98.138/default-project/vmware/dch-photon:1.13
time="2017-09-01T15:44:58.941529156Z" level=warning msg="[!] DON'T BIND ON ANY IP ADDRESS WITHOUT setting -tlsverify IF YOU DON'T KNOW WHAT YOU'RE DOING [!]"
time="2017-09-01T15:44:58.944292943Z" level=info msg="libcontainerd: new containerd process, pid: 18"
time="2017-09-01T15:44:59.952830029Z" level=error msg="'overlay' not found as a supported filesystem on this host. Please ensure kernel is new enough and has overlay support loaded."
.....
```
However, I agree conventionally the name should be <project>/<repo_name>:<tag> 
i.e. `default-project/dch-photon:1.13`

**Comment by mshipkovenski** [comment]
@andrewtchin that's the error I got from Admiral on vic-be

**Comment by andrewtchin** [comment]
@mshipkovenski Could you investigate from the Admrial side and provide more info and logs? Daniel and I were able to pull the image correctly

**Comment by andrewtchin** [comment]
Is the `vmware/` in the image name the cause of the error?

**Comment by mshipkovenski** [comment]
Yes, I believe so. The correct format for an image is [hostname:port/][namespace/]reponame[:tag]

**Comment by andrewtchin** [comment]
To repro, add a VCH and try to provision a DCH container. In library public repositories search `dch-photon` then provision.
