### ISSUE TITLE
Document that debug --rootpw enables SSH and changes the default password

### ISSUE THREAD

**Issue by stuclem** [vmware/vic-product#738]
From Slack: 

Eduardo Meirelles [7:47 PM] 
BTW… not sure if you guys have a chance to look at --rootpw behavior…when I ran debug --rootpw it also enabled SSH access, even though I did not specify --enable-ssh option.

Matt Williamson [8:00 PM] 
i just confirmed that using the rootpw flag in 1.1.1 also enabled ssh access.

[8:00] 
the docs should be updated to reflect that rootpw enables SSH AND changes the default password

[8:00] 
where enable_ssh turns it on with the default password

**Comment by stuclem** [comment]
@mdubya66 and @emeirell if I remember correctly the discussions that I had with @hickeng at the time that he added these options, this is actually a bug in the implementation of `--rootpw`. 

I believe that the intention is for `vic-machine debug` to work as documented, i.e. `--rootpw` activates Shell access only, and then if used in combination with `--enable-ssh`, it enables shell and SSH access, using the same password. I can't fully remember why this separation was necessary, but @hickeng and I did go around the houses a few times when I wrote up these topics (with substantial contribution from @hickeng, IIRC).

Of course, even if the docs do present the desired behaviour, they do not present the actual behaviour. So, we have two options:

- Make the current behaviour the official behaviour and rewrite the docs accordingly.
- Fix the implementation of `--rootpw` in the product, and in the meantime, document the fact that `--rootpw` also enables SSH as a Known Issue in the release notes.

Which do you prefer?

**Comment by emeirell** [comment]
Fixing the implementation of `--rootpw` seems the right thing to do.
This security granularity control is greatly appreciated within customers.

**Comment by stuclem** [comment]
In the meantime, I'll add this as a Known Issue in the release notes.

**Comment by stuclem** [comment]
Moving this to the `vic` repo, as this is an engineering issue rather than a doc issue. I did not find an existing issue about `--rootpw` enabling SSH.

**Comment by stuclem** [comment]
Issue moved to [vmware/vic #6402](https://github.com/vmware/vic/issues/6402) via [**ZenHub**](https://www.zenhub.com/)
