### ISSUE TITLE
Update docs to point to downloads on Google Storage rather than Bintray

### ISSUE THREAD

**Issue by stuclem** [vmware/vic-product#74]
_From @stuclem on March 16, 2017 14:43_

Per https://github.com/vmware/vic/issues/4183, we are moving the binary downloads to Google Cloud Storage. 

_Copied from original issue: vmware/vic#4276_

**Comment by stuclem** [comment]
Not sure if this is happening for 1.1.

**Comment by stuclem** [comment]
@mhagen-vmware confirms that this is not happening for 1.1.

**Comment by stuclem** [comment]
@mhagen-vmware is working on this now.

**Comment by mdubya66** [comment]
we will be deprecating bintray altogether but not as part of this PR. So we will need to update all references to bintray.

**Comment by mhagen-vmware** [comment]
all released, tagged builds will be moved to here:
https://storage.googleapis.com/vic-engine-releases/<release-num>.tar.gz

**Comment by mhagen-vmware** [comment]
All builds now uploaded, here is an example URL:
https://storage.googleapis.com/vic-engine-releases/vic_1.1.0.tar.gz

I will be moving all the github release links over now.

**Comment by mhagen-vmware** [comment]
All github release links should be updated now.

**Comment by stuclem** [comment]
In the main docs, the only place where we mention the different downloads are in the topic on downloading VIC:
https://vmware.github.io/vic-product/assets/files/html/1.1/vic_vsphere_admin/download_vic.html

Under Open Source Builds of the VIC Components, we use the following links:

- Tagged builds point to https://github.com/vmware/vic/releases (same for Harbor/Admiral)
- Latest builds point to https://bintray.com/vmware/vic-repo/build

The same is true for the downloads section on https://vmware.github.io/vic-product/index.html and https://vmware.github.io/vic/index.html.

So, if we aren't deprecating Bintray for the latest, non-tagged builds just yet, I think that we're all good for now. @mhagen-vmware and @mdubya66 do you concur?

**Comment by stuclem** [comment]
Landing page at http://www.vmware.com/support/pubs/vsphere-integrated-containers-pubs.html only points to official download, https://vmware.github.io/vic-product/index.html, and the top levels of the 3 Github repos.

Release notes at http://pubs.vmware.com/Release_Notes/en/vsphere-integrated-containers/11/vsphere-integrated-containers-11-release-notes.html don't link to any downloads.

**Comment by stuclem** [comment]
Think that it's safe to move this one back to Not Ready and out of 1.1.1, pending the final part of the migration.

**Comment by stuclem** [comment]
Turns out that the automatic builds have been transferred to google storage now: https://console.cloud.google.com/storage/browser/vic-engine-releases/
