### ISSUE TITLE
Document OVA deployment scenarios with multiple registries

### ISSUE THREAD

**Issue by stuclem** [vmware/vic-product#740]
I have some questions about how a user can/might/should set up multiple instances of VIC Registry.

**What I Did**

- Deployed two instances of VIC appliance (fresh installations, not upgrades) to the same vCenter Server/PSC. Let's call the appliances VIC1 and VIC2, their respective Registry instances Reg1 and Reg2, and the respective Management Portals MP1 and MP2. 
- In MP1, registered Reg2 as a replication endpoint for Reg1. Created and enabled a replication rule in the `default-project` in MP1, that uses this endpoint. I had to disable remote cert verification in MP1 for this to work.
- In MP2, registered Reg1 as a replication endpoint for Reg2. Created and enabled a replication rule in the `default-project` in MP2, that uses this endpoint. I had to disable remote cert verification in MP2 for this to work.
- Pushed a `busybox` image to Reg1. It replicated nicely to Reg2.
- Pushed an `ubuntu` image to Reg2. It replicated nicely to Reg1.
- Pushed `busybox` image to Reg2. It did not appear to replicate to Reg1, since Reg1 already has that image. 
- In addition to configuring Reg2 as a replication endpoint for Reg1, I also registered Reg2 as a source registry in MP1.

**Questions**

- [x] Do we support deploying the two OVAs, VIC1 and VIC2 to the same vCenter Server instance, i.e. registering both instances with the same PSC? Could this cause problems with users?
- [x] Is two-way replication as described above supported? Is it something users should do or avoid?
- [x] Is it always necessary to disable remote cert verification if the replication endpoint is a VIC Registry?
- [x] Do we support registering a registry, e.g. Reg2, as a source registry in MP1 if it is already a replication endpoint for Reg1? Is there any reason why users should or shouldn't do it?
- [x] If you do everything that I did above, could/should you then shut down the MP, fileserver, Demo VCH, services on VIC2, leaving only the Reg2 service running, and manage Reg2 and Reg1 exclusively through MP1? I'm thinking that if Reg2 is registered as a source registry in MP1, then you might not want MP2 to linger around for people to log into and mess about with. Afterall, in this case, the only part of VIC2 that you are interested in is Reg2.

I think that the best people to answer these questions might be @reasonerjt @andrewtchin @sergiosagu, but I decided to put it in an issue so that others can be dragged in easily. 

Thanks in advance!

cc @alextopuzov

**Comment by stuclem** [comment]
Also @mhagen-vmware might have some input.

**Comment by andrewtchin** [comment]
I think only one OVA per vCenter is supported @hmahmood

**Comment by hmahmood** [comment]
I believe that is correct. @pdaigle

**Comment by mdubya66** [comment]
This is correct.

**Comment by stuclem** [comment]
OK, thanks @andrewtchin @mdubya66 and @hmahmood. Created https://github.com/vmware/vic-product/issues/745 for the one-appliance-per-PSC update.

What about the other questions? Specifically the last bullet? Is that a valid thing to do?

**Comment by stuclem** [comment]
Actually, @andrewtchin @hmahmood @mdubya66 my question about deploying VIC appliances to the same VC was badly worded. What I should have asked was can you deploy multiple appliances to multiple VCs that are all managed by a single PSC?

**Comment by andrewtchin** [comment]
@sergiosagu can you help answer the above?

**Comment by stuclem** [comment]
@reasonerjt says that these are questions for PM. So, @pdaigle can you please take a look? Thanks!

**Comment by sergiosagu** [comment]
> Do we support deploying the two OVAs, VIC1 and VIC2 to the same vCenter Server instance, i.e. registering both instances with the same PSC? Could this cause problems with users?

A priori, there's no limitation in how many VIC OVA deployments can be registered with a single PSC. PSC is used only to authenticate and retrieve (AD) users & groups information. Than means that if VIC1 and VIC2 are using the same PSC (and the same users are available to them), user X could have specific role(s) in VIC1 and a different one(s) in VIC2, but that's all.

The other questions are more Harbor/Registry oriented so, as mentioned above, @reasonerjt and @pdaigle could add some more info.

**Comment by stuclem** [comment]
Great, thanks @sergiosagu. I'll update the deployment doc with the PSC info.

**Comment by reasonerjt** [comment]
> Is two-way replication as described above supported? Is it something users should do or avoid?

It is supported, some community users use it for back up images, but I'm not sure we should encourage users doing this, because it only replicates the image, not other data.
> Is it always necessary to disable remote cert verification if the replication endpoint is a VIC Registry?

It is not always necessary, if user use correct certificate (with valid CA, correct IPSAN) it is not necessary.  **disable remote cert verification** is a workaround for the users who use self-signed certificate.  In the case of .ova deployment, when no certificate provided it will generate a new cert, that's why it's very common the verification is disabled.
> Do we support registering a registry, e.g. Reg2, as a source registry in MP1 if it is already a replication endpoint for Reg1? Is there any reason why users should or shouldn't do it?

Yes, we do. No particular reason for should or should not IMO..
> If you do everything that I did above, could/should you then shut down the MP, fileserver, Demo VCH, services on VIC2, leaving only the Reg2 service running, and manage Reg2 and Reg1 exclusively through MP1? I'm thinking that if Reg2 is registered as a source registry in MP1, then you might not want MP2 to linger around for people to log into and mess about with. Afterall, in this case, the only part of VIC2 that you are interested in is Reg2.

This is more a PM decision.  But IMO should not, because replication is based on project, not how registry.

**Comment by stuclem** [comment]
Thanks @reasonerjt I'll write up something about deployment scenarios after GA, based on your comments above.

**Comment by mlh78750** [comment]
@mdubya66 your comment at https://github.com/vmware/vic-product/issues/740#issuecomment-327629122 seems to be the only definitive answer on why we can't deploy two OVAs to a single VC. Do you know why that is not supported? It is just a testing issue? or does something not work?

**Comment by dbarkelew** [comment]
There are some deployments with multiple VIC appliances already. If this is a problem we will need to know how to fix it when the symptoms start cropping up.

**Comment by mlh78750** [comment]
@dbarkelew that's a common setup. Which is why I am wondering about this. @emeirell posted https://github.com/vmware/vic-product/issues/826 against vic-product to see if this was in fact a limitation or a doc issue. I suspect doc issue and I'd like to revert the doc change unless someone can tell me why it doesn't work or is not supported. We might need to add some tests to ensure we're testing something like the use case you called out in https://github.com/vmware/vic-product/issues/740#issuecomment-329871049

**Comment by stuclem** [comment]
I introduced the one-appliance-per-VC limitation in 1.2, so it's only been visible publicly for a couple of days. I can pull that out if we want to avoid complaints about us forbidding setups that customers already have. Then, when we agree on a position, I can document some suggested setups per @dbarkelew 's comment above. I'm glad that I started this conversation!

**Comment by mlh78750** [comment]
Let's revert @stuclem until we know for sure that it's not supported.

**Comment by mlh78750** [comment]
Note that it is not supported to add a VCH instance to more than one VIC Appliance (Admiral). But that doesn't preclude us from allowing more than one VIC appliance per VC.

**Comment by mlh78750** [comment]
Confirmed. @stuclem please remove the note about support for only one VIC appliance per VC. 

We should also add a note saying that a VCH should only be added to one VIC appliance for management.

**Comment by stuclem** [comment]
@mlh78750 done in https://github.com/vmware/vic-product/pull/832. Please can you review it?

**Comment by pdaigle** [comment]
A customer has submitted the following additional scenario. I believe this would be a common request among medium/large vSphere installations:

- They have a 6 vCenters in as many locations;
- vCenters are not all part of the same SSO domain;
- Customer would like to have a centralized Registry, replicated to all vCenter locations for data proximity (Hub&Spoke-like scenario) with a registry instance for each vCenter instance;

**Comment by andrewtchin** [comment]
@stuclem For the detail in #832 if you think it's necessary, you can add a note that if a VCH is added to more than one VIC appliance, behavior of trusted content will be undefined.

**Comment by stuclem** [comment]
Moving back to backlog as I haven't touched this in a while.

**Comment by stuclem** [comment]
Medium priority as we really need to add something about deployment scenarios.

**Comment by stuclem** [comment]
We need to clearly state somewhere that it is entirely possible to have multiple appliances with multiple registries on the same VC.
