### ISSUE TITLE
Disable default SSH access to OVA and print warning banner on login

### ISSUE THREAD

**Issue by pdaigle** [vmware/vic-product#742]
**User Statement:**

As a vSphere Admin or Cloud Admin, I want to protect the VIC Management OVA against misuse to prevent disruption of service on Management Portal and registry.

**Details:**

We should warn customers against using the OVA for anything other than VIC services and against logging in for anything other than GSS-assisted troubleshooting.

Customers using the OVA for things other than running the VIC services could potentially impact the VIC services. For example:

- Filling up the filesystem
- Accidentally stopping necessary services
- Accidentally shutting down the OVA

**Acceptance Criteria:**

Please change the following:

- Change the default SSH setting in the OVF options to `disabled`
- Print a banner on user log in that warns them about misusing the OVA and recommends that logging in should only be done under GSS supervision, for the purposes of troubleshooting

**Comment by pdaigle** [comment]
@stuclem The recommendation above should be explicitly stated in the documentation as well. Something along the lines of:
"SSH access to the vSphere Integrated Containers OVA can be used in exceptional cases that cannot be handled through standard remote management or CLI tools. This is primarily intended for use in break-fix scenarios, under the guidance of VMware GSS."

**Comment by stuclem** [comment]
@pdaigle the one drawback of disabling SSH access by default is that it is a required step of the upgrade process. But, I can certainly add the warning somewhere, and we do tell people to edit the appliance settings to allow it if the SSH access option has been disabled.

**Comment by stuclem** [comment]
@pdaigle do we want to go as far as to recommend that users disable SSH access at step 3 of the OVA deployment procedure? 
https://vmware.github.io/vic-product/assets/files/html/1.2/vic_vsphere_admin/deploy_vic_appliance.html

**Comment by pdaigle** [comment]
@stuclem 
Good catch about the upgrade requirement for `ssh`.
Let's stick with a warning in the docs and a warning in the welcome banner for now.

**Comment by stuclem** [comment]
Added the warning about SSH'ing into the appliance in PR https://github.com/vmware/vic-product/pull/784. Do we want to say the same about SSH'ing into VCHs?

**Comment by andrewtchin** [comment]
Reopening for motd and option to disable SSH work

**Comment by mdubya66** [comment]
adding to 1.3 and making high priority per @pdaigle

**Comment by stuclem** [comment]
Removing user-doc flag as I am tracking this in https://github.com/vmware/vic-product/issues/924

**Comment by AngieCris** [comment]
Fixed in pr #927 (merged). Close this issue.

**Comment by AngieCris** [comment]
Fixed in pr #927 (merged). This issue is closed.
