### ISSUE TITLE
Separate persistent data to individual disks on the vSphere Integrated Containers Appliance

### ISSUE THREAD

**Issue by dbarkelew** [vmware/vic-product#743]
Tracking for separating the MySQL DB for the registry and management portal to second vDisk and separate the log files to a third vDisk.

Use case to mitigate issues if the root disk becomes full.

Bug Ref# 1954150

**Comment by andrewtchin** [comment]
**User Statement:**

As a user I want a separate persistent disk for each logs and databases on the appliance.

**Details:**

**Acceptance Criteria:**
- [ ] Separate disks
- [ ] Handles upgrade
- [ ] Documentation

**Comment by corrieb** [comment]
We need to consider the needs of backup here - what is ephemeral data vs persistent data. I would suggest for example that logs could just go in a separate logical partition from images and be on the same VMDK - no need for either to be backed up. Any database info should be on a VMDK that can be backed up independently.

**Comment by dbarkelew** [comment]
I have had customer look at logs as important particularly ones that have SLAs with their clients and need to account for any issues. If the logs do not take that much space, including them in the backup would benefit the customer who require RCAs for any downtime.

**Comment by corrieb** [comment]
@dbarkelew Interesting. I know customers consider logs important, but didn't know that there was a backup strategy in place around those. Good input. Just wanted to make sure that the business needs fit the solution

**Comment by mdubya66** [comment]
adding to 1.3 and making high priority per @pdaigle

**Comment by andrewtchin** [comment]
@stuclem This will need docs on the different disks now used by the appliance

**Comment by morris-jason** [comment]
@stuclem The layout is consistent with the ova design doc, but in short we have four disks now.
`/` - root disk
`/storage/data/` - data disk; a catch-all disk containing, among other things, the harbor registry.
`/storage/log/` - logging disk; contains the `harbor` and `admiral` directories for component logs.
`/storage/db/` - database disk; contains harbor's mysql, clair, and notary databases.

**Comment by andrewtchin** [comment]
Referenced design doc is here https://github.com/vmware/vic-product/blob/master/installer/DESIGN.md
