### ISSUE TITLE
OVA separate disk for logs and databases

### ISSUE THREAD

**Issue by andrewtchin** [vmware/vic-product#744]
**User Statement:**

As a user I want a separate persistent disk for each logs and databases on the appliance.

**Details:**

**Acceptance Criteria:**
- [ ] Separate disks
- [ ] Handles upgrade
- [ ] Documentation

**Comment by corrieb** [comment]
We should close #743 if this is related to the same question.

We need to consider the needs of backup here - what is ephemeral data vs persistent data. I would suggest for example that logs could just go in a separate logical partition from images and be on the same VMDK - no need for either to be backed up. Any database info should be on a VMDK that can be backed up independently.

**Comment by mdubya66** [comment]
duplicate of #743
