### ISSUE TITLE
Add option to specify distributed switch when port group name is ambiguous

### ISSUE THREAD

**Issue by philosifer** [vmware/vic-product#747]
VIC Product version:

vic-v1.1.1.56a309fb.ova

Deployment details:

VSCA 6.5 u1 and ESXi 6.5u1

Steps to reproduce:

vic-machine create cannot handle ambiguous port group names

Actual behavior:

Attempting to use a port group name that is identical under multiple distributed switches on the same vcenter results in an error.

Sep  7 2017 10:44:28.408+01:00 ERROR Error checking network for --public-network: ambiguous network dvPortGroup-vLAN100

This is at odds with that same port name being suggested as a possible value

Sep  7 2017 10:44:27.717+01:00 INFO  Suggested values for --public-network:
Sep  7 2017 10:44:27.717+01:00 INFO    "dvPortGroup-vLAN100"

Expected behavior:

Add an option to specify the dvswitch name to remove the ambiguity

**Comment by andrewtchin** [comment]
Issue moved to [vmware/vic #6628](https://github.com/vmware/vic/issues/6628) via [**ZenHub**](https://www.zenhub.com/)
