### ISSUE TITLE
Document that VCH can have one interface per network

### ISSUE THREAD

**Issue by stuclem** [vmware/vic-product#749]
https://github.com/vmware/vic/issues/2802 is fixed in PR https://github.com/vmware/vic/issues/6201. So, we can remove all of the notes about 2 networks having to share an interface from the docs.

**Comment by stuclem** [comment]
This fix is definitely in 1.3. Awaiting confirmation from @andrewtchin whether it would also be in an eventual 1.2.2 release.

**Comment by andrewtchin** [comment]
1.2.2 is not currently planned so determination to pull this fix in would be made if we have that release
