### ISSUE TITLE
Document Getting Started Page/Initialization error

### ISSUE THREAD

**Issue by andrewtchin** [vmware/vic-product#763]
If the user receives the error `Failed to locate productVM, trusted content is not available` one cause may be that the user entered credentials for a vCenter that is different than the one that the VIC Appliance is running on. The user should reinitialize the appliance with the correct vCenter credentials.

Also opened #762 to improve error messages

**Comment by andrewtchin** [comment]
Based on https://github.com/vmware/vic-product/pull/806 the error message is updated to `Failed to locate VIC Appliance. Please check the vCenter Server provided and try again`

**Comment by stuclem** [comment]
To be addressed along with https://github.com/vmware/vic-product/issues/681.
