### ISSUE TITLE
dch-photon image not present after upgrade from 1.1.1 to 1.2 RC3

### ISSUE THREAD

**Issue by stuclem** [vmware/vic-product#769]
**VIC Product version:**

OVA version `vic-v1.2.0-rc3-ce9fca67.ova`

**Deployment details**

Upgraded OVA version `vic-v1.1.1_56a309fb.ova` to `vic-v1.2.0-rc3-ce9fca67.ova`

**Steps to reproduce:**

- Deployed two 1.1.1 instances, and populated one with projects, images, etc, and with replication endpoint/rule to replicate to the other instance.
- Upgraded the instance with the source registry to 1.2 RC3 (didn't upgrade the replication target)
- All projects, replication configuration, images successfully migrated to 1.2.

**Actual behavior:**

Looked for `dch-photon` in the new `default-project` in 1.2, but `default-project` is empty.

**Expected behavior:**

`dch-photon` should be present in the `default-project` repo after upgrade, as is the case for a fresh installation.

**Comment by stuclem** [comment]
I just deployed a fresh installation of 1.2 RC3, and dch-photon is there:

![rc3-fresh](https://user-images.githubusercontent.com/16718369/30212741-858191b6-94a6-11e7-8d49-b2f83ebf4245.png)

But in the 1.1.1 to 1.2 RC3 upgrade, no dch-photon:

![rc3-upgrade](https://user-images.githubusercontent.com/16718369/30212744-8af701b2-94a6-11e7-8661-a0e257cc12b2.png)

**Comment by stuclem** [comment]
Added to https://github.com/vmware/vic-product/releases/tag/v1.2.0#knownissues.

**Comment by stuclem** [comment]
I think I must have closed this by mistake

**Comment by andrewtchin** [comment]
need to verify what happens for 1.2 to 1.3 upgrade and change upgrade script accordingly if needed

**Comment by mdubya66** [comment]
still an issue? @andrewtchin

**Comment by stuclem** [comment]
I think that it's not an issue if you upgrade from 1.2 to 1.3, since the image is present in 1.2. But, if you upgraded from 1.1 to 1.2, and then from 1.2 to 1.3, then presumably the image would still not be present in 1.3. Is this a bit of a corner case?

**Comment by andrewtchin** [comment]
I tested a 1.1 to 1.2.1 to 1.3.1 upgrade and dch-photon is present at the end. We add dch-photon at startup now so this isn't an issue. Closing.
