### ISSUE TITLE
Demo VCH documentation needs to be clear that it only supports DHCP

### ISSUE THREAD

**Issue by mdubya66** [vmware/vic-product#772]
# For bug reports, please include the information below:

**VIC Product version:**

OVA version 1.2.0-rc3

We need to update the demo VCH documentation to be very succinct in what the demo VCH installer does provide and does not. 

https://vmware.github.io/vic-product/assets/files/html/1.2/vic_vsphere_admin/deploy_demo_vch.html

This specific report is for DHCP only. Let's also identify any other limitations that users might expect.

**Comment by corrieb** [comment]
More significantly, it has no option for a volume store, which will make numerous containers fail to start out of the box: https://github.com/vmware/vic/issues/6145
