### ISSUE TITLE
Homogenize certificate requirements across components

### ISSUE THREAD

**Issue by stuclem** [vmware/vic-product#781]
As described in https://github.com/vmware/vic-product/pull/752 and documented in the [VIC Certificate Reference](https://github.com/vmware/vic-product/blob/master/docs/user_doc/vic_vsphere_admin/vic_cert_reference.md), if you use custom certificates, the different components all have different requirements in terms of the type of certificate that they can accept. 

After discussion with @zjs, we should attempt to homogenize these requirements across all components that accept custom certificates.

**Comment by andrewtchin** [comment]
Related https://github.com/vmware/vic/issues/5640

**Comment by andrewtchin** [comment]
@stuclem #881 has been resolved, doc updates and examples are in there and https://github.com/vmware/vic-product/pull/1272

**Comment by stuclem** [comment]
I am overhauling the certificates docs in #https://github.com/vmware/vic-product/issues/1828. This issue is replaced by that one.
