### ISSUE TITLE
Document docker exec support

### ISSUE THREAD

**Issue by stuclem** [vmware/vic-product#79]
_From @stuclem on November 11, 2016 14:9_

Per https://github.com/vmware/vic/issues/3048

_Copied from original issue: vmware/vic#3123_

**Comment by stuclem** [comment]
https://github.com/vmware/vic/issues/3048 is in 0.10

**Comment by stuclem** [comment]
Actually, this is being dev'd in https://github.com/vmware/vic/issues/3649.

**Comment by stuclem** [comment]
Definitely in 1.1.

**Comment by stuclem** [comment]
Now pushed to 1.2.

**Comment by stuclem** [comment]
Actually, this is in 1.1, it's just attach that isn't supported. So, we need to document it as supported but with caveat.

**Comment by stuclem** [comment]
@karthik-narayan should we drop support for `exec` in 1.1 if `attach` is not working? Thanks!

**Comment by karthik-narayan** [comment]
@stuclem Exec support is scheduled for 1.2. We can drop support for it now.

**Comment by stuclem** [comment]
Definitely in 1.2.

**Comment by stuclem** [comment]
https://github.com/vmware/vic/issues/3649 is complete.
