### ISSUE TITLE
Harbor registry fails to start when CA signed certificate added during OVA deployment

### ISSUE THREAD

**Issue by mattstocum** [vmware/vic-product#797]
**VIC Product version:**

OVA vic-v1.2.0-rc3-ce9fca67.ova

**Deployment details:**

vCenter 6.5 VSA 6.5.0.5100

**Steps to reproduce:**

1. Deploy VIC from OVA.
2. During initial deployment, enter a CA signed certificate in section 4.2 and key in section 4.3 (Management Portal Configuration) of the vApp options.
3. Power on VM and wait for it to finish booting

**Actual behavior:**

Harbor registry (port 443) fails to start. Port 9443 does start properly using the correct certificate.

**Expected behavior:**

Harbor registry should start.

**Workaround:**

1. Shutdown VM
2. Clear sections 4.2 and 4.3 from vApp options
3. Start VM and verify that the registry is listening with a self-signed certificate
4. Shutdoown VM
5. Enter CA signed certificate and key in 4.2 and 4.3
6. Start VM and verify that the registry is listening with CA signed certificate

**Notes:**
I'm not sure if this is relevant, but the CA cert I have does have an intermediate certificate that I am not able to supply using the vApp options. The intermediate certificate is installed and trusted on the systems where I need to access VIC from, however.

**Comment by andrewtchin** [comment]
Hi @mattstocum thank you for your report
As an additional data point - did Admiral start with the correct certificate in this deployment? `https://<appliance_ip>:8282`

**Comment by mattstocum** [comment]
@andrewtchin Yes, Admiral started properly using the same certificate.

**Comment by andrewtchin** [comment]
@reasonerjt could you triage this?

**Comment by mattstocum** [comment]
On further inspection with the 1.2.0 release, I have some new information. harbor_startup.service is what's failing to start

```
systemctl status harbor_startup.service
● harbor_startup.service - Harbor Startup Configuration
   Loaded: loaded (/usr/lib/systemd/system/harbor_startup.service; disabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Wed 2017-09-13 17:58:07 UTC; 6min ago
     Docs: http://github.com/vmware/harbor
  Process: 797 ExecStartPre=/usr/bin/bash /etc/vmware/harbor/configure_harbor.sh (code=exited, status=1/FAILURE)

Sep 13 17:58:07 anchorage.lebow.drexel.edu systemd[1]: Starting Harbor Startup Configuration...
Sep 13 17:58:07 anchorage.lebow.drexel.edu bash[797]: cp: cannot stat '/data/admiral/cert/ca.crt': No such file or directory
Sep 13 17:58:07 anchorage.lebow.drexel.edu systemd[1]: harbor_startup.service: Control process exited, code=exited status=1
Sep 13 17:58:07 anchorage.lebow.drexel.edu systemd[1]: Failed to start Harbor Startup Configuration.
Sep 13 17:58:07 anchorage.lebow.drexel.edu systemd[1]: harbor_startup.service: Unit entered failed state.
Sep 13 17:58:07 anchorage.lebow.drexel.edu systemd[1]: harbor_startup.service: Failed with result 'exit-code'.

```

After further testing, it looks like the certificate needs to be omitted from Management Portal (port 8282) rather than the File Server. I guess the Admiral startup generates /data/admiral/cert/ca.crt on boot, and Harbor is checking for the existence of the file. I believe the proper Work Around steps would be to boot them VM once using self-signed certs for all services, shutdown, add CA signed certs to both locations, then boot the VM.

**Comment by andrewtchin** [comment]
Thanks for the additional info we'll take a look at this

**Comment by andrewtchin** [comment]
From slack 
```
When Admiral redirects to vCenter for SSO, vCenter is redirecting back to Admiral’s IP, rather than the hostname


6 replies
lazo [7 days ago] 
@mattstocum (cc @mwilliamson) vCenter SSO is using Admiral address which is defined when a registration towards that vCenter is made. In order host name to be used the registration when installing VIC should be done with that hostname (edited)


mattstocum [2 days ago] 
So…how do I do that? I’m just following the first run that happens when you first install the OVA, and use the hostname everywhere possible from the initial deployment of the OVA


lazo [2 days ago] 
Don't know if it's possible currently out of the box, from reading the code, the installer is always using the IP address
https://github.com/vmware/vic-product/blob/0dc963d0427e11ef0181261c74d321a019689e76/installer/fileserver/tasks.go#L99
```

**Comment by andrewtchin** [comment]
@mattstocum just to be clear - the issue you described in slack about vCenter redirecting back to Admiral's IP instead of hostname seems different than what you wrote in this issue. Are these 2 separate issues?

**Comment by mattstocum** [comment]
@andrewtchin yes, two separate issues. Sorry for the confusion.

**Comment by andrewtchin** [comment]
Cool 797 is for the described issue, I'm opening another for the redirect issue

**Comment by andrewtchin** [comment]
The cause of this is that we don't put the ca cert in `/data/admiral/cert/ca.crt` so that file doesnt exist and thats why harbor fails to star
