### ISSUE TITLE
Update build for vic-ui repo

### ISSUE THREAD

**Issue by andrewtchin** [vmware/vic-product#803]
**User Statement:**

As a developer I want to pull in the VIC UI artifact from the vic-ui build.

**Acceptance Criteria:**
- [ ] Determine what bucket to get vic-ui build from
- [ ] Update OVA build to pull in artifact

**Comment by andrewtchin** [comment]
Pending creation of vic-ui repo and build setup

**Comment by zjs** [comment]
Removing estimate based on grooming meeting.

**Comment by andrewtchin** [comment]
verify that this work has already been done

**Comment by mdharamadas1** [comment]
This has been taken care in `vic` repo by @jooskim
