### ISSUE TITLE
Activate existing OVA CI Build pipeline

### ISSUE THREAD

**Issue by andrewtchin** [vmware/vic-product#804]
**User Statement:**

As a developer I want to build the OVA when any of its components has a new artifact.

**Details:**
When any of Admiral, Harbor, Engine, UI plugin push a new artifact, run the OVA build

Pipeline steps are already existing in `drone.yml` file but commented. This issue involves uncommenting those steps, run and resolve any issues, build server (used for packer) assignment.
 
**Acceptance Criteria:**
- [ ] Automated build produces an OVA
- [ ] OVA is uploaded to `vic-product-ova-builds`
- [ ] Existing `dinv` is renamed to DCH

**Comment by mdharamadas1** [comment]
Existing CI setup where we have a VM running to build OVA doesn't seem reliable in the sense that builds don't pass all the time (not consistent). Also, there are some manual steps involved in setting up that builder VM including checking out repo code.
So I'm going to stop working on this until the container based build process is available.

**Comment by mdharamadas1** [comment]
I will resume working on this using the new build process (#804).
