### ISSUE TITLE
Document external PSC registration script

### ISSUE THREAD

**Issue by stuclem** [vmware/vic-product#808]
Per PR https://github.com/vmware/vic-product/pull/778, that allows you to register VIC appliance with an external PSC. This will be in 1.2.1.

**Comment by stuclem** [comment]
In the short term, we need to document this procedure for 1.2.0:
https://gist.github.com/anchal-agrawal/b80d87ee6865c4a2ee0c7b1569674c37

**Comment by anchal-agrawal** [comment]
Thanks @stuclem - this is needed only for 1.2.0. 1.2.1 will include the fix and the workaround won't be needed.
