### ISSUE TITLE
vCenter redirects to Admiral IP rather than hostname after login

### ISSUE THREAD

**Issue by mattstocum** [vmware/vic-product#816]
**VIC Product version:**

OVA vic-v1.2.0-d0ea01c2

**Deployment details:**

vCenter 6.5 VSA 6.5.0.5100

**Steps to reproduce:**

1. Deploy OVA and register with vCenter
2. Log in to Admiral

**Actual behavior:**

vCenter SSO service redirects to https://<<admiral IP>>:8282/ and the browser gives a certificate warning due to the hostname mismatch. Ignoring the browser warning, or marking the certificate as trusted for the IP does allow normal use of Admiral.

**Expected behavior:**

vCenter SSO service redirects to https://<<admiral hostname>>:8282/ and the browser presents a trusted certificate.

**Additional details as necessary:**

The reason why this is an issue for me is that the CA my employer has a subscription with does not allow us to get SSL certificates for IP addresses, or to include an IP address as a SAN in the certificate. We are only able to use hostnames.

**Comment by anchal-agrawal** [comment]
See https://github.com/vmware/vic-product/issues/815#issue-257832511 for the code related to this issue.

**Comment by andrewtchin** [comment]
Workaround is to manually verify that the cert presented in the browser is the one from the server as described in https://vmware.github.io/vic-product/assets/files/html/1.2/vic_vsphere_admin/obtain_appliance_certs.html

**Comment by andrewtchin** [comment]
Open an issue to use transient hostname when we switch to photon 2.0
https://bugzilla.eng.vmware.com/show_bug.cgi?id=1865714
