### ISSUE TITLE
Documentation does not make the process of supplying intermediate certificates clear

### ISSUE THREAD

**Issue by mattstocum** [vmware/vic-product#818]
**VIC Product version:**

OVA vic-v1.2.0-d0ea01c2

**Additional details as necessary:**

The documentation for section [Deploy the Appliance](https://vmware.github.io/vic-product/assets/files/html/1.2/vic_vsphere_admin/deploy_vic_appliance.html), does not state how to supply intermediate certificates if necessary.  From what I've been able to test, the proper procedure is to concatenate the host certificate, followed by intermediate certificates with each intermediate certificate coming before the certificate that signed it, into the SSL certificate fields in the vApp options.

For example, if you have a certificate host.cer that is signed by intermediate certificate interB.cer, which is signed by intermediate certificate interA.cer, which is signed by CA root certificate ca.cer, sections 4.2 and 5.2 should contain the contents of host.cer, followed by interB.cer, followed by interA.cer. Now, as long as ca.cer is trusted by the client system, the certificate on ports 9443, 8282, and 443 will be trusted by the client system. Otherwise, at a minimum, interB.cer would need to be explicitly trusted by the client system.

**Comment by andrewtchin** [comment]
@stuclem 
This procedure is correct. Here is an example I used:
Given these files: 
```
ca.cert.crt - CA certificate
sc-rdops-vm09-dhcp-27-198.eng.vmware.com.key.pem - Server key
sc-rdops-vm09-dhcp-27-198.eng.vmware.com.key.pkcs8 - Server key in PKCS8 format
sc-rdops-vm09-dhcp-27-198.eng.vmware.com.cert.pem - Server certificate signed by CA
```

Generate the certificate chain by:
```
cp sc-rdops-vm09-dhcp-27-198.eng.vmware.com.cert.pem sc-rdops-vm09-dhcp-27-198.eng.vmware.com.cert.pem.chain
cat ca.cert.crt >> sc-rdops-vm09-dhcp-27-198.eng.vmware.com.cert.pem.chain
```

When deploying a new appliance supply:
- the contents of `ca.cert.crt` for 
- the contents of `sc-rdops-vm09-dhcp-27-198.eng.vmware.com.cert.pem.chain`
- the contents of `sc-rdops-vm09-dhcp-27-198.eng.vmware.com.key.pkcs8`

To update the certificates on an existing appliance:
- Shut down guest OS
- Edit Settings -> vApp Options
- Paste the new values in the appropriate fields
- Power on the appliance
- Verify that the certificate chain is displayed 

Without chained server cert:
![screen shot 2017-09-14 at 5 25 39 pm](https://user-images.githubusercontent.com/1649165/30458567-c25afeb8-9971-11e7-9a36-ddad5870fdac.jpg)

With chained server cert:
![screen shot 2017-09-14 at 4 58 55 pm](https://user-images.githubusercontent.com/1649165/30457703-06418614-996e-11e7-9aae-a0fde604d297.jpg)

I believe that with the current implementation the certificate chain provided for the server certificate field should include all the intermediates and the root certificate so that the full chain is presented to the browser. In the next release we can look at automatically taking that from the CA cert input field.  I'm testing with an intermediate now.

**Comment by andrewtchin** [comment]
Verified that the cert chain should include intermediates and roots 
![screen shot 2017-09-14 at 6 02 38 pm](https://user-images.githubusercontent.com/1649165/30459535-fae68554-9976-11e7-9545-3c9ac2d25f11.jpg)

```
ca.cert.crt - Root CA cert
intermediate.cert.pem - Intermediate CA cert
ca-chain.cert.pem - Chain of intermediate CA cert and root CA cert
sc-rdops-vm09-dhcp-27-198.eng.vmware.com.key.pem - Server key
sc-rdops-vm09-dhcp-27-198.eng.vmware.com.key.pem.pkcs8 - Server key in PKCS8 format
sc-rdops-vm09-dhcp-27-198.eng.vmware.com.cert.pem - Server cert
sc-rdops-vm09-dhcp-27-198.eng.vmware.com.cert.pem.full - Full chain of server cert including intermediate and root
```

Generate the full chain:
```
cat sc-rdops-vm09-dhcp-27-198.eng.vmware.com.cert.pem intermediate.cert.crt ca.cert.crt > server-chain.pem
```

**Comment by andrewtchin** [comment]
Also they symptoms of providing a cert format other than PKCS8 are
- Admiral fails to start (unable to access Admiral UI at `https://IP:8282`
- Admiral startup process failed
```
root@localhost [ ~ ]# systemctl status admiral_startup
● admiral_startup.service - Admiral Startup Configuration
   Loaded: loaded (/usr/lib/systemd/system/admiral_startup.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Thu 2017-09-14 23:53:48 UTC; 1min 51s ago
     Docs: http://github.com/vmware/admiral
  Process: 984 ExecStartPost=/usr/bin/systemctl start admiral.service (code=exited, status=1/FAILURE)
 Main PID: 696 (code=exited, status=0/SUCCESS)

Sep 14 23:52:40 localhost.localdomain bash[696]: Certificate was added to keystore
Sep 14 23:52:40 localhost.localdomain bash[696]: [Storing /data/admiral/cert/trustedcertificates.jks]
Sep 14 23:52:40 localhost.localdomain bash[696]: Enable admiral startup
Sep 14 23:52:40 localhost.localdomain bash[696]: Created symlink from /etc/systemd/system/multi-user.target.wants/admiral_startup.service to /usr/lib/systemd/system/admi...up.service.
Sep 14 23:52:40 localhost.localdomain bash[696]: Created symlink from /etc/systemd/system/multi-user.target.wants/admiral.service to /usr/lib/systemd/system/admiral.service.
Sep 14 23:53:48 localhost.localdomain systemd[1]: admiral_startup.service: Control process exited, code=exited status=1
Sep 14 23:53:48 localhost.localdomain systemctl[984]: Job for admiral_default_users.service failed because the control process exited with error code. See "systemctl stat...r details.
Sep 14 23:53:48 localhost.localdomain systemd[1]: Failed to start Admiral Startup Configuration.
Sep 14 23:53:48 localhost.localdomain systemd[1]: admiral_startup.service: Unit entered failed state.
Sep 14 23:53:48 localhost.localdomain systemd[1]: admiral_startup.service: Failed with result 'exit-code'.
Hint: Some lines were ellipsized, use -l to show in full.
```
- Admiral process failed
```
root@localhost [ ~ ]# systemctl status admiral
● admiral.service - Admiral is a highly scalable and very lightweight Container Management platform for deploying and managing container based applications.
   Loaded: loaded (/usr/lib/systemd/system/admiral.service; enabled; vendor preset: enabled)
   Active: activating (auto-restart) (Result: exit-code) since Thu 2017-09-14 23:55:32 UTC; 3s ago
     Docs: https://github.com/vmware/admiral
  Process: 7483 ExecStopPost=/usr/bin/docker rm vic-admiral (code=exited, status=0/SUCCESS)
  Process: 7472 ExecStop=/usr/bin/docker stop vic-admiral (code=exited, status=0/SUCCESS)
  Process: 7362 ExecStart=/etc/vmware/admiral/start_admiral.sh (code=exited, status=1/FAILURE)
 Main PID: 7362 (code=exited, status=1/FAILURE)

Sep 14 23:55:32 localhost.localdomain systemd[1]: admiral.service: Unit entered failed state.
Sep 14 23:55:32 localhost.localdomain systemd[1]: admiral.service: Failed with result 'exit-code'.
```

Solution:
- Shut down Guest OS
- Edit vApp Options to replace the Management Portal key with the correct PKCS8 format key
- Power on appliance

**Comment by stuclem** [comment]
Thanks @mattstocum and @andrewtchin. I'll get this into a 1.2 update in the near future.

**Comment by stuclem** [comment]
See PR https://github.com/vmware/vic-product/pull/817, which implements https://github.com/vmware/vic-product/issues/797

**Comment by stuclem** [comment]
See also #1600

**Comment by andrewtchin** [comment]
Procedure for 1.4 is in #1600
