### ISSUE TITLE
vmware.github.io/vic doesn't render some content correctly on mobile

### ISSUE THREAD

**Issue by stuclem** [vmware/vic-product#82]
_From @anchal-agrawal on December 17, 2016 17:51_

The top navigation bar and the Fork button don't render correctly on mobile browsers.

On the mobile site, the nav bar appears as a grey Menu button that's not clearly visible. Also, the Fork button doesn't spread across the entire text:

![mobile-site](https://cloud.githubusercontent.com/assets/4361620/21288609/abce29d0-c44d-11e6-8281-a5e6ac0c44ae.png)

On the desktop site from a mobile browser, the nav bar isn't clearly visible:

![desktop-site](https://cloud.githubusercontent.com/assets/4361620/21288608/abce0bf8-c44d-11e6-8735-8483c4cbe406.png)

Repro'd on Chrome and Firefox on Android 7.1.1 with vmware.github.io/vic and vmware.github.io/vic-product.

_Copied from original issue: vmware/vic#3534_

**Comment by stuclem** [comment]
_From @anchal-agrawal on December 17, 2016 17:52_

Assigned to @stuclem for triage.

**Comment by stuclem** [comment]
@anchal-agrawal sorry for the delay - only just noticed this one. I just this checked on Safari and Chrome on iOS 10.2.1 and, other than the menu bar at the top being grey on grey, it doesn't suffer from the other problems that you describe on Android.

However, I checked https://vmware.github.io/harbor and https://vmware.github.io/admiral on iOS and they both have the menu bars with a grey background, so something is wrong with my tagging somewhere.  

Thanks for spotting this!

**Comment by stuclem** [comment]
Applies to both https://vmware.github.io/vic and https://vmware.github.io/vic-product.

**Comment by stuclem** [comment]
@anchal-agrawal this turned out to be a simple as the link texts in the top menu being too long. Harbor and Admiral don't have the same problem because the product names are short. I truncated the texts and the page now renders correctly on desktop and on iOS. I haven't tested Android. Can you please have a go?

https://vmware.github.io/vic-product/
https://vmware.github.io/vic/

I was unable to reproduce the issue with the Fork text going outside of the green button. This renders OK on iOS. If the text still wraps we can shorten it to "Fork me on GitHub".

**Comment by anchal-agrawal** [comment]
Thanks @stuclem - the issue shown in the second screenshot has been resolved! However, both issues in the first screenshot remain.

I suppose we could do without fixing the light gray Menu button, but the Fork button - I'd say we replace the "Fork..." text with something else, since it isn't a Fork" button" - it's simply a link to the GitHub repo. We could replace the text with something like "Visit the repo on GitHub" or just get rid of the button since there's a "Fork me" link in the picture above it.

**Comment by stuclem** [comment]
Reduced the font size of the product name a tiny bit and replaced the green button text with Go to Github:
https://stuclem.github.io/vic/

The MENU still jumps out of the grey bar on phones when held vertically, but the product name is too long to avoid this happening. Renders correctly on tablet and desktop. I think that phones are not our primary target device, so I vote that we don't compromise tablet/desktop by making phones perfect.

@anchal-agrawal if you agree I'll make the same changes in https://stuclem.github.io/vic-product/

**Comment by anchal-agrawal** [comment]
Looks good - for the button text, the correct capitalization is "GitHub".

**Comment by stuclem** [comment]
Fixed button text. Replicated the fixes in https://stuclem.github.io/vic-product/. Without the "Engine", the vic-product header renders correctly and the MENU appears in the correct place on all platforms except iPhone 5. @anchal-agrawal can we live with that?

**Comment by anchal-agrawal** [comment]
Absolutely! Thanks.
