### ISSUE TITLE
Documentation request for backup instructions and strategy BugRef: 1960802

### ISSUE THREAD

**Issue by dbarkelew** [vmware/vic-product#824]
Request to have a backup instruction and/or strategy documented for the VIC solution. Including all of VIC's components VIC-Engine, Harbor and Admiral.

BugRef: 1960802

**Comment by corrieb** [comment]
I was halfway through this exercise and then VMworld got in the way.

**Comment by stuclem** [comment]
@corrieb has produced a doc:
https://docs.google.com/document/d/17kSqNdD6C69UdLhZ9f2bA0MNUB1k00IQnsrorkA27lU/edit

I need to convert this to markdown, break it up, and integrate it into the vSphere admin doc.
