### ISSUE TITLE
Document that dch-photon creates an anonymous volume

### ISSUE THREAD

**Issue by corrieb** [vmware/vic-product#825]
The anonymous volume created by dch-photon is like a little poop it will leave in your datastore. It's a helpful illustration as to why you might want a real volume with dch-photon, but the user needs to be aware that they will not only need a "default" volume store, but they'll need to perform manual cleanup. 

Once we have `docker rm -v`, we won't need this manual step anymore.

**Comment by stuclem** [comment]
@corrieb I noticed when I was playing with `dch-photon` that it created about 20 odd volumes that didn't go away when I destroyed the containers.

**Comment by stuclem** [comment]
Closed in https://github.com/vmware/vic-product/pull/813
