### ISSUE TITLE
Documentation about VIC appliance per vCenter

### ISSUE THREAD

**Issue by emeirell** [vmware/vic-product#826]
Documentation says "You can only deploy one vSphere Integrated Containers appliance per vCenter Server instance"
https://vmware.github.io/vic-product/assets/files/html/1.2/vic_overview/introduction.html

It appears to be a documentation issue.
It was nice to know if it's incorrect or why of this limitation.

**Comment by mlh78750** [comment]
I'm looking into this and will report back. See https://github.com/vmware/vic-product/issues/740 for discussion.

**Comment by mlh78750** [comment]
Pending the change asked for in https://github.com/vmware/vic-product/issues/740#issuecomment-329905230 you should see this note removed. 

It is supported to have more than one VIC appliance per VC.
