### ISSUE TITLE
Document changes to cname requirements

### ISSUE THREAD

**Issue by stuclem** [vmware/vic-product#83]
_From @stuclem on February 22, 2017 14:33_

Per https://github.com/vmware/vic/issues/3946

_Copied from original issue: vmware/vic#4001_

**Comment by stuclem** [comment]
Not in 1.1.

**Comment by stuclem** [comment]
Definitely in 1.2.

**Comment by stuclem** [comment]
Looking at comments from @gigawhitlocks in https://github.com/vmware/vic/issues/3946#issuecomment-318466483, it looks like there was no change to `--tls-cname` behavior in the end. 

We currently do document how to auto-generate a cert using `--tls-cname` and by specifying a static IP on the VCH. @gigawhitlocks can you please confirm that the following docs are still correct?

- [Restrict Access to the Docker API with Auto-Generated Certificates](https://github.com/vmware/vic-product/blob/master/docs/user_doc/vic_vsphere_admin/vch_installer_options.md#restrict_auto)
- [Set static IP address on client network](https://github.com/vmware/vic-product/blob/master/docs/user_doc/vic_vsphere_admin/vch_installer_options.md#--client-network-ip---public-network-ip---management-network-ip)

Thanks!

**Comment by gigawhitlocks** [comment]
Correct @stuclem `--tls-cname` is unchanged. Docs are correct. For the networking options (second link) you should check with @hmahmood

**Comment by hmahmood** [comment]
@gigawhitlocks is this statement still correct (taken from the second link)? 
>If you assign a static IP address to the VCH endpoint VM on the client network by setting the --client-network-ip option, and you do not specify one of the TLS options, vic-machine create uses this address as the Common Name with which to auto-generate trusted CA certificates. If you do not specify --tls-cname, --no-tls or --no-tlsverify, two-way TLS authentication with trusted certificates is implemented by default when you deploy the VCH with a static IP address on the client network. If you assign a static IP address to the endpoint VM on the client network, vic-machine create creates the same certificate and environment variable files as described in the --tls-cname option.

**Comment by gigawhitlocks** [comment]
Yeah

**Comment by stuclem** [comment]
Excellent, thank you @gigawhitlocks and @hmahmood! I'll happily close this issue.
