### ISSUE TITLE
Upgrading the VIC appliance fails with external PSC BugRef 1962217

### ISSUE THREAD

**Issue by dbarkelew** [vmware/vic-product#837]
**BugRef:** 1962217

**VIC Product version:**
v1.1.1-10711-56a309f

**Deployment details:**
Deployed with Windows vCenter and External PSC also Windows. 
vSphere version=6.0.0, build=3634793

**Steps to reproduce:**
Follow:
https://vmware.github.io/vic-product/assets/files/html/1.2/vic_vsphere_admin/upgrade_appliance.html

In attempt to fix PSC registration follow:
https://vmware.github.io/vic-product/assets/files/html/1.2/vic_vsphere_admin/ts_register_psc_fails.html

**Actual behavior:**
Upgrade script registration fails with message"Failed to register appliance. Check vCenter target and credentials."

After following manual registration upgrade does work partially. Admiral no longer has container hosts. These can be added back in, however these do not allow for deploying images.

**Comment by anchal-agrawal** [comment]
@stuclem Proposed additions to https://vmware.github.io/vic-product/assets/files/html/1.2/vic_vsphere_admin/upgrade_appliance.html:

In the **Procedure** section, step 12 (added material is italicized for clarity):

---

When prompted, enter the address of the vCenter Server instance on which you deployed the new appliance and the Single Sign-On credentials of a vSphere administrator account. _If you are using an external PSC instance, also provide the FQDN of the PSC instance and the PSC Admin Domain when prompted. If you are using an embedded PSC, you can leave the PSC input fields blank._ The script requires these credentials to register the new version of vSphere Integrated Containers with the VMware Platform Services Controller.

---
