### ISSUE TITLE
OVA upgrade 1.1.1 to 1.2.y fails during harbor's data migration

### ISSUE THREAD

**Issue by lgayatri** [vmware/vic-product#841]
[upgrade.txt](https://github.com/vmware/vic-product/files/1317686/upgrade.txt)
1.1.1 OVA: vic-v1.1.1_56a309fb.ova
1.2.y OVA: https://storage.googleapis.com/vic-product-ova-builds/vic-5b3261d8-devrc3.ova

Had inventory of VCH, containers, projects, users on 1.1.1 which I migrated to 1.2.y
```
root@vic-st-h2-186 [ /etc/vmware/upgrade ]# ./upgrade_1.1_to_1.2.sh
Getting password from harbor.cfg
Enter vCenter Server FQDN or IP: wdc-stvc3944-152-dhcp212.eng.vmware.com
Enter vCenter Administrator Username: administrator@vsphere.sgp.dbs.com
Enter vCenter Administrator Password:
If using an external PSC, enter the FQDN of the PSC instance (leave blank otherw                                                                                                                     ise): wdc-stvc3944-152-dhcp211.eng.vmware.com
If using an external PSC, enter the PSC Admin Domain (leave blank otherwise): vs                                                                                                                     phere.sgp.dbs.com
Starting upgrade 2017-09-20 12:00:46 +0000 UTC
Preparing upgrade environment
Disabling and stopping Admiral and Harbor path startup
Finished preparing upgrade environment
Performing pre-upgrade checks
Starting Admiral upgrade
[=] Shutting down Harbor and Admiral
[=] Upgrade Admiral
Admiral migration complete
Archiving previous Admiral data
Cleaning up
Admiral upgrade complete
Starting Admiral
Updating Admiral configuration
Performing pre-upgrade checks
Starting Harbor upgrade
[=] Shutting down Harbor
[=] Migrating Harbor data
Harbor up head command failed
```
Attached upgrade log

**Comment by anchal-agrawal** [comment]
@reasonerjt Adding you as assignee - please help triage this.

**Comment by reasonerjt** [comment]
we have upgraded successfully, it's probably a usage error I will check with @lgayatri

**Comment by lgayatri** [comment]
@reasonerjt 
Yesterday, after powering on the new OVA, I would have accidentally reinitialized causing the Database password to be over written  and there by causing upgrade to fail. I redid the upgrade steps and could upgrade successfully, here is the snippet
```

root@vic-st-h2-186 [ /etc/vmware/upgrade ]# ./upgrade_1.1_to_1.2.sh
Getting password from harbor.cfg
Enter vCenter Server FQDN or IP: wdc-stvc3944-152-dhcp212.eng.vmware.com
Enter vCenter Administrator Username: administrator@vsphere.sgp.dbs.com
Enter vCenter Administrator Password:
If using an external PSC, enter the FQDN of the PSC instance (leave blank otherwise): wdc-stvc3944-152-dhcp211.eng.vmware.com
If using an external PSC, enter the PSC Admin Domain (leave blank otherwise): vsphere.sgp.dbs.com
Starting upgrade 2017-09-21 06:24:11 +0000 UTC
Preparing upgrade environment
Disabling and stopping Admiral and Harbor path startup
Finished preparing upgrade environment
Performing pre-upgrade checks
Starting Admiral upgrade
[=] Shutting down Harbor and Admiral
[=] Upgrade Admiral
Admiral migration complete
Archiving previous Admiral data
Cleaning up
Admiral upgrade complete
Starting Admiral
Updating Admiral configuration
Performing pre-upgrade checks
Starting Harbor upgrade
[=] Shutting down Harbor
[=] Migrating Harbor data
[=] Finished migrating Harbor data
[=] Migrating Harbor configuration
[=] Finished migrating Harbor configuration
[=] Importing project data into Admiral
[=] Finished importing project data into Admiral
[=] Mapping project data into Harbor
[=] Finished mapping project data into Harbor
Harbor upgrade complete
Starting Harbor
Enabling and starting Admiral and Harbor path startup
Upgrade script complete. Exiting.
```
Was able to login to :8282 and :9443 but VCH data seems to be messed up. Will file separate PR for that

**Comment by lgayatri** [comment]
Have double entries for VCHs. 
![image](https://user-images.githubusercontent.com/25006749/30682240-7aa8a016-9ec6-11e7-8c2f-957cf8adedf7.png)

**Comment by mhagen-vmware** [comment]
Can we please release note this, with what not to do? It seems like this could be a fairly common issue with customers, and I think we should really try to do what we can to prevent this from happening as well..

**Comment by stuclem** [comment]
@mhagen-vmware what do you want me to document in the release notes? The double entries for VCHs?

**Comment by mhagen-vmware** [comment]
Ideally: how did a user get into the situation, what it looks like when you are in the situation, and how to resolve the situation once you are in it ( @lgayatri )

**Comment by andrewtchin** [comment]
@lgayatri How did you resolve this?

**Comment by anchal-agrawal** [comment]
> @lgayatri: Was able to login to :8282 and :9443 but VCH data seems to be messed up. Will file separate PR for that

https://github.com/vmware/vic-product/issues/847 has more details.

**Comment by stuclem** [comment]
@lgayatri I'm still not very clear about what I am supposed to document here. Tell people not to hit the reinitialize button? Thanks in advance for any clarifications!

**Comment by lgayatri** [comment]
@stuclem , Yes, user should NOT hit reinitialize button before running the upgrade.sh . Accidentally hitting reinitialize will cause complete damage.

**Comment by anchal-agrawal** [comment]
We have noted this in our docs already. Step 10: https://vmware.github.io/vic-product/assets/files/html/1.2/vic_vsphere_admin/upgrade_appliance.html

**Comment by stuclem** [comment]
@lgayatri and @anchal-agrawal we also have more information about when and when not to hit the initialize button in PR https://github.com/vmware/vic-product/pull/852, which I will merge when we release 1.2.1, since it contains information specific to 1.2.1.

**Comment by lgayatri** [comment]
Ok @stuclem
