### ISSUE TITLE
Update OVA upgrade test plans

### ISSUE THREAD

**Issue by anchal-agrawal** [vmware/vic-product#846]
We should update the [OVA upgrade test plan](https://github.com/vmware/vic/blob/master/tests/manual-test-cases/Group19-VIC-Product/19-8-VIC-Upgrade.md) for the following upgrade scenarios:

* 1.1.1 to 1.2.0
* 1.1.0 to 1.2.1
* 1.2.0 to 1.2.1

**Comment by mdubya66** [comment]
let's add 1.1.1 to 1.2.0 to 1.2.1
