### ISSUE TITLE
Add links to Docker 101 education resources

### ISSUE THREAD

**Issue by stuclem** [vmware/vic-product#848]
Per comment from @hickeng we need to provide links to Docker resources for vSphere admins who don't know Docker, for example: http://labs.play-with-docker.com/

A decent Docker terminology guide would be useful too.

@hickeng @corrieb @mlh78750 can you provide some pointers to good ones here, please?

**Comment by stuclem** [comment]
Added the following links in the overhauled networking overview: 
- [Docker container networking](https://docs.docker.com/engine/userguide/networking/)
- [Docker Networking Options video](https://www.youtube.com/watch?v=Yr6-2ddhLVo) 
- [vSphere Integrated Containers Networking Overview video](https://www.youtube.com/watch?v=QLi9KasWLCM)

**Comment by stuclem** [comment]
Some more resources to add in the docs: 

- https://docs.docker.com/glossary/
- https://docs.docker.com/get-started/
- [What is a Container? (Ben)](https://www.youtube.com/watch?v=EnJ7qX9fkcU)
- [The Benefits of Containers (Ben)](https://www.youtube.com/watch?v=cCTLjAdIQho)
- [VMware Cloud Native YouTube Channel](https://www.youtube.com/channel/UCdkGV51Nu0unDNT58bHt9bg)
- [Container Registry](https://www.youtube.com/watch?v=76rX4s73MrM)

**Comment by stuclem** [comment]
All of these resources are now included in the doc. @hickeng can you think of any more? Thanks!

**Comment by stuclem** [comment]
There are also some good Harbor videos here: https://www.youtube.com/channel/UCSxaozHKrX3F0UnZeYe5Itg

**Comment by stuclem** [comment]
More links can surely be added, so moving this into 1.3.

**Comment by pescerosso** [comment]
I categorized all the lighboards that we have in this ppt. some of them are uploaded on the official vmware pages
[Lightboard map.pptx](https://github.com/vmware/vic-product/files/1482953/Lightboard.map.pptx)

**Comment by stuclem** [comment]
Also: http://training.play-with-docker.com/

**Comment by stuclem** [comment]
Thanks @pescerosso - there are definitely some vids in your pptx that I have not seen before.
