### ISSUE TITLE
Minor documentation issues on docker client certificate names.

### ISSUE THREAD

**Issue by reenberg** [vmware/vic-product#850]
In the documentation of VIC 1.2: [Use and Limitations of vSphere Integrated](https://vmware.github.io/vic-product/assets/files/html/1.2/vic_app_dev/container_limitations.html), at the end under "Using docker-compose with TLS" it says that you need to name the client certificate and keys `client_cert.pem` and `client key.pem` (I assume the missing underscore is also a mistake).  

However, in the docker documentation on [environment variables](https://docs.docker.com/compose/reference/envvars/#docker_tls_verify) it is stated that they should be named `cert.pem` and `key.pem`.  I am using these names (*cert.pem* and *key.pem*) in combination with `DOCKER_CERT_PATH`, and it works.  I have not confirmed if the names from the VIC 1.2 documentation works or not.

In the VIC 1.2 documentation (same place as above), you also mention that you need to add `COMPOSE_TLS_VERSION=TLSv1_2` if you want to use `docker-compose`.  It would be nice, if that could be added to the environment file that `vic-machine` generates when creating a VCH.

**Comment by stuclem** [comment]
Thank you @reenberg, I get this fixed ASAP.
