### ISSUE TITLE
Typo `admrial` in upgrade script failure message causes command to fail if you copy/paste it

### ISSUE THREAD

**Issue by stuclem** [vmware/vic-product#857]
**VIC Product version:**

1.2.1 RC 3 `vic-5b3261d8-devrc3.ova`

**Deployment details:**

Upgrading 1.2.0 GA to 1.2.1.

**Steps to reproduce:**

1. Attached disk from 1.2.0 appliance to newly deployed 1.2.1 appliance.
2. SSH'd into new appliance and ran upgrade script.
3. Upgrade failed (will potentially file another issue about that).
4. Attempted to run upgrade script again, saw message: <pre>Performing pre-upgrade checks
Admiral upgrade container already exists
If upgrade is not already running, execute the following command and rerun the upgrade script:
   docker rm -f vic-upgrade-admrial</pre>
5. Copied and pasted the `docker rm` command, which failed because of the typo `admrial` in the command provided.

**Actual behavior:**

Typo`admrial`

![upgrade_typo](https://user-images.githubusercontent.com/16718369/30744908-6c81076a-9fa4-11e7-879d-e2c4bf370d7a.png)

**Expected behavior:**

No typo.

**Comment by anchal-agrawal** [comment]
I'm fixing this with #839. Closing.
