### ISSUE TITLE
Update upgrade script name in docs

### ISSUE THREAD

**Issue by stuclem** [vmware/vic-product#859]
The script to upgrade the VIC appliance is named `upgrade_1.1_to_1.2.sh`. However, you use this script to upgrade from 1.2.0 to 1.2.1 as well as to upgrade from 1.1 to 1.2.

Would `upgrade_to_1.2.sh` be more appropriate? Is it sufficiently clear that this script is for x.y.z update releases as well as for x.y releases? 

Ideally, I think that the script filename should include the full version number, i.e. `upgrade_to_1.2.1.sh`.

**Comment by anchal-agrawal** [comment]
@stuclem The current upgrade script `upgrade_1.1_to_1.2.sh` is not meant for upgrading 1.2.x to 1.2.y. We should revise the note in https://vmware.github.io/vic-product/assets/files/html/1.2/vic_vsphere_admin/upgrade_appliance.html for the 1.2.0 release to say:

> If you deployed a 1.1.x version of the vSphere Integrated Containers appliance, you can upgrade your existing installation to 1.2.~x~0. ~You can also upgrade a 1.2.x appliance to a later 1.2.y update release.~

@andrewtchin does the above look good?

To upgrade to 1.2.0+ releases, such as 1.1.x to 1.2.1 or 1.2.0 to 1.2.1, the `upgrade_1.1_to_1.2.sh` will be replaced by `upgrade.sh`. It requires the same input fields (vSphere target, user, password, (optional) external PSC FQDN, (optional) PSC admin domain) but will detect whether the upgrade-from OVA version is 1.1.x or 1.2.y and perform the upgrade accordingly.

**Comment by anchal-agrawal** [comment]
We can leave this issue open for doc purposes - the fix for the script is in #855.

**Comment by stuclem** [comment]
OK, thanks @anchal-agrawal. I'll check this in the next OVA build and update the doc accordingly.
