### ISSUE TITLE
Document how to add VCHs/Docker hosts to projects from Projects view

### ISSUE THREAD

**Issue by stuclem** [vmware/vic-product#865]
I don't think that we have this in the docs yet, namely adding a VCH by doing **Administration** > **Projects** > **Details** > **Infrastructure** > **+NEW**.

This does seem to be exactly the same as adding a VCH in the **Home** > **Infrastructure** tab, but maybe we need to check whether there is a difference for the DevOps and Cloud admins.

**Comment by alextopuzov** [comment]
DevOps admins cannot manage hosts. They can only view the currently added to MP hosts.

As for cloud admins the procedure is identical.

**Comment by stuclem** [comment]
So, this a non-issue?

**Comment by alextopuzov** [comment]
That's how i see it.

**Comment by stuclem** [comment]
Closing, then.
