### ISSUE TITLE
Automate build of docs in master and push to vmware.github.io

### ISSUE THREAD

**Issue by stuclem** [vmware/vic-product#877]
Ideally, we would like the docs in `/vic-product/tree/master/docs/user_doc` to be built automatically. The generated HTML should also be pushed automatically to `https://vmware.github.io/vic-product/assets/files/html/workinprogress`.

**Comment by stuclem** [comment]
@alextopuzov is currently investigating Travis CI as a means of doing this. https://travis-ci.org/

**Comment by stuclem** [comment]
Comment from @zjs via email:

----

This looks like it will be really useful!

I think it should be really easy to take what you had in your .travis.yml and port it over to a .drone.yml (which works a bit differently, and uses slightly different syntax) for consistency with the rest of our CI/CD infrastructure.

---

@zjs @renmaosheng, if this is relatively easy, would it be possible to implement it before 1.5? Thanks!

**Comment by lgayatri** [comment]
@stuclem ,implementing Travis will be very useful. Thanks for initiating.

**Comment by stuclem** [comment]
We have several branches of the docs, for each version of VIC. So, if and when we implement this, would it be possible to have the branch for each doc version publish to the appropriate folder in gh-pages? Namely:

- `master` publishes to a `wip` or `latest` folder
- the `1.3-docs` branch publishes to the https://github.com/vmware/vic-product/tree/gh-pages/assets/files/html/1.3 folder
- the `1.4-docs` branch (when we create it) publishes to the https://github.com/vmware/vic-product/tree/gh-pages/assets/files/html/1.4 folder, etc.

@zjs @renmaosheng what do you think?

**Comment by zjs** [comment]
That seems doable!

As an aside: I've been meaning to take another look at this now that GitHub has announced [actions](https://github.com/features/actions) as that may be a more natural way to automate this than Drone.
