### ISSUE TITLE
[OVA] Admiral container should define a volume to persist the logs there

### ISSUE THREAD

**Issue by andrewtchin** [vmware/vic-product#885]
@sergiosagu commented on [Tue Apr 11 2017](https://github.com/vmware/vic/issues/4680)

Within the OVA for 1.1 we need Admiral container to define a volume to persist the logs there, otherwise the container logs are lost when, for example, the VA is restarted and (a new) Admiral container is recreated.

**Steps to reproduce:**
Deploy VIC 1.1 OVA.
Do some operation in Admiral (e.g. add host, add certificate, whatever), and check that it will generate some logs.
Restart the VA and check whether the old logs are there.

**Actual behavior:**
Admiral container logs are brand new after restarting the VA.

**Expected behavior:**
Admiral container logs are brand new after restarting the VA, but the logs from previous Admiral containers runs are kept somewhere and are accessible.

**Additional details as necessary:**
cc @frapposelli @tgeorgiev 

---

@frapposelli commented on [Wed May 10 2017](https://github.com/vmware/vic/issues/4680#issuecomment-300556791)

We do persist admiral logs using systemd (`journalctl -u admiral.service`) so we're not losing logs at restart.

Moving to priority low

**Comment by mdubya66** [comment]
adding to 1.3 and marking high pri, per @pdaigle

**Comment by andrewtchin** [comment]
Depends on https://jira-hzn.eng.vmware.com/browse/VBV-1711

**Comment by sergiosagu** [comment]
The Jira task mentioned above has been resolved.
See commit https://github.com/vmware/admiral/commit/949511f9a6a69c3eb3672990decb243bacd60a50 for more info.
cc @stuclem

**Comment by andrewtchin** [comment]
@stuclem This will also need a doc on how to configure Admiral log retention through the config file

**Comment by morris-jason** [comment]
@stuclem 
The OVA now contains a logging configuration file for admiral at `/etc/vmware/admiral/logging-vic.properties`. User's can edit this file if the default log retention isn't enough for their use case - defaults are 1gb files with 10 rotations.
The other change in this issue is moving admiral logs to `/storage/log/admiral/`. Users should now use the log files in that directory instead of journalctl to view admiral logs.
