### ISSUE TITLE
Improve upgrade failure condition

### ISSUE THREAD

**Issue by andrewtchin** [vmware/vic-product#886]
@andrewtchin commented on [Fri Aug 04 2017](https://github.com/vmware/vic/issues/5923)

**User Statement:**
As a user I want better info when OVA upgrade fails due to resizefs unit failure

**Details:**
Add a log when the block device doesn't exist as right now we just exit 1

**Acceptance Criteria:**
- [ ] Log when block device doesn't exist in `resize_data_volume.sh`, user must delete and readd data disk on SCSI (0:1)

**Comment by zjs** [comment]
No longer seems relevant.
