### ISSUE TITLE
upgrade script for 'upgrade_1.1_to_1.2.sh' fails to locate db_password key 

### ISSUE THREAD

**Issue by awninc** [vmware/vic-product#899]
**VIC Product version:**

OVA version 1.2.0 VMWare Official

**Deployment details:**

VCSA 6.5u1, Embedded PSC

**Steps to reproduce:**

attempt to run upgrade script for VIC 'upgrade_1.1_to_1.2.sh', have password with special characters. I suspect maybe the '=' at the beginning of the password 

**Actual behavior:**

Key not found: db_password --dbpass not set and value not found in /data/harbor/harbor.cfg"

Issue appears to be related to how grep/cut are being utilized:
`grep "^db_password =" harbor.cfg | cut -d'=' -f 3` - Still truncates '=' from password value

`grep "^db_password " harbor.cfg | cut -d' ' -f 3` - returns full KV after '=' delimiter, notice the space char included after field in grep query

**Expected behavior:**

db_password key is located in harbor.cfg, KV inserted and used as db_password variable

**Logs:**

```
## Configuration file of Harbor

#The IP address or hostname to access admin UI and registry service.
#DO NOT use localhost or 127.0.0.1, because Harbor needs to be accessed by external clients.
hostname = vic.xxxxx.local

#The protocol for accessing the UI and token/notification service, by default it is http.
#It can be set to https if ssl is enabled on nginx.
ui_url_protocol = https

#The password for the root user of mysql db, change this before any production use.
#Managed by configure_harbor.sh

#Please note, I have changed all alpha characters to X's, and numeric to 1's and left in special characters for obfuscation
db_password = =11xxxx:xx?xxx

<snip snip>
```

I hope this is everything needed.

**Comment by andrewtchin** [comment]
@awninc Thanks for your bug report!
I believe the workaround for this is to provide `--dbpass` e.g. `./upgrade_1.1_to_1.2.sh --dbpass pass`

**Comment by anchal-agrawal** [comment]
Should we release note this for 1.2.1? @stuclem

**Comment by stuclem** [comment]
@anchal-agrawal and @andrewtchin since this applies to the 1.2.0 script, I don't think that we need to release note this in 1.2.1. Agree?

**Comment by anchal-agrawal** [comment]
This is present in the renamed script `upgrade.sh` as well. Pinging @andrewtchin for the release note entry.

**Comment by stuclem** [comment]
OK, in that case we need it in the 1.2.1 notes. Thanks!

**Comment by andrewtchin** [comment]
Closing as we don't use this script anymore and db passwords are internal
