### ISSUE TITLE
How to report when scan is reporting vulnerabilities

### ISSUE THREAD

**Issue by lgayatri** [vmware/vic-product#909]
![image](https://user-images.githubusercontent.com/25006749/31222708-b543f340-a9e5-11e7-9bcf-5fd3db88df3c.png)
![image](https://user-images.githubusercontent.com/25006749/31223578-68414c34-a9e8-11e7-96e9-eeab10f8f12e.png)
I do not see an option to download the vulnerability scan report. How  to interpret this output?

**Comment by gigawhitlocks** [comment]
Labelled this as both a bug and an enhancement due to this being sort of a bug-by-omission

**Comment by andrewtchin** [comment]
Issue moved to [vmware/harbor #3402](https://github.com/vmware/harbor/issues/3402) via [**ZenHub**](https://www.zenhub.com/)
