### ISSUE TITLE
Research Spike: VAC integration for OVA appliance

### ISSUE THREAD

**Issue by andrewtchin** [vmware/vic-product#911]
@frapposelli commented on [Wed Mar 15 2017](https://github.com/vmware/vic/issues/4250)

User Statement: Want to track usage of the OVA Appliance, if the user has given consent.

Acceptance Criteria: Design for supporting Phone Home (VAC) with granular properties about what is currently installed in the appliance

---

@mdubya66 commented on [Wed Mar 15 2017](https://github.com/vmware/vic/issues/4250#issuecomment-286795477)

Given this is our last sprint for 1.1 features I asked @mhagen-vmware to lower this priority. We will need to pull it into the 1.2 release. 

---

@andrewtchin commented on [Wed May 10 2017](https://github.com/vmware/vic/issues/4250#issuecomment-300574417)

Need to figure out how to have a property collector process running in OVA

---

@mdubya66 commented on [Thu May 11 2017](https://github.com/vmware/vic/issues/4250#issuecomment-300815332)

Not sure this is a 1.2 topic. I don't see it in the PM ask. Let's make it opportunistic.

---

@andrewtchin commented on [Mon May 15 2017](https://github.com/vmware/vic/issues/4250#issuecomment-301511244)

That's true, removed 1.2 label

**Comment by mdubya66** [comment]
https://github.com/vmware/vic/issues/3913

**Comment by mdubya66** [comment]
https://github.com/vmware/vic/issues/4250

**Comment by andrewtchin** [comment]
We will have to write a collector service that runs in the VIC Appliance and forwards telemetry. Services running on the Appliance will send their telemetry to this forwarding service.
