### ISSUE TITLE
Document the VCH wizard in vSphere Client

### ISSUE THREAD

**Issue by stuclem** [vmware/vic-product#929]
Per Epic https://github.com/vmware/vic/issues/5150

**Comment by stuclem** [comment]
This is the big kahuna in 1.3, so probably a high priority.

**Comment by stuclem** [comment]
@jooskim and @zjs, I have a question for you: if you deploy multiple VIC appliances to the same VC (confirmed as supported in https://github.com/vmware/vic-product/issues/740#issuecomment-329865184), which `vic-machine-server` is used to deploy VCHs from the UI? Does this matter at all? If not, then that's great, but both @lgayatri and I asked the question this morning, and I am sure that users will ask it too, so I'd like to document something about how this is handled. 

Incidentally, just performed the following test:

- Deployed `stuvch1` from the UI of a VC with only one VIC appliance, `stuappliance1`.
- Deployed a second VIC appliance, `stuappliance2`, to the same VC instance.
- Deployed `stuvch2` from the UI of the same VC instance. I have no idea whether 

Incidentally, just performed the following test:

- Deployed `stuvch1` from the UI of a VC with only one VIC appliance, `stuappliance1`.
- Deployed a second VIC appliance, `stuappliance2`, to the same VC instance.
- Deployed `stuvch2` from the UI of the same VC instance. I have no idea whether `stuappliance1` or `stuappliance2` was used to deploy the VCH, but there were no problems.
- Logged into the management portal for `stuappliance2`.
- Added `stuvch1`, which was definitely created by `stuappliance1`, as a container host in `stuappliance2`. No problem.
- Provisioned a container in the management portal for `stuappliance2`. Container created in `stuvch1`. So, again, there seems to be no problem with deploying a VCH from one appliance and adding it as a container host in the management portal of another appliance. I suppose I was just curious to see that it worked.

**Comment by stuclem** [comment]
@zjs, a question:

When you deploy a VCH from `vic-machine`, you can specify `--tls-cname` without specifying `--no-tlsverify`, which results in the auto-generation of both client and server certificates. However, in the UI, if you auto-generate certs, you have the option to disable client verification or to upload an existing client cert. There doesn't seem to be an option to auto-generate a client cert in the UI-based deployment. Is this indeed the case? Thanks!

**Comment by stuclem** [comment]
@zjs another question for you (that I also asked via Slack, forgetting that it's Thanksgiving): 

In the VCH wizard, the ops user is mandatory. Is it now the case that you have to specify an ops user? I saw in a mockup that there would be a checkbox that automatically gives a specified user the correct permissions, and also remember reading that if no ops user is specified, it creates one. Is this being implemented in 1.3? Thanks!

**Comment by stuclem** [comment]
@zjs, regarding the checkbox to auto-assign permissions to --ops-user, that is now implemented in the latest build.

**Comment by stuclem** [comment]
@zjs and @jooskim another question. When you deploy a VCH from the command line, if you don't specify `--public-network`, it defaults to the VM Network. But, in the UI, the only networks that you can select are port groups. Until now, whenever I have deployed VCHs, I have always used the default VM Network as the  public network and the resulting VCHs got their IP addresses from DHCP. In the UI, I have to select a port group, and my VCHs do not get IP addresses.

I am sure that there is some config that I can do on the port group that I assign to the public network, but I am wondering why the CLI default of VM Network is not permitted in the UI. Thanks!

**Comment by jooskim** [comment]
Could you file this as an issue? If it's supported by CLI so should UI

**Comment by stuclem** [comment]
@jooskim OK, will do. Thanks!

**Comment by stuclem** [comment]
@jooskim : https://github.com/vmware/vic-ui/issues/124

**Comment by stuclem** [comment]
Merged in https://github.com/vmware/vic-product/pull/1259/
