### ISSUE TITLE
Document vic-machine upgrade --resume

### ISSUE THREAD

**Issue by stuclem** [vmware/vic-product#93]
_From @stuclem on January 31, 2017 13:35_

Per https://github.com/vmware/vic/issues/3766

_Copied from original issue: vmware/vic#3778_

**Comment by stuclem** [comment]
Not in 1.2.

**Comment by stuclem** [comment]
Doesn't look like this is in 1.3.

**Comment by stuclem** [comment]
Not in 1.4.x

**Comment by zjs** [comment]
Closing as vmware/vic#3766 was closed.

**Comment by stuclem** [comment]
Not in 1.5.x, but still valid.
