### ISSUE TITLE
Document separation of vic-machine and vic-engine logging

### ISSUE THREAD

**Issue by stuclem** [vmware/vic-product#931]
Per https://github.com/vmware/vic/issues/6319.

**Comment by stuclem** [comment]
The investigation for splitting the vic-machine/engine logs was done in 1.3, but is the implementation happening in 1.3? Marking low priority pending response from @sgairo.

**Comment by sgairo** [comment]
@stuclem implementation was not done in 1.3, thanks!

**Comment by stuclem** [comment]
Thanks @sgairo !

**Comment by stuclem** [comment]
Looks like this was done in PR https://github.com/vmware/vic/pull/6945, but I don't think that there's actually anything to document.
