### ISSUE TITLE
Document how to specify internal Docker networks

### ISSUE THREAD

**Issue by stuclem** [vmware/vic-product#938]
Per https://github.com/vmware/vic-product/issues/667

**Comment by stuclem** [comment]
#667 has been removed from 1.3, but @pdaigle has provided a workaround in https://github.com/vmware/vic-product/issues/667#issuecomment-334790118. @pdaigle do we want to document this workaround pending the implementation of #667 in a later release?

**Comment by stuclem** [comment]
Not a new feature, but probably a useful bit of doc. Medium priority.

**Comment by stuclem** [comment]
See also internal bug 2141182.

**Comment by stuclem** [comment]
Comment from @hickeng in the internal bug: "(we need to determine) if the workaround from #667 is still viable and whether the custom docker0 steps work. If so we should document this formally until the option is configurable during OVA deployment."

**Comment by stuclem** [comment]
Looks like the workaround from #667 has been approved. See the internal bug for details. Moving this up to To Do.

**Comment by dbarkelew** [comment]
KB 56445 will need to be updated with links to the documentation that results when this issue is resolved.

**Comment by stuclem** [comment]
https://github.com/vmware/vic-product/issues/667 is in 1.5.3.

**Comment by stuclem** [comment]
Pushed out to 1.5.4.

**Comment by stuclem** [comment]
According to @renmaosheng in https://github.com/vmware/vic-product/issues/667#issuecomment-516350869 this won't be fixed, but there is a workaround that requires documentation.

**Comment by stuclem** [comment]
https://kb.vmware.com/s/article/56445 is publicly available, so I consider this fixed.
