### ISSUE TITLE
Document using ovftool for deploying VIC Appliance

### ISSUE THREAD

**Issue by andrewtchin** [vmware/vic-product#941]
**User Statement:**

As a vSphere admin I want to know how to deploy VIC Appliance with ovftool.

**Details:**
Example command:
```
ovftool --datastore=vsanDatastore --noSSLVerify --acceptAllEulas --name=<vch_name> --diskMode=thin --powerOn --X:waitForIp --X:injectOvfEnv --X:enableHiddenProperties --prop:appliance.root_pwd=<root_pwd>' --prop:appliance.permit_root_login=True --net:"Network"="vm-network" installer/bin/vic-*.ova 'vi://<vc_username>:<vc_pwd>@10.160.222.221/vcqaDC/host/cls' 2>&1
```
This is a basic command that only sets appliance root password and uses defaults for everything else. The other values that can be customized can be found in the ovf file. https://github.com/vmware/vic-product/blob/master/installer/build/vic-unified.ovf

We probably also want to include an example of using user provided TLS certs.

**Acceptance Criteria:**
- [ ] Documentation describing how to use `ovftool` to deploy OVA

**Comment by stuclem** [comment]
Not a new feature, but a useful piece of info. Medium priority.

**Comment by stuclem** [comment]
The link in https://github.com/vmware/vic-product/issues/941#issue-266247212 no longer works. You can see the ovftool options in https://github.com/vmware/vic-product/blob/master/tests/resources/OVA-Util.robot.
