### ISSUE TITLE
store vic-machine-server logs on the appliance

### ISSUE THREAD

**Issue by andrewtchin** [vmware/vic-product#944]
**User Statement:**

As a user I want to manage vic-machine-server logs.

**Details:**
Depends on https://github.com/vmware/vic/issues/6571

**Acceptance Criteria:**
- [ ] Update service to mount volume and put logs in the right place
- [ ] Able to configure log rotation or set a max log size

**Comment by zjs** [comment]
In case it enables parallel work on this issue: In the WIP code for vmware/vic#6571, the plan is to add a command-line argument (likely `--logs-directory` or similar) to control the logging destination with a reasonable FHS-compatible default like `/var/log/vic-machine-server/`.

We're expecting that the container or appliance will configure [`logrotate`](https://linux.die.net/man/8/logrotate) to handle rotation outside the server itself (as expected by our logging framework: https://github.com/sirupsen/logrus#rotation).

**Comment by morris-jason** [comment]
Bumping estimate to 2 for addition of `logrotate` step.
