### ISSUE TITLE
Minor documentation improvement for docker-compose

### ISSUE THREAD

**Issue by pdaigle** [vmware/vic-product#955]
When trying to use `docker-compose` with a VCH that has TLS enabled, you get the following error:

"ERROR: SSL error: [SSL: TLSV1_ALERT_PROTOCOL_VERSION] tlsv1 alert protocol version (_ssl.c:661)"

This is because `docker-compose` defaults to TLSv1. We need TLSv1_2 with VCH. The user will need set the environment variable with:

`export COMPOSE_TLS_VERSION=TLSv1_2`

This could be added to:
"Supported Docker Compose File Options"
OR
"Deploy Container VMs with Compose"

We could also make that part of the environment information we provide after VCH creation in `vic-machine`

Ref.: [https://docs.docker.com/compose/reference/envvars/](https://docs.docker.com/compose/reference/envvars/)

**Comment by stuclem** [comment]
@pdaigle this is already documented in https://vmware.github.io/vic-product/assets/files/html/1.2/vic_app_dev/deploy_multiple_docker_compose.html. I need to do a clean up on these topics, as they are raw content taken directly from Ben, that I haven't had a chance to edit.

Can you please confirm that this topic covers it?

**Comment by stuclem** [comment]
Also documented here: https://vmware.github.io/vic-product/assets/files/html/1.2/vic_app_dev/container_limitations.html.

I think that it's safe to close this one.
