### ISSUE TITLE
Document docker unpause

### ISSUE THREAD

**Issue by stuclem** [vmware/vic-product#96]
_From @stuclem on March 2, 2017 15:3_

Per https://github.com/vmware/vic/issues/382. Not in 1.1.

_Copied from original issue: vmware/vic#4131_

**Comment by stuclem** [comment]
Not in 1.2.

**Comment by stuclem** [comment]
Doesn't look like this is in 1.3.

**Comment by stuclem** [comment]
Not in 1.4.x.

**Comment by zjs** [comment]
Closing as vmware/vic#382 was closed.
