### ISSUE TITLE
TS doc ovf environment

### ISSUE THREAD

**Issue by andrewtchin** [vmware/vic-product#961]
If when booting the VIC Appliance the console screen displays the error `unable to unmarshal ovf environment`, the appliance will be in an unusable state.

Solution:
- Power off guest OS
- Right click the appliance, Edit Settings
- Go to `vApp Options`, click OK
- Verify that a `Reconfigure virtual machine` task is completed for the appliance
- Power on the appliance
- Verify that the console does not display error message

These steps rewrite a corrupted or missing ovfenv data.

**Comment by andrewtchin** [comment]
related https://github.com/vmware/vic-product/issues/741

**Comment by anba89** [comment]
Hi 

My VIC Appliance displays the error unable to unmarshal ovf environment and I tried the steps above without success. Is there another solution?

**Comment by stuclem** [comment]
Thanks for raising this @anba89. @andrewtchin do you have any ideas?

**Comment by andrewtchin** [comment]
@anba89 Sometimes it takes multiple attempts following the entire procedure above to write the OVF data again. Please try a few times and let us know if it doesn't work still.

**Comment by anba89** [comment]
@andrewtchin I tried it more than six times and then I redeployed the appliance.

**Comment by andrewtchin** [comment]
Thanks @anba89 could you provide a description of the environment you deployed in? vCenter version, datacenter configuration, datastore configuration, etc? I will get an issue opened in vCenter for this.

**Comment by anba89** [comment]
Hi @andrewtchin 

I simulated an ESXi crash today. And was able to restore the new VIC appliance with the documented steps. 

vCenter version: 6.5.0, 7119157
ESXi version: 6.5.0, 5224529
Datastore: NFSv3
Environment: Cisco HyperFlex Solution

**Comment by stuclem** [comment]
Thanks @anba89. Can we close this one again now?

**Comment by andrewtchin** [comment]
Yes closing.
