### ISSUE TITLE
Subject Alternative Name is missing from SSL certificate

### ISSUE THREAD

**Issue by jak-atx** [vmware/vic-product#962]
**Details:**
The SAN needs to be added to the ssl certificate coming from the appliance that serves vic-machine-service 

Current error is shown here:
https://vmware.slack.com/files/U6E08J80P/F7FMR0NUX/screen_shot_2017-10-06_at_1.29.15_pm.png

**Acceptance Criteria:**
Dev is able to accept the certificate as valid from the vic-machine-service response.

**Comment by zjs** [comment]
By default, the SSL certificate generated by the OVA seems to have the VM's IP address as the certificate's CN. What additional information are you expecting the SAN to contain?

**Comment by andrewtchin** [comment]
https://github.com/vmware/vic-product/blob/master/installer/build/scripts/systemd/vic_machine_server/configure_vic_machine_server.sh#L45

**Comment by andrewtchin** [comment]
Appliance cert has SAN in it
