### ISSUE TITLE
Document that persistent data is separated into individual disks

### ISSUE THREAD

**Issue by stuclem** [vmware/vic-product#967]
Per https://github.com/vmware/vic-product/issues/743, implemented in https://github.com/vmware/vic-product/pull/960.

**Comment by andrewtchin** [comment]
Will probably need to doc the process to expand disk size

**Comment by stuclem** [comment]
Details are in https://github.com/vmware/vic-product/issues/743#issuecomment-341147411. As @corrieb states in a comment in that issue, this is going to affect backup strategy, which we added to the docs in 1.2. Marking high priority.
