### ISSUE TITLE
Command Example Improvement Feedback

### ISSUE THREAD

**Issue by dbarkelew** [vmware/vic-product#969]
In the documentation it is not clear for some what kind of container engine to use based on the examples commands.
 
There are three main formats used with SSL secure and insecure versions that I have found as follows.

Typical VCH container and vic-engine:
```
docker -H vch_address:2375 info
docker -H vch_address:2376 --tls info
```

Docker build slave with port mapping through a parent VCH:
```
docker -H vch_address:12375 info
docker -H vch_adress:12376 --tls info
```

In these docs seems assumed to be docker engine deployed on a VM or bare metal.
```
docker info
docker --tls info
```

This can easily be confusing when a page of the documentation is read out of context like the example below.
https://vmware.github.io/vic-product/assets/files/html/1.2/vic_app_dev/photon_cert_custom.html

Is there a way to clarify  this more, maybe with a note under the command stating engine the command is intended for.
Maybe something like the following might reduce possible confusion. 

```
docker pull registry_address/default-project/dch-photon:1.13
## Run from a native docker instance

docker -H vch_address:12375 build -t registry_address/default-project/test-container .
## Run from a build-slave container instance
```
bug1984007

**Comment by stuclem** [comment]
Enhancement. Medium priority.

**Comment by stuclem** [comment]
Connected to the `dch-photon` doc improvements.

**Comment by stuclem** [comment]
Fixed in https://github.com/vmware/vic-product/pull/1989/commits/9e68f3d5ddd68bf1798d535d39e43a039a0fbf55.

**Comment by stuclem** [comment]
Fixed in https://github.com/vmware/vic-product/pull/1989
