### ISSUE TITLE
Document relaxation of DVS check when VC manages a single host

### ISSUE THREAD

**Issue by stuclem** [vmware/vic-product#97]
_From @stuclem on January 31, 2017 11:6_

Per https://github.com/vmware/vic/issues/3767. 

_Copied from original issue: vmware/vic#3777_

**Comment by stuclem** [comment]
Doesn't appear to be in 1.2.

**Comment by stuclem** [comment]
Doesn't look like this is in 1.3.

**Comment by stuclem** [comment]
Not in 1.4.x.

**Comment by zjs** [comment]
Closing as vmware/vic#3767 has been closed.
