### ISSUE TITLE
Regression : ifconfig command is missing from VIC 1.3 OVA

### ISSUE THREAD

**Issue by lgayatri** [vmware/vic-product#976]
Build used: https://storage.googleapis.com/vic-product-ova-builds/vic-2161-v1.2.0-rc1-132-g89afccc.ova
Could not find ifconfig command on OVA . This command was available on VIC 1.2.1 GA build.

VIC 1.3 
![image](https://user-images.githubusercontent.com/25006749/31937211-63d31982-b8d1-11e7-8dae-b5b381b91058.png)

VIC 1.2.1
![image](https://user-images.githubusercontent.com/25006749/31937276-8818c670-b8d1-11e7-9e9e-22ed6e7cec8a.png)

**Comment by andrewtchin** [comment]
`ifconfig` is deprecated, use `ip` instead
