### ISSUE TITLE
--force is more than bypassing thumbprints

### ISSUE THREAD

**Issue by dbarkelew** [vmware/vic-product#982]
"--force" should be discouraged for a way to bypass thumbprints. While this is true, it also by passes a lot of other things that can result in unexpected data loss. 

The sentence might be better removed "If your vSphere environment uses untrusted, self-signed certificates, you can bypass certificate thumbprint verification by specifying the --force option instead of --thumbprint" 

https://vmware.github.io/vic-product/assets/files/html/1.2/vic_vsphere_admin/vch_installer_options.html

**Comment by andrewtchin** [comment]
this should cover all cases where force is cited in the docs - we should discourage use of force as it is intended for developer use and may have unintended effects. we will be looking at replacing or removing force in the future.

**Comment by stuclem** [comment]
@dbarkelew and @andrewtchin I have updated all mentions of `--force` in https://github.com/stuclem/vic-product/commit/7e0174ae7f669626b739f94975ef90be43d765e8, to include the following:

----

**CAUTION**: Specifying the `--force` option bypasses certificate thumbprint verification. Using `--force` in this way exposes VCHs to the risk of man-in-the-middle attacks, in which attackers can learn vSphere credentials. Using `--force` also bypasses other checks, and can result in data loss.

----

Is this strong enough?

**Comment by andrewtchin** [comment]
I would edit the end to say something along the lines of "use of --force is strongly discouraged and should not be used in production environments", but either looks fine

**Comment by stuclem** [comment]
Thanks @andrewtchin. Updated as follows:

----

**CAUTION**: Specifying the `--force` option bypasses certificate thumbprint verification. Using `--force` in this way exposes VCHs to the risk of man-in-the-middle attacks, in which attackers can learn vSphere credentials. Using `--force` also bypasses other checks, and can result in data loss. As consequence, only use `--force` for troubleshooting purposes. Do not use `--force` in production environments. 


-----

**Comment by stuclem** [comment]
This update is in https://github.com/stuclem/vic-product/commit/cbf56b54e7d43a2d5b8cd9be4f719c94657b95b8, alongside a bunch of other security-related updates that are part of a general reorg of the vic-machine options.

**Comment by dbarkelew** [comment]
Not sure I think should have wording should be something like 

Caution: Using --force bypasses safety checks that are in place to protect the deployment including but not limited to certificate thumbprint verifications. Using --force can result in unexpected deployment topologies that would otherwise normally fail with an error.

**Comment by stuclem** [comment]
@dbarkelew and @andrewtchin how about this, which combines both of your suggestions, and retains the warning about man-in-the-middle attacks, which came from @hickeng:

----

**CAUTION**: Specifying the `--force` option bypasses safety checks, including certificate thumbprint verification. Using `--force` in this way can expose VCHs to the risk of man-in-the-middle attacks, in which attackers can learn vSphere credentials. Using `--force` can result in unexpected deployment topologies that would otherwise fail with an error. Do not use `--force` in production environments.

-----

**Comment by stuclem** [comment]
This update is in https://github.com/vmware/vic-product/pull/996/commits/78201faf190d7e81599eb424433b3be981d815a9.

**Comment by dbarkelew** [comment]
I think that should work.
