### ISSUE TITLE
128 character password for Users is too much to ask

### ISSUE THREAD

**Issue by lgayatri** [vmware/vic-product#983]
Build: https://storage.googleapis.com/vic-product-ova-builds/vic-2161-v1.2.0-rc1-132-g89afccc.ova
![image](https://user-images.githubusercontent.com/25006749/31990022-80c6eb20-b991-11e7-86f5-74dc300ef815.png)
This check is too much to expect from users. Please review.

**Comment by andrewtchin** [comment]
I don't think this is a bug. If users want a 128 character password they should have the option to. The acceptable lengths are defined here https://github.com/vmware/vic-product/blob/master/installer/build/vic-unified.ovf#L299
If the UI won't allow you to deploy with < 128 characters, that is a bug In the UI.

**Comment by lgayatri** [comment]
@andrewtchin , ovf descriptor is showing correctly , so this bugs goes to H5 client. I filed another bug internally copying you and @mdubya66 .

**Comment by andrewtchin** [comment]
Cool thanks 👍
