### ISSUE TITLE
Document how to test NFS connectivity from VCH

### ISSUE THREAD

**Issue by corrieb** [vmware/vic-product#986]
** Problem **

At a customer last week, I sat with them while they tried to set up NFS volume support in VIC 1.2.1. 

NFS client mount isn't that helpful at the best of times, but the combination of permissions and settings on the server side and the subsequent number of possible combinations of options on the client side make it very difficult to test. Add to that the question of which ports need to be open on firewalls even if the client can ping the NFS server.

Installing / deleting the VCH and looking for errors in the VIC management portal is too clumsy to be practical and in the experience at this customer site, wasn't showing any useful info.

** Solutions **

The most obvious and simplest solution is to enable SSH on the endpoint VM using vic-machine debug and try to mount the NFS server from inside the endpoint VM. One should assume that if this works, the NFS datastore configuration should also work. However, the problem here is that mount.nfs is not included in the endpoint and it's not at all obvious how to add it.

Another option is to start a container that has an nfs client and attempt a mount from within the container. This is a better option for a VCH user that doesn't have access to vic-machine, but we should assume that setting up NFS for a datastore is a vSphere admin task that presumes vic-machine access.

**Comment by stuclem** [comment]
@corrieb regarding "the problem here is that `mount.nfs` is not included in the endpoint and it's not at all obvious how to add it", can you please add some details about how to do this? Thanks!

**Comment by stuclem** [comment]
Thanks @tschwaller

**Comment by stuclem** [comment]
Enhancement, not new feature. Medium.

**Comment by tschwaller** [comment]
This is actually blocking a customer go-to production situation since the NetApp NFS share can not be mounted successfully. We need to document NFS server configuration assumptions VIC is making and test against a few NFS servers..

**Comment by stuclem** [comment]
Boosting priority to high following request from @pauldul and @tschwaller

**Comment by matthewavery** [comment]
Some assumptions that we are making is that the share is configured for anonymous mounting. and that if a `UID` and `GID` is not specified at create time of the volumestore then we also used `1000:1000` to attempt to create the volume store as well. I will work on making a list of this information here @stuclem

**Comment by stuclem** [comment]
First priority post-GA
