### ISSUE TITLE
Document which external network trust levels support which -p constructions

### ISSUE THREAD

**Issue by stuclem** [vmware/vic-product#987]
Per https://github.com/vmware/vic/issues/6515 and the following comment from @hickeng via Slack:

"We should have a chart of what external network trust levels support which -p constructions, and what the end result is. Possibly with illustrations".

**Comment by stuclem** [comment]
This looks tricky but it isn't a new feature. Medium priority.

**Comment by stuclem** [comment]
Having looked at https://github.com/vmware/vic/issues/6515 and https://github.com/vmware/vic/issues/6271, I have no idea what we should document here.

@hickeng can you please provide more details?

**Comment by zjs** [comment]
@yuyangbj, could you provide @stuclem with the requested details? (Ping @hickeng for a pointer to the relevant code if needed.)

**Comment by hickeng** [comment]
#2252 added some information regarding `-p` and container networks, but not the table that's requested.

**Comment by stuclem** [comment]
I think that this is something that we definitely help from dev on. @yuyangbj can you please provide the information requested in https://github.com/vmware/vic-product/issues/987#issuecomment-456616708 above? Thanks!

**Comment by stuclem** [comment]
@renmaosheng do we need to address this in 1.5.4?

**Comment by yuyangbj** [comment]
@stuclem based on current VIC customers usage, they do not complain this problem and it is just missing a summary in table format, so we will not fix it in VIC. My recommendation is close it.

**Comment by stuclem** [comment]
OK, thanks @yuyangbj
