### ISSUE TITLE
Build version should be updated to 1.3 

### ISSUE THREAD

**Issue by lgayatri** [vmware/vic-product#989]
1.3 OVA Build - https://storage.googleapis.com/vic-product-ova-builds/vic-2161-v1.2.0-rc1-132-g89afccc.ova

root@Ubuntu-VIc:/home/vmlib/VIC/VIC-1.3/vic# ./vic-machine-linux --version
vic-machine-linux version v1.2.0-rc1-14150-93ba694

OVA file name and vic version both spell 1.2.0 even though they are for 1.3. We need to update the files version.

**Comment by andrewtchin** [comment]
This will happen when we tag but 1.3 has not been tagged yet

**Comment by lgayatri** [comment]
@andrewtchin 
Can you please keep the issue open until it is tagged, so that I do not miss it verifying?

**Comment by andrewtchin** [comment]
I'd rather not because this is expected at this point. I'll be sure to check it when we tag and message you.
