### ISSUE TITLE
Clair download goes to different sites from the one in docs

### ISSUE THREAD

**Issue by sgtserge** [vmware/vic-product#994]
We are using VIC 1.2.1 GA on vSphere 6.0 u3a and vCenter 6.0 u3b

We are trying to set up Clair to work behind a proxy so we have to provide a list of required sites.

In Clair doc available here I can see the Database URLs are all on github

But in Clair logs I see that it tries to go on these other sites:

Oct 26 21:56:39 192.168.9.1 clair[249]: {"Event":"could not download Oracle's update list","Level":"error","Location":"oracle.go:134","Time":"2017-10-26 21:56:39.132198","error":"Get **https://linux.oracle.com**/oval/: Forbidden"}
Oct 26 21:56:39 192.168.9.1 clair[249]: {"Event":"could not download Oracle's update list","Level":"error","Location":"oracle.go:134","Time":"2017-10-26 21:56:39.178998","error":"Get https://linux.oracle.com/oval/: Forbidden"}
Oct 26 21:56:39 192.168.9.1 clair[249]: {"Event":"could not download RHEL's update list","Level":"error","Location":"rhel.go:106","Time":"2017-10-26 21:56:39.179353","error":"Get **https://www.redhat.com**/security/data/oval/: Forbidden"}
Oct 26 21:56:39 192.168.9.1 clair[249]: {"Event":"could not download Debian's update","Level":"error","Location":"debian.go:68","Time":"2017-10-26 21:56:39.179831","error":"Get **https://security-tracker.debian.org**/tracker/data/json: Forbidden"}

This log filled up the disk in just 1 day making VIC appliance to crash, which is not expected to happen. Maybe it is possibile to increase log rotation for this log file.

Thanks

Sergio

**Comment by sgtserge** [comment]
We are using VIC 1.2.1 GA on vSphere 6.0 u3a and vCenter 6.0 u3b

We are trying to set up Clair to work behind a proxy so we have to provide a list of required sites.

In Clair doc available [here](https://github.com/vmware/vic-product/pull/933/files/71dcf3c67dfbcafb1a82a907f8d19dbc4a777734) I can see the Database URLs are all on github 

But in Clair logs I see that it tries to go on these other sites:

> Oct 26 21:56:39 192.168.9.1 clair[249]: {"Event":"could not download Oracle's update list","Level":"error","Location":"oracle.go:134","Time":"2017-10-26 21:56:39.132198","error":"Get **https://linux.oracle.com**/oval/: Forbidden"}
Oct 26 21:56:39 192.168.9.1 clair[249]: {"Event":"could not download Oracle's update list","Level":"error","Location":"oracle.go:134","Time":"2017-10-26 21:56:39.178998","error":"Get https://linux.oracle.com/oval/: Forbidden"}
Oct 26 21:56:39 192.168.9.1 clair[249]: {"Event":"could not download RHEL's update list","Level":"error","Location":"rhel.go:106","Time":"2017-10-26 21:56:39.179353","error":"Get **https://www.redhat.com**/security/data/oval/: Forbidden"}
Oct 26 21:56:39 192.168.9.1 clair[249]: {"Event":"could not download Debian's update","Level":"error","Location":"debian.go:68","Time":"2017-10-26 21:56:39.179831","error":"Get **https://security-tracker.debian.org**/tracker/data/json: Forbidden"}
 
This log filled up the disk in just 1 day making VIC appliance to crash.

**Comment by andrewtchin** [comment]
Issue moved to [vmware/harbor #3524](https://github.com/vmware/harbor/issues/3524) via [**ZenHub**](https://www.zenhub.com/)
