### ISSUE TITLE
VIC Appliance Component Upgrade Testing

### ISSUE THREAD

**Issue by morris-jason** [vmware/vic-product#997]
**User Statement:**

As a vAdmin, I expect Harbor upgrades to run on the ova from versions 1.2.x -> 1.3. 

**Details:**

As part of story #743 the data paths in the upgrade script were altered. As part of this refactor,  it was revealed that the upgrade scripts for admiral and harbor need re-evaluation for the 1.3 upgrade path.
#743 also separated the upgrade script per-component to be in line with the OVA Design doc.

**Acceptance Criteria:**

- Find out if we still need the Harbor map projects step in 1.3. 
- Update version of harbor db migrator when necessary. 
- With respect to harbor configuration keys, make sure 1.3 values are defaulted if 1.2 values are not present for a specific key.
- Testing from 1.2 -> 1.3 and 1.2.1 -> 1.3.

**Issue**

When running the current DB migrator image for map projects, the script exists with `Map projects finished` but the container stops with exit code 1. This causes an upgrade script failure.

**Comment by wy65701436** [comment]
1, Map projects is only for VIC 1.2 to map project ID of harbor with Admiral. It should be dropped from 1.3.
2, We're still working on the implementation of DB migrator, will use vmware/harbor-db-migrator:1.3 as the image name.
3, Yes, the new items of 1.3 should be set as default and should not impact the system after update from 1.2.
4, It should be the same for Harbor in VIC 1.2 and 1.2.1, but I agree the testing.

**Comment by andrewtchin** [comment]
Harbor upgrade script additions have been merged. Testing for this story can begin

**Comment by andrewtchin** [comment]
1.2.1. to 1.3.0-rc2
```
root@Photon [ /etc/vmware/upgrade ]# ./upgrade.sh
Enter vCenter Server FQDN or IP: x.eng.vmware.com
Enter vCenter Administrator Username: administrator@vsphere.local
Enter vCenter Administrator Password:
If using an external PSC, enter the FQDN of the PSC instance (leave blank otherwise):
If using an external PSC, enter the PSC Admin Domain (leave blank otherwise):

-------------------------
Starting upgrade 2017-11-28 17:43:48 +0000 UTC
Detected old OVA's version as 1.2.x. Upgrade will perform data migration, but previous component logs won't be transferred.
If the version of the old OVA is not 1.2.x, please enter n and contact VMware support:
Do you wish to proceed with a 1.2.x to 1.3.x upgrade? [y/n]
y
Continuing with upgrade

Preparing upgrade environment
Disabling and stopping Admiral and Harbor path startup
Finished preparing upgrade environment

-------------------------
Starting Admiral Upgrade 2017-11-28 17:43:48 +0000 UTC

Performing pre-upgrade checks
Starting Admiral upgrade
Updating Admiral configuration
Admiral upgrade complete

-------------------------
Starting Harbor Upgrade 2017-11-28 17:43:48 +0000 UTC

Performing pre-upgrade checks
Starting Harbor upgrade
[=] Shutting down Harbor
[=] Migrating Harbor data
[=] Finished migrating Harbor data
[=] Migrating Harbor configuration
[=] Finished migrating Harbor configuration
Harbor upgrade complete
Starting Harbor
Enabling and starting Admiral and Harbor path startup
Upgrade script complete. Exiting.
```
- [x] confirmed harbor and admiral started
- [x] confirmed correct files on fileserver
- [x] confirmed previous VCH added
- [x] confirmed previous containers show up
- [x] confirmed new container from harbor registry launches

- `vic_machine_server` service fails to start, fix in progress

**Comment by andrewtchin** [comment]
Tested chained upgrade from 1.1 to 1.2.1 to 1.3.0-dev
```
root@Photon [ /etc/vmware/upgrade ]# ls
upgrade-admiral.sh  upgrade-harbor.sh  upgrade.sh  util.sh
root@Photon [ /etc/vmware/upgrade ]# ./upgrade.sh
Enter vCenter Server FQDN or IP: 10.192.58.102
Enter vCenter Administrator Username: administrator@vsphere.local
Enter vCenter Administrator Password:
If using an external PSC, enter the FQDN of the PSC instance (leave blank otherwise):
If using an external PSC, enter the PSC Admin Domain (leave blank otherwise):

-------------------------
Starting upgrade 2017-11-29 19:49:39 +0000 UTC
Detected old OVA's version as 1.2.x. Upgrade will perform data migration, but previous component logs won't be transferred.
If the version of the old OVA is not 1.2.x, please enter n and contact VMware support:
Do you wish to proceed with a 1.2.x to 1.3.x upgrade? [y/n]
y
Continuing with upgrade

Preparing upgrade environment
Disabling and stopping Admiral and Harbor path startup
Finished preparing upgrade environment

-------------------------
Starting Admiral Upgrade 2017-11-29 19:49:39 +0000 UTC

Performing pre-upgrade checks
Starting Admiral upgrade
Updating Admiral configuration

-------------------------
Starting Harbor Upgrade 2017-11-29 19:49:39 +0000 UTC

Performing pre-upgrade checks
Starting Harbor upgrade
[=] Shutting down Harbor
[=] Migrating Harbor data
[=] Finished migrating Harbor data
[=] Migrating Harbor configuration
[=] Finished migrating Harbor configuration
Harbor upgrade complete
Starting Harbor
Enabling and starting Admiral and Harbor path startup
Upgrade script complete. Exiting.
```
```
root@Photon [ /etc/vmware/upgrade ]# cat /etc/vmware/version
appliance=v1.4.0-dev-0-63016d16
harbor=harbor-offline-installer-v1.3.0-rc2.tgz
engine=vic_15140.tar.gz
admiral=vmware/admiral:vic_v1.3.0-rc2 d3f94aa7417c
vic-machine-server=gcr.io/eminent-nation-87317/vic-machine-server:latest 10086a96d90e
```

**Comment by andrewtchin** [comment]
verified chained upgrade again with `vic-machine configure` to update registry cert. created a container from harbor at each version and all containers show up after upgrade
