### ISSUE TITLE
Add persistent warning on getting started page when initalization has not completed

### ISSUE THREAD

**Issue by andrewtchin** [vmware/vic-product#998]
**User Statement:**

As a user I want to know if the VIC Appliance has not been successfully registered.

**Details:**
The red error bar for failed appliance initialization currently disappears if users navigate away. This confuses users because they think the error has resolved, but the appliance is still not functional.

**Acceptance Criteria:**
- [ ] Add a persistent error bar on the Getting Started Page if initialization has failed

@ali5ter

**Comment by pureshine** [comment]
@andrewtchin Are you talking about the error message that appears here when the initialization fails, or can you provide a screenshot?
![image](https://user-images.githubusercontent.com/40712758/50581008-54a9bb80-0e90-11e9-8199-fbdcf0080a31.png)

**Comment by andrewtchin** [comment]
@pureshine Yes the bar is similar to the one you have highlighted, but it is the red bar that is displayed when appliance initialization fails. If the user misses this warning then reloads the page, the bar is no longer displayed so the user has no indication that the appliance will not work.

**Comment by renmaosheng** [comment]
won't fix this one.
